### ISSUE TITLE
Proof-of-concept: Update permission checking for replication operations

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1024]
Figure out if replicating data bypasses permission checks. If it doesn't, awesome. If it does, figure out why and if there's a way for us to enforce permissions manually.

**Comment by garethbowen** [comment]
The validation functions run, so :+1:.

Potential issues:

- The validation function only has access to the userCtx and the doc, so we can't determine if the user has the correct district. This is probably ok. We may be able to do some additional permissions checking as part of the auditing work.
- The change remains in the local PouchDB, so if you delete a doc you shouldn't be able to then the remote couch doesn't get updated, but it looks to you like it has been. We could listen to the `denied` event and roll back the change, or at least show the information to the user. However because this is highly unlikely to happen unless someone's hacking the system I'm not too worried about having a nice UI.
