### ISSUE TITLE
Support a new `date` type

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1050]
We are getting several feature requests that relate to dates: [duplicates](https://github.com/medic/medic-webapp/issues/992), [reporting rate analytics](https://github.com/medic/medic-webapp/issues/1028), [dob calculations](https://github.com/medic/medic-webapp/issues/1029). These are being requested for a variety of use cases, including registrations for immunizations, as well as service/stock reporting.

Currently, since there is no dedicated date strategy, date fields we have been implemented dates in a variety of ways across projects. Some projects implement this as separate fields, some times with int, or even lists with non standard values (eg year 2015 having value 1 since we only support values starting at 1). We also use strings since the value sent from the date field in `medic-collect` uses the `YYYY-MM-DD` format (eg 2014-12-31).

We should consider having a more native-like date type in our form definitions so that dates are used in a common way across projects. Using a standard date type could allow us expose date formatting and calculations in the configurations (eg 5 days after `date_of_birth`).

**Comment by browndav** [comment]
In the `cic-guatemala` branch of `medic-simapp`, there is now working support for `date` and `numeric` types, plus library code that's capable of validating and subtracting dates. The `date` type is implemented as a three-field sequence that's joined in to a single field via a special `SCHEMA_ITEM_DELIMITER` directive.

Two remaining issues: (i) the form compiler's validation/conditions code currently miscounts fields when a `date` field is used. This was already fixed in one spot, but the condition/validation-emitting code needs to be fixed too; and (ii) the date validation code is currently in a special `malnutrition` library, and isn't merged in to the core or applied automatically by the form compiler.

I'd suggest we file issues for those two on `medic-simapp` once we have a strategy picked out for the other repos/components.

**Comment by sglangevin** [comment]
@abbyad is this still relevant? If not, let's close and re-open when this is needed.

**Comment by abbyad** [comment]
Seems as though we can get by without it now, and open new issue when needed.
