### ISSUE TITLE
Android container: find a way to manage project-specific branding without branching, apply branding as a near-final build step

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1051]
In addition to the generic Medic Mobile Android container, we'll need to produce/deploy branded versions for some larger deployments. These versions may have customized names, application icons, Google Play store listings, and configuration/URLs.

We'd like to manage the application of branding as a build step, rather than per-project branches. Do a test run with some fictitious branding, and ensure it works with our CI setup.

**Comment by alxndrsn** [comment]
Implemented on `master` branch of [`medic-android`](https://github.com/medic/medic-android) project.  Commit: https://github.com/medic/medic-android/commit/2c5bd4108a69afdda31b6fbf3606b122f1445adf

**Comment by abbyad** [comment]
Thanks @alxndrsn. This builds well and seems to be a good solution. I am moving to Ready but pinging @browndav to take a look as well.

A couple of comments/suggestions:
- Is there a reason to use icn_launcher instead of ic_launcher?
- Can we add a quick note on how to add additional branded builds, or where to edit existing ones - I can help with this if you don't already have something.
- Minor point for the sake of avoiding clutter... can the different flavors be moved to a directory? Eg `src/flavors/livinggoods/` vs 'src/livinggoods/`. I couldn't see an evident way of doing this in the [docs](http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Product-flavors), do you know if this is possible?

**Comment by garethbowen** [comment]
This works well for me (after a couple of tweaks). LG G3 running Android 5.0.
