### ISSUE TITLE
Run e2e testing in continuous integration

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1055]
We should run the e2e testing during the CI build so we catch breakages early. This is dependant on having an [alternative to basic auth](https://github.com/medic/medic-webapp/issues/1038).

**Comment by garethbowen** [comment]
Code snippets required to get this to work:

### Gruntfile.js

```
    // ci task...
    'exec:addadmin',
    'exec:runapi',
    'exec:sleep',
    'protractor'
```

### .travis.yml

```
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  ...
  - npm --prefix api install
  - ./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update
  - nohup bash -c "./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager start 2>&1 &"

script:
  ...
  - cat nohup.out
  - cat api.out
```

**Comment by garethbowen** [comment]
Reverted this change out again. I have no idea why the login page is doing this:

`::ffff:127.0.0.1 - ci_test [22/Jul/2015:02:39:41 +0000] "POST /medic HTTP/1.1" - - "-" "-"`

Enough time has been spent on this. Walking away.

**Comment by browndav** [comment]
Fair enough; we can probably revisit this issue once we've cleared out some of the big-feature issues/milestones.

**Comment by garethbowen** [comment]
At least it now works locally again.

**Comment by SCdF** [comment]
@garethbowen [in the docs](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI) they recommend a sleep time after starting xvfb, did you give that a try?

Also, apologies if this is a dumb question, but have we considered something like PhantomJS? I'm not actually aware of pros and cons regarding this. We have phantomjs in our dev dependencies already, though it's not entirely clear how it's used.

**Comment by garethbowen** [comment]
I think PhantomJS was used for some unit tests once upon a time. Look into it - we may be able to drop that dependency.

IIRC Phantom doesn't work well for e2e tests because it's missing some fairly important bits. Also e2e tests are an attempt to mimic an end user so should be run in a browser that users use. Chrome or Firefox would be fine for now with an eye to running in both as the next step.

I can't remember if I tried a timeout exactly there, but I did try sprinkling timeouts throughout the code.

It's possible it'll run better now as I did a bunch of reworking to get it running reliably locally. I also added more logging, for example, api output will be logged in the build script now.

The first step is to get them all to pass locally. Then add it back to the CI grunt task and take it from there...

**Comment by SCdF** [comment]
OK they should run locally now, just a minor change was required.

**Comment by SCdF** [comment]
(oh, I also removed phantomjs, but my brain is fried and I removed them under #2587. The two commits are https://github.com/medic/medic-webapp/commit/da6bf928179a747d1b7d657f90aed2fc693cf7ba and https://github.com/medic/medic-webapp/commit/e52bbd9c40c459d606c68624bffc9c72563cae40 )

**Comment by SCdF** [comment]
@garethbowen OK it's half (sort of) done! It's time for me to sign off. Where we're at:
 - Created a branch: https://github.com/medic/medic-webapp/tree/e2e_in_ci
 - I dropped 0.12 support because the webdriver location is different and whatever. We can solve that once at least one of the versions run through
 - 5.6 **actually passes**!!! Feel free to [let your down, down…](https://www.youtube.com/watch?v=LcGXR00x1ro)
 - 6.x is not so lucky. Got the admin user being created correctly, api boots and runs, and selenium seems to connect, but then it just never seems to connect:
```
WEBDRIVER:
16:47:42.602 INFO - Selenium Server is up and running
16:50:29.091 INFO - Executing: [new session: Capabilities [{count=1, browserName=firefox}]])
16:50:29.104 INFO - Creating a new session for Capabilities [{count=1, browserName=firefox}]
16:50:31.482 INFO - Done: [new session: Capabilities [{count=1, browserName=firefox}]]
16:50:31.501 INFO - Executing: [set script timeout: 11000])
16:50:31.513 INFO - Done: [set script timeout: 11000]

TESTS CONNECTING:
api] Migration "extract-translations" completed successfully
Database migrations completed successfully


/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2200
            reject(Error((opt_message ? opt_message + '\n' : '') +
                   ^
Error: Server should start within 10 seconds
Timed out waiting for promise to resolve after 10007ms
```

5.6's first log after `Database migrations completed successfully` are web logs, so I'm not sure exactly what is breaking, and why it's breaking on 6 and not 5. Here is the [failing test](https://travis-ci.org/medic/medic-webapp/jobs/148362033), and here is [the passing one](https://travis-ci.org/medic/medic-webapp/jobs/148362034).

Feel free to take a crack on Monday, or I'll continue to poke around when I'm up.

**Comment by garethbowen** [comment]
Some initial thoughts...

Does 6.3 reliably fail? Is it worth upping the timeout and seeing if that helps? Are you running node v6.3.1 locally? The way we check if the server is started is by scanning for the database migration success output so it's possible that a different node version is outputting it in a slightly different way. NB that as of https://github.com/medic/medic-api/commit/b807bfaa92a6f0be59485462e7436e90f5e003c7 we're going to need to check for a different message anyway (maybe starts with "Medic API listening"?).

Let's pair it when you get online.

**Comment by SCdF** [comment]
It passes for me in 6.3.1 locally, _in Chrome_.

I've never actually run them in FF (the default is Chrome): trying that now, they don't work for me in Firefox, but under any node version (I've tried v5 and v6). They fail for a completely different reason to why Travis fails. It's hard to tell if that means there is still more issues, or that's just OSX, or I have a version of FF that is too new, or something else entirely.

I'll take a quick stab at getting FF to work locally, since at least for now there is no way of configuring the e2e tests to run under Chrome locally and FF on Travis, so I might as well try to get them working.

**Comment by SCdF** [comment]
But OK reading your comments and looking at the code, that seems to be the main difference between 5 and 6, 5 has:

![image](https://cloud.githubusercontent.com/assets/583851/17287843/db2004ec-57c9-11e6-8bbc-2c764453d28e.png)

Whereas 6 has:

![image](https://cloud.githubusercontent.com/assets/583851/17287856/f08c2982-57c9-11e6-8a04-61652d7b3b57.png)

Looks like in 6 they may not pass data chunks back in convenient lines. I'll change the check to be a contains and see if that helps.

**Comment by SCdF** [comment]
Yay, that worked, both 5.x and 6.x pass in Travis. Now to add 0.12 back…

**Comment by SCdF** [comment]
![image](https://cloud.githubusercontent.com/assets/583851/17290183/170fab78-57d5-11e6-9f22-40c709a1db2b.png)
 ^-- why FF doesn't work for me locally. Oh well.

**Comment by SCdF** [comment]
@garethbowen take a look at https://github.com/medic/medic-webapp/pull/2593 and feel free to merge if you're happy with it!

**Comment by garethbowen** [comment]
LGTM

**Comment by SCdF** [comment]
Merged
