### ISSUE TITLE
medic-collect and medic-android apps have the same name

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1088]
Both of these apps are calling themselves `Medic Mobile`.  For `medic-android` this is happening in the default flavour only; for `medic-collect` this happens in:
* intrahealthsenegal

**Comment by alxndrsn** [comment]
Hi @abbyad, any suggestions for differentiating these?

**Comment by abbyad** [comment]
According to our branding scheme that is OK... but since both will live in Google Play Store simultaneously we discussed last week about differentiating them as "Collect" for medic-collect and "Medic Mobile" for medic-android - at least for now while they are in pre-release.

Also, for medic-collect they currently are all "Medic Mobile" *except* for intrahealthsenegal, which is "SEDA". @alxndrsn are you seeing that differently?

**Comment by alxndrsn** [comment]
@abbyad wasn't seeing _SEDA_ until I added the extra branding folder

**Comment by alxndrsn** [comment]
Done in https://github.com/medic/medic-collect/commit/f7502e03065460be2613814cd878f87f766c2871 and https://github.com/medic/medic-projects/commit/97d1d3f67249ef6919263760e14f9e6f3dc97f90

Available to download (debug) from version `1.4.5.1101`

**Comment by abbyad** [comment]
Thanks for the edits @alxndrsn. I cleared up the branding with https://github.com/medic/medic-collect/commit/49465710c16f305f0c81676b2155255074246e04

Removing `Acceptance Testing`
