### ISSUE TITLE
Chrome: Reports tab fails to load

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1112]
![x](https://cloud.githubusercontent.com/assets/763977/9015514/4b86ca8a-377e-11e5-99af-9825669c6987.jpg)

This might be related to #1108 and/or #1111, in that the currently-logged-in user name appears to have been lost. I can't (yet) reproduce this on Firefox or Webkit.

**Comment by browndav** [comment]
For the record, this is after (a) verifying that the login page appears; (b) verifying that an invalid password is correctly rejected; and (c) completing a successful login.

**Comment by garethbowen** [comment]
I think the `null` userCtx is the key here. Because the userCtx is stored in the HTML it is cached in the appcache. If this happens, you will have a `null` userCtx until you refresh the appcache, ie: when the app itself is updated.

To stop this happening I've removed the userCtx from the HTML and added a cookie instead which is set by API and then checked in the webapp.

I wasn't able to replicate this bug but I think this will fix it (or at least work around it).
