### ISSUE TITLE
Using media files with ODK XForms

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1157]
ODK XForms can include media files, which we are planning to use for training materials as well as to complement the assessment protocols. Currently the forms in medic-webapp (and those served to medic-collect) can only have the form XML, not the associated media files.

We would need to be able to upload multiple media files with a form, and be able to access them from the form using the standard ODK paths.

There is a related issue (#979) which was focused on serving those same media files to the Collect application when it downloads new forms.

**Comment by abbyad** [comment]
This may also be useful: http://opendatakit.github.io/odk-xform-spec/#media

**Comment by alxndrsn** [comment]
```
TODO
* reference media files in an example form
* understand how/if enketo supports external media files
* provision files in couch
* interpret local media requests in xforms, and redirect them to pouch

**Comment by alxndrsn** [comment]
# Viewing Forms

Media is included in xforms via `jr:` protocol (short for javarosa).  So once enketo has converted a form to HTML, you get an image tag such as:
```html
<img lang="default" class="active" src="jr://images/nuthatch.png" alt="image">
```

## Options

### Custom protocol support
Browsers don't have support arbitrary custom protocols, for security reasons:
> ### `Navigator.registerProtocolHandler()`
> For security reasons, by default, web sites may only register protocol handlers for themselves — the domain and protocol of the handler must match the current site.
> _https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler_

We could add support for the `jr:` protocol in our Android webview, similar to how we [handle SMS links](https://github.com/medic/medic-android/blob/master/src/main/java/org/medicmobile/webapp/mobile/EmbeddedBrowserActivity.java#L101), but this wouldn't help with users accessing via web browsers.  I'm also not sure how tricky it would be to implement - ideally the media would be stored in pouch and synced from the server like any other doc/attachment, but it may be tricky to redirect the request from the java code in `EmbeddedBrowserActivity` to pouch.

### Translating `jr:` URIs in XSLT
Another option would be to scan for `jr://`-prefixed text in the XForm -> HTML XSL transform and converting these links to `http://` links to a shim which pulls attachments out of pouch.
It seems media URIs are included in a number of ways, including:

* via `<itext>` elements:
```xml
<text id="robin">
    <value form="long">European robin</value>
    <value form="short">European robin</value>
    <value form="image">jr://images/robin.png</value>
    <value form="audio">jr://audio/european-robin.mp3</value>
</text>
```
> _https://opendatakit.org/help/form-design/itext/_

* via inline `itext()` calls:
```xml
<text id="/widgets/display_widgets/select_media/nut:label">
    <value form="image">jr://images/nuthatch.png</value>
    <value>nuthatch</value>
</text>
...
<item>
    <label ref="jr:itext('/widgets/display_widgets/select_media/nut:label')"/>
    <value>nut</value>
</item>
```
> _https://ona.io/enketo/forms/68781/form.xml_

### Translating `jr:` URIs in JS (with pouch shim)
Similar to above, we could scan the generated HTML for `jr:` references and convert these to point to a URL representing the document via a local pouch shim.  This could be done synchronously before a form is displayed, or asynchronously afterwards.  This approach may not work with pouchdb, as deep-linking attachments may only be possible with couch.

### Translating `jr:` URIs in JS (with embedded `data:`)
Media could be embedded directly in the page via the [`data:` URI scheme](https://en.wikipedia.org/wiki/Data_URI_scheme)).  `data:` URIs seem unlikely to be cache-friendly, although this may not be a significant worry for our use cases.  This could be done synchronously before a form is displayed, or asynchronously afterwards.

-----

I have filed a related query on the `enketo-core` repository: https://github.com/enketo/enketo-core/issues/289.  It may be that this problem is understood already by other enketo users and there is a standard solution.

# Creating forms

## Queries
@abbyad how are media files embedded using the form editors?  Can we get some examples of this?  What file(s) do the form editors supply when exporting a form?

# Uploading forms

## Notes
* forms should probably be uploaded at the same time as associated media
* simplest approach is to store media as [attachments](https://wiki.apache.org/couchdb/HTTP_Document_API#Attachments) on a form - this should be supported by pouch: http://pouchdb.com/guides/attachments.html
* pouch's attachment format seems to translate directly to `data:` URIs
* if media is to be shared between different forms, this will have implications for how uploads work

**Comment by alxndrsn** [comment]
From rereading this, it looks like parsing the DOM for `jr:` URIs and replacing them with `data:` URIs will be simplest.  It's not clear how this will work for [`big-image`](https://opendatakit.github.io/odk-xform-spec/#supported-media-types).

**Comment by alxndrsn** [comment]
@abbyad which media types are we looking to support?
Options are:

> * `image`
> * `audio`
> * `video`
> * `big-image`
>
> _https://opendatakit.github.io/odk-xform-spec/#supported-media-types_

I will begin working on support for images immediately.

**Comment by alxndrsn** [comment]
```
TODO
[x] understand how/if enketo supports media files
[ ] reference an image in an example form
[ ] store example form and associated image in couch
[ ] interpret `jr:` image requests in `medic-webapp`'s form display, and redirect them to pouch
[ ] update `medic-webapp/scripts/upload_xform` to accept media attachments for a form
[ ] add support for `big-image`
[ ] add support for `audio`
[ ] add support for `video`
[ ] consider allowing a form to reference media from another form

**Comment by abbyad** [comment]
@alxndrsn, in order of priority:
1) image
2) video
3) big-image
4) audio

For our current deployment we definitely need images, and had planned to use video as well.  We don't have an immediate need for audio, but can see us using it eventually. Support for big-image would be nice if it is supported by Enketo. If not I would not add support for it as part of this issue.

**Comment by alxndrsn** [comment]
Form with image available at: https://github.com/alxndrsn/enketo-client-side-transformer/tree/master/xforms/with-media

Upload via `webapp/scripts/upload_xform`:

```sh
../../webapp/scripts/upload_xform.sh pictorial-report pictorial-report.xml picture.png
```

**Comment by alxndrsn** [comment]
Separated `big-image` support as https://github.com/medic/medic-webapp/issues/1168, because it's not high priority and not supported upstream.

**Comment by abbyad** [comment]
This was working well in online mode, but not in offline mode. Moving to Ready and we can create a new issue for offline access to media when needed.
