### ISSUE TITLE
Incorrect uname/pword on alpha.dev triggers basic-auth prompt

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1179]
If you enter an incorrect username/password combo on http://alpha.dev.medicmobile.org/medic/login, a standard basic auth prompt is displayed.
<img width="1280" alt="screen shot 2015-08-20 at 20 32 32" src="https://cloud.githubusercontent.com/assets/191496/9392052/9d9f317a-477a-11e5-8440-5bbdb05cb7c2.png">

**Comment by garethbowen** [comment]
Doesn't happen in Firefox but can reproduce in Chrome.

**Comment by garethbowen** [comment]
I think this now happens because requests to _session go directly to couch not via api so the basic auth header isn't clobbered.

My proposed solution is to have the login page submit to an api URL (not _session directly) and have the api controller attempt to login and handle the response manually.
