### ISSUE TITLE
Reports list not updated when enketo forms submitted or edited

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1239]
The list of `reports` is no longer accessible on the `$scope` in `EditReportCtrl` at 56be5f65615a37ce43528158f636cbeaa8f0ce1e and https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/edit-report.js#L102.

I would expect the list of reports to now be available as `$scope.$parent.reports`, but I can't find a `reports` property attached to any scope in the hierarchy.

@garethbowen please advise!

**Comment by garethbowen** [comment]
The parent of EditReportCtrl is InboxCtrl, not ReportCtrl. This is because modals need to be at the root of the DOM to keep bootstrap happy and controllers and dom elements need to have the same hierarchy to keep angular happy. We're about to reorganise things a bit so the enketo forms are in the right hand pane, not in a modal so that might help.

Why are you unshifting the doc anyway? It looks like because a report has just been added you're trying to add it to the list of reports in the left hand side of the Reports tab. If so there are issues with unshifting the content, for example, if you are on any tab other than Reports.

I think the correct approach here is that the doc gets added to the DB, and the DB changes listener updates the view. This should already work out of the box. If so, remove the unshift and you're done.

**Comment by alxndrsn** [comment]
Nice - I'll give it a go.

**Comment by alxndrsn** [comment]
@garethbowen 9/10, but how do I set the selected report to the one that's just been submitted?  Or don't we care about that?

**Comment by garethbowen** [comment]
@alxndrsn Select an item by changing the URL to /reports/{id}. Something like this...

```js
if ($state.includes('reports')) {
  // on a reports page
  $state.go('reports.detail', { id: id });
}
```
