### ISSUE TITLE
Open form directly from task list

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1242]
In order to streamline the task-to-form process, we should have a task type which opens the associated form directly from the task list. This means that clicking on that task in the left pane shows the Enketo form in the right pane.

**Comment by garethbowen** [comment]
During the iteration planning meeting we thought the best way to do this would be to have the right pane still have the task meta data, but if there's an enketo form to show this should be rendered below the meta data immediately rather than requiring clicking on a button.

It's worth keeping in mind that a task may have zero, one, or many actions that can be taken. Possibly we should only automatically show the form when there is one and only one possible action.

**Comment by mandric** [comment]
After today's call we decided to skip the task detail rendering and go straight to the form if there is only one form and the description on the task is empty.

**Comment by abbyad** [comment]
This has been working well for many months. Moving to Ready.
