### ISSUE TITLE
Update to Enketo navigation buttons

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1249]
From feedback from several testers, we will not be showing the `submit` button until you have reached the end of the form. That means showing only `back` and `next` as such:
![image](https://cloud.githubusercontent.com/assets/789512/9688431/2eb94122-52fd-11e5-8910-c8fe4a70eb68.png)

When the end of the form is reached, instead of a `next` button it would show the `done` button in its place. The `back` button should be disabled when on the first page of the form.

**Comment by garethbowen** [comment]
Instead of disabling prev I'm just hiding it...

![first-page](https://cloud.githubusercontent.com/assets/2064938/9732437/f85b5d30-5677-11e5-9ca0-a3276dacee9a.png)
![middle-page](https://cloud.githubusercontent.com/assets/2064938/9732435/f8570884-5677-11e5-9c80-8c926b481395.png)
![last-page](https://cloud.githubusercontent.com/assets/2064938/9732436/f858fbee-5677-11e5-927b-66401baf884e.png)

**Comment by abbyad** [comment]
Looks good. Moving to Ready.
