### ISSUE TITLE
[Contacts] Person profile updates

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1262]
Three sections for the person profile page:
- **Base info**: Info from the person creation form. Ideally we could select which subset of info is being shown here since we want this to be compact so that the Tasks are not below the fold.
- **Tasks**: All tasks related to this person. Clicks through to the task's form.
- **Reports History**: All reports submitted about this person. Clicking through brings you to the report's view.

![image](https://cloud.githubusercontent.com/assets/789512/9692359/8588c9fa-5316-11e5-9a62-b75077fb98ca.png)

**Comment by browndav** [comment]
Advisory information for prioritization: if necessary, the report history feature may be deferred until after the October field test.

**Comment by garethbowen** [comment]
The outcome of the iteration planning was to have a new section for filing a new report between the Tasks and Reports History sections. This will have a button for each type of report. Clicking the button launches a report in the patient context. Think about whether this should update the URL, eg: `/contacts/{contactid}/form/{formid}`.

**Comment by garethbowen** [comment]
This is working but isn't very attractive. I think we need some design thought into how it should work on desktop and tablet, as well as for use cases other than LG.

Also, instead of having the task button link directly to the form to complete it currently links to the task itself. This is because the task could have multiple possible actions. This could be solved the same way as #1242 when it's done.
