### ISSUE TITLE
[enketo] current user should be set as form's `contact` and `from` fields on save/update

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1292]
Since #1214 an enketo Report is not attached to a particular user.  It should instead be tied to the currently-logged-in user.

**Comment by garethbowen** [comment]
It should be associated with a Contact not a User. Currently there is no association between Users and Contacts, and Users don't necessarily correspond to a User. This will need some thought.

**Comment by abbyad** [comment]
Currently:
- A user _can be_ associated to a place
- A place had a primary contact
We could associate the report to the user>place>primary contact. This may be suitable for the short term.

With CHWs loging in via mobile app, we may want to associate a user directly to a person. In the long term we may want to have a smoother integration of the user and person. For instance, an admin could create/manage a user from the person profile.

**Comment by garethbowen** [comment]
> A user can be associated to a place

Not precisely. A user can be _restricted_ to a place. I'm not sure permissions are the same thing as primary location.

I think you're right - every user that wants to file reports must have a contact associated with them. The more I think about it the more I think User and Contact should (conceptually) be the same thing.

**Comment by abbyad** [comment]
Good point. So far the place a user is restricted to is also their primary location. I can't see why that this will change for upcoming projects. That said, we may as well start working toward the ideal scenario.

**Comment by browndav** [comment]
For other SMS-only use cases, I could definitely see us having contacts (e.g. patients or CHWs) who we don't want to assign passwords to and/or provide any interactive access to the system over HTTP. So I might go with "every user must be associated with a contact, but not every contact needs to be associated with a user".

This would probably require that we start creating contacts at first-run, but we (i) talked about doing that already for unrelated reasons; and (ii) we need to patch `concierge` to create `UserSettings` documents anyway.

**Comment by garethbowen** [comment]
Going with the "every user must be associated with a contact" suggestion.

I think we should have a migration to create a contact for all existing users. This will

1. create unnecessary contacts for people using the SMS only setup, and
1. create duplicate contacts if an installation has already manually created contacts for users.

I don't think 1 is particularly serious, or 2 is particularly likely. Thoughts?

**Comment by abbyad** [comment]
For the migration, can we do the following:
1. If a user is associated to a place, associate the user to the primary contact of that place.
2. Not create a contact if the user type is any of the ones listed under "Computer" (eg Analytics or Gateway)
![image](https://cloud.githubusercontent.com/assets/789512/9923186/e1e1877a-5cbf-11e5-9e4f-f0492adcf062.png)

If the additional effort isn't considerable, then I think that this would be preferred since I can see it saving our project managers time when we finally upgrade instances from 0.4 to 0.6. 

That said, do we really need the migration at all? If we don't do contact association during the migration we run the risk of having a user not associated to a contact. What would happen then when they try to submit a report, and what would happen if a contact is deleted, but the previously related user tries to submit a report? If in any case we will need a mechanism to prevent those users from trying to complete a form and tell them to contact their admin, then we may not need to take any action upon migration.

**Comment by garethbowen** [comment]
The two options I can see for what to do if the user doesn't have a contact associated are, 1) don't even let them start filing the report, 2) allow them to file a report that isn't assigned to anyone. Currently there's no way to assign an Enketo report to someone after the fact (which probably deserves it's own issue) so option 2 might leave the report in limbo.

I propose we don't do the migration because most existing CHWs aren't also users, and don't let users without contacts create reports.

**Comment by abbyad** [comment]
> I propose we don't do the migration because most existing CHWs aren't also users, and don't let users without contacts create reports

That seems good to me.

**Comment by browndav** [comment]
+1 here

**Comment by abbyad** [comment]
Works well in my tests, both if user is associated to contact and not. Moving to Ready.
