### ISSUE TITLE
Access person/place profile's fields from within a report

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1310]
When starting a new form about a person or place we need to access a variety of fields from their profile. This is used for instance to prepopulate an ID field so that the form is attached to the appropriate person. From a Task the prepopulation is possible using the task rule. We need a way to do this for forms initiated from the person/place's profile page. 

Currently the `place_id`/`patient_id` can be passed to a report. We also want to use other fields such as Name, DOB, LMP, EDD, or any field configured for that project's profiles, so it makes sense to consider the work done in #1260 before tackling this.

This is a followup to #1060 and #1185.

**Comment by garethbowen** [comment]
In a separate conversation we talked about grouping by contact so when generating tasks you can easily access all reports for that contact, and also generate tasks when there are no reports for a contact. This would potentially solve this issue too as the contact would be available at the group level.

**Comment by abbyad** [comment]
That approach may help with passing the info via tasks, but some forms are only initiated from the profile page, such as New Pregnancy, or New Assessment. For example, in the New Assessment form we need to know the patient's age to change the recommendations.

This may be solved together with #1293 if the rules engine is used for showing relevant forms.

**Comment by abbyad** [comment]
This feature is needed to move forward with some form configuration. For instance within the Assessment form we use the child's date of birth to determine doses. 

To be future proof, we should consider passing all available patient fields, and using the new `inputs._{fields}` convention.

_In the Pregnancy followup form we use the LMP to determine which questions to ask and give recommendations. The LMP is not in the patient profile, but rather sits in a form. I think this may be a separate issue, but wanted to raise it here in case it is solvable concurrently. We could either find a way to put the LMP/EDD in the patient profile (this is ideal since it is visible to the user), or find a way to get the LMP to the form via the profile. For now the approach is to not show this form in the patient profile - it would only be available via a task, which can populate the LMP field. This may actually be preferred since the form would not be available when it is not relevant (complementing #1293)_

**Comment by abbyad** [comment]
@garethbowen I assigned this to you since you have the highest chance of getting to this before I get back to the form/task content early next week.

**Comment by garethbowen** [comment]
The tricky part of this is how to access the fields when the contact is selected as one step of the form, for example, when going from Reports > Submit Report.

**Comment by abbyad** [comment]
Ya, it would be ideal to have that resolved too. For now we can train users to access these forms via the contact profile. To avoid workflow issues the XForm can be configured to restrict submission via the Reports tab.

**Comment by garethbowen** [comment]
@alxndrsn Any thoughts on this? The prepopulation is fairly straightforward from both tasks and contact screens because we have the contact already. However when launching the report from the reports tab the contact will be selected from the dropdown. This will give us the entire contact doc so we can get all the data we need. How can we make that data available to subsequent calculations?

My initial thought is the form will need to be configured to have all the required contact fields which can be hidden and the widget would bind into them. These would either be grouped or namespaced so we can bind all the configurable fields on the patient on to the form without overwriting other fields.

**Comment by alxndrsn** [comment]
@garethbowen something like that sounds sensible.  Simplest to implement might be to have an empty section of model such as:
```xml
...
<inputs>
  <person>
    <name/>
    ...other fields
  </person>
  ...
</inputs>
```
You can probably get hold of a direct reference to the model via `form.getModel()` inside the widget, and set this stuff directly, although this may not be as 'correct' as binding via hidden fields etc.

**Comment by garethbowen** [comment]
This change means if you have a dropdown that binds a patient then we will attempt to bind to other fields in the selected object at the same root. For example, if you have:

```xml
<model>
  <bind nodeset="/data/patient/id" type="db:person" required="true()" />
  <bind nodeset="/data/patient/name" type="string" />
</model>
```
Then when a patient is selected from the dropdown, if the patient has a `name` field, the value will be bound to `/data/patient/name`.

Another change as part of this is the entire contact doc is bound to inputs, not just the id. Existing configurations will have to be updated so...

```xml
<inputs>
  <patient_id/>
</inputs>
```

becomes

```xml
<inputs>
  <patient>
    <_id/>
  </patient>
</inputs>
```

Tasks actions should be updated so instead of just passing in the id the entire contact is passed in, eg:

```js
visit.actions.push({
  ...
  content: { patient_id: r.fields.patient_id }
});
```

becomes

```js
visit.actions.push({
  ...
  content: { patient: c.contact }
});
```

**Comment by alxndrsn** [comment]
Looks good; minor comments on PRs.

**Comment by alxndrsn** [comment]
This has causes #1454

**Comment by alxndrsn** [comment]
I can see how this could work, if the existing forms and form generation is changed.

**Comment by alxndrsn** [comment]
This also requires changes to form generation.

**Comment by garethbowen** [comment]
Was there just #1454 to fix or is something more needed here too?

**Comment by alxndrsn** [comment]
#1454 was all I found.

**Comment by abbyad** [comment]
Works well, moving to Ready.
