### ISSUE TITLE
Turn on CORS by default

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1317]
CORS is [required by PouchDB](http://pouchdb.com/errors.html#no_access_control_allow_origin_header) so we should turn it on in medic-os. Consider the security implications.

**Comment by garethbowen** [comment]
Before doing any work establish if CORS is actually required by our replication workflow.

**Comment by browndav** [comment]
If I'm understanding things correctly (big if): I think PouchDB marks CORS as required because they're assuming that the web server URL and CouchDB URL will differ by port (e.g. in their example, the web app is being served by localhost:8000 and CouchDB is on localhost:5984). Differing ports count as different origins per the MDN docs, so CORS would be necessary in that case to make the XHR request. Because we're proxying everything through nginx and medic-api, we use port 80 for all HTTP/HTTPS traffic and shouldn't strictly need CORS at all.
