### ISSUE TITLE
Application cache does not load changes after an exception

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1352]
# Environment
Chromium 44
# Steps to reproduce
1. browse to `medic-webapp` (logged in)
1. stop the server
1. observe a pouch error similar to:

> `GET http://localhost:5988/medic/_changes?timeout=25000&feed=longpoll&since=29376&limit=25&_nonce=1443629241197 net::ERR_INCOMPLETE_CHUNKED_ENCODING`

1. restart the server
1. observe that the app does not prompt you to reload

This seems to happen for any `Error` thrown, even if it is not pouch, and happens _before_ the server has been stopped.

# Expected behaviour
The prompt to reload the app/assets should still happen even if there were other errors - it may even be *more* important in that case!

**Comment by browndav** [comment]
Decision: can be worked around for Monday's demo.

**Comment by alxndrsn** [comment]
Shouldn't be any code changes during the demo, so no need to reload app cache.  Hopefully no exceptions either, of course!

**Comment by garethbowen** [comment]
This seems more random than just when an exception is thrown.

The ddoc changes feed errors out with:

```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Stack trace:
onSuccess@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:38207:15
ajax/<@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:38295:7
xhRequest/xhr.onreadystatechange@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:38635:7
xhRequest/abortReq@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:38562:5
```

After this is never recovers.

Interestingly this changes feed is in the DB service and uses different code to the Changes service. The latter doesn't seem to get cancelled. It might be possible to hook in to the Changes service rather than registering a dedicated listener, or at least use the Changes service as a guide to fixing this.

**Comment by garethbowen** [comment]
The ddoc is kept up to date using a dedicated Changes listener.

We opted out of using replication because our ddoc has lots of server side code (eg: sentinel, api) for deployment which isn't needed on the client side. This means we can't efficiently replicate the ddoc until PouchDB has an option for [excluding attachments from replication](https://github.com/pouchdb/pouchdb/issues/4362).

Unfortunately the Changes api doesn't have a `retry` option so when it errors it never recovers.

We'll need to implement our own retry handling, and try to work out why the Changes feed is failing so often.

**Comment by garethbowen** [comment]
I've added a retry so it's more robust. I'll replace this with replication once the PouchDB issue is resolved.

**Comment by alxndrsn** [comment]
Code looks nice, but doesn't appear to work for me :¬(

**Comment by garethbowen** [comment]
Yeah I think I can see a problem. I wait for 10 seconds then register the listener from 'now' which means if the change came in during that 10 seconds it won't fire the modal. I'll have another look.

**Comment by garethbowen** [comment]
It should now work reliably, though you may have to wait up to 10 seconds for the notification to appear.

**Comment by alxndrsn** [comment]
Working good :+1:
