### ISSUE TITLE
[enketo] Markdown in Notes not rendering

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1354]
Using develop, the markdown in Enketo note field was rendering properly last week, but currently doesn't.

**Comment by browndav** [comment]
Hey @alxndrsn, if you have a second can you look in to this? We're hoping to have this working for the SF demo on Monday, as a lot of the forms have instructions/text associated with them.

**Comment by alxndrsn** [comment]
Here's the problem https://github.com/enketo/enketo-core/commit/22846d9eb933d86d5628ff032bc07a9bac03a79e

**Comment by alxndrsn** [comment]
If we have a markdown lib available anywhere else in the app, it would probably make sense to use that.  Above I have just imported the implementation from enketo-core (i.e. https://github.com/enketo/enketo-core/commit/22846d9eb933d86d5628ff032bc07a9bac03a79e#diff-8976b944a21c1533787f38cb75e407daL75), although it is no longer applied to the jquery object prototype.

**Comment by mandric** [comment]
I see markdown converter in two places in the source code but I'm not sure they are being included in the app...

packages/dust/node_modules/dustjs-linkedin/vendor/showdown.js
packages/showdown

**Comment by alxndrsn** [comment]
Yep, my scientific test was to open `static/dist/inbox.js` and search for `showdown` - no results :¬)

**Comment by mandric** [comment]
I don't think we're using a markdown anymore for the help pages because [the html is stored in the translations](https://github.com/medic/medic-api/blob/develop/translations/messages-en.properties#L375).  So appears we are not storing markdown anymore.  I will remove packages/showdown since it's not used anywhere and you can decide if you want to include a markdown lib or leave as-is if it suffices for this issue.  Seems generally useful to have a markdown lib available but up to you if you want to tackle in this issue or not.

**Comment by alxndrsn** [comment]
I'd stick with this - minimal code, and it's the same code that's worked up til now.

**Comment by abbyad** [comment]
Works well, moving to Ready.
