### ISSUE TITLE
Access person/place profile's fields from within a task

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1357]
Similar to #1310, but specifically to access a person's info from a task so that we can use it in the Task title or details - and can also be used to populate fields in the action's form.

**Comment by garethbowen** [comment]
Instead of tasks being Report centric they are now Contact centric. This will break all previous nools configurations completely. In your configuration...

Replace `define Report` with

```js
define Contact {
  contact: null,
  reports: null
}
```

Add `contact` to your Task definition, eg:

```js
define Task {
  _id: null,
  doc: null,
  contact: null,
  icon: null,
  date: null,
  title: null,
  fields: null,
  resolved: null,
  reports: null,
  actions: null
}
```

Change your `when` block to:

```js
  when {
    c: Contact
  }
```

Loop over reports, eg: `c.reports.forEach(function(r) { ... });`.

Stick the contact on the task so you can access it in the title or details.

**Comment by abbyad** [comment]
This has been working well throughout the field test. Moving to Ready.
