### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1366]
I added it manually on the lg.dev instance but flagging it here to add to the proper translation files.

**Comment by garethbowen** [comment]
Related: #1333

**Comment by abbyad** [comment]
List of missing translations:
- [ ] clinic.field.children
- [ ] person.field.national_id_number
- [ ] person.field.date_of_birth
- [ ] person.field.alternate_phone

**Comment by garethbowen** [comment]
`action.clinic.add` is defined in the default translations. The others are all fields that are specific to LG and should be added to medic-projects. I suspect this is already done. @abbyad Can you confirm?

**Comment by abbyad** [comment]
All of those are in the LG config. @garethbowen, how do we differentiate project specific fields vs built in fields? I would have expected `clinic.field.children` and `person.field.date_of_birth` to also be included in all projects moving forward.

**Comment by garethbowen** [comment]
IMO anything that's defined in medic-projects should be translated in medic-projects to keep them in sync. eg: `person.field.date_of_birth` is defined in the enketo form definition for person (I assume) so the translation should be stored in the config right beside the form definition. Otherwise we could end up with many unused translations just taking up space and bandwidth.
