### ISSUE TITLE
Fix form type filter

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1409]
The form type filter lists all available JSON forms but it should be a combined list of JSON and Enketo forms.

**Comment by abbyad** [comment]
When we include XForms it may be better to only show the form title and not the ID.

XForm IDs aren't intended to be user friendly, and even when they are legible they push the actual form title away:
![image](https://cloud.githubusercontent.com/assets/789512/13861970/653c2a28-eca1-11e5-8093-52c5c68fe180.png)

**Comment by abbyad** [comment]
This is only showing the forms that can be submitted via the Reports tab given their context:

![pasted image at 2016_04_06 06_45 pm](https://cloud.githubusercontent.com/assets/789512/14337069/7ea75b62-fc38-11e5-8417-c3563bc1cf86.png)

It should however include all non-contact XForms - meaning all forms except for the contact forms.

**Comment by garethbowen** [comment]
@abbyad Why can't all non-contact forms be submitted via the reports tab?

**Comment by abbyad** [comment]
Some forms require info from a previous form so if you were to open those forms from the history tab you wouldn't get the necessary info to complete that form. For instance, the ANC visit form relies on the LMP from the registration form, and without it the form could not be adequately completed. Similarly, from the patient profile we are only showing forms that can be completed independently. 

If we want to pass info to a form we have to create a task and populate some fields via the rule. In the future we will want to be bring in data from a previous form to any form, regardless of where it is opened. We had not prioritized this for this release since it was not a requirement, although it would have come in handy. I suspect this will be a prominent feature request for a future release.

**Comment by sglangevin** [comment]
Looks good!
