### ISSUE TITLE
For the field test, names should be re-ordered as Surname Given Names

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1477]
When users create people, they will enter Surname (e.g. Nesbit) and then Given Names (e.g. Josh). We should display names as Surname Given Names throughout the app, including the contacts list, on profile screens, and in forms. This change is needed for family names (e.g. Nesbit Josh family) and names of people (e.g. Nesbit Josh).

**Comment by abbyad** [comment]
I made the change in the form for families, including the caregiver and children registered at that time.

We likely still need to update the [contact-schema](https://github.com/medic/medic-webapp/blob/9f28297e670d195db596d0c4fddbc702abc1f88f/static/js/services/contact-schema.js#L66) so that the name change is also in effect for family members added after the initial registration.

**Comment by garethbowen** [comment]
I think you should just provide your own xform configuration to supplant the default contact schema generation code and then you can configure whatever LG specific concatenation you like.

**Comment by abbyad** [comment]
Moving to Ready.
