### ISSUE TITLE
Passing info to the person creation forms

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1490]
When using the /add/person form to add family members we want to populate some of the fields using the parent's fields (eg last name, phone numbers). 

When accessing our forms from the context of a contact we can access the contact's info via inputs (eg `/inputs/patient/last_name`). It would be convenient to use the same method to access the contact data when adding people as well.

**Comment by garethbowen** [comment]
From looking [at the code](https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/contacts-edit.js#L93) it looks like when adding a person to a family the prepopulation data is `{ parent: 'abc' }`. Instead we should fetch the parent from the database and pass that in so the form has access to all the parent fields.

This information is passed in to the [jsToFormInstanceData function of the EnketoTranslation service](https://github.com/medic/medic-webapp/blob/develop/static/js/services/enketo-translation.js#L244). This function doesn't handle nested properties so we wouldn't be able to access `parent.contact.last_name` (for example). The Enketo service has a similar method of getting xml instance data from a json object which works recursively so we should just pass in the `$scope.contact` object instead of using the jsToFormInstanceData function. As this is the only use of the jsToFormInstanceData function it can then be deleted.

I think these two changes will allow Marc to access all the fields he needs.

**Comment by abbyad** [comment]
This is still useful, but no longer needed for the field-test as we wont populate the last name and phone numbers for the children.

**Comment by garethbowen** [comment]
I've done the second part of my suggested solution as part of #1392 which just leaves the fetching the parent from the DB to go.

**Comment by sglangevin** [comment]
Is this still needed? cc @abbyad

**Comment by abbyad** [comment]
Seems as though current projects are doing well without this so I think this can wait until it comes up again for a project.

**Comment by abbyad** [comment]
Closing as this hasn't come up again since.
