### ISSUE TITLE
Freetext search should split the search key

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1500]
Searching for `Laurel`: result includes the person named "Laurel Smith"
Searching for `Smith`: same as above, finds "Laurel Smith"
Searching for `Laurel Smith`: result **does not include** "Laurel Smith"

Tested on lg.dev running 0.6.0-alpha.2244

**Comment by garethbowen** [comment]
This is because we don't split the search key. To fix this do 1 request per search word and get the intersection of the results. This is a slight performance hit but nothing major.

**Comment by abbyad** [comment]
From my testing the `name` field is included in the search, so I am not sure why we'd need to split the search key.... but whatever works!

![image](https://cloud.githubusercontent.com/assets/789512/10887392/c55bf16c-8154-11e5-881e-4c81790888a1.png)

**Comment by alxndrsn** [comment]
@garethbowen I hope you're suggesting we fix this in code - I'd hate to be the user having to process those intersections :¬p

**Comment by alxndrsn** [comment]
@abbyad on re-reading this I'm confused - did you try searching for _Smith Laurel_?  Your initial report and your screenshot suggest that probably the mix up is caused by having fields called _first_name_ and _last_name_, but combining these fields in the opposite order than their names would suggest.

**Comment by garethbowen** [comment]
@abbyad Because we always split the keys in the keys for this will be something like: 'laurel', 'smith'. We also include the fields with a prefix so you can search specifically on them, eg: 'first_name:laurel', 'last_name:smith', 'name:"smith laurel". So searching for "laurel smith" or "smith laurel" won't match any of the above. We do a starts with search so searching for "laur" will work. But we really should be doing a tokenised starts with search so "laur smi" looks for records with "laur*" and "smi*". If you're interested in the keys have a look at the `contacts_by_freetext` view in couchdb.

This probably worked previously when we used lucene.

**Comment by abbyad** [comment]
@alxndrsn: sorry for the confusion, I used "Laurel Smith" just as the example, but did in fact search for it the way it was in the `name` field.

@garethbowen: thanks for the clarification.

**Comment by estellecomment** [comment]
Cool!
