### ISSUE TITLE
Clicking on contacts tab in mobile should show the list of contacts

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1515]
Sometimes, clicking the contacts tab auto-opens the first contact. This happens most often after switching away from the contacts tab and then clicking back into the contacts tab. After exiting the profile view and viewing the contacts list, I can switch between tabs without problems. I've reproduced this on phones and in firefox on lg.app as demo.

I'd expect to be able to click the contacts tab and view my list of contacts.

**Comment by garethbowen** [comment]
All the list-detail views check `$('#back').is(':visible')` to detect if we're running in mobile or not to help determine whether or not to select the first item. I suspect the recent changes to the back button making it not visible at all times in mobile have made this an unreliable test. Consider replacing it with something more robust.

**Comment by mandric** [comment]
We can't use `:is_visible` here, it returns false because height/width is zero.  https://api.jquery.com/visible-selector/  

Will replace with `$('#mobile-detection').css('display') === 'inline'`

![screen shot 2015-11-05 at 2 07 46 pm](https://cloud.githubusercontent.com/assets/25641/10973997/0fdc5000-83c7-11e5-8bf6-bd411d3f8438.png)

**Comment by garethbowen** [comment]
Good catch!
