### ISSUE TITLE
Contacts do not load

### ISSUE THREAD

**Issue by fredatthehub** [medic/medic-webapp#1516]
![loading](https://cloud.githubusercontent.com/assets/2064938/10928464/5f963a58-830d-11e5-965c-00240017f272.png)

**Comment by browndav** [comment]
Clarification question: is this in the Chrome's responsive mode, on Chrome Canary but not previous builds of Chrome, or across-the-board everywhere you've tested?

**Comment by fredatthehub** [comment]
@dave, Chrome Canary's responsive mode

**Comment by garethbowen** [comment]
I'm seeing it in Chromium desktop mode. The workaround is to select another tab and the select Contacts again.

**Comment by fredatthehub** [comment]
Yes. Any idea how take a screen-shot of the device emulation only?

**Comment by garethbowen** [comment]
Steps to replicate is something like: load Reports tab, refresh, select Contacts tab.

**Comment by garethbowen** [comment]
This was due to the task generator querying for all contacts, at the same time as the contacts LHS was querying for all contacts. Because the exact same query was initiated at the same time the Search service thought it was a user double clicking search and killed the second query. I've added an option to the Search service to ignore debouncing to fix this.

**Comment by alxndrsn** [comment]
Seems over-complex - why not just prevent the user triggering multiple searches via the UI, and ditch all "debounce" code?

**Comment by garethbowen** [comment]
I'm not convinced there will be less code or less complex code doing it in the UI, but it is more appropriate now that we're using search for other things. Is it ok with you if we raise a technical debt issue for this?

**Comment by alxndrsn** [comment]
Yep, fine by me.
