### ISSUE TITLE
Ensure that video works in mobile app

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1531]
Right now video within a form plays in browsers, but not in the mobile app on the Tecno Y4.

[Sample video](https://github.com/medic/medic-projects/blob/master/lg-uganda/forms/timer.mp4)

**Comment by alxndrsn** [comment]
This video definitely plays on tecno's browser when embedded in HTML `<video>` tags - demo at https://alxndrsn.github.io/test-video/

**Comment by abbyad** [comment]
What browser version is it? The assessment form in the LG app has the video as well if you want to see it within app.

**Comment by alxndrsn** [comment]
Updated test page now with object URL video: https://alxndrsn.github.io/test-video/

I suspect videos from Object URLs are not supported: https://code.google.com/p/chromium/issues/detail?id=346718#c7

**Comment by alxndrsn** [comment]
Proposed solutions:

1. modify pouch to save `attachments` to disk instead of to `localStorage`; link directly to these using the `file://` protocol
2. ???

**Comment by alxndrsn** [comment]
Updated test page now with object URL video: https://alxndrsn.github.io/test-video/

I suspect videos from Object URLs are not supported: https://code.google.com/p/chromium/issues/detail?id=346718#c7

The suggestion above is that Chrome on Android will only play videos served from either `http[s]?://` or `file:` URLs.  This means we either need to stream videos from the server, or save them locally before playing them.

-----

# Proposed solutions:

1. temporarily save file locally just before playing
1. modify pouch to save `attachments` to disk instead of to `localStorage`; link directly to these using the `file://` protocol

# Modifying pouch

This should involve overriding the behaviour of 

- http://pouchdb.com/guides/attachments.html

**Comment by browndav** [comment]
Counter proposal: implement a timer widget using native HTML and CSS, after verifying that we're able to play audio (either a simple tone or a waveform) on the mobile device by some means.

**Comment by alxndrsn** [comment]
Embed a timer in a form like this:
```xml
    <input appearance="countdown-timer" ref="/data/timer">
      <hint>Poke the timer to start it.</hint>
    </input>
```
The `hint` text will appear above the widget:
<img width="376" alt="screen shot 2015-11-10 at 11 53 56" src="https://cloud.githubusercontent.com/assets/191496/11060644/c8f3bc4e-87a1-11e5-921a-2b5887fb0366.png">
Use a `label` or `note` to display text below.

The duration of the timer can be set in the associated data item.  If no value is set, the duration will default to 60s.  E.g. for a 9 second timer:
```xml
    <model>
      <instance>
        <data id="TMR" version="2015-06-05">
          <timer>9</timer>
```

**Comment by alxndrsn** [comment]
# N.B. this work did not fix video issues!  We just added an animation specifically for countdown timer

**Comment by abbyad** [comment]
Works great, nice job @alxndrsn. Moving to Ready and will update the issue title to reflect the approach taken.
