### ISSUE TITLE
Standardise HBB, `<` and `X`

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1564]
<img src="https://cloud.githubusercontent.com/assets/763977/10923764/995967dc-8237-11e5-977a-ef9e2c16538f.png">

# From the diagram:

## Filter-bar Button

* [x] this will always be an X sometimes and a < sometimes
* [x] if editing some object **_O_** -> view **_O_**
* [x] if creating a new report in context of a contact **_C_** -> view **_C_**
* [x] if creating a new person in context of a contact **_C_** -> view **_C_**
* [x] if following up a task **_T_** and task has multiple actions -> view **_T_**
* [x] otherwise, go to LHS _done on branch_

### keyboard open

* [x] close keyboard _(built in)_

### select2 open

* [x] close select2

### viewing content ("RHS")

* [x] if editing an enketo form and not on first page, go to previous page
* [x] otherwise, do as per filter-bar button

### viewing list ("LHS")

* [x] if on primary tab, close app (`activity.finish()`) _[done]_
* [x] otherwise, return to primary tab _[done]_

### viewing login screen

* [x] quit app

**Comment by alxndrsn** [comment]
The `livinggoods`-branded `medic-android` build compatible with the webapp changes (`0.1.102`) is uploaded to appstore.  This will need an update to `lg.app` to work.

Uploading `unbranded` to appstore fails.

**Comment by abbyad** [comment]
That diagram was missing the drilled in RHS for contacts. The case for that is mentioned in https://github.com/medic/medic-webapp/issues/1513#issuecomment-153474186.

The top bar back button should drill out, rather than going straight to the top level.

Also, from early tests it seems as though the `x` and `<` are swapped. We should use the chevron for navigating back, and the close button when exiting a form (discussed in https://github.com/medic/medic-webapp/issues/1513#issuecomment-153410221)

**Comment by alxndrsn** [comment]
@abbyad I have switched `<` and `X` as per your request.

**Comment by alxndrsn** [comment]
#1565 has been split from this ticket to detail more complicated behaviours of the HBB and filter-bar-back buttons.
