### ISSUE TITLE
HTTP 500 when attempting to replicate from PouchDB back to CouchDB

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1570]
I'm seeing persistent HTTP 500s after adding data in offline mode on the Tecno Y4 and then reenabling internet connectivity. Investigate this and figure out why it's happening.

<img width="787" alt="replication-http-500" src="https://cloud.githubusercontent.com/assets/763977/11161622/b3626726-8a36-11e5-875f-e098d577efe9.png">

**Comment by browndav** [comment]
I've unassigned myself just to make it clear that additional testing/troubleshooting is welcome.

**Comment by abbyad** [comment]
I am seeing something likely related in the browser, with a 500 every 2-3 seconds:

![image](https://cloud.githubusercontent.com/assets/789512/11161792/08c0ed14-8a55-11e5-8150-d93bfe6bfe70.png)

**Comment by browndav** [comment]
That exactly matches what I'm seeing.

**Comment by garethbowen** [comment]
There is an error in the api log which looks like it's the other side of this bug:

```
2015-11-16T00:05:58.242Z - info: 127.0.0.1 - demo [16/Nov/2015:00:05:58 +0000] "POST /medic/_bulk_docs?_nonce=1447632358193 HTTP/1.0" - - "https://lg.app.medicmobile.org/medic/_design/medic/_rewrite/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2561.0 Safari/537.36"
 
2015-11-16T00:05:58.399Z - info: ERROR Failed retrieving existing document. Error: missing
 
2015-11-16T00:05:58.405Z - info:   detail: "Failed retrieving existing document. Error: missing"
```
That error message comes from the audit code. It tries to detect if it's a new doc based on the rev (eg: `_rev: '2-xxx'`), and then attempts to get it from the database which fails because it hasn't been added yet. I'll have a look at updating the code to check for the existence of the doc rather than checking the rev prefix.

**Comment by alxndrsn** [comment]
(closed in error - waiting for code review)

**Comment by browndav** [comment]
Reviewed; LGTM. Closing and moving to acceptance testing.
