### ISSUE TITLE
Handle page load fails and illegal URLs elegantly within the android app

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1641]
- [ ] if the app attempts to load an external URL, we should open that in a separate browser
- [ ] if the app detects a page timeout or server not found, it should display helpful native-android error messages, including options to try again/go back to start/etc.

Related: #1606, #838

**Comment by SCdF** [comment]
@browndav please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by browndav** [comment]
I'm somewhat torn on this one. As best as I can understand, this seems to be proposing that we capture 4XX/5XX errors and timeouts on the Webview's main page load only, and respond with a custom message. This seems like it'd have to be done carefully to avoid false positives (e.g. avoid erroring out on XHR requests). It also seems like the non-timeout might be better located in-app, so that all visitors would benefit from improved error messages.

My proposal: close this. Open independent issues for external URL loads and timeout/error messages as they become priorities or as technical debt / slack time allows.
