### ISSUE TITLE
Server side replication performance analysis

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1665]
We recently had 20 users log in and perform regular actions and noticed some performance issues. In particular beam.smp was clocked using up most of a CPU.

Investigate and benchmark server side performance, attempt to make improvements, and benchmark again.

**Comment by garethbowen** [comment]
My suspicion is that filtered replication is a significant bottleneck. This is because the results of the filter function aren't cached so every time a user replicates couchdb has to execute the function on every document. Ideally we'd use a view so the filtering was done on write, not on read, however it's unclear from the documentation if you can pass parameters to a view via a filter.

**Comment by garethbowen** [comment]
Shockingly, view filtered replication is slower than function filtered replication. Don't ask me how that makes sense. I also couldn't get the parameters working so it looks like filtering by view is a non-starter.

**Comment by garethbowen** [comment]
Pouch plugins that may help replication performance:

- https://github.com/nolanlawson/pouchdb-load
- https://github.com/nolanlawson/pouchdb-replication-stream and associated community of plugins
- https://github.com/nolanlawson/socket-pouch

**Comment by estellecomment** [comment]
For first sync of data : 
Just ran into PouchDB Load too, and its friend PouchDB Dump. 
http://pouchdb.com/external.html#plugins
Produce a dump file, then load it into another DB, and the resulting DB will be in the same state as if it had gone through replication. Neat!

Sounds better than using a view query, since it avoids reimplementing the filter as a view. 
Ideally we'd need to create the dump file on-demand in the server code, and return it (? in medic-api?). Or pre-compute it every so often (the changes that are missed would be fetched over replication later, that's fine)

**Comment by garethbowen** [comment]
Closing as we've made lots of improvements to replication performance since this was raised, for example, using erlang for the filter, reducing the number of documents, etc.

It looks like the next big improvement will come with couchdb 2.0 with bulk get functionality.
