### ISSUE TITLE
Prevent CHP user from editing uname & password

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1683]
Should probably block access to _Edit user Profile_

**Comment by alxndrsn** [comment]
@abbyad this will require suitable extra permissions to be set up (i.e. _____)

**Comment by browndav** [comment]
Why are we trying to block our users from managing their own password? What's the rationale for this?

**Comment by garethbowen** [comment]
We need to figure out how to define all the permissions somewhere. At the very least document them...

**Comment by mandric** [comment]
What was the reason for doing that?  Kind of wish we just stayed with `can_*` instead of introducing `cannot_*`.  Is that so you can explicitly exclude roles from certain permissions without knowing ahead of time what roles are available?  Because it seems ideal (more straightforward) to know what roles are available on a deployment and just include the ones that are allowed in the `can_*` permission then implicitly anyone not in the `can_*` permission is denied.

**Comment by alxndrsn** [comment]
@mandric  `cannot_` did not seem to complicate the permission logic, but it did expose a bug in it.  You are correct, it would be possible to use a `can_` permission and add extra config.

What state is this ticket now in?  `Open` but in `Acceptance testing` is confusing.

**Comment by alxndrsn** [comment]
Done in b67a4b1c42fe8cc12aa596552497b9ffdc611ec5
