### ISSUE TITLE
"Add New Family" should be "Add New Place" (confusing UX)

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1766]
The "add family" button leads you to add three types of places (District, Health Center, Catchment), but not family. 
![screen shot 2015-12-16 at 09 58 10](https://cloud.githubusercontent.com/assets/911434/11836603/0fd9cca6-a3dc-11e5-9b1e-25fad346c6ed.png)

**Comment by abbyad** [comment]
Thanks for pointing that out @estellecomment. 

In our first deployment of v0.6 the following labels are used:
District = `Branch`
Health Center = `CHP Area`
Catchment Area = `Family`

And the `action.clinic.add` key should be "Add Place" in the generic form. It seems that the base config that we have going in 0.6 so far may be mixing the two naming conventions.

**Comment by estellecomment** [comment]
Actually it does say "Add new place" once you have places created, see screenshot.
The bug is just for when you have no contacts.
![screen shot 2015-12-16 at 14 19 19](https://cloud.githubusercontent.com/assets/911434/11841891/7522ad34-a400-11e5-82ed-ab1f8525f883.png)

**Comment by abbyad** [comment]
Ah ok, thanks for clarifying. This is a by-product of trying to simplify the interface for CHW users so that they can only see and add to their own place. Because of this, there is logic to show "Add Family" instead of "Add Place" if the user does not see any places outside of their own assigned place. When there are no contacts at all that is the case even for all users. 

That doesn't explain why the _Add Family_ shows the more general _Add Place_ on the right though... We need to sort all that out along with the other _Contacts_ design issue mentioned in #1767.

**Comment by alxndrsn** [comment]
> That doesn't explain why the Add Family shows the more general Add Place on the right though...

Admins can create places, so they see the option of different places to create.  It looks like the bug here is in the logic deciding whether to show `Add Clinic` vs `Add Place` - this should be determined the same way that the right-hand pane decides whether to go directly to the Clinic form, or display the choice of place types.

**Comment by sglangevin** [comment]
This should be resolved by the updated people tab - only one type of place can be created on the LHS, other places are created on the RHS. Closing - please re-open if needed.
