### ISSUE TITLE
Requesting audit log makes server unresponsive

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1789]
When requesting the audit log via `configuration/export` the server became unresponsive for about 10 minutes.

Marking as a bug as this could have adverse effects.

**Comment by browndav** [comment]
Is this locally or on a specific hosted instance?

**Comment by abbyad** [comment]
Saw it happening on lg.app

**Comment by sglangevin** [comment]
Cannot export Audit logs on v2.10. Ideally we should fix this in v2.11 so that we can access these logs when supporting projects. Moving into this iteration.

**Comment by estellecomment** [comment]
Looks like the same behavior as https://github.com/medic/medic-webapp/issues/2695, except for audit logs. 
Reproduced on both local and lg.dev.

The fetch from couch happens ok (1000 docs, I can print them out from api code), 200.
And then the streaming to client fails silently somewhere along the way. No errors in api log (at least locally, gonna check on server...).
With a smaller audit db, or a `limit=<smaller number>` db query, it goes through all right.

**Comment by estellecomment** [comment]
Looks like we're doing the download weird: we're downloading the whole thing into browser memory, and THEN opening the dialog box and starting the write to file. Instead of streaming to file. So browser is having memory problems.

Network request fetching 16MB of audit logs into memory:
![image](https://cloud.githubusercontent.com/assets/911434/23624279/8a9bbd36-02a5-11e7-86f5-e789fd6329c9.png)

So next, checking how [ajax-download](https://github.com/medic/medic-webapp/blob/master/static/js/modules/ajax-download.js) is working...

**Comment by estellecomment** [comment]
@SCdF please review : https://github.com/medic/medic-webapp/pull/3210
Want a test? Unit test didn't seem very relevant, but e2e test probably more so.

**Comment by SCdF** [comment]
@estellecomment yeah a protractor test would be pretty cool

**Comment by estellecomment** [comment]
Lunch would be even cooler, so I'll do that, and then tackle this second-coolest thing in my life, a protractor test

**Comment by SCdF** [comment]
@estellecomment forgot to drop my assignment, reviewed, made comments, back to you.

**Comment by estellecomment** [comment]
Submitted the code, still needs e2e test ideally. Part way done in https://github.com/medic/medic-webapp/pull/3210

**Comment by garethbowen** [comment]
The e2e testing has been split off to #3303 so this can be ATed.
