### ISSUE TITLE
Merge master to develop

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1805]
Related : #1342 (merge to testing)

**Comment by mandric** [comment]
This will likely never happen because it causes the tree and visual git log/history/visual tools to make our commit tree look very ugly, master and develop have diverged too much.  Also resolving the conflicts is unrewarding and probably not valuable work since it causes git log ugliness.  We're much more likely to merge master to `v0.4` branch and do security and bug fixes on that branch and cherry picking going forward until v0 EOL.

**Comment by garethbowen** [comment]
Closing as I agree with @mandric - we've diverged to far for this to be reasonably done, or even useful.
