### ISSUE TITLE
Nginx: enable gzip/deflate for application/json, including longpoll APIs

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1828]

**Comment by SCdF** [comment]
Note: there are some conversations on #1777

**Comment by browndav** [comment]
I'll take this one. IIRC, all that needs to be done is to (1) modify the nginx configuration to turn on deflate for `application/x-json`; (2) retest the longpoll endpoints to make sure we weren't just hallucinating that bug; then (3) selectively turn off deflate for any of the longpoll endpoints that were shown to not work.

**Comment by browndav** [comment]
Update
------

I can't find any reason for gzip or deflate to have been disabled for `application/json`. I've updated `lg.dev` to a new nginx configuration, added some additional deflatable MIME types for fonts and images, and done some basic testing with no apparent problems. Performance appears to be improved considerably:

App load time
------------------

Before: 32 requests, 2.7MiB, 19.11 seconds.
After: 32 requests, 1.6MiB, 12.48 seconds.


Changes feed
-------------------

$ curl 'https://admin:********@lg.dev.medicmobile.org/medic/_changes?style=all_docs&heartbeat=10000&since=0' --silent --write-out "%{size_download}\n" --output /dev/null
954617

$ curl -H 'Accept-Encoding: gzip, deflate' 'https://admin:********@lg.dev.medicmobile.org/medic/_changes?style=all_docs&heartbeat=10000&since=0' --silent --write-out "%{size_download}\n" --output /dev/null
283800

Comparison notes
----------------

App load time is measured relative to the old configuration, i.e. with `application/json` and a few other image/font-specific MIME types excluded, not against a gzip-disabled configuration. The changes feed comparison _is_ a deflate-off vs. deflate-on, since it's `application/json` when requested from our app (read: with `Accept: application/json` set).

Merge, Testing
--------------

I've left this configuration in place for `lg.dev` so we can dogfood it. I'll merge the configuration change to medic/medic-os before tomorrow morning NZST.

**Comment by browndav** [comment]
Follow-up tasks:
  - [ ] I still need to test a full application update via Garden.

**Comment by browndav** [comment]
Problem: Dashboard relies on the `ETag` header to discover the design document's `_rev`, which changes when gzip or deflate is enabled, causing dashboard to request a document with a bad `_rev`, leading to update failure.

Problem is here: https://github.com/garden20/dashboard-core/blob/master/lib/dashboard_core.js#L898

I'll look in to (in order of preference): either getting the `_rev` another way, selectively disabling `Accept: gzip,deflate,sdch`, or finding some way to pass through the `_rev` differently as a header.

**Comment by browndav** [comment]
Actually, it looks like it's the same ETag, just prefixed with a `W/`. I'll do some quick reading on ETags and `Accept-Encoding`, and then I think it should be a relatively easy dashboard patch.

**Comment by browndav** [comment]
Final to-do items:

- [ ] Push dashboard-core `0.0.6` to Kanso repository
- [ ] Bump `dashboard` version number to trigger a CI build/release

**Comment by alxndrsn** [comment]
@browndav is there still stuff to finish up on this ticket, or do you want someone else to review it?

**Comment by browndav** [comment]
Just the two final items above, then I'll unassign/close and move to acceptance testing.
