### ISSUE TITLE
Code opt for size : split inbox.js

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1830]

**Comment by garethbowen** [comment]
There is a balance between multiple small files and a few large files. Smaller files lead to a larger overall download size, and longer download times due to limits on parallel downloading. Few files lead to overzealous cache invalidation and large individual downloads. For our use case I don't think updates will happen very often so cache invalidation isn't common, so we should err towards large bundled files.

Serious profiling is needed before doing anything here as it would be easy to make things worse...
