### ISSUE TITLE
Update failed, migration not found

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1892]
When updating lg.dev I got the following error:
`Update failed: settings migration failed /medic/_design/medic/_rewrite/migration Not Found`

Here is a screenshot of the network tab during the failed update:
![image](https://cloud.githubusercontent.com/assets/789512/12936638/5f596bca-cf6e-11e5-9d9a-57bd80ed3526.png)

**Comment by abbyad** [comment]
And trying again with a page refresh, all seems ok.

![image](https://cloud.githubusercontent.com/assets/789512/12936722/47f48568-cf6f-11e5-9324-c0881f10be4e.png)

**Comment by garethbowen** [comment]
This was caused by a recent commit that removed the migrations completely as it's no longer needed. The kanso.json contained a reference to the migration URL to use and has also been removed. Therefore gardener shouldn't have been attempting to do the migration. Possibly that the migration code uses the previous kanso.json not the newly updated one.

**Comment by abbyad** [comment]
Do we need to do anything about this, or just tell people to retry if they encounter this?

**Comment by garethbowen** [comment]
We should look at it to work out exactly what's going wrong.

**Comment by garethbowen** [comment]
It looks like Dashboard is using the previous settings to find the migration URL, and because we _used_ to have a migration it's trying to run it. This explains why re-running it works. I'll look at fixing dashboard and perhaps provide a dummy migration URL in medic-webapp for backwards compatibility.

**Comment by garethbowen** [comment]
I've created an issue in Dashboard, and provided a null migration endpoint so this error won't be shown in future.

**Comment by SCdF** [comment]
Looks legit
