### ISSUE TITLE
Cannot load forms 

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1921]
Seeing `Error loading form` for all forms on alpha.dev running 2718. 

Tried as a restricted user in a fresh browser as well as logged in as admin.

```
https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/xslt/openrosa2html5form.xsl Failed to load resource: the server responded with a status of 404 (Not Found)
inbox.js:14 Error loading form. Objectconfig: Objectdata: nullheaders: (c)status: 404statusText: "Not Found"__proto__: Objectconsole.(anonymous function) @ inbox.js:14
https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/static/dist/xslt/openrosa2xmlmodel.xsl Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by alxndrsn** [comment]
This appears to have been introduced by the upgrade to Node 5.6 on travis:
<img width="375" alt="screen shot 2016-02-18 at 00 43 43" src="https://cloud.githubusercontent.com/assets/191496/13128798/ccf2604a-d5d8-11e5-9df5-ec19ad228561.png">
<img width="414" alt="screen shot 2016-02-18 at 00 44 02" src="https://cloud.githubusercontent.com/assets/191496/13128799/ccf892f8-d5d8-11e5-9eb9-3eeae5b708e9.png">

**Comment by alxndrsn** [comment]
@SCdF @garethbowen any chance that node `5.x` puts the `node_modules` dir somewhere different to node `0.12`?

**Comment by garethbowen** [comment]
Yes it absolutely does. npm v3 (which comes with node 4+) as opposed to npm v2 (from node < 4). Where possible it puts all dependencies at the top level rather than nested under their parent.

However looking at the source the copy:enketo-xslt task copies from "node_modules/enketo-client-side-transformer/xslt/client-side/*.xsl" so it doesn't look at any nested modules and should just work.

Furthermore it works as expected on my local machine:

```
Running "copy:enketo-xslt" (copy) task
Copied 2 files
```

I agree that it's likely to be from the upgrade but I'm not quite sure why...

**Comment by garethbowen** [comment]
I updated to node v5.6 and it's still working as expected. Checking travis.

**Comment by garethbowen** [comment]
The name of the dependency was wrong in the package.json which I'm guessing npm v2 ignored, but was rejected silently by v3.

**Comment by alxndrsn** [comment]
good spot :+1:

**Comment by abbyad** [comment]
Thanks for the quick fix. Works well in 2723, moving to Ready.
