### ISSUE TITLE
Update notice after every change in configuration

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1937]
Every change in the Targets tab config pages (eg editing a target) changes the app_settings, which in turn prompts the user to Update/Reload the page.

![image](https://cloud.githubusercontent.com/assets/789512/13160149/d42fdd7a-d663-11e5-8dc9-0b940888b228.png)

**Comment by garethbowen** [comment]
Actually it's worse than that - any settings update triggers the "update" modal. This is by design because we're not doing a good enough job of listening and dynamically updating the UI on settings change. This works ok for CHPs as we don't expect the settings to change much, but it makes configuring the app a real pain.

The correct solution is to make sure that everywhere that gets settings is listening for updates and updating the UI correctly.

**Comment by alxndrsn** [comment]
Please re-open if this is still a concern.

**Comment by abbyad** [comment]
Has this been resolved/improved in any way in 3.0? If not, then it is still a concern, but a low priority one.
