### ISSUE TITLE
Content page loads twice on Reports tab

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1963]
When you select a report you've never loaded before it loads, then immediately loads again.

My guess is that this is due to the report being marked as "read" which causes an update to fire which reloads the UI. Maybe we just shouldn't show the spinner when an update happens and just update the content directly.

**Comment by estellecomment** [comment]
I tried to detect whether the change was due to the change in read status, so that we could ignore it, but turns out that's a hard thing to figure out (the rev changes are in the xml too... much complicated parsing, not a good idea).

Another is to update silently as @garethbowen mentioned, so that if it's the same content it doesn't show. 
I'm not sure that's great behavior for when it isn't the same content though (silent update that user may or may not notice is pretty confusing). 

But would work for now. I'm trying to figure out where I would do it and it's tricky, there's a number of `setSelected`/`selectRecord`/`setSelecting`/`_setSelected` in diverse levels of the hierarchy of controllers/scopes and I keep getting lost in them :)

**Comment by estellecomment** [comment]
When `id` is empty, we're not calling `clearSelected` any more.
It could help to have a `unselectCurrentReport()` instead of `selectReport()` with empty args.

**Comment by estellecomment** [comment]
See comment on the commit, for something a bit clearer : https://github.com/medic/medic-webapp/commit/74d55eca393d2869de5266bfb47cd07032f0de23#commitcomment-16892470

**Comment by estellecomment** [comment]
Actually did it myself, can you review?

**Comment by estellecomment** [comment]
updated diff for review : https://github.com/medic/medic-webapp/compare/5f82e3a7db0a2feb44b7200a2480c9a8c5059112...a01bf5146b3acb1522aa24c95112afa4b0df4366

**Comment by garethbowen** [comment]
Look good.
