### ISSUE TITLE
Contact info not populated for forms from Reports tab

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1982]
As mentioned on #1938, when completing a form from the Reports (aka History) tab the dropdown populates the _id field, but not the other contact fields. When accessing the same form from a contact page the full set of contact group fields are populated.

This means that forms can only be reliably completed from the Tasks tab and the contact's profile in the Contact. The "alternate" workflow of selecting the form first then the contact is not reliable if any other contact info (eg name or date of birth) is needed.

**Comment by garethbowen** [comment]
I think this was a regression from updating to select2 v4 as part of #1395 . Doing more investigation.

**Comment by garethbowen** [comment]
This fixes the issue with the select2 upgrade, which no longer passes the selected doc to the change handler.

The rest can be fixed in configuration. I had to make several changes to the LG assessment form definition in order to get it to work, eg:

```xml
...
      <bind nodeset="/assessment/inputs/contact" relevant="../source = 'user'"/>
      <bind nodeset="/assessment/inputs/contact/_id" type="db:person"/>
      <bind nodeset="/assessment/inputs/contact/name" type="string"/>
...
    <group appearance="field-list" ref="/assessment/inputs/contact">
      <label>Contact: <output value=" /assessment/inputs/contact/name "/></label>
      <input appearance="db-object" ref="/assessment/inputs/contact/_id">
        <label>Select Contact</label>
      </input>
      <input ref="/assessment/inputs/contact/name" appearance="hidden"></input>
    </group>
```

The widget works by finding inputs to update. These are found by finding inputs with a ref of the base path of the select field with the selected objects properties appended, eg: `/assessment/inputs/contact/` + `name`. Therefore I needed to add the last `input` element above so the new name could be bound. In this example I've hidden it so it doesn't show in the UI. The `change` event is then fired on this hidden input which updates all other fields referring to the same field, eg: the `output` element in the code above.

It'd be nice if there was a hook (a custom event or similar) into enketo to update a model value but this will work for now.

**Comment by alxndrsn** [comment]
Looks good.  :+1: for updating the model directly; did this work previously or have the extra fields always been required in the form definitions?

**Comment by garethbowen** [comment]
IIRC and looking at the code we always required the extra fields.

**Comment by abbyad** [comment]
Just verified and this is working when the fields are present. This has the side effect of simplifying the xform conversion as well since we dont need to remove/replace the inputs html.
