### ISSUE TITLE
Can remove permissions from "Full Access" user

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2079]
It's possible to deny permission to some features for the so-called "Full Access" user:

<img width="436" alt="screen shot 2016-03-15 at 10 39 15" src="https://cloud.githubusercontent.com/assets/191496/13770733/397d0762-ea9a-11e5-9fc1-93d88cec3312.png">

Either this user should not be described as "full access", or it should not be possible to restrict permissions from this user.

**Comment by nice-snek** [comment]
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by estellecomment** [comment]
Makes sense to me, setting Scheduled.
(I'd go for keeping the Full Access user, leaving it displayed, but blocking all the checkboxes to checked)

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by alxndrsn** [comment]
This has already been triaged.

**Comment by cbrwizard** [comment]
Looks like by default 'Full access' users have some permissions unchecked on an almost clean system on `master`.
<img width="604" alt="screen shot 2017-10-19 at 18 50 15" src="https://user-images.githubusercontent.com/1615659/31780447-6dd0df68-b4fe-11e7-8408-a8d0a31d8d17.png">
Looks quite confusing. Is it intended? If so, should it be possible to check/uncheck them but not uncheck other permissions?

Update: on the other hand, I was able to create/update persons while logged in as a Full access (not admin) user, even though my permissions for updating/creating users were visually unchecked. Looks like that the code doesn't actually check for these permissions, but checks if a user has full access (haven't found yet how it does that so I can't be sure atm).

I conclude that all permission checkboxes should be visually checked for a Full access user and disabled. Or did I miss something?

**Comment by alxndrsn** [comment]
Hi @cbrwizard!  As per your findings and the discussion above, these permissions boxes don't actually do anything for `full_access` users.  Fix is either to get rid of them, or set them all to be both `checked` and `disabled`.

**Comment by garethbowen** [comment]
The user role formerly known as "full access" is for people who can access all docs, but not necessarily have all permissions so being able to remove permissions is actually correct in this case. I completely agree the name is misleading so I've updated it to "National manager - access to all docs". It's not a role we use much any more and the design team are currently going through a role and permission redesign so I expect it'll change a lot then, perhaps to have a configurable set of roles rather than these hardcoded ones.

@cbrwizard You actually found another bug where the `can_create_people` and `can_create_places` were not being used in the UI, only in the API we use for scripting.

@alxndrsn Please code review both of these fixes in the attached PR.

**Comment by cbrwizard** [comment]
@garethbowen gotcha.
I confirm that `can_create_people` and `can_create_places` permissions are not checked when creating persons/health centers (I assume they're people and places) for any - even not `full_access` - user. I've created a `Restricted to their place` user and was able to create those records both with those permissions checked and unchecked.

Unless this is urgent, I'd like to contribute and work on this, do you mind that?

**Comment by garethbowen** [comment]
Merged.
