### ISSUE TITLE
Show list of available forms and their version numbers on About page

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2085]
Show the list of available forms, and their corresponding versions, on the _About_ page so that as a tech lead (MM or partner) you can check that all forms are downloaded and available at the correct version.

This may require a new `version` property on form docs, which would be extracted from the form's XML at upload time.

It would be good if this list updates live, as otherwise tech lead may repeatedly hit the **Reload** link to see if the form has downloaded.

**Comment by garethbowen** [comment]
Forms are replicated along with all other docs so it should be possible to just check if the replication from is up to date and put a big green tick.

**Comment by alxndrsn** [comment]
Definitely true if you're online.

**Comment by garethbowen** [comment]
You're right, there is no way to tell if you're up to date while offline. We could still have a seq number from the last sync so two devices can be compared.

Also the _rev would work as a version. You couldn't compare between test and prod, but you could compare for two devices against the same server.

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by SCdF** [comment]
So listing the forms on the about page is probably a quick 30 minute thing we could just do and get out of the way.

Requiring people add a version to a form seems unrealistic, though in lots of XML forms that I'm aware of you can find a version at `/h:html/h:head/model/instance/*[@version]` so we could just presume it's there.

It doesn't seem too feasible or useful to know if it's up-to-date or not, except generally whether or not we're currently replicating. If you're offline you can't tell, if you're online you can only tell if you've downloaded the correct chunk of the changes feed.

My suggestion for this ticket then is to just add a list of XML forms with the potential version from that xpath location. In terms of whether it's up to date we should deal with that more globally.

Thoughts @garethbowen / @alxndrsn. If you're happy with the above I'll just do it, should be fast.

**Comment by garethbowen** [comment]
@SCdF I'm not a fan. As I understand it, what the tech lead wants to know is, "is the replication complete?". Forms are one of the most obvious things that could be missing but the ddoc (settings and views), resources, translations, and so on are all critical to replicate too. At best this is a little bit of useless code, at worst this is a false positive that the app is ready to go offline.

This issue has been alleviated by not loading the app until replication is finished the first time. What this means is you won't even be able to get to this page until the app has all the forms anyway. I'm not sure what happens if the initial replication fails (I suspect we just load the app and hope for the best) but this would be better handled by a "retry" button on the initial load.

It'd be worth talking to tech leads to find out if they still have an issue here and if so working out a solution that works for all replication items, not just forms.

**Comment by sglangevin** [comment]
In practice, we are not using the "version" for xforms. We had been using it earlier on, but we haven't kept up the practice. It's entered manually into the form (for now), and that's why it's been hard to use consistently. It could be useful if medic-configurer set the version to the current date automatically, though that wouldn't capture multiple iterations happening in the same day.

I think as far as initial replication goes, I haven't heard of any issues for quite some time, now that the app doesn't load until it's complete. Would be good to check with tech leads and/or partners too.

The real user need I've heard related to forms is that managers want to know which version of a form each CHW has on their phone so that they can make sure every CHW is on the latest version. That is a separate issue from the one at hand, though.

**Comment by SCdF** [comment]
There isn't much demand for this, and we don't really usefully version forms right now.

**Comment by abbyad** [comment]
I agree that this isn't a priority for checking if everything is downloaded, but want to clarify that we _do_ usefully version forms. In the Standard config for instance the version is set to the time the XLSForm is converted to a XForm. This is set in the Settings tab of the XLSForm, with `version` set to `=TEXT(NOW(), "yyyy-mm-dd_HH-MM")`

**Comment by sglangevin** [comment]
Note that we are only doing that for projects that use medic-configurer.
