### ISSUE TITLE
Task icons don't load if page refreshed on About tab

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2094]
# Observed

Task icons don't always load:

<img width="496" alt="screen shot 2016-03-16 at 13 00 57" src="https://cloud.githubusercontent.com/assets/191496/13808455/34f072be-eb77-11e5-93e1-c711c5a2108d.png">
<img width="475" alt="screen shot 2016-03-16 at 13 00 45" src="https://cloud.githubusercontent.com/assets/191496/13808456/34f22c80-eb77-11e5-9144-d687587156a0.png">

# Steps to recreate

1. browse to _About_
1. hit **Reload** or press browser refresh button
1. browse to _Tasks_
6. observe that icons are missing (possibly only for some types of task)
17. refresh page
9. observe that icons are now visible for all tasks

# Expected

Task icons should always show, whatever the initial page was.

**Comment by garethbowen** [comment]
Ahh interesting. I didn't realise LiveList was generating HTML at startup and not attaching it to the dom. This means that if it runs before the ResourceIcons have finished it gets the placeholder, but the placeholder is never removed because it can't be found in the DOM.

The solution is a bit heavy handed - ResourceIcons is initialised correctly, and this makes it initialise again when the tasks list is loaded when we just need to replace the placeholders. Furthermore this bug could reoccur for any other LiveList that uses ResourceIcons. I suspect it also won't respond to changes in the icons, because unless it's in the dom the icon can't be found.

Instead of calling `updateResources` how about expose just the bit that updates the HTML. This could then optionally take a DOM element (or selector string) as a parameter to replace only over the part we're interested in. Then we can have the `LiveList.refresh` function run the `ResourceIcons.updateDOM` function after it's appended all the list elements.

**Comment by garethbowen** [comment]
@alxndrsn Any thoughts on this?

**Comment by alxndrsn** [comment]
My preference would be to close this ticket and open the optimisations as a new ticket.

**Comment by garethbowen** [comment]
@alxndrsn Too lazy to raise an issue. Instead can you review that commit please?

**Comment by alxndrsn** [comment]
I'm seeing this exception locally:

<img width="449" alt="screen shot 2016-04-07 at 13 33 26" src="https://cloud.githubusercontent.com/assets/191496/14349738/66f9d55c-fcc5-11e5-9e6f-3d8c06b3d49c.png">

Possibly caused by this change?

**Comment by garethbowen** [comment]
It looks like your replication isn't complete. The "bad doc in batch" error gave it away. Can you wait for it to complete and check again?

**Comment by alxndrsn** [comment]
Is the error expected when replication is slow?

**Comment by alxndrsn** [comment]
This seems generally fine, but there is perhaps room for simple performance improvements if needed - one is commented on in the code; the other is that it looks like the same elements will have their icons updated every time the LiveList is refreshed.
