### ISSUE TITLE
Phone number field in add family (type: tel) doesn't allow a 3 as the 3rd digit

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2105]
Currently, 073X-XXX-XXX isn't allowed but there is an MNO in Uganda that issues numbers like this. We need to make sure a number with this format passes validation. This validation is not done within the form.

**Comment by browndav** [comment]
Do you know which MNO it is off the top of your head? I can check the libphonenumber rules and see if it's a new prefix.

**Comment by sglangevin** [comment]
@browndav Simon from LG mentioned an operator called K2 in Uganda that uses the 073x prefix. He said that 072x was also not supported by our app (Vodafone in Uganda) but I couldn't reproduce that - it worked for me.

**Comment by sglangevin** [comment]
Actually, 072x also doesn't work for me, upon further testing.

**Comment by browndav** [comment]
Could you PM me a full phone number on Slack? The 072x and 073x prefixes aren't globally unique, and it's possible that it's matching the prefix but failing later on in the number (libphonenumber validates as much internal phone number structure as it reasonably can, IIRC).

**Comment by alxndrsn** [comment]
Checking number `+256736123123` with latest version of libphonenumber:
```
****Parsing Result:****
{"country_code":256,"national_number":736123123,"raw_input":"+256736123123","country_code_source":1,"preferred_domestic_carrier_code":""}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: UG
Result from getNumberType(): UNKNOWN

****Formatting Results:**** 
E164 format: invalid
Original format: +256 736 123123
National format: 0736 123123
International format: invalid
Out-of-country format from US: invalid
Out-of-country format from Switzerland: invalid
```
Maybe I chose a bad example, or maybe libphonenumber is not familiar with the issuing of every new area code in every region.

Also, while libphonenumber last had a release 9 days ago, we have not updated in over 13 months.

To reduce issues like this, I'd recommend using `isPossibleNumber()` rather than `isValidPhoneNumber()` at https://github.com/medic/medic-webapp/blob/develop/packages/libphonenumber/libphonenumber/utils.js#L25.

**Comment by garethbowen** [comment]
We should probably bump our version of libphonenumber at the same time. Also, this change breaks tests.

**Comment by garethbowen** [comment]
Looks good.
