### ISSUE TITLE
Messages tab is visible on lg.dev

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2106]
It appeared in the hotdog menu sometime last week. Even though the permissions have can_view_messages_tab unchecked, it still shows. Possible regression.

https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/#/configuration/permissions

**Comment by sglangevin** [comment]
All of a sudden it disappeared today, even though the app has not been updated. Remains an unsolved mystery.

**Comment by sglangevin** [comment]
All of a sudden it disappeared today, even though the app has not been updated. Remains an unsolved mystery.

**Comment by garethbowen** [comment]
`can_view_messages_tab` determines whether or not the Messages link shows up as a tab or in the hotdogs - it should always be in one place or the other. It's used to control which tabs are primary for an instance. Having it come and go like that is definitely a bug.

Are we doing any LG specific manipulation to remove the link?

**Comment by sglangevin** [comment]
I did try unchecking two other boxes that were also associated with Messages (one was export) and sometime after that the Messages tab went away. However, when I look at the Permissions page now, it looks the exact same way that it did prior to me trying that. So I think there is a bug somewhere, but I haven't pinned it down.

**Comment by garethbowen** [comment]
The current configuration exploits a bug in the permissions implementation. Currently for a specific role a permission can be configured to be `true`, `false`, or `null`. The first two behave as expected, but `null` always returns false even when asking if a specific user _doesn't_ have permission. In the current configuration `can_view_messages_tab` is null, which means it doesn't show in the tabs _or_ the menu, when the design was to always show tabs in one or the other.

It turns out that LG don't want to see Messages in the tabs _or_ the menu so this bug was actually working for them. There is currently no way to configure a permission to be `null` through the UI. Furthermore I find it confusing to have a ternary state.

I think what happened here is someone used the configuration UI to set the permission which changed it from `null` to `false` and changed the behaviour. Then I think the configuration was updated via script which reverted it back to `null`.

I propose we change the code so `null` behaves just like `false` which is easier to understand and configure. Then to get LG's desired view I'll add another permission `can_view_messages`. This will allow admins to configure whether the tab is shown, whether the menu item is shown, or neither.

**Comment by garethbowen** [comment]
This fix adds the following permissions: "can_view_tasks", "can_view_messages", "can_view_reports", "can_view_analytics", "can_view_contacts". Configuring these to be false will hide the respective tab _and_ dropdown menu item.

**Comment by SCdF** [comment]
This causes my local environment to break:
```
$ git hist -10
*   1587108 2016-03-23 | Merge pull request #2131 from medic/refactor-task-generator (HEAD -> develop, origin/develop) [Stefan du Fresne]
|\
| * 1695d4d 2016-03-22 | Rename to make clearer (origin/refactor-task-generator, refactor-task-generator) [Stefan du Fresne]
| * c5d6f44 2016-03-22 | Rename task-generator to be clearer [Stefan du Fresne]
* | 21e93d1 2016-03-23 | Treat an unconfigured permission as if it's set to false. Issue: #2106 [Gareth Bowen]
* | 293d7af 2016-03-23 | Sort the permissions on permission configuration page. [Gareth Bowen]
|/
* 9f4b21d 2016-03-22 | Render complex report fields better. Issue: #1473 [Gareth Bowen]
* ad12edf 2016-03-19 | bumped api submodule [Milan Andric]
* af1d372 2016-03-18 | Use day granularity for showing tasks [Marc Abbyad]
* 3d13238 2016-03-18 | Add xforms to filter dropdown. Issue: #1409 [Gareth Bowen]
* b0d0093 2016-03-17 | Don't block UI on network. Issue: #2057 [Gareth Bowen]
```

Checking out and pushing 293d7af (commit prior) means my page looks like this:

![image](https://cloud.githubusercontent.com/assets/583851/13984388/f79b1244-f106-11e5-937c-e3b82ef93013.png)

Checking out and pushing 21e93d1 means my page looks like this:

![image](https://cloud.githubusercontent.com/assets/583851/13984423/358c26f6-f107-11e5-8bae-bea7a9b5acda.png)

Looks like either you've broken something unintentionally or (more likely) we need a migration script.

**Comment by SCdF** [comment]
To fix it I went into the permissions tab and changed the defaults to make sure the show_xyz_tab was selected.

FWIW these permissions seem to have really odd defaults that aren't actually expressed in the app. For example, the admin user, whom I presume is the left-most column, can do all the things that the permissions imply they can't do.

**Comment by garethbowen** [comment]
The admin user is not shown on the permissions configuration page. The admin user can do everything and no configuration can change that.
