### ISSUE TITLE
App-settings gets out of sync with the github repo

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2110]
The full app-settings are mostly edited by Tech Leads, but the PMs also make small tweaks sometimes. The Tech Leads make sure that they upload their changes to medic-projects, but the PMs may not notify them. @henokgetachew mentioned an instance when he reverted the PM's changes by mistake by reloading the github version into the app.

Would be nice to automate backup of app-settings to github, or to get automatic version control some other way.

**Comment by estellecomment** [comment]
Also it sounds like PMs tweak translations sometimes, does this fit into the [POEditor workflow](https://github.com/medic/medic-docs/blob/master/md/dev/translations.md)? Is that an issue?

**Comment by garethbowen** [comment]
Translations should be tweakable, no problem. As far as I'm concerned medic-projects represents the base configuration for a project, not necessarily the current configuration. Once an instance is in production we should not deploy settings or forms from medic-projects any more because of this.

Related issue: #1616

**Comment by mandric** [comment]
It would be nice to audit settings changes.

**Comment by sglangevin** [comment]
This seems like something that can be solved between TLs and PMs. Closing in favor of #1616.
