### ISSUE TITLE
Middleware's Google sheets are overwhelmed

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2120]
The middleware relies on computing on google sheets. 
When the computing is too long, google kills it and the data refresh fails (Interhealth Senegal does that a lot). Klipfolio's fetch then fails too and the whole thing is stuck.
When the sheets are are too big, we can't add any more cells or formulas. 

We're going towards postgres and will remove google sheets, so that'll all go away.

However, I'm curious if there's some temporary fixes in the meantime which would help the TL's workflow.

**Comment by SCdF** [comment]
I imagine @btbonval has things to say about this

**Comment by bishwas-medic** [comment]
Also want to add that the import scripts we use for importing data from Couch DB to Google Sheets also has time limits and crashes frequently. We've tried to work around this by increasing the time interval for the triggers that runs the import functions.

**Comment by estellecomment** [comment]
Priority : 4/5
This blocks dashboards : when the scripts fail they show up empty. The partner's decision-makers look at this, so it makes us look pretty bad.

One quick win would be to first fetch the data, then wipe the sheet. That way when fetch fails, you're not left with empty sheet.

**Comment by btbonval** [comment]
Actually that isn't what happens and the solution wouldn't change anything.

The form sheets are never blank.

The blank sheets are a result of custom functions written in JavaScript which do not complete because Google decides to go look at cat images on the internet rather than complete the function and return data. Some forms are fake forms which are a combination of other forms. For example, ANCR is a combination of P and R forms using a custom function. If Google decides not to complete the custom function, ANCR shows up blank except for one cell which says `#ERROR!`.

I've been constantly working to keep this stuff maintained. When Google is completely overwhelmed and has no choice but to look at cat images on the internet to relieve its stress, then part of the fix involves offloading custom functions into our time-scheduled processes so that the import can finish and other calculations are performed at a later time using a separate Google process.

We're also running into situations where we have too many rows of data for this or that calculation, so it won't finish. One fix there can be to make sure all the useless data (test data, trial data) is cleaned up or filtered out.  Another fix is to partition by time, as we had to do for one particular project which spans 2013-2016 with a _ton_ of data.

Honestly Google can't handle what we're doing. I have employed so many temporary fixes it would make your head spin. Please continue letting me know which things are breaking so that I can figure out annoying and clever work arounds. The tech leads generally tell me when things are broken right off the bat, at least that's what I had thought.

**Comment by btbonval** [comment]
The real fix to this problem, btw, is to get off the Google infrastructure for any project having repeated problems with the Google infrastructure.

**Comment by yembrick** [comment]
Estelle, yea the sheets are never empty once an import completes successfully a single time. If an import fails, the sheet should keep the data from previous import sessions. When there are blank sheets, its due to what Bryan mentioned above (generation of new tabs outside of the import process). Only a few projects have those, for example on Christian Aid when we are combining SIm app and SMS forms of the same type (like registrations or visits). The import issue would make dashboards less up to date, but not blank (or wrong besides being delayed). When google decides to stop processing custom functions or executing whatever formulas they feel like in spreadsheets, thats a more major problem for dashboards. Unfortunately, its also hard to know when this happens. The import failures send email alerts that are forwarded to Richard and can easily be monitored as part of a standard process. The other in-spreadsheet failures essentially ahve to be found by hand. I find them frequently, just by seeing something I know doesnt look reasonable, or looks different than it did when I saw it some time recently. sometimes there are more obvious red flags like a blank ANCR tab, but it could definitely be more subtle. We do know many of the types of things that crash (perhaps not common enough knowledge), and building some procedures in to check every so often would likely be very helpful, for starters. I dont look at every project frequently enough to catch these things consistently enough for deployments.

**Comment by garethbowen** [comment]
Closing as the fix is to replace the Google infrastructure with the couch2pg adapter as @btbonval mentioned.
