### ISSUE TITLE
Inputs are not assigned properly when field name is not unique

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2146]
With our XForm notation for inputs, and assigning `content.contact` in a task, we can have a form with `contact.parent.contact.phone` assigned to `/assessment_follow_up/inputs/contact/parent/contact/phone`. From what we've seen, this works as long as there is not also `contact.phone` field. If there is, the `contact.phone` value is assigned to the xform field instead of the parent's.

We need to respect the full path to avoid assigning incorrect values.

**Comment by alxndrsn** [comment]
@abbyad please provide example forms showing good and bad behaviour

**Comment by abbyad** [comment]
@alxndrsn there is an example with files in https://github.com/medic/medic-projects/issues/129

**Comment by SCdF** [comment]
The fundamental problem is that data is allowed to be bound to arbitrarily deep children: it doesn't not have to be at the same "level", meaning you can have data that looks like this:
```JSON
contact: {
  "deep": {
    "deeper": {
      "foo": 1234
    }
  },
  "foo": "OMG I'M AN EVIL VALUE"
}
```
And when you bind it to the following elem structure:
```xml
<any>
  <random>
    <fluff>
      <contact>
        <deep>
          <deeper>
            <foo></foo>
          </deeper>
        </deep>
      </contact>
    </fluff>
  </random>
</any>
```
Then these two things will happen in an un-documented order:
 - from the context of `any` we will find `contact`, and in that context `deep`, then `deeper`, then finally `foo`, which we will set the value to `1234`
 - from the context of `any` we will directly find `foo`, and set the value to `OMG I'M AN EVIL VALUE`

**Comment by SCdF** [comment]
Unfortunately we:
 - need this current structure. It's not like the data and the xml are 1:1 right now, so correct binding depends on being able to bound to arbitrarily deep children
 - can't make up rules like "if there is already data in that element ignore this data" because there are examples where the form elem has default values we want to override

We *might* be able to have the rule that if that data is empty ignore it, which could possibly solve the linked phone number issue, but may not actually be a sound rule (because maybe wiping a default value is exactly what you wanted.

Another option would be some kind of record of what you've already set, so that you never bind the same value twice, along with making sure you always bind depth first (so the most "correct" or "specifc" value always binds first, and less specific values are ignore).

**Comment by SCdF** [comment]
I've also noticed that we use `$(...).find`, which will return more than one element. I haven't worked out if this is also a problem, but it sure seems weird.

**Comment by SCdF** [comment]
(not weird that it returns more than one value, more weird that we'd actually intend on that happening)

**Comment by SCdF** [comment]
Will have to write tests, but perhaps the absolutely smallest fix would be applying a sort before the [_.pairs](https://github.com/medic/medic-webapp/blob/develop/static/js/services/enketo-translation.js#L331) that puts values first and objects last, so that any objects (ie more specific declarations that have a more specific scope) get applied after and thus over values.

**Comment by SCdF** [comment]
I haven't written any tests yet because I'm a bad person, but this proposed commit fixes the one noted issue in https://github.com/medic/medic-projects/issues/129 (though it may cause other issues)

**Comment by SCdF** [comment]
I have written a couple of tests, you can see them and the suggested fix against the linked PR: https://github.com/medic/medic-webapp/pull/2163

There is also a conversation going on an outdated commit, that I think we probably should be having directly on this ticket. You can see the current conversation here: https://github.com/medic/medic-webapp/commit/4138000e43f69423fd32e0b996a461e3bd6e9b30#commitcomment-16967432

To continue the discussion, I guess where we are up to in it is this: @garethbowen:
 - Is it intentional or an oversight (a [happy accident](https://www.youtube.com/watch?v=wCsO56kWwTc) if you will) that:
   - the data model binds to arbitrary deep decedents on the XML model (as seen in the first test that I wrote)
   - the data model binds to all matching XML nodes (as seen in the first test that I wrote)
 - How do you personally think this should work? Do you like that the model binds this way, or do you believe it's more correct for the binding to be stricter?
 - If your answer is for the binding to be stricter, do you foresee this being a massive change to fix? Would it make sense to merge this change into `testing` as it stands and then make the binding stricter in `develop`?

**Comment by garethbowen** [comment]
I think it's a happy accident. There is definitely some complexity WRT root nodes (eg: when loading a report form vs a contact form), but once the root node is found it should only bind when the path matches exactly.

It shouldn't be a massive change, but given the above complexity it could be risky. I don't recall specifics but I do remember a bunch of bugs cropping up in this area when changes have been made in the past. Given this I think it's best to make it strict in development and leave testing less strict - it's just something we'll have to watch when they update.

I've added a comment to the commit but feel free to merge the PR as is.

**Comment by SCdF** [comment]
I've merged the code into both develop and testing, and I'm going to close this ticket so it can be put into Acceptance Testing, and raise another one about making the binding more specific.

**Comment by abbyad** [comment]
Known to be working, moving to Released.
