### ISSUE TITLE
Cannot enter recipient for outgoing messages

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2174]
If you open go to send a message from the RHS and "add recipient" the person select box is shown incorrectly and cannot be type into:
![image](https://cloud.githubusercontent.com/assets/789512/14361104/57db8b36-fcc7-11e5-9da1-10f38d346666.png)

If you open it from the LHS it shows up normally. If you open it from the LHS, close it, then open it as done originally above, then it will also show up normally.

On build 3084, related to https://github.com/medic/medic-webapp/issues/2147

**Comment by garethbowen** [comment]
@abbyad Did you check for JS errors?

**Comment by abbyad** [comment]
I hadn't noticed any errors originally, but see one now on initial load:

```
Error watching for db changes Object { status: 500, name: "unknown_error", message: "Database encountered an unknown err…", error: true, stack: "" }
```
![image](https://cloud.githubusercontent.com/assets/789512/14364243/fb118c52-fcd5-11e5-8cb5-d6ee5de92c93.png)

and a 404 on https://diy.dev.medicmobile.org/medic/eeb17d6d-5dde-c2c0-62c4a1a0ca17fd16?

**Comment by garethbowen** [comment]
I think that "error watching" one is when you refresh because the db forcibly closes the connection (we should be cleaning up our watches on unload, but meh).

**Comment by SCdF** [comment]
Code looks fine, but I mean, I have no idea what it does :P The comment doesn't go into rich detail…

**Comment by garethbowen** [comment]
The change was quite small, but because it changed indenting it's hard to tell...

There's an event registered on everything with a "send-message" class so when you click it it opens the modal dialog. It also used to initialise the select2. However sometimes we want to open the modal from a angular call instead of from a jquery event on an element, and for this we use the `exports.showModal` function that the jquery event handler also calls. But this function didn't have the select2 init code in it.

So the fix was to move the init code up to the `showModal` function then both entry points will call the initialisation. It changes the order of initialisation slightly but it looks fine to me and it still works.

**Comment by SCdF** [comment]
> So the fix was to move the init code up to the showModal

Well, or move it down (from bodyClick->Init->call showModal to bodyClick->call showModal->init) but yeah, I guess you can visualise that in either direction.

But yep, makes sense :+1:
