### ISSUE TITLE
Ages of children showing up strangely

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2191]
In a new test family, "Dianna Kane Family," two children were added with ages input at 3 and 2 years. Upon returning to the family, the children are listed at (Sammy) 2 years and (Rose) 23 months. Both of their birthdates are set for tomorrow, when I figure they will become the ages I meant them to be. 

Is this the behavior we want / expect? I imagine that if you input the age of child, you can assume they are already that age, or at the very least the birthdate should be marked as today.

**Comment by alxndrsn** [comment]
Another timezone issue?  ref #2185

**Comment by sglangevin** [comment]
This was a configuration issue due to approximating birthdates and has since been resolved with a workaround.

**Comment by alxndrsn** [comment]
@sglangevin so it's still an issue, but less-high priority, or it should be closed?

**Comment by sglangevin** [comment]
Actually, that comment jogged my memory. I have a complete fix for this in the `person` form, but it wouldn't work in family creation (`clinic` form), which I think is because of the issue we were discussing in #1655. All of my children ended up with the birthdate of the first child. I never filed that, I just did a different approximation which is working for now. This particular issue would be resolved completely if I could use my fix in the `clinic` form as well.

**Comment by sglangevin** [comment]
This has now been resolved in the `clinic` form as well. It was a configuration issue related to how we calculate approximate birthdates.
