### ISSUE TITLE
Decision about dependency versioning

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2195]
Our current [`package.json`](https://github.com/medic/medic-webapp/blob/develop/package.json) has a mix of `~` and `^` semvers in it. It is unclear how intentional or not this is.

We should:
 - Pick a dependency strategy that will be obvious when you look at `package.json`, so that everyone easily keeps to the strategy
 - Make is clear when we are deviating from the strategy and why, so that people don't think it's a "mistake" and fix it later (ie we're holding back this version for these reasons)
 - Change `package.json` to fit this

## Option A: Loose versioning
_(use `^` as a default, if not note why)_
```js
  "dependencies": {
    "angular": "^1.5.3",
    "jquery": "~2.1.4", // 2.2.x breaks enketo, see #1234
    "enketo-core": "git://github.com/enketo/enketo-core.git#4.5.5", // not yet on npm, see #5678
    "underscore": "1.8.3", // 1.8.4 has security issues, see #9012
  }
```

## Option B: Automatic patches
_(use `~` as a default, if not note why)_
```js
  "dependencies": {
    "angular": "~1.5.3",
    "jquery": "~2.1.4", // NB: 2.2.x breaks enketo, see #1234
    "enketo-core": "git://github.com/enketo/enketo-core.git#4.5.5", // not yet on npm, see #5678
    "underscore": "1.8.3", // 1.8.4 has security issues, see #9012
  }
```

## Option C: Strict versioning
_(specific versions only )_
```js
  "dependencies": {
    "angular": "1.5.3",
    "jquery": "2.1.4", // NB 2.2.x breaks enketo, see #1234
    "enketo-core": "git://github.com/enketo/enketo-core.git#4.5.5", // not yet on npm, see #5678
    "underscore": "1.8.3", // NB 1.8.4 has security issues, see #9012
  }
```

**Comment by SCdF** [comment]
I like Option A!

**Comment by SCdF** [comment]
I like Option B!

**Comment by SCdF** [comment]
I like Option C!

**Comment by SCdF** [comment]
@estellecomment @alxndrsn @garethbowen @mandric @browndav @abbyad cast your votes at your earliest convenience… (or we can just talk about it on Slack or a call or something…)

**Comment by alxndrsn** [comment]
I like Option C!

**Comment by garethbowen** [comment]
Option C isn't good, because if package x depends on package z@5.5.1 and package y depends on package z@5.5.2 we'll end up with two versions of the package included in inbox.js. We should at least be flexible about the service pack version (`~`, option B), and I think even the minor version (`^`, option A), and trust that our dependencies are following semver.

For example, enketo depends on jquery 2.1 and I recently tried to bump our jquery dependency to 2.2. The broke things horribly because both jquery instances got included, and enketo added it's plugins to one, and we added our plugins to the other. jquery is an extreme case due to the plugins but interesting nonetheless.

The versions that get distributed are nailed down at build time so we effectively `shrinkwrap` due to kanso bundling, so there's no problem with debugging - if two instances have the same version of medic they will have the same version of all the dependencies too.

it's also worth noting that `npm --save` defaults to `^` (option A).

So my vote is option A. Keep the bundle small and be consistent with npm's default setting.

**Comment by SCdF** [comment]
Option A for me.

_(I was on the fence between A and C: A because it's the default for npm (based on what `--save` does) and C because it's what I've always done in the past on other systems, and having versions change under you is a scary concept. Having said that, the JS community moves quickly and having to deal with massive version differences because you waited too long is scarier)_

**Comment by garethbowen** [comment]
Decision from iteration call: Go with `^` (option A).

Also investigate using shrinkwrap to make reproducible builds. This could either be done in a dev environment when dependencies are changed and committed to git, or in CI. The former probably makes more sense as then we can see for any commit which versions were used.

**Comment by alxndrsn** [comment]
One confusing file change in there (comment on commit).

Any guidance on how package/shrinkwrap updates should be done?  Is it simply:

```shell
rm npm-shrinkwrap.json
npm install
npm shrinkwrap
```
?

**Comment by garethbowen** [comment]
That's one way. The `npm install` automatically updates both the npm-shrinkwrap.json and the package.json so it's easier to just install the package and version you want with the `save` flag, eg: `npm install grunt@1.0.1 --save-dev`
