### ISSUE TITLE
/tasks/ -> /tasks/:id and /messages/ -> /messages/:id are broken

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2198]
Go to http://localhost:5988/medic/_design/medic/_rewrite/#/tasks/
Click on a task : url is right, but "No task selected" is displayed.
Refresh : the task displays properly.

Same with messages.

**Comment by estellecomment** [comment]
Got it! Comes from the previous controller instance cleaning up after itself by calling `$scope.clearSelected()`, but there's a race condition and it unselects the selection of the next instance, not its own. 
https://github.com/medic/medic-webapp/commit/ba4162c7ed8d4abd2b70408e767c1cc9b7f8af3f

**Comment by garethbowen** [comment]
So what's happening is the `destroy` is called _after_ the new controller is initialised. I think this is by design so you can animate from from one view to another and only when the animation is finished is the destroy called. So the solution here is to only destroy if you're not longer in the same state. For example, if you nav from `messages.content` to another `messages.content` then the new controller has set the new selected and the new title and so on and we should no longer clear it. But if you navigate from `messages.content` to `messages` or `about` then we should clear it because the new controller doesn't know how to clean up the previous controllers mess.

**Comment by estellecomment** [comment]
Non-culturally-ambiguous-cross-platform-happyface-emoji! Cool fix.
