### ISSUE TITLE
Index xmlforms_uuid on dynamically generated tables

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#2232]
Dynamically generated tables are currently created using `CREATE IF NOT EXISTS`. Unfortunately, indexes cannot be crated with `IF NOT EXISTS`.

The logic for IF NOT EXISTS needs to be moved into the adapter, and then for each table created, an index should be added to xmlforms_uuid (which is the only non-dynamic field of any xml forms table).

**Comment by SCdF** [comment]
FWIW PostgreSQL 9.5 supports `IF NOT EXISTS` on indexes.

If we've decided we need an index on the report UUID for performance reasons one way of solving this cleanly would be:
 - Change the code so that on any newly created dynamic table this is added (ie make the code right)
 - Write a migration script that uses looks for existing dynamic tables and adds the index

**Comment by SCdF** [comment]
This ticket isn't relevant: our implementation no longer works like this
