### ISSUE TITLE
Improve search performance

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2302]
Currently the Search service fetches the entire doc and then in all instances the result is summarised to be displayed. We can improve performance by modifying the views to return a summary object as the value.

The summary would contain something like: `name`, `location` (array of parent names recursively), and `reported_date`.

This is a requirement to make Select All in bulk delete #1000 work sensibly.

**Comment by SCdF** [comment]
This seems legitimate. The views used in searches are (IIRC) exclusively used for searching, which is a good start. They currently blurp out some stuff in their values, and at some point I tried removing it to increase performance, but I horribly broke things. That either means someone already relies on them, or I just broke something (could be either).

Thoughts to chew on:
 - We'd have to think a little on what values we want to include. I suppose it's easy to change / add to later so it's not a big deal, but it's a clear opportunity to standardise how we present search results if they are currently not in sync.
 - We'd want to make sure they are the same on every one of our views. It might help IMO to rename these views so it's clear they go together and are for search (you can have more than one layer of `/` right? maybe `doc_by_place` goes to `search/doc_by_place` or something), so that people aren't tempted to monkey with their output values.
 - Does the size of the value impact performance? Not actually sure how that's stored…
 - Could this potentially be worse performance? The search service flow IIRC is that we query a bunch of IDs from a bunch of views, and then find their unique intersection and _then_ grab all the documents. If we are getting a lot of duplicates we may end up pulling more data back than before
 - On that note, and with reference to keeping the values the same noted above, an alternative might be to have a `search_result` view, which contains every document but is where we store and get our value from. This would mean the Search service would change from calling allDocs and getting docs to querying this view with a set of ids. The pros is that it can't get out of sync with itself, and that it's clearly there to be the output for search. The downside being it's one more view.

We'd also have to make sure that Search service makes it clear you're not getting real documents out the end of it, since I know some usecases (ie the dropdown stuff in forms) expects that. I can't think of any cases where we can't just get one doc from P/Couch, so it's not a problem, just a note.

**Comment by garethbowen** [comment]
This change conflicts with the bulk delete branch but I'll update that branch before merging it into develop.

**Comment by SCdF** [comment]
Looks good! Out of interest, do you have any fun stats re: bandwidth / perf differences?

**Comment by garethbowen** [comment]
No I was too lazy. I'd guess it's about 10% the size before gzipping.
