### ISSUE TITLE
Make actionbar a reusable component

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2320]
Right now actionBar is owned by inbox, and each controller has to call inbox's `setActionBar` to place the stuff it wants in it.
It would be better to make an actionBar angular directive, that each controller could set in its template and fill in with whatever icons and actions.

**Comment by garethbowen** [comment]
Because of the way it's fixed to the bottom it needs to be outside of the individual controllers scope so AFAICT this is not currently possible. Yes, a CSS limitation is causing this... ugh.

By changing the design I think we could make this much better. For example if the action bars weren't floating but actually inline at the bottom then it would be easy. Alternatively we could use the material style floating action button which I think would also solve the problem.

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by SCdF** [comment]
Sounds like a lot more work than the gain you'd get.
