### ISSUE TITLE
Create default Edit Place forms that allow users to edit a family's primary contact

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2333]
This is not currently editable after the household is created. All fields in household creation form should be editable from the Place profile. If possible, only that family’s members should appear on the list, with the ability to search for other people in the system if desired, such as the family’s CHP.

**Comment by sglangevin** [comment]
@diannakane a piece of this is a form configuration issue. It's possible to make the primary contact editable, we are just hiding that option currently for LG. However, limiting the people who appear in a particular drop-down is not currently possible and would be a very useful feature.

**Comment by abbyad** [comment]
Seems related to #2828, but for the _Edit_ place forms.

**Comment by abbyad** [comment]
Marking as no action needed anymore and closing since this is configurable per project. 

For example, [this default form for SMS workflow projects](https://github.com/medic/medic-projects/blob/003f459ac1f2b271876d69d1ba6f28375b9d6300/default-sms-workflow/health_center-edit.xml) allows editing of the primary contact place.
