### ISSUE TITLE
Spike: CouchDB database compaction/recreation to improve replication performance

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2358]
Exploratory test: try to recreate the current production database, with the aim of compacting it, removing revisions that are no longer materially useful (e.g. deletions, edits of deleted documents), and otherwise attempting to reduce the size of the history to improve replication performance. Figure out if clients break when you do this (e.g. can't cope with a `seq` reset), then measure any performance improvement.

**Comment by SCdF** [comment]
So the main problem that I see is that the `seq` gets reset and it's not clear if it's possible to manually set the `last_seq` on a couchdb for compatibility purposes. Because we can't force the `seq` to be what it was before and because by definition the `seq` will be lower (and thus clients will be higher) all of our clients will fail to sync properly.

**Comment by SCdF** [comment]
@browndav let me know if I missed the point of this, but since the seq resets to a lower value and I can't find a way of setting it arbitrarily I don't think there is anything else to be done here?

**Comment by estellecomment** [comment]
I don't think they'd fail to sync properly : they'll start comparing changes from that smaller seq, and since they'll already have most of the changes, they won't download the docs. There'll be a lot of useless `_changes` and `revs_diff` happening though. So server load.
So it would be painful for existing clients and hopefully nicer for new clients.

**Comment by SCdF** [comment]
@estellecomment do I misunderstand how replication works?
 - PouchDB client successfully replicates to seq `10,000`.
 - We bounce the couchdb server db around to remove edit history and deleted documents, so now the max seq is going to be smaller at `5,000`
 - When the PouchDB client connects it asks for the changes feed since `10,000`, and thus **misses the next 5,000 changes on the server**.

**Comment by estellecomment** [comment]
Oh you're right. Never mind.
