### ISSUE TITLE
national_managers cannot submit reports

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2386]
According to : https://docs.google.com/drawings/d/1XyeF5MRsT-kLqFlK8ZySq5xQQXVsY0HbJvUQmsi4rZI/edit

When upgrading .4 -> 2.8, we want a `person` associated to the national manager. That's so that the national manager can have a phone number, and send reports associated to him/her. 
(Any other functionality we need @abbyad ?)

We can do that by adding a `contact_id` field to the `user-settings` doc, which gets created from the migration. 
However, the national manager doesn't have a place (it has the imaginary-for-now root place), so test that whatever functionality we're looking for is actually working. (or create the root place!)

**Comment by alxndrsn** [comment]
> so test that whatever functionality we're looking for is actually working

Any guidance on what we're looking for?

**Comment by estellecomment** [comment]
As mentioned, we want the national manager to be able to send reports, and maybe @abbyad has more suggestions.

**Comment by garethbowen** [comment]
Assuming that the national manager has permission to see all records then we also need to ensure they don't attempt to replicate data. It'd be best to have no `facility_id` set rather than creating a root facility but we need to check that submitting forms still works if you have no facility.

We need more information about what sort of reports this user will submit because they currently won't be accessible to any other user who's not also a national admin (or db admin of course).

**Comment by alxndrsn** [comment]
Works for me on latest `master`.

**Comment by ngaruko** [comment]
Need more information on who are national managers and how to create those...Any thought @sglangevin

**Comment by sglangevin** [comment]
National manager is the "full_access" user. You can create one of these using the Users Configuration UI in the app. From the way I read this issue, this user will need a person, but not a place. You can leave the place blank.
