### ISSUE TITLE
Initial replication gets stuck on Tecno

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2394]
@garethbowen here is a summary of my findings. Let me know if I can investigate anything more thoroughly.

Everything looks great on Chrome, all data loads within a minute or two. On Tecno, here is where I get stuck:
![image](https://cloud.githubusercontent.com/assets/1286381/16053257/e48c8a46-321c-11e6-8e3d-1ea8da668810.png)

On the phone, initial replication status is in progress and I have a spinner on the History page, the + sign is not illuminated, even though I know the forms downloaded because I saw the requests come through on dev tools.

I tested using one of the Iganga users so that there would be some data in there to download. Could it be that my phone is slow?

Eventually it finished up:
![image](https://cloud.githubusercontent.com/assets/1286381/16053564/37b48204-321e-11e6-86bf-fb450eca2012.png)
![image](https://cloud.githubusercontent.com/assets/1286381/16053575/40ee5660-321e-11e6-9629-5d5a064c36e7.png)

The + sign illuminated after this, but I get "No reports found" on the History page. The Contacts tab has a spinner as well - I gave up after about 6 minutes of waiting for it to load.

Next, I reloaded. It still took over a minute for initial replication to complete:
![image](https://cloud.githubusercontent.com/assets/1286381/16053904/9713c056-321f-11e6-88b2-3706e7797982.png)

Contacts loaded in about 20 seconds, History in 5-10.

Compare this to logging in as the same user on Chrome - initial sync completed in 12.58 seconds, History page shows reports, and Contacts tab loads within 5 seconds. On reload, initial sync completes in 3.5 seconds.

We've got an order of magnitude difference between Chrome and Tecno, which is worth investigating, IMHO.

**Comment by garethbowen** [comment]
My working theory is the long delay is in processing the views for all the new data. It all seems to download correctly and then spend ages waiting until the initial replication completes. One possible way to mitigate this is to have a bootstrapping screen, so before angular loads and starts making requests of pouchdb we complete the initial bootstrap. Hopefully this means instead of trying to update the views multiple times as data is loaded, the views are only generated once when all the data is available. I'll run some tests to determine if this helps.

This doesn't explain the contacts and reports tabs not loading eventually - I'm still looking into this.

**Comment by garethbowen** [comment]
Assigning for review: https://github.com/medic/medic-webapp/pull/2398

**Comment by SCdF** [comment]
@garethbowen Code looks good, I can't think of any particular downsides of this, all good from me :-)

I didn't merge because you actually made a PR, which is odd for you.

**Comment by garethbowen** [comment]
@SCdF Shots fired!
