### ISSUE TITLE
Get medic-analytics deployable 

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2402]
We need:
 - postgresql credentials for every client that currently uses it
 - potentially couchdb credentials that either bypass medic-api or allow for reading the raw changes feed
 - a init.d script that can be used to start, stop and restart instances of medic-analytics per client. This would also probably just hard-code their credentials for now, later on we can do something more clever.

Also to document this stuff all somewhere internal.

**Comment by SCdF** [comment]
So honestly while googling the basic structure for an init script (I've never written one before) I came across this: https://gist.github.com/naholyr/4275302

@browndav can you think of any reason why we wouldn't just copy / paste that guy everywhere?

**Comment by browndav** [comment]
The init scripts we're using are currently the blocking style (similar to the ones used by Daniel Bernstein's `daemontools` with `qmail`, or `launchd` or `runit` or `supervisor` or any of the millions that have popped up since 2011). I have some work-in-progress documentation at https://gist.github.com/browndav/2fba8460b2510e2f63e1e9f5026c9b37; I suspect a cut/paste of what's already been done for `medic-core` might be the most direct path.

**Comment by SCdF** [comment]
I've tested it with 2.6 data, looking now to make sure it runs the same with 0.4.

**Comment by SCdF** [comment]
I've added documentation on how to use Upstart, which works on the version of Ubuntu we're currently using, and is dirt easy.

**Comment by SCdF** [comment]
This is complete, from a code perspective. When individual projects are ready to migrate other issues (like credentials etc) will be dealt with as they come up.
