### ISSUE TITLE
Add basic sync status to about page

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2415]
Related to #1849 but only do the bare minimum to give administrators feedback on when the last successful sync to and from completed.

**Comment by diannakane** [comment]
Our plan was to put the last sync date and synced/not synced icon at the bottom of the hamburger drop-down. Is that more work than putting it in the About page?  

Related to this decision is whether a "start sync" button is necessary -- or does syncing reliably happen automatically? @sglangevin made the good point that users want to know that syncing is happening, so perhaps what's most needed is a "sync in progress" indicator of some kind which can happen elsewhere in the app.

**Comment by garethbowen** [comment]
@diannakane Yes that's more work. Here's what I ended up with. Looking forward to getting the mockup done!

![basic-sync](https://cloud.githubusercontent.com/assets/2064938/16214590/1d1ca850-37ae-11e6-87ea-5cdbf7ecd4b0.png)

**Comment by diannakane** [comment]
OK, we'll save it for later. The questions I listed are what we need to
know to finish it. Do we need a "start sync" button?

On Mon, Jun 20, 2016 at 5:46 PM, Gareth Bowen <notifications@github.com>
wrote:

> @diannakane <https://github.com/diannakane> Yes that's more work. Here's
> what I ended up with. Looking forward to getting the mockup done!
>
> [image: basic-sync]
> <https://cloud.githubusercontent.com/assets/2064938/16214590/1d1ca850-37ae-11e6-87ea-5cdbf7ecd4b0.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2415#issuecomment-227311216>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABmSXijLS3BQ_2Dhcyd0XWKmvUkSj-B9ks5qNzRQgaJpZM4I6QdM>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by garethbowen** [comment]
Syncing should happen all the time reliably. It's attempted every couple of minutes so there should be no real need for a "start sync" button. If something goes wrong clicking the "refresh" button on the about page will also force it to restart.

**Comment by diannakane** [comment]
OK. @slangevin do you think a "sync in progress" indicator is important to
include in this update?

On Mon, Jun 20, 2016 at 6:19 PM, Gareth Bowen <notifications@github.com>
wrote:

> Syncing should happen all the time reliably. It's attempted every couple
> of minutes so there should be no real need for a "start sync" button. If
> something goes wrong clicking the "refresh" button on the about page will
> also force it to restart.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2415#issuecomment-227315484>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABmSXrUkMEHUDX9sHT0mJJ2EdgJvR6GWks5qNzwhgaJpZM4I6QdM>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by estellecomment** [comment]
Code LGTM.

This indicates that some data has synced, but can we guarantee the full replication is done? Could it be one batch out of several? 
Also, what happens if there's a failure, e.g. because of network interruption, do we get `on(error)` or `on(pause)` in that case? Is `on(pause)` necessarily successful? (that's when the status is updated)

Basically, make sure the displayed message doesn't promise more than what's actually happened.

Cool!

**Comment by garethbowen** [comment]
From the pouchdb docs:

> This event fires when the replication is paused, either because a live replication is waiting for changes, or replication has temporarily failed, with err, and is attempting to resume.

If it's temporarily failed it passes `err` which I'm checking for. As far as I can tell, `paused` without an error means "up to date and waiting for more changes".

**Comment by sglangevin** [comment]
@diannakane I think for now, a "last successful sync" is helpful. LG is already using the Reload button to force syncing to start again. This way they will know when everything has synced - previously they had no way to confirm that a phone was up to date.

Indicating that the phone is syncing would be helpful to a CHP, though. For example, a CHP has been working offline for a few days and then connects to the internet to sync. She would want to know that syncing has started and be alerted when the phone has successfully synced all docs to and from the server. Not sure if that fits in this issue, but I do think we should explore further and find a way to provide a visual indicator to a CHP so that she knows when her phone is synced and can be disconnected from the internet.

**Comment by sglangevin** [comment]
@garethbowen The sync status is now showing up for me, but the formatting looks strange on mobile. Here is a screenshot:
![screenshot_2016-06-21-14-02-37](https://cloud.githubusercontent.com/assets/1286381/16240902/1f6805d6-37a0-11e6-87b2-b9d3828a8864.png)

Returning this so that we can update the formatting to be more mobile-friendly. Perhaps left-justify everything so that we have more space?

**Comment by garethbowen** [comment]
I might just make it a vertical list on mobile with

- label
- value
- _padding_
- label...

**Comment by diannakane** [comment]
@slangevin I think the second part of your comment is the original issue
#1849, I will add these notes to that issue.

On Tue, Jun 21, 2016 at 1:50 PM, Gareth Bowen <notifications@github.com>
wrote:

> I might just make it a vertical list on mobile with
>
>    - label
>    - value
>    - *padding*
>    - label...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2415#issuecomment-227567727>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABmSXiBMhI0emXFrvPWcrz7n6ToCsmJAks5qOE6wgaJpZM4I6QdM>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by garethbowen** [comment]
I've updated the styles for mobile.

**Comment by sglangevin** [comment]
This now looks good on mobile. Moving to ready.
