### ISSUE TITLE
Local DB grows without limit

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2434]
1. Log in as a restricted user
1. Wait for replication to complete
1. Check the size of the IndexedDb
1. Update the app to the same version
1. Reload when prompted
1. Check the size of the IndexedDb again

The DB size should be roughly identical as the old ddoc was replaced with an identical ddoc. What I'm actually seeing is the DB size increase by around 600KB every time a new ddoc is retrieved.

**Comment by garethbowen** [comment]
Probably caused by https://github.com/pouchdb/pouchdb/issues/4372 - if revs_limit and auto_compaction are on neither work. Fixed in the latest PouchDB.

**Comment by garethbowen** [comment]
From my testing there is no combination of settings that can fix this bug. I think the correct setting for us is `revs_limit:1` which will also imply `auto_compaction:true`. Wait until PouchDB 5.4 is stable, and we've made the ddoc small enough that performance doesn't regress, then test these settings again.

**Comment by garethbowen** [comment]
Even with the latest pouchdb and playing with those settings I can't resolve this leak.

**Comment by estellecomment** [comment]
@garethbowen how do you get the size of the indexeddb? With android app manager? Or are you on desktop?

**Comment by estellecomment** [comment]
Ok here's something fun. Running `db.compact()` makes the db **grow** by 140KB.

Running in console :
```
var db = new window.PouchDB("medic-user-demo");
db.compact().then(function (result) {
  // handle result
  console.log(result)
}).catch(function (err) {
  console.log(err);
});
```
With latest webapp code, on tecno Y4, user demo (2 families). No app update.
![screen shot 2016-08-12 at 15 53 29](https://cloud.githubusercontent.com/assets/911434/17624445/f412c974-60a4-11e6-9992-652cb0810cf9.png)

**Comment by estellecomment** [comment]
(how we get to 22MB with 2 families is another question)

**Comment by garethbowen** [comment]
I measured it on desktop. In retrospect I'm starting to think it might be a bit misleading. Maybe even if `compact` is called the browser doesn't GC right away. More investigation needed for sure.

**Comment by SCdF** [comment]
OK so I think this is working as well as PouchDB can manage. Whether or not IndexDB itself is cleaned up in the background is an exercise in mysticism.

Steps that I followed to test:
 - Use Chrome Canary. While this reliably crashes after <5min every time I boot it, its indexdb inspector actually works correctly, allowing you to search and filter for things (filter in stable is broken for me)
 - Load up a CHW to completion. Open indexdb and find the `_design/medic-client` entry:
![image](https://cloud.githubusercontent.com/assets/583851/18164044/d87d7588-7035-11e6-8ab8-3221b45c630e.png)
There is a lot of interesting stuff there, esp in the `data` block. The only bit you care about it the seq: 1314.
 - Look up that value by hand:
![image](https://cloud.githubusercontent.com/assets/583851/18164063/f0513ce4-7035-11e6-85a4-f893f5c735c8.png)
 - Forcibly change the DDOC (I changed the gateway phone number in app settings using futon. The only stuff you can change in code is views, and who wants to wait for those to regenerate!)
 - Open Chrome Canary again (because it crashed) and reload everything
 - Open indexdb and find the `_design/medic-client` entry again:
![image](https://cloud.githubusercontent.com/assets/583851/18164169/5d3e2768-7036-11e6-9c56-4621916d027c.png)
 - Note the different seq number. Check for the *original* seq number. It helps to filter for a slightly earlier number:
![image](https://cloud.githubusercontent.com/assets/583851/18164187/7bf1827c-7036-11e6-85d1-ae4bef38f936.png)

^ As you can see, the original document (1314) is gone, replaced by the new one (1315).

@garethbowen / @estellecomment does this convince us that PouchDB is doing the right thing? Not sure what else to look for.

**Comment by SCdF** [comment]
(where Code Review in this case is really Testing Methodology Review, but we don't have a label for that one…)

**Comment by garethbowen** [comment]
I wonder if [viewCleanup](https://pouchdb.com/api.html#view_cleanup) would fix the problem... Can you try that and see if the IDB space reduces? This is the same issue we hit with couchdb recently.

**Comment by garethbowen** [comment]
Running viewCleanup on my local install cut the IDB size down from 6MB to 2.4MB. We should probably be running it every time any ddoc is changed.

**Comment by garethbowen** [comment]
The above changes are, as far as I can see, the best practice for recovering disk space. It wasn't clear in testing whether this fully resolved the issue but as above I think we don't fully control when disk space is recovered as sometimes restarting the browser freed up more IDB space.

I think we've done all we can and we have to leave the rest up to pouchdb and browser implementations.

**Comment by SCdF** [comment]
Made some comments on the commit

**Comment by garethbowen** [comment]
Replied to said comments on the commit.

**Comment by sglangevin** [comment]
The local DB seems to be growing in size now. Started at 98 MB after I completed syncing. I did 1 reload from the About page and let the phone sit a while, and I'm not at 119 MB. This is different from the relatively stable app size I've seen in the past. I wasn't exactly sure how to test this one though.

**Comment by garethbowen** [comment]
This is basically impossible to acceptance test - there's just too much going on under the hood. I'm confident we're doing more compaction now than before so we'll leave it at that. If it happens again we can raise a new issue.
