### ISSUE TITLE
`extract-person-contact` migration can leave data mangled if it hits an unexpected format 

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2435]
When creating a contact for a facility, if the creation of the new `person` fails, the whole migration fails, leaving the facility contact-less (because the contact was previously deleted in order to create the `person` with a loop-less parent).

Either reset the facility's `contact` field to what it was before migration, or don't remove it until we're sure the `person` is created ok. (this means maybe not using the api call to `people.createPerson`)

**Comment by alxndrsn** [comment]
Have you got example data that will break the migration?

**Comment by estellecomment** [comment]
No. This would happen if the `person` can't be created. I don't remember if I saw this happening specifically.

**Comment by garethbowen** [comment]
I've updated the migration to attempt to restore the facility contact if creating the person or updating the contact fails. It's worth noting that there are many other ways that this (or any other) migration can mangle the data. Because we don't have transactions we can't revert properly. For example, if api crashes in the middle of a migration it's almost guaranteed to leave it in a corrupt state. That's why we always recommend to back up your db/instance before running an upgrade.

**Comment by estellecomment** [comment]
LGTM

**Comment by estellecomment** [comment]
Skipping acceptance testing, cos that is pretty hard to test
