### ISSUE TITLE
Reports are being sent twice

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2439]
Seen on Brac : 
https://brac-ug.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/BE7716E6-2E58-6030-B72B-EC54AD7B7269
https://brac-ug.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/2536C3F7-1AA0-5C5B-9D21-72ADDA87A349

The reported_dates are about 1s apart:

```
new Date(1467053446457)
Mon Jun 27 2016 20:50:46 GMT+0200 (CEST)
new Date(1467053447036)
Mon Jun 27 2016 20:50:47 GMT+0200 (CEST)
```

That looks like a button that was clicked twice, we should disable buttons properly.

@Enock1990 reported it in https://github.com/medic/medic-projects/issues/455.
Enock, how many times did you see this happening?

**Comment by sglangevin** [comment]
Tagging @michaelkohn as we have also seen this in a few cases with LG. I did some testing and it is not possible to reproduce this in a browser because the button disables too quickly. It is possible to reproduce on the Tecno, though. The button does disable, but if you tap the button a few times really quickly you can submit multiples of the same report before the disabling happens.

**Comment by sglangevin** [comment]
A debouncing feature was introduced in v2.8.4 to help with multiple form submissions.
