### ISSUE TITLE
medic-webapp complete server setup process

### ISSUE THREAD

**Issue by waqar-ah** [medic/medic-webapp#2461]
Hi, i recently started working on medic-webapp, i have deployed it on localhost.it is showing dashboard but i don't know how to configure SMS module of it i does nothing when i click on new SMS button.

I want to run medic-webapp in a server environment with SMS gateway please guide me what is the process to do this.... 

and whats the difference between all these

```
medic-webapp
medic-gateway
SMSSync
medic-api
medic-os
kujua lite

```
Help is appreciated in advance

**Comment by garethbowen** [comment]
medic-webapp: This is the main app and it includes medic-sentinel and medic-api as git submodules. 
medic-gateway: This is an android app for sending and receiving SMS messages.
SMSSync: This is a deprecated version of medic-gateway
medic-api: This is the node server for controlling access to couchdb.
medic-os: This is for building a stripped down linux OS with the whole medic stack.
kujua lite: This is a deprecated version of medic-webapp
medic-sentinel: This is a node server which can make async modifications to docs and check whether scheduled messages are due to be sent.

**Comment by waqar-ah** [comment]
ok Thanks .. Got it my concern is medic-webapp and medic-gateway now to run complete app.  but medic-gateway not sending messages. issue is: [#2551](https://github.com/medic/medic-webapp/issues/2551)
