### ISSUE TITLE
Language dropdown is empty when adding or editing a user

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2462]
lg-testing.app (v2.7.1-beta.3547)

![image](https://cloud.githubusercontent.com/assets/1286381/16600573/93bbbe2e-42bc-11e6-9bc2-175fc9f502a2.png)

**Comment by garethbowen** [comment]
Translations have been heavily refactored in `develop` so the solution there is completely different and thus both need code review. The bug was introduced when we converted the edit user modal to the new Modal format which means it no longer had access to the InboxCtrl scope which is usually a good thing but the modal was using that to get enabled locales.

**Comment by estellecomment** [comment]
LGTM

**Comment by sglangevin** [comment]
Looks good - moving to Ready.
