### ISSUE TITLE
lg.app update error

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2485]
When updating lg.app to 2.7.2 @sglangevin got this error:

![pasted image at 2016_07_11 04_13 pm](https://cloud.githubusercontent.com/assets/2064938/16750591/fa241e26-4826-11e6-87be-2ab7c32d1579.png)

This indicates the "Configuring Type" step has failed. Unfortunately this step ignores any errors so we don't have any more information about what went wrong. Because we were experiencing connection issues at the time I suspect the server was just overloaded and rejected the request.

This step updates some of the Dashboard information about the update which means in this case Dashboard is still reporting 2.7.1 is installed and has an active Update button. Clicking that button gives the following error...

![pasted image at 2016_07_11 04_18 pm](https://cloud.githubusercontent.com/assets/2064938/16750636/4204c510-4827-11e6-8aac-63e301816491.png)

This indicates that the cleaning up that wasn't done in "Configuring Type" has left Dashboard in an inconsistent state.

Fortunately the app appears to have been updated correctly, the API patch can be seen in `/srv/storage/gardener/data/working_dir`, and I've restarted API to ensure it's running. So this doesn't affect users, however it presumably will stop us updating in future. Clean up the dashboard database so we can update in future.

**Comment by mandric** [comment]
So there is an install doc for every app that is installed by dashboard and we see a failure here during the final Configure Type step of the install.  The install doc was not completely updated/the install failed.  You can easily find the install docs by looking at this dashboard view e.g. `https://myproject/_utils/database.html?dashboard/_design/dashboard/_view/by_active_install`.  So I confirmed the `kanso` property of the install doc was still at `2.7.1` while the `kanso` property on the actual ddoc was at `2.7.2` and updated the install doc manually in futon.  The update button is gone now and I future installs should not be affected.  

It appears we failed to reach couchdb in that last step because of our couchdb performance issues, we could look at the logs further at that time to see what failed or if any errors are reported.  Also keep in mind there is a direct couchdb proxy rule in the nginx config that allows dashboard direct access to couchdb, I would have to confirm by looking at more logs, but nearly certain this was a direct couchdb request that failed.

Error/failure handling is missing in that last step as you noted in the channel during the incident, the dashboard code is lacking. Linking a related Garden Dashboard issue here, if we continue seeing errors like this we should look at fixing it. https://github.com/garden20/dashboard/issues/85

**Comment by mandric** [comment]
Actually looking at the console screen it looks like the request to staging failed for some unknown reason.  So we might just chalk this up to bad garden dashboard error/failure handling.  Most of these steps should all be done server side anyway when at all possible, so the installer/client would just start the install process on the server and get a response when it finishes.  Or if a server side process is not available then at least run the same library (garden-core), that has decent error handling, in the browser.

**Comment by garethbowen** [comment]
Thanks @mandric - I'll keep an eye on it during the next install.
