### ISSUE TITLE
Review contents of docs Estelle wrote

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2501]
Estelle wrote, for instance, that nginx is used for load balancing, which doesn't quite sound right. (thanks @SCdF for the catch)

Please reread and comment on this diff, so I can fix it : 
https://github.com/medic/medic-webapp/commit/e9e9d7364b8c6df32cfc41b08b9a0f6250e7e843

**Comment by SCdF** [comment]
I've made some comments. Writing stuff like architecture documents is generally quite hard to make succinct and accurate. I'd suggest you start (or go to next, since you already wrote some stuff) with getting a diagram and getting it accurate, with the right amount of detail. On paper, or some internet tool, whatever makes sense. That will perhaps make it clear which components are important and how much detail each one requires. I'd also think about your audience and what their goal is when they're reading the document: ie developers who are looking to understand the codebase and contribute to it.

**Comment by garethbowen** [comment]
I've added some comments. My main concern is all the lines that suggest SMS only works pre v2 which will be out of date in a month or so.

@estellecomment This has been sitting around for over a month now. I think it's ready for the review comments to be approved and merged and this issue closed off. I'm happy to help out if you have too much on your plate.

**Comment by estellecomment** [comment]
Updated!
I'm closing this, reopen if there's more to discuss and update. Thanks for the inputs!

**Comment by estellecomment** [comment]
Reopening, it's worth a second round of review. Thanks @SCdF for volunteering!

**Comment by SCdF** [comment]
Just a couple of minor comments, nothing to write (!) home about. LGTM!
