### ISSUE TITLE
Add recipients doesn't work

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2659]
To reproduce:
 - Go to the messages tab
 - Click on already contacted person
 - Click reply to and type some stuff
 - Click add recipients

What you'd expect to see:
 - The send message modal
 - with the contact already in the to box
 - and your message in the message box

What you actually see
 - The send message modal
 - You message in the message box
 - **Noone in the To box!**

This is probably because select2 changed.

NB:
 - This actually sort of works if select2 has seen this contact before on this refresh / session. If you send a message to someone and then click them and hit add recipient you get their ID, but none of the rest of the data. This looks terrible, and doesn't actually end up sending anything.

NBNB: This is true both in master and once #2500 is merged. We obviously want to fix the #2500 case.

**Comment by SCdF** [comment]
Hey @garethbowen check out https://github.com/medic/medic-webapp/pull/2672

If you're happy with it I'll squash it into a sensible commit message.

**Comment by garethbowen** [comment]
I've added some comments to the PR.

There seems to be a change where instead of passing the given doc to send message, we just pass doc._id, and then fetch the doc from the DB again. This shouldn't be necessary. If you're given an object with a _id property then we should just be able to supply that directly and only go to the DB if we're given a string that's not a phone number.

**Comment by SCdF** [comment]
> If you're given an object with a _id property then we should just be able to supply that directly

This might work for selections added via being automatically injected from the message pane, but it doesn't work for search results for example, which are summaries not documents.

**Comment by SCdF** [comment]
Squashed and merged.
