### ISSUE TITLE
Add `public_access` flag to app_settings

### ISSUE THREAD

**Issue by wombleton** [medic/medic-webapp#267]
... which, if truthy, does not display the "Facility not found" error for messages from unknown numbers.

**Comment by mandric** [comment]
`public_form` still exists on the form definition and pretty sure that's the right place for it.  It works as expected, when true the facility not found error is not assigned to new records.  

We should consider creating a new issue for documentation for this, or add a new item to the issue for forms format documentation since we have none afaik.

**Comment by mandric** [comment]
tested on:
medic-os-v1.1.0-x64-alpha-20150107
webapp 0.5.0-alpha.1533
