### ISSUE TITLE
e2e test for the app_settings update flow

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2676]
- make a change to `medic` ddoc app_settings
- the app_settings get copied over to `medic-client`'s app_settings
- the change in `medic-client` triggers the Update modal
- user clicks modal
- page gets refreshed, and new settings are present (e.g. new form in the list, or something else visible)

**Comment by garethbowen** [comment]
Step 3 won't happen. Unfortunately we've had to turn off all longpoll requests (read: changes feeds) because they cause protractor to hang while waiting for the page to load.

There is still plenty of value in testing that the setting is copied to medic-client and when the page is manually refreshed the setting takes effect.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by alxndrsn** [comment]
Sounds worthy, but doesn't look like it's happening.  Also I don't think this code is likely to change.
