### ISSUE TITLE
Field descriptions in Dashboard's App Settings are formatted as section titles

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2686]
# Example 1:

![image](https://cloud.githubusercontent.com/assets/789512/18099278/c0e1bd54-6eb3-11e6-9a5d-4981ecaaf7f8.png)
# Example 2:

![image](https://cloud.githubusercontent.com/assets/789512/18099293/d4443f3e-6eb3-11e6-80c0-a09a84a7c0e9.png)

**Comment by garethbowen** [comment]
This is due to a bug in a [json.edit](https://github.com/marianoguerra/json-edit) which is the library dashboard uses to render the app-settings page. `description` fields on inputs render nicely, but `description` fields on groups of inputs render as a header.

We can update dashboard to overwrite the CSS, or attempt to patch the original library, but json.edit has many such issues so I recommend continuing to move settings configuration into the app and removing out dependence on it altogether.

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by SCdF** [comment]
It sounds like dashboard-based configuration is, if not deprecated, relegated to minor edits only these days. I think we can close this for now. I imagine the next piece of work we'll be doing on this area will either be deleting it completely, or making such a massive change this will get solved in the process.
