### ISSUE TITLE
Add User modal doesn't display errors to user

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2696]
Here, saving failed, no error was displayed. 
(it failed because there was already a user with the same username)
![screen shot 2016-09-01 at 13 50 44](https://cloud.githubusercontent.com/assets/911434/18166391/33ac5f86-704b-11e6-8003-f35c89c2dc79.png)

**Comment by garethbowen** [comment]
This affected all modals - not sure how it escaped my testing but something must've changed. The problem is due to the isolated scope of directives, meaning the directive can't access variables in the controllers scope. The fix is to pass through a `status` variable which contains the processing and error state.

**Comment by estellecomment** [comment]
ha! Thanks!
