### ISSUE TITLE
Default "New Person" form doesn't alow editing the parent place

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2704]
In the default "New Person" form (the generated contact form for when there is no contact form uploaded) has no field to see/choose what the selected parent is, which [the mocks](https://projects.invisionapp.com/share/XA7CTCBGU#/screens/159906705_District-area) want. 
It looks like this.
![screen shot 2016-09-02 at 16 40 52](https://cloud.githubusercontent.com/assets/911434/18207612/27cc7386-712c-11e6-8ad4-3d4754e189db.png)
Add a parent select2 field.

(Note that if you get there from "New Person" from a place, the person is correctly created in the place. That's cool.)
Useful for #2344

**Comment by SCdF** [comment]
This requirement was spawned from the reading of a design mockup, specifically this one: https://projects.invisionapp.com/share/XA7CTCBGU#/screens/159906666_District-branch

It shows the new person form like this:
![image](https://cloud.githubusercontent.com/assets/583851/18339044/fcc8ecec-7594-11e6-9935-94495a1b203d.png)

@Lesterng / @diannakane is an intentional addition to the form (compared to the current one) that the user can change the parent place of a person when they create it? Considering they (afaik) can only create new people in the context of a selected place, I would imagine their usage flow would have made them select the correct place already.

**Comment by diannakane** [comment]
I think you are right, @stefan. We were probably following convention of
being able to do that in the current web app, but those long drop-down
lists are hard to navigate. We do want to show what place you are adding
the new person or place in this form, but I think it could be grayed out.
@slangevin, what you do think?

**Comment by sglangevin** [comment]
Yeah, I think that it should just display the place you are creating the person within, no need for a drop-down to allow the user to change as they should be getting to adding a person by navigating to the place they want to add them to. I'd vote for simply displaying the name of the parent place, if that is doable, no dropdown.

**Comment by diannakane** [comment]
I think that makes sense as well.

**Comment by estellecomment** [comment]
Ok! So this issue is a non-issue. Thanks all!

I'm going to open another one to remove the dropdowns in the default forms.
