### ISSUE TITLE
Use proper pluralization in translations

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2712]
So far, the translations have two different keys from plural and singular.
I don't know the plural rules of the languages we support, and whether they need more than one vs. many.

We can use this : 
https://angular-translate.github.io/docs/#/guide/14_pluralization

**Comment by SCdF** [comment]
So I've created this branch / pr: https://github.com/medic/medic-webapp/pull/2747

The current status is that when you have this code in  place bootstrap never lets goes of its straps, and spins its spinner for ever.

Cannot work out why.

**Comment by garethbowen** [comment]
Ok. It's working, but still a work in progress.

I was getting an exception in the console (firefox vs chrome?) which helped me track down the problem. Switching to use a different messageformat fixed it ([as covered by this doc](https://angular-translate.github.io/docs/#/guide/14_pluralization)).

You had an incorrect syntax on the "n.weeks" value (an extra comma). I also had to switch to optional messageformat interpolation otherwise it breaks all the existing translation values due to the different format.

The upshot is it works:

```
<a
  translate
  translate-values="{ MONTHS: 6 }"
  translate-interpolation="messageformat"
>
  n.month
</a>
```
![proof](https://cloud.githubusercontent.com/assets/2064938/18570916/50a0e4dc-7c02-11e6-8ed5-a2145c618a54.png)

Still to do:
* Something funny happened with the enketo-core and bootstrap-datepicker modules and now sass fails to compile. I just commented it out and moved on. I suspect it's something to do with the shrinkwrap changing the version of one or other of those dependencies. Revert back to the same shrinkwrap as master and try to make the minimal change for the new lib.
* In app.js the import URL for the `angular-translate-interpolation-messageformat` lib is really ugly. See if it can be improved for reliability and readability.

**Comment by garethbowen** [comment]
@SCdF All yours!

**Comment by SCdF** [comment]
Dropping this so someone else can pick it up. I haven't made any interesting progress passed what Gareth made in the linked PR / branch.

**Comment by garethbowen** [comment]
I've cleaned up the PR so it's ready to merge IMO now. Assigning to @estellecomment for code review as @SCdF is away.

**Comment by estellecomment** [comment]
Cool! We can now support Polish and Turkish and other obscurely pluralled languages!
Good job! 
One comment to check so I left the merge for you, but LGTM.
