### ISSUE TITLE
Some fields in new People tab are not present in default forms

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2719]
There are fields in the new People tab mocks that we don't currently collect. If we want to collect them, we should add them to the default forms. 

Ids for places : Branch id, CHW id, Household Id
Gender (for all Persons : family members, CHW, various managers)
Titles of Persons (e.g. "Branch Manager", "CHW", "Intern")

There are also not present in the ContactSchema. If they are defaults, they should be added to it.

@diannakane please confirm these fields should be present by default. If yes, on to form design!

**Comment by garethbowen** [comment]
IDs only make sense for SMS installations so shouldn't exist in the default forms. The others are optional extras - it's not necessary to have everything available in the default forms, but the new profile will support whatever fields the tech leads decide to configure.

**Comment by estellecomment** [comment]
> IDs only make sense for SMS installations

I disagree with that. Partners can have their own id system for places and people. We have instances with CHWs with external_ids.

They are optional extras so far, yes. I'd like to know if the design folks mean to change that. I expect that default forms should get you the results shown in the mocks.

**Comment by diannakane** [comment]
@garethbowen  I understood from @sglangevin that the fields we display in the profile are hard-coded and not yet configurable (I was going to create an issue for that). It's somewhat hard to design for unlimited configurability because there could be a long list of fields a tech lead chooses to display. 

@estellecomment I had included titles of persons in the mock because it seems useful to know whether you are about to call a manager, nurse, CHW, or patient. This was before I learned that we can't have place-specific "add person" forms as logged in #2693 . We could include a drop-down in all add-person forms that asks about the type of person and include "family member" as an option (or even more granular distinctions) if others don't think that would be too confusing. Or, we could use the notes field and instruct managers to manually enter the role of the staff person. @sglangevin any thoughts? 

We included external ID so the cards would work for both SMS and Android projects. I don't believe there's any use for IDs in our current Android projects (it's a much longer ID format), but I could imagine scenarios where there would be, and don't think it affects those users too much to see it. @sglangevin let me know if you disagree.

**Comment by sglangevin** [comment]
@garethbowen I don't know of a way to configure which fields display on a particular contact's profile. Is that something that can be configured? If so, let me know how! My understanding was that the fields on the contact profile were hard-coded, with certain fields displaying for families, certain fields displaying for primary contacts and certain fields displaying for other family members (mostly children). I've included screenshots below.

I would lobby for using a field that asks about the type of person as opposed to a notes field. That way, if/when we are able to display different types of people in different lists, we'll know who is who and it will be relatively standardized. The more ideal situation would be to have different types of add person forms at different hierarchy levels, as Dianna mentioned.

The ID that is in the mockups is representing the 5-digit ID code generated by the web app in all SMS projects. We are not currently generating these IDs for Android projects. However, this is an important piece of data to display for SMS projects. Perhaps we can make that configurable by project? Then we could choose to show or hide that information as needed.

In general, I think it would help to have a way to configure which fields from a `person` doc will get displayed on the profile page, so perhaps we can create an issue for that.

Families have no contact info:
![image](https://cloud.githubusercontent.com/assets/1286381/18369571/69f05d8c-75db-11e6-8a3e-46ee2c69060c.png)

Primary contacts have name, age, the family they are part of, and a details section that can be shown or hidden:
![image](https://cloud.githubusercontent.com/assets/1286381/18369583/830e9bf8-75db-11e6-890e-40251ec310f9.png)

Children/other family members have name, age and the family they are part of:
![image](https://cloud.githubusercontent.com/assets/1286381/18369598/a1b1e6be-75db-11e6-9684-9a9d7665d793.png)

**Comment by garethbowen** [comment]
I never meant to imply the fields are configurable. In the new UI we simply output an Age (for example) if one exists. If the form doesn't have an `date_of_birth` field then nothing will ever be displayed there.

**Comment by sglangevin** [comment]
Ok, so what did you mean when you said "the new profile will support whatever the tech leads decide to configure"? Did you mean that we can choose not to collect data that is part of the default form / contact profile view and it just wouldn't be displayed?

**Comment by garethbowen** [comment]
Tech leads can choose not to configure a `date_of_birth` field in their contact form. If they decide not to configure that field then their Age will be blank on the profile.

**Comment by sglangevin** [comment]
Ok, got it. Then I think this is just a matter of agreeing on what should be in the default form and then displayed on the contact profile. The ID field needs more discussion - perhaps we include it and then it is only populated for SMS projects. We could also make that configurable - hide or show depending on the project.

I'd also propose opening another issue for a feature where we could have an additional "more info" type of section on the contact profile that is configurable up to a certain number of fields so that tech leads could display other custom fields on contact profiles. We've already had requests for such a feature and it would enable better flexibility around what information a user can access on a contact's profile page.

**Comment by diannakane** [comment]
The ID is the only thing on this list that is set by Medic (not input from
a form) and not editable. Would it be possible, and would it help this
issue, if we displayed that somewhere outside of the rest of the profile
info? Would that make it configurable and easy to hide for Android projects?

**Comment by estellecomment** [comment]
If that can help, here's what the default form looks like right now.

Currently, when you are in, e.g., a branch, and you click "Add Area", you get this : 
![screen shot 2016-10-07 at 11 50 26](https://cloud.githubusercontent.com/assets/911434/19186151/26acff60-8c85-11e6-90c3-f003dfcf61e2.png)
 - The Branch/Area/Household selection is preset, but changeable. (do we want this?)
 - The parent branch is not preset, and is changeable (not sure why it's not preset actually) (do we want this?)
 - Not sure what the supervisor field is.
 - Don't know if the fields collected for the CHP are the right ones.

**Comment by diannakane** [comment]
From what I understand, all "add person" forms have to be the same for all
places (issued filed for place-specific add person forms), though I know
there are some exceptions for when you create a person when creating a
place.

Since level 3 is formatted for households (android) and areas (SMS), would
the "age" field displayed under the name in the list of people be hidden if
it was not collected for CHWs? (this could be good, because it would help
us differentiate CHWs from other type of people). If not, it means we have
to collect their age in this form.

We discussed this in another issue somewhere and think we agreed that
because you are creating a person or place from within a selected place, we
do not need a changeable parent place option.

If there are multiple supervisors at a branch, and you are adding a new
area to it, the supervisor field could allow you to choose which branch
manager is in charge of this area. Could be a useful feature. In this case,
this drop-down list should only show the people belonging to the parent
place. Another example of this is adding a household and selecting which
CHW should be the supervisor, where two are sharing an area. (this is a
common set up in some places, and we'd want our permissions to support
co-CHWs to see the same list of households... that's another conversation).

**Comment by sglangevin** [comment]
The form in @estellecomment's screenshot is a form for creating a CHP Area. This form (like the form for creating a family/household) creates both the place (CHP Area) and the person (CHP). The CHP is the primary contact for the CHP Area, which is why this form creates both. Is this the default form? If so, it probably shouldn't be as this is an LG-specific form.

Seems like the CHP Area / health center creation form should be similar to the branch/district form where it allows you to give the place a name and then you can either choose an existing person as the primary contact or create a new person.

All projects have the option of overriding the default forms if they need to collect additional information about people or places, so I think sticking with a minimum number of fields for the default forms makes sense. If a project wants to collect other information, then a custom form can be built, as we have done for LG and other projects.

**Comment by diannakane** [comment]
Thanks for calling out the piece about the primary contact, @slangevin.
Devs, most likely this will be a new contact, but for instance, we don't
want to force a manager to create new contacts for a bunch of areas that
haven't yet been assigned to CHWs so in this case they could assign
themselves. That is included in the lo-lo-fi mockup in the spec.

We didn't include a supervisor field in that mockup, but given that it's
been used in LG standard forms and there is a useful user story for it, we
can include it.

**Comment by estellecomment** [comment]
Sorry, actually that WAS LG's form (good catch @sglangevin !) so my intervention was most unhelpful. Here it is, all over again, with the default forms this time.
(I don't know if you guys all have access to the default forms and know what they look like; if you already do, then this is old news for you. If not, then it'll be helpful hopefully)

**New Place default form**
 - The Branch/Area/Household selection is preset, but changeable. (do we want this?)
 - The parent branch is preset (ignore above when I said it wasn't), and is changeable (do we want this?)

![screen shot 2016-10-10 at 11 41 57](https://cloud.githubusercontent.com/assets/911434/19232190/c0d78a28-8ede-11e6-9288-6a9371a9068e.png)
![screen shot 2016-10-10 at 11 42 09](https://cloud.githubusercontent.com/assets/911434/19232192/c0edb942-8ede-11e6-8ff9-30e8105f5d57.png)
![screen shot 2016-10-10 at 11 42 17](https://cloud.githubusercontent.com/assets/911434/19232191/c0e80236-8ede-11e6-973a-9b3d8f0755c3.png)

**New Person default form**
 - No "role" field
 - doesn't show the parent place (though it does create the person attached to the place, it's just a display problem)

![screen shot 2016-10-10 at 11 45 39](https://cloud.githubusercontent.com/assets/911434/19232409/e8a07758-8edf-11e6-8da0-8f8e5fe3611b.png)

**Comment by estellecomment** [comment]
Now, about the various features and variations : I'd like to split out what we want now, vs what we'll get to. Not saying we shouldn't do all the things, but I'm trying to prioritize what to do in People tab redesign.
Especially, I'm trying to split out what's just changing the default forms, vs. what requires work elsewhere in the app (and thus more likely to be out of scope)

**Requires other work (and thus more likely to be out of scope for People tab redesign)**
 - having separate forms for creating different kinds of people (e.g. managers vs CHW vs patients) @sglangevin I think LG have gone around that by customizing the "New Household" form to also create patients? Or something?
 - attaching a given supervisor, picked from several supervisors, to a CHW area. Right now, the relationships we have are : 
   - the CHW is the single primary contact for the area (there can be other people in the area)
   - the parent of the area is the branch
   - the branch has a single primary contact (there can be other people in the branch)
 - attaching a given CHW, picked from several CHWs of the area, to a household: this is the same case as the one just above, one level down.
 - creating a place with a temporary contact. As @diannakane mentioned you could set a temporary one and change it later, but that is currently **broken**, because when you change the contact the change is only half-done (the place knows its contact has changed, but the contact doesn't know its parent has changed). We should **not** rely on this flow right now. I don't know if we should even allow changing contacts in the given that it's broken, but maybe admins still need it, @sglangevin would know better.
 - changing the "visual design" (e.g. colors, shape of dropdowns, font sizes etc). That's changeable though, eventually. The change would apply to all forms, for all projects (e.g. all dropdowns would be blue, in the whole project, and for all projects).
 - select boxes with dropdowns which offer selections by person type. We can do *some* things but not everything. Selecting by user type (e.g. CHW vs. intern), not sure. 

**Only requires editing the form (we already support it)**
 - adding fields
 - changing the name of fields
 - changing the order of fields
 - changing required/not required fields
 - select boxes which offer choices of a given contact type (e.g. only Persons, or only Households, or only Areas, or only Branches)

**Comment by estellecomment** [comment]
Actually, is this within scope of the People tab redesign at all? Happy to hear opinions.

I think there are minimum variations that are within scope: 
 - making sure we gather the fields that we want to display in the profiles (e.g. user role)
 - allowing/disallowing changing the parent

**Comment by sglangevin** [comment]
@estellecomment, just chatted with Dianna and wanted to add a few points of feedback to your "Requires other work" list.

> having separate forms for creating different kinds of people (e.g. managers vs CHW vs patients) @sglangevin I think LG have gone around that by customizing the "New Household" form to also create patients? Or something?

That is not the case. LG has the same "add person" form at all levels of the hierarchy, whether it's a branch manager or family member.

> attaching a given supervisor, picked from several supervisors, to a CHW area. Right now, the relationships we have are :
- the CHW is the single primary contact for the area (there can be other people in the area)
- the parent of the area is the branch
- the branch has a single primary contact (there can be other people in the branch)
attaching a given CHW, picked from several CHWs of the area, to a household: this is the same case as the one just above, one level down.

This makes sense - I'm assuming you mean that we can't have a dropdown that only contains a subset of people. That would be a very useful feature for many things, like selecting a supervisor or changing the primary contact of a family. Not a priority at the moment.

> creating a place with a temporary contact. As @diannakane mentioned you could set a temporary one and change it later, but that is currently broken, because when you change the contact the change is only half-done (the place knows its contact has changed, but the contact doesn't know its parent has changed). We should not rely on this flow right now. I don't know if we should even allow changing contacts in the given that it's broken, but maybe admins still need it, @sglangevin would know better.

I don't think that we should block this right now. And I think we're confusing changing the primary contact with moving someone from one place in the hierarchy to another (say, from one branch to another). When you assign a primary contact, that person doesn't have to be a child of the place for whom they are the primary contact. It doesn't signify a hierarchical relationship. So the problem you're referencing likely doesn't apply in this case (I'd have to test to confirm).

> select boxes with dropdowns which offer selections by person type. We can do some things but not everything. Selecting by user type (e.g. CHW vs. intern), not sure.

This sounds like form configuration to me - if you say someone is a CHW, you get different questions than if they are a family member. Perhaps I am misunderstanding?

**Comment by diannakane** [comment]
I added default Add Place and Add Person forms to the spec -- feedback welcome. 

These forms are for our default config which is for SMS. That means that we won't be creating households and family members from the app, giving us more flexibility to create default forms that prioritize facilities and staff.

**Comment by estellecomment** [comment]
Relevant part in the spec : https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit?ts=57f7fabd#bookmark=id.kaz9vme2zuol

Filed https://github.com/medic/medic-webapp/issues/2828

**Comment by estellecomment** [comment]
@sglangevin 
> > select boxes with dropdowns which offer selections by person type. We can do some things but not everything. Selecting by user type (e.g. CHW vs. intern), not sure.

> This sounds like form configuration to me - if you say someone is a CHW, you get different questions than if they are a family member. Perhaps I am misunderstanding?

Yeah, that's in the list of things we can do with just form changes.

**Comment by sglangevin** [comment]
Ok - I saw that in the list of things that require other work, so I wanted to make sure I understood what you meant.

**Comment by estellecomment** [comment]
Oh sorry read too fast.
I don't know if we can offer a dropdown that filters only `person`s of `role == 'CHW'`. That's what I meant.

**Comment by sglangevin** [comment]
Ah, ok, cool. You are right - we can't currently do that. It would be a great feature to add in the future though. What we can do is have a dropdown in the form where the user selects the contact type and then based on their answer, ask different questions.

**Comment by diannakane** [comment]
That feature would also be helpful in filtering contacts and sending
messaging to groups. "Only people with role = CHW." I think this is where
roles and tags start to overlap, such as "Only people with schedule = HIV
treatment" or "Only people with form = danger sign." We should take that
into consideration when we develop for people roles.

**Comment by estellecomment** [comment]
Looks like we have a resolution, so closing. Reopen if you have more about the default "Add People/Places" forms.
