### ISSUE TITLE
Update mockups : "Belongs to" should show all levels of hierarchy + show links appropriately

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2729]
In this one, it only shows the place just above (missing : Area, Branch)
https://projects.invisionapp.com/share/XA7CTCBGU#/screens/163504603

**Comment by estellecomment** [comment]
That one too : https://projects.invisionapp.com/share/XA7CTCBGU#/screens/163504245

**Comment by Lesterng** [comment]
@diannakane @estellecomment This is true. The "Belongs to" in the profile card is a breadcrumb that show the hierarchal levels. We should discuss if they are actual links. Also depending on what level the user is logged in at will depend on if they have access to a branch or district view. For this reason we might opt for showing the hierarchal order and **not** making them clickable links.

**Comment by estellecomment** [comment]
So we agree that "Belongs to" will show all the hierarchy. That's the subject of this issue. 

Also agree we can't links to places that the current user cannot see (the doc isn't there on the device anyway, so the the link would be broken...). 

Mocks whose text has missing links in the Belong to field : 
https://projects.invisionapp.com/share/QD7ML6T7C#/screens/166037428
https://projects.invisionapp.com/share/QD7ML6T7C#/screens/166359152
https://projects.invisionapp.com/share/XA7CTCBGU#/screens/163504620

**Comment by diannakane** [comment]
@Lesterng @estellecomment 

Here's an updated mock showing all levels of hierarchy. Can the height of these fields expand if it runs to the second line, as shown, or must they all be hard-coded to be slightly larger to accommodate this?

https://invis.io/JA89C042Q#/179840795_Person_View
https://invis.io/JA89C042Q#/179813485_Household_View

I didn't want to spend too much time on showing the links, since this will change depending on user permission.

I don't have access to the CHW profile card in Sketch since it is not included in "mobile app 2.0" (you were in mContacts restricted when you saw it), but all profile cards follow the same rule.
