### ISSUE TITLE
Tecno screens are kinda small for side-by-side display

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2737]
For example, when displaying the [persons list in a place](https://projects.invisionapp.com/share/QD7ML6T7C#/screens/166340435), you display the name side-by-side with the phone number. Here's the relevant piece of mock:
![screen shot 2016-09-12 at 15 44 23](https://cloud.githubusercontent.com/assets/911434/18438016/d1d50d9a-78ff-11e6-9b43-6d4b7d01a06d.png)

On Tecno screen (320px wide!), if the name is a bit long, it almost touches the phone number, which is not very legible (ignore the wrong font sizes and weights):
![screen shot 2016-09-12 at 15 42 39](https://cloud.githubusercontent.com/assets/911434/18437980/abe22744-78ff-11e6-91ad-29ab1084e5e5.png)

It would probably work best displaying them one per line.
More generally, I suggest a new rule : only display one information item per line on mobile (the CSS library we use, bootstrap, actually defaults to this).
@diannakane what do you think?

**Comment by estellecomment** [comment]
Hmm actually, some things are probably narrow enough to fit, like age + gender : 
![screen shot 2016-09-12 at 16 02 17](https://cloud.githubusercontent.com/assets/911434/18438609/6aead530-7902-11e6-9d89-e14acbb15dba.png)

So the general rule may be overreaching.

The issue remains for the name + phone example above.

**Comment by diannakane** [comment]
Thanks for flagging this, @estellecomment !

Additionally, nearly all of our users have requested that we increase the font size, which would only exacerbate this issue.

Assigning to @Lesterng to see what he thinks

**Comment by Lesterng** [comment]
@estellecomment @diannakane 
It might be best to remove the phone number in mobile. Right now you cannot select the phone number to call the contact. You will see the phone number in the individuals profile card RHS or when you select the list item.

**Comment by diannakane** [comment]
@lesterng phone number is often used to verify identity... maybe less
relevant in the mobile app with all of the other contextual data there, but
in the event that two patients have similar names and birthdays, seeing the
phone number may be an important unique identifier

cc @slangevin

**Comment by sglangevin** [comment]
I can see this applying to the web app for SMS projects, where you might have a long list of people within the CHW area since we won't have families in that hierarchy. However, for the Android app, people are split up by family, so I'm not sure how important it would be to differentiate by phone number. It might be more useful to have the family designation (spouse, son, brother, etc.) as a way to know who is who in a family. I'm not saying we should add family designation into the mix now, just saying that phone number might not be relevant for that level of the hierarchy.

@diannakane did you have a specific example in mind where the phone number would help differentiate? I think many people will not even have phone numbers (kids, possibly other adults who don't have phones) so there may not be a phone number to display for people other than the primary caregiver and potentially his/her spouse.

**Comment by Lesterng** [comment]
@diannakane Good to know. The phone number would still be in the RHS in web view. Only removed in the LHS list item mobile view.

**Comment by diannakane** [comment]
@lesterng I missed that we were talking about LHS vs. RHS. I take it that
showing it in the LHS would cause the same querying load trouble as
displaying number of family members there, so fine to leave it out.

@slangevin I see your point about it likely only applying to a relatively
small number of people (head of household). Should we make this field
available in the primary contact creation form only, and leave it out of
the standard add person form? If you want to reassign the primary contact
at a later date (say to someone else already in the household), would you
have access to this field?

On the topic of unique IDs, I know anecdotally that ph# is the most common
form of identifier in rural communities -- names are often similar, get
mispelled or stated differently, and birthdates are often approximated. In
the case of CB-HIPP, phone number may end up being a more reliable "patient
name" than the patient's name itself, since there is stigma associated with
sex work and HIV.

**Comment by sglangevin** [comment]
The primary contact doesn't have a specific form - when you list the primary contact during family creation, a person is created (same as all other people, like family members) and that person's information is listed in the `contact` field for the place, in this case, the family. If you wanted to edit someone's phone number, you'd go to that person, click edit, and either add or change the phone number. I would not leave it out of the standard add person form as many people do have phone numbers, like spouses, parents, brothers/sisters of the primary caregiver who may live in the same household or compound and have their own phone numbers. I would keep it there and make it an optional field that a health worker can fill in if the information is available. Also, since we only have 1 person form for every type of person, for now we should leave the phone number in so that when we create CHWs or other health workers in our app, we can include a phone number for them.

In terms of using phone numbers to identify people, that should still work as long as we can search the contacts tab by phone number, right? I'm assuming you wouldn't scroll through a list if you were looking someone up by phone number, unless you had a very small number of people in your list.

**Comment by Lesterng** [comment]
Every person should have the option of having a phone number when creating a contact from a form. The phone number would be displayed on their profile card. Let's just remove it from the list items because it is a fit problem for people with long names. List items are both in the LHS and RHS.

**Comment by estellecomment** [comment]
> I take it that showing it in the LHS would cause the same querying load trouble as
displaying number of family members there, so fine to leave it out

No, it doesn't. The issue with number of family members is that you have to fetch all the members in the family to be able to count them. The phone number is already part of the person doc, like the name, so you get it at the same time as the name, it doesn't cost anything.

**Comment by estellecomment** [comment]
Persons are never present in the LHS, on any device. (I this is wrong then I'm missing mocks, please point them out to me.)

@Lesterng Can we make mobile mocks 320px wide, like the tecno screens? That would allow for issues like these to pop up as soon as possible.

@diannakane Interesting point about the font size. I think it makes sense to include it in this redesign, while we're at it. 
Please confirm whether we are including it in this redesign, as this will probably mean changes of layout in mobile.

There's other examples in the mobile layout that I think won't work on 320px. Please check off the checkbox when the mocks are updated to solve each issue.
- [ ] Person in the person list in a place card, RHS (the first one mentioned):
![screen shot 2016-09-12 at 15 44 23](https://cloud.githubusercontent.com/assets/911434/18466540/653fdce4-799c-11e6-86bc-d8aa667cb3eb.png)

- [ ] task in the Task list on the RHS:

![screen shot 2016-09-13 at 10 19 05](https://cloud.githubusercontent.com/assets/911434/18466351/a82ac79a-799b-11e6-85be-c26dfee14c52.png)

- [ ] report in the History list on the RHS:

![screen shot 2016-09-13 at 10 19 10](https://cloud.githubusercontent.com/assets/911434/18466375/bc875be0-799b-11e6-9cda-f67b0a3d9130.png)

- [ ] Person card : 

![screen shot 2016-09-13 at 10 24 08](https://cloud.githubusercontent.com/assets/911434/18466586/93c7d184-799c-11e6-94f9-77a3afdc85e7.png)

Until then, I'm going to block off implementation of mobile layout.

**Comment by Lesterng** [comment]
@estellecomment I will take a look at 320 width screen size. Trying to keep the font size the same throughout the application's media queries. Do you have a query at 320px. What is the breakpoint?

**Comment by estellecomment** [comment]
I just googled what a media query is, so I'm not an expert here, but we switch 
 - from double-pane mode to single-pane mode at <=767px
 -  to "mobile" mode <= 400px.

Mobile mode drops labels off buttons and tabs, and probably some other things.
Code for media requests at 400px : https://github.com/medic/medic-webapp/search?utf8=%E2%9C%93&q=%22max-width%3A+400px%22

**Comment by Lesterng** [comment]
@estellecomment Perfect. Exactly what i need to know.

**Comment by diannakane** [comment]
> No, it doesn't. The issue with number of family members is that you have to fetch all the members in the family to be able to count them. The phone number is already part of the person doc, like the name, so you get it at the same time as the name, it doesn't cost anything.

Good to know! Sounds like we will still leave it off though, because as you mentioned it is relevant to people, not households.

> Persons are never present in the LHS, on any device. (I this is wrong then I'm missing mocks, please point them out to me.)

They are present on the LHS in search results only. We have no mocks for search results @Lesterng #2339

**Comment by sglangevin** [comment]
This looks to have been resolved, based on what I have seen in the current UI on alpha.dev. Can we close this issue and open a new one once there is a specific request?
