### ISSUE TITLE
Households have different styling than other places

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2743]
Implement the household-specific styling.

The Person list, which looks like this for a normal place on desktop:
![screen shot 2016-09-13 at 15 47 17](https://cloud.githubusercontent.com/assets/911434/18476195/620bdd48-79c9-11e6-8200-2009f2a55d75.png)
and on mobile:
![screen shot 2016-09-13 at 18 03 35](https://cloud.githubusercontent.com/assets/911434/18481438/804b7274-79dc-11e6-902e-628453265228.png)

looks like that for Households on desktop:
![screen shot 2016-09-13 at 15 47 45](https://cloud.githubusercontent.com/assets/911434/18476223/79c9cb66-79c9-11e6-8be0-292814658149.png)
and on mobile : 
![screen shot 2016-09-13 at 18 01 42](https://cloud.githubusercontent.com/assets/911434/18481362/3ad616a4-79dc-11e6-9a86-e9db527f3ca9.png)

In detail : 
 - [ ] card icon is different
 - [ ] card title : no title -> Family Members
 - [ ] title and phone number -> no title and phone number (for phone number : wait for confirmation of decision: https://github.com/medic/medic-webapp/issues/2732)
 - [ ] new field : age
 - [ ] persons sorted by name -> persons sorted by age (primary contact is still at the top)
 - [ ] "Primary Contact" displayed under name -> "Head of Household" displayed next to name.
 - [ ] new field : Number of tasks (wait for confirmation on whether this is both mobile and desktop : https://github.com/medic/medic-design/issues/2)

**Comment by estellecomment** [comment]
Still missing, covered elsewhere : 
 - non-fontawesome icons (#2730)
 - number of tasks for a person is always 0 (#2742)

@garethbowen please review! Let me know if I'm introducing messiness in the less file, I can refactor.
@diannakane check out screenshots! As discussed they differ slightly from mocks. Thoughts welcome.

Screenshots : 
Normal place (not a household), mobile : 
![screen shot 2016-09-20 at 15 12 41](https://cloud.githubusercontent.com/assets/911434/18671810/d45b3340-7f45-11e6-8c67-54ecad10b6d4.png)

Normal place (not a household), desktop : 
![screen shot 2016-09-20 at 15 12 56](https://cloud.githubusercontent.com/assets/911434/18671820/de269932-7f45-11e6-8c15-b3a2f570e7b6.png)

Household, mobile : 
![screen shot 2016-09-20 at 15 12 17](https://cloud.githubusercontent.com/assets/911434/18671838/ea8ee7ec-7f45-11e6-8621-c7c75b669ed8.png)

Household, desktop : 
![screen shot 2016-09-20 at 15 13 12](https://cloud.githubusercontent.com/assets/911434/18671852/f5cfd418-7f45-11e6-8e8d-5488af8a7a9b.png)

**Comment by garethbowen** [comment]
I didn't realise this was in a branch right away so comments are on individual commits - if I'd realised I would've PRed it and made it easier for myself  :(

**Comment by garethbowen** [comment]
Overall really good work. It flows really nicely for a range of resolutions - I wasn't able to break it!

Right - picky UI review time! These are taken in Firefox as an admin.

### Desktop

The hover border doesn't go all the way to the bottom of the cell any more. This only affects the cards with columns.

![border-no-fit](https://cloud.githubusercontent.com/assets/2064938/18688603/355b1a8c-7fd9-11e6-8b95-3cea688c8d5d.png)

Is it correct to have an empty People list in a health centre? I'm honestly not sure...

![empty-list](https://cloud.githubusercontent.com/assets/2064938/18688690/8ee56cec-7fd9-11e6-8bd3-2f424be67d15.png)

The icons for the lists don't line up nicely. Use class "fa-fw" on the icon element to make them all the same width.

![icon-unaligned](https://cloud.githubusercontent.com/assets/2064938/18688722/ad9435d8-7fd9-11e6-9bc8-39cf33cc4651.png)

This is more of a design question, but I don't think we need the gold star _and_ the "head of household" label - the label is redundant. I think it's pretty obvious what the gold star means. This is taking up valuable real estate by adding a row to the element, and adds complexity because it has to move around for mobile.

![redundant-label](https://cloud.githubusercontent.com/assets/2064938/18688794/02c27b0a-7fda-11e6-856c-c48034d7a2cc.png)

The tasks column should probably be "col-xs-1" and looks really pretty with `text-align: right`, eg:

Current:
![tasks-current](https://cloud.githubusercontent.com/assets/2064938/18689412/2270767a-7fdd-11e6-9325-8bdf5981ea91.png)

Proposed:
![tasks-right-aligned](https://cloud.githubusercontent.com/assets/2064938/18689417/268d4b20-7fdd-11e6-8ae3-851397f04b5b.png)


### Mobile

There's a space before the comma before "Primary Contact". This is because there's whitespace in the HTML between the two elements. You can either remove the whitespace, or look for the slightly complicated CSS solution to this. Alternatively if we decide (as above) that the label is unnecessary when you have a gold star then it can just be removed.

![space-comma](https://cloud.githubusercontent.com/assets/2064938/18689032/348a5b5c-7fdb-11e6-9e22-bd9546b88cbd.png)

Another design question - it looks weird to have the person icon with no label beside it.

![weird-title](https://cloud.githubusercontent.com/assets/2064938/18689096/8a08782a-7fdb-11e6-898c-d7e97405e809.png)

Probably not anything you did, but this list of Households is hard to scan because the primary contact is as prominent as the name of the household. I think we should make the "primary contact: xxx" line grey so the family name is easier to scan.

![flat-list](https://cloud.githubusercontent.com/assets/2064938/18689172/f0b2d020-7fdb-11e6-86d4-6bacfcf7eea0.png)

**Comment by estellecomment** [comment]
Thanks! Splitting it up.

Prettiness issues : will solve now
- [ ] 1) Hover borders
- [ ] 3) Icons vertically aligned
- [ ] 5) Right align tasks column
- [ ] 6) Whitespace before comma (unless we remove the "Primary Contact" text but we'll see)
- [ ] 8) Hard to scan household list: [on the mockup the first line is bold, the second isn't](https://projects.invisionapp.com/share/JA89C042Q#/screens/179813485), which solves that. Will add it, I'd forgotten it. 


Design choices issues : let's discuss first, @diannakane speak your mind!
- 2) Empty people list : I think all places should have at least a contact person, so I think yeah you want an empty section, to show something is wrong. (but could remove section too)
- 4) Redundant label: I brought it up too! I agree it's taking up too much space. Turns out the star is not understood well by itself by users, so you can't rely on it by itself without a label. I suggest more thought on that one, @diannakane please file a medic-design issue if it's useful?
- 7) Unlabelled title : for context, here's the relevant mock, it's the person page : https://projects.invisionapp.com/share/JA89C042Q#/screens/179840795. It looks a bit less weird in the mock because there's "Primary Contact" next to it, but for a non-primary-contact person it's empty. Agree that it looks kinda weird. I suggest adding "Profile", like on the household pages : https://projects.invisionapp.com/share/JA89C042Q#/screens/179813485 (and btw, I suspect it's a mockup error, for households, wouldn't "Household" make more sense than "Profile"?)

**Comment by estellecomment** [comment]
- [ ] more instances of 7) (Unlabelled title) : in my current implementation, it happens on the Place pages too. But the mocks have been updated since then to add labels, so I'll add them.

**Comment by estellecomment** [comment]
@garethbowen, second round please! Commits : https://github.com/medic/medic-webapp/compare/04e6966...2743-households-ui
The various ways I found to remove the whitespace before the comma all sounded absurd, so I picked one. If you know a better way, let me know!

**Comment by estellecomment** [comment]
Also, the font sizes are all out of whack, but I think it needs to be tackled across the whole page in one go, and we need the style guide to be final, so I just left it out of whack for now. (#2709)

**Comment by garethbowen** [comment]
Lovely. Good job.

**Comment by estellecomment** [comment]
For records, here's what the implementation looks like for 7) Unlabeled title : 
![screen shot 2016-09-22 at 15 09 45](https://cloud.githubusercontent.com/assets/911434/18749388/f4fa01ca-80d6-11e6-93a6-390d63f99722.png)
![screen shot 2016-09-22 at 15 09 53](https://cloud.githubusercontent.com/assets/911434/18749390/f4fdf60e-80d6-11e6-815f-7f58603f9030.png)
![screen shot 2016-09-22 at 15 10 04](https://cloud.githubusercontent.com/assets/911434/18749389/f4fcf0ce-80d6-11e6-9fa0-b1c4e60a7736.png)

**Comment by estellecomment** [comment]
Reopening so I don't forget the couple design points that need to be solved.

**Comment by diannakane** [comment]
> 2) Empty people list : I think all places should have at least a contact person, so I think yeah you want an empty section, to show something is wrong. (but could remove section too)

I think is required for a place to have a primary contact as part of the place creation process, but I suppose it's possible that that contact could be deleted; i'm not sure what happens in that event. For the purpose of this issue, I agree that we want to keep that section empty if there is no PC listed.

> 4) Redundant label: I brought it up too! I agree it's taking up too much space. Turns out the star is not understood well by itself by users, so you can't rely on it by itself without a label. I suggest more thought on that one, @diannakane please file a medic-design issue if it's useful?

7) Unlabelled title : 
What do you guys think of this: using the label "Profile" as you suggest and as we have already mocked for Place cards (see below), also for People, except where a person is the Primary Contact and then list that instead next to the star: 
![image](https://cloud.githubusercontent.com/assets/1675870/18805558/09dae2a4-81c6-11e6-9924-ae66192b5e42.png)
![image](https://cloud.githubusercontent.com/assets/1675870/18805544/bc400092-81c5-11e6-94bf-fa34855d3b06.png)
![image](https://cloud.githubusercontent.com/assets/1675870/18805551/e97b3f90-81c5-11e6-99a6-87b121662f7b.png)

I think we can lose the Primary Contact label in the list view, but can see it being helpful to reinforce the meaning of the icon in the Person view. 

![image](https://cloud.githubusercontent.com/assets/1675870/18805539/a039728e-81c5-11e6-9dd9-fa796c6d65d5.png)

I am using Primary Contact interchangeably with Head of Household. Since we're setting ourselves up for SMS projects which will include CHWs at the lowest hierarchy place, we have good reason to go generic on some of our labels and opt for Primary Contact, but they can always be changed in translations.

**Comment by estellecomment** [comment]
SGTM!
@diannakane just to make this clear : I think we should go for the best UI-designed solution, not the easiest to implement.
For the titles, if it's better with different titles for different types of pages, we should do it, we don't have to stick to uniform title for all.
For Head of Household vs. Primary Contact, if we think it's a better UI for CHWs to use "Head of Household" and for managers to see "Primary Contact", then we should do it.
(What I do think we should avoid is adding variations where they don't add value. Then it's just more work and more confusion for users.)

Based on what I understand so far, these are the changes to implement. 
- [ ] Primary contact : remove it when in a list (for all places including households)
- Titles in single-pane view : 
   - [ ] "Profile" for all people and places
   - [ ] except when it's a primary contact: "Primary Contact" or "Head of Household", with star between icon and title (see mockup above)

**Comment by diannakane** [comment]
Agree to all of the above!

On the topic of "head of household" label, I'm not sure it is meaningful. Culturally speaking, a woman wouldn't be considered the head of household so "primary contact" may in fact be more accurate, but some partners will request their own terminology to be used so we know we'll have to remain flexible on our labeling. We can stick with "head of household" for families for the default, since it helps clarify where you are in demos and such.

**Comment by estellecomment** [comment]
*Primary contact labels in lists* 
For normal places, desktop:
![screen shot 2016-09-27 at 10 44 37](https://cloud.githubusercontent.com/assets/911434/18866389/f9cf4b8e-849f-11e6-8938-aecba489213f.png)

For normal places, Mobile:
![screen shot 2016-09-27 at 10 44 50](https://cloud.githubusercontent.com/assets/911434/18866396/00451dd6-84a0-11e6-9ff5-cff820dfba35.png)

For households, Desktop:
![screen shot 2016-09-27 at 10 45 04](https://cloud.githubusercontent.com/assets/911434/18866408/0e2c7ba6-84a0-11e6-93f4-996bbbdc01ab.png)

For households, Mobile:
![screen shot 2016-09-27 at 10 45 15](https://cloud.githubusercontent.com/assets/911434/18866403/057a3836-84a0-11e6-98b7-d3eca47e3fee.png)

-------
*Page Titles*
Place or Person, not primary contact, desktop:
![image](https://cloud.githubusercontent.com/assets/911434/18867733/b99d91dc-84a5-11e6-83d4-61dd23965d5d.png)
Place or Person, not primary contact, desktop:
![image](https://cloud.githubusercontent.com/assets/911434/18867766/d3bc79ac-84a5-11e6-8c10-6346a8b7d987.png)

Person, primary contact/head of household, desktop:
![image](https://cloud.githubusercontent.com/assets/911434/18867875/3e526402-84a6-11e6-8e70-6af1e2a4ff8a.png)
Person, primary contact/head of household, mobile:
![image](https://cloud.githubusercontent.com/assets/911434/18868009/e0ad241c-84a6-11e6-900b-1feed006f552.png)

**Comment by diannakane** [comment]
I don't think we need to treat web app differently by listing "head of
household" or "primary contact" in the family member list view, but it also
doesn't hurt to do so. Open to others' thoughts.

**Comment by estellecomment** [comment]
I left it in because we don't have space issues on double-pane view, and we know that the star by itself is not always understood. Can change it.

**Comment by garethbowen** [comment]
I agree with @diannakane it seems unnecessary but doesn't really hurt. On desktop the user can hover over the star for clarification anyway.

I've made one small comment on one commit but otherwise good to go.

**Comment by estellecomment** [comment]
And it's a CLOOOSSSSSE
