### ISSUE TITLE
Reports "Send Message" button is always disabled

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2745]
The Send Message action bar button is permanently disabled on the Reports tab. This is due to a recent refactoring which meant the Reports tab is setting the model in a way that's inconsistent with the template.

![disabed](https://cloud.githubusercontent.com/assets/2064938/18544231/c72109d2-7b87-11e6-8cb9-7e7f3adc8e82.png)

Also check all other uses of the action bar model to ensure no other regressions have occurred.

**Comment by estellecomment** [comment]
I don't think this is related to the actionbar refactor. It was trying to get the `phone` field from a `data_record`, which doesn't exist. Not sure since when this was happening. 

I'm assuming this button is supposed to send a message to the CHW who sent the report. Is that right?

Filed https://github.com/medic/medic-webapp/issues/2748: the contact data isn't getting to the send-message modal.

**Comment by garethbowen** [comment]
Ahh, I see, we've duplicated the Send Message button in the action bar and I was looking at the wrong one. So confusing... Thanks!
