### ISSUE TITLE
Medic OS: ensure useful stuff is on $PATH by default

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2750]
It would be great if things like `curl` were on the path by default.

You can currently incant this: `source /boot/include/utility && prepend_paths /srv/software/medic-core/current/default`

Which solves problems. Should be auto-magic though.

**Comment by alxndrsn** [comment]
One solution would be to include that line (`source /boot/include/utility && prepend_paths /srv/software/medic-core/current/default`) in `.bash_profile` (or similar) for the `vm` user.

**Comment by browndav** [comment]
There's an equivalent for it in `~/.profile` already, even in older builds (`ash` doesn't use `.bash_profile`) but IIRC a global `/etc/ashrc` misconfiguration IIRC is causing the per-user `.profile` to not be picked up. I'll take a look today and at least verify it's fixed in new builds.

**Comment by browndav** [comment]
Here's a minimal fix for all existing deployed instances:

```patch
--- /etc/profile
+++ /etc/profile
@@ -1,7 +1,6 @@
 # /etc/profile:
 #   System-wide .profile file for the Busybox `ash` shell
 
-export ENV='/etc/ashrc'
 export PATH='/usr/sbin:/usr/bin:/sbin:/bin:/boot'
 
 # set_prompt:
@@ -56,4 +55,6 @@
    source "$script"
  fi
 done
+
+source /etc/ashrc
```

A better fix is in `master` of Medic OS already, but from what I can surmise, the use of `$ENV` to pick up `/etc/ashrc` was somehow leading to either (a) `~/.profile` just not being read at all, or (b) `$PATH` being overwritten at some point. Here's some manual page fun:

<img width="906" alt="man-ash" src="https://cloud.githubusercontent.com/assets/763977/21774085/2ad55708-d646-11e6-8bd5-acb862bec69c.png">

This should be easy enough to deploy in one shot after a few tests:

  - [ ] Develop remote deployment command
  - [ ] Test deployment on low-risk instances
  - [ ] Deploy hotfix en masse to existing instances
  - [ ] Specifically confirm that this remains fixed in a build of `master`

**Comment by browndav** [comment]
The deployment may be worth a separate issue; will defer decision to today's mid-iteration call.

**Comment by browndav** [comment]
Here's a single-command / single-file self-deploying version of the patch:

```shell
#!/bin/ash

cd / && sudo patch "$@" -p0 <<EOF
--- /etc/profile
+++ /etc/profile
@@ -1,7 +1,6 @@
 # /etc/profile:
 #   System-wide .profile file for the Busybox \`ash\` shell
 
-export ENV='/etc/ashrc'
 export PATH='/usr/sbin:/usr/bin:/sbin:/bin:/boot'
 
 # set_prompt:
@@ -56,4 +55,6 @@
    source "\$script"
  fi
 done
+
+source /etc/ashrc
EOF
```

**Comment by browndav** [comment]
Confirmed that this works remotely using `ssh lg.dev.medicmobile.org < path-hotfix`.

**Comment by sglangevin** [comment]
@browndav what is the status of this issue?

**Comment by garethbowen** [comment]
Randomly picking @SCdF for CR

**Comment by browndav** [comment]
Sorry for the non-response. I've applied the fix to `lg.dev` for easy post-application testing. In addition, if you want, you should be able to toss https://github.com/medic/medic-webapp/issues/2750#issuecomment-271359419 in a file named `path-hotfix.sh` and run it from any working directory with `sudo sh path-hotfix.sh`.

**Comment by SCdF** [comment]
@browndav is there anything to code review here? Sounds like it's fixed in master of medic os, and if we want to there is a script that can be applied to existing instances?

**Comment by browndav** [comment]
Yeah, this is fixed in Medic OS `master`, and I've ATed it on `lg.dev` and a couple other non-critical issues to verify it works. The fix is present in the latest pre-production image, which will become 1.0 when we do the end-of-February production upgrades.
