### ISSUE TITLE
Status icon for `delivered` is orange instead of green

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2752]
The status icon for delivered is showing as orange instead of green.
![image](https://cloud.githubusercontent.com/assets/789512/18596978/bd79f668-7c19-11e6-87f4-b7e14fe7e692.png)

Changing the CSS class to `sent` works (eg `class="state delivered"` switched to `class="state sent"`) so we should either be using the `sent` class or style the `delivered` class.

**Comment by garethbowen** [comment]
@abbyad I think it was styled yellow to indicate that it had been picked up by the transport but not yet sent to the carrier. Is this distinction not worth showing? Will the user consider it sent as soon as the transport has picked it up?

**Comment by abbyad** [comment]
From [the latest docs](https://github.com/medic/medic-docs/blob/f4f5011eb966d8a4f260e57204ee442359c24048/md/message-states.md#message-states), my understanding is that delivered means that the message has been sent and received, so I would expect `delivered` to be _at least_ as green as `sent`.

**Comment by garethbowen** [comment]
@abbyad Colours...

| State | Current | Proposed |
|------|------|
| scheduled | Blue | Yellow |
| pending | Salmon | Blue |
| forwarded-to-gateway | undefined (grey) | Blue |
| received-by-gateway | undefined (grey) | Blue |
| sent | Green | Green |
| delivered | Yellow | Green |
| failed | Blue | Red |
| denied | undefined (grey) | Grey |
| cleared | Yellow | Grey |
| muted | Grey  | Grey |

The logic for the proposed scheme is:

* Yellow - scheduled
* Blue - in the process of being sent
* Green - delivered/sent. I've included the `sent` state here because sometimes we don't get notified about `delivered` so the message will be forever stuck in `sent`
* Red - fatal failure
* Grey - won't be sent but not due to error

Does that make sense?

**Comment by diannakane** [comment]
@garethbowen I only have two suggestions to make: scheduled as blue and pending as yellow. The rest look really good!

@Lesterng anything you would change?

**Comment by garethbowen** [comment]
@diannakane "pending", "forwarded-to-gateway", and "received-by-gateway" are pretty much the same state - we're processing the message but it's not sent yet. So I think these three states should be the same (or similar) colour. How about I change all of these are yellow?

The colour flow then will be: blue, yellow, green/red
My proposal was: yellow, blue, green/red

**Comment by Lesterng** [comment]
@diannakane I would need to look at this in context to make any recommendations. If you need to implement go ahead otherwise create a design issue and we can schedule it.

**Comment by garethbowen** [comment]
I've gone with this for now - we can change it later if necessary:

| State | Updated |
|------|------|
| scheduled | Blue |
| pending | Yellow |
| forwarded-to-gateway | Yellow |
| received-by-gateway | Yellow |
| sent | Green |
| delivered | Green |
| failed | Red |
| denied | Grey |
| cleared | Grey |
| muted | Grey |

@estellecomment review please (commit, no PR sorry).

**Comment by estellecomment** [comment]
one's mixed up! https://github.com/medic/medic-webapp/commit/33413f6aa7e4d33af11f5579ef0ee67559e6906d#commitcomment-20703217
Apart from that LGTM.

**Comment by diannakane** [comment]
Agreed, @garethbowen
