### ISSUE TITLE
Status time for messages does not update automatically

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2753]
The time in the status message does not update automatically, especially noticeable when it is a time in the future due to clock sync issues. This status messages stayed like this until I switched to another record and back, at which point it said `5 minutes ago`.
![image](https://cloud.githubusercontent.com/assets/789512/18597087/49d75b82-7c1a-11e6-93f1-48128f88a963.png)

**Comment by garethbowen** [comment]
We have special handling for this in the live list code, but nowhere else in the app do the relative dates get updated automatically. We should consider how to do this reliably across the app, perhaps by storing the raw date on the element and periodically (every 5 minutes?) updating all.

This didn't happen in 0.4 either so I'll change the labels.

**Comment by nice-snek** [comment]
hi frand @mandric, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by mandric** [comment]
Assigning to Marc because I don't know what to do with this.

**Comment by abbyad** [comment]
I don't think we should close this since it seems like a UX bug to me -- a user would expect relative dates to be accurate.

**Comment by cbrwizard** [comment]
Hey, here are some of my thoughts on solving this:
1. https://github.com/urish/angular-moment#am-time-ago-directive could've been used here. It auto-updates the time automagically and also accepts the [date format](https://github.com/urish/angular-moment#amdateformat-filter). A possible way to use it here would be to convert the `relativeDate` filter to a directive with a template and use that `am-time-ago` directive inside. In my opinion, `relativeDate` filter should be refactored into the directive anyway if we want it to update DOM, because a filter should be simple.
2. Mimic the above solution in the filter so that it calls re-render on itself every n ms with `setInterval`. The problem here is that a `scope` will need to be passed into this filter so that it can listen to a `scope`'s `destroy` event, so that `setInterval` gets properly removed when needed, like [here](https://github.com/urish/angular-moment/blob/4a299f82b28bf8748e99aa3d54fb65af9391beec/angular-moment.js#L330). Another downside here is that this filter becomes too smart and complicated.
3. Hack: convert this filter into a stateful one. This way every time a page's content changes, the relative time will get updated too.

Third option is as simple as:
before:
```js
  module.filter('relativeDate', function(FormatDate) {
    'ngInject';
    return function (date) {
      return getRelativeDate(date, { FormatDate: FormatDate });
    };
  });
```
after:
```js
  module.filter('relativeDate', function(FormatDate) {
    'ngInject';
    function relativeDateFilter(date) {
      return getRelativeDate(date, { FormatDate: FormatDate });
    };
    relativeDateFilter.$stateful = true;

    return relativeDateFilter;
  });
```
After the changes, for instance, on a messages page, all relative times get updated when a different message is selected, like in [this recorded video](https://drive.google.com/file/d/0B4K14pCvJ8ErZ0JhdkRaYWxBT1k/view).

Personally, I'd go with the first option if the change isn't urgent or with the 3rd if the result is satisfactory. What do you think? If you don't mind, I'd like to work on this.

**Comment by garethbowen** [comment]
@cbrwizard The first option looks great, so long as we can get it to work with our custom styling (eg: full date shown in a tooltip on hover/touch). Let me know if I can help at all!

**Comment by cbrwizard** [comment]
Thanks, @garethbowen! I think the only thing I could've used here is help with setting up Tasks to test the rendering locally. Tasks also use the `relativeDate` filter, so it makes sense refactoring their calls to it too.
Some steps required to create the Tasks from the clean db would be great. Or maybe you can give me a copy of a working full dev db?

**Comment by garethbowen** [comment]
@cbrwizard We have some documentation to help with [configuring Tasks](https://github.com/medic/medic-docs/blob/master/configuration/tasks.md). We're working on making a generic configuration that we can share publicly which will really help with this initial setup.

The absolute simplest possible Tasks configuration is something like...

```js
define Target {
  _id: null,
  deleted: null,
  type: null,
  pass: null,
  date: null
}

define Contact {
  contact: null,
  reports: null
}

define Task {
  _id: null,
  deleted: null,
  doc: null,
  contact: null,
  icon: null,
  date: null,
  title: null,
  fields: null,
  resolved: null,
  priority: null,
  priorityLabel: null,
  reports: null,
  actions: null
}

rule GenerateEvents {
  when {
    c: Contact
  }
  then {
    var task = new Task({
        _id: c._id,
        doc: c.contact,
        contact: c.contact,
        date: new Date(),
        title: 'do something',
        resolved: false,
        actions: [{
          type: 'report',
          form: 'pregnancy_visit',
          label: 'Follow up',
          content: {
            source: 'task',
            contact: c.contact
         }
      }]
    });
    emit('task', task);
  }
}
```

This will emit one Task for each Contact in your database. Hope this helps!

**Comment by cbrwizard** [comment]
Hey @garethbowen please help me out with this. Where do I run this code? I've figured that it's nools DSL. An idea which comes to mind is creating a js file with this contents, requiring `nools`, `Task`, then telling `nools` to compile the rules, then executing a file with Node... Looks quite complicated and I'm not sure that it will run. Please note that I don't have experience with CouchDB, so this might be the case as well.
The `tasks.md` document describes using a `task-rules.js` file somehow, but I cannot find it anywhere.

**Comment by garethbowen** [comment]
@cbrwizard Sorry about that! That's the configuration that needs to be inserted into a specific point in our JSON settings. The easiest way to do this is to use Dashboard.

1. Go to `<host>/dashboard/_design/dashboard/_rewrite/settings#/apps`
2. Beside "medic" click "Settings"
3. Click "app settings"
4. Scroll way down to "Task Generation" and in the "rules" textarea enter the above config.
5. Scroll to the bottom of the page and click "save"
6. Once that settings change reaches your browser you should be prompted to refresh to get the new config.

NB: I haven't tested the configuration so it could easily have syntax errors but these will become obvious when you load the rules in the app.

NB2: We're moving off Dashboard so will have a brand new way to configure the app in v3.0.

**Comment by cbrwizard** [comment]
Thanks, @garethbowen, that got me closer, hehe!

The issue now is with the Dashboard. I've followed this tutorial https://github.com/medic/medic-webapp#push-the-dashboard-optional but I wasn't able to change branch to `develop` as stated there. It seems to me that the tutorial is old as there is no `develop` branch anymore https://github.com/garden20/dashboard/branches/all.

Anyway, I've skipped it and eventually was able to visit http://localhost:5984/dashboard/_design/dashboard/_rewrite/settings#/apps. I see no "medic" with the "Settings" there and could not find "app settings", so I figured I should install the app as stated in the tutorial. I've entered `https://staging.dev.medicmobile.org/markets-alpha/details/medic` in the input, clicked next but it didn't install, with an error `Install failed: a problem deleting the non prefixed doc`. On stage Cleaning Up it got stuck with `POST http://localhost:5984/dashboard/_design/dashboard/_rewrite/_couch/medic_3/_purge 501 (Not Implemented)` `{"error":"not_implemented","reason":"this feature is not yet implemented"}`. I wonder if this has anything to do with the `develop` branch missing or maybe I need to toggle a feature flag somewhere or something else I'm missing here.

So... what do I do there? [: I've figured you didn't have a new developer trying to contribute to the development for quite a while hehe. Once we set up some Tasks I will open a PR with updated docs so that others will not slow down like I did.

**Comment by garethbowen** [comment]
@cbrwizard Ok, I'm not sure what's going on there but as you say we haven't had someone go through these steps in a while.

Instead you can modify the app_settings directly on the medic ddoc.

1. Go to futon (or fauxton if you're using couchdb 2)
2. Find the "medic" ddoc
3. Edit the ddoc and set `app_settings.tasks.rules` to the above block of code
4. Save the ddoc and wait for it to replicate to your browser

**Comment by cbrwizard** [comment]
@garethbowen I did as you told, but on the Tasks page when logged in not as admin the tasks could not be fetched for some reason, so I've decided to skip this. In my case, the tests were enough, imo.
I've opened a pull request, feel free to check it out when you have time! https://github.com/medic/medic-webapp/pull/3998

**Comment by garethbowen** [comment]
@cbrwizard Thanks! I've run out of time this week but will check it out next week.

**Comment by cbrwizard** [comment]
@garethbowen resolved merge conflict, please check it out =]

**Comment by garethbowen** [comment]
Ready for AT.

**Comment by ngaruko** [comment]
LGTM
