### ISSUE TITLE
We get multiple instances of the same modal dialog

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2764]
If the same modal dialog is invoked multiple times they layer up in the UI which looks ugly and is wasteful. The most obvious example of this is the "update available" modal.

Add a check to either dismiss the first instance or not create a second instance of the same dialog.

**Comment by estellecomment** [comment]
Lots of update modals, stacked into the modal of doom:
![screen shot 2016-09-19 at 23 09 43](https://cloud.githubusercontent.com/assets/911434/18660697/33f53e06-7f12-11e6-9b53-edbefa0a7fc0.png)

**Comment by garethbowen** [comment]
[PR](https://github.com/medic/medic-webapp/pull/2829)

Not all modals should be singletons - it would be really annoying if a modal you were working on closed while you were typing into it. I've set it on some that require no user input.

That being said, most modals won't have this issue because users can't interact with the page while the modal is visible. This one is affected because it's triggered by a background event not a user action.

**Comment by SCdF** [comment]
LGTM!

_(Interestingly, re the example screenshot above, there is a separate issue--that I've yet to file because I've yet to really have anything intelligent to pin down about it--where grunt seems to be firing multiple times for just one change, and only the last firing generating a useful build.)_
