### ISSUE TITLE
Alerts to `reporting_unit` not working

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2779]
In v2.9 Alerts meant to be sent to the `reporting_unit` don't translate that to the reporting unit's phone number. On the gateway I can see that it tried to literally send to `reporting_unit` as the phone number. I haven't tested, but suspect that other places such as `parent` and `grandparent` would be subject to the same problem.

## app_settings
![image](https://cloud.githubusercontent.com/assets/789512/18766212/1503a95c-80e7-11e6-9f50-e45b70f40ed5.png)

## failed send
![image](https://cloud.githubusercontent.com/assets/789512/18766230/34801e8c-80e7-11e6-968c-22d17262b23f.png)

**Comment by garethbowen** [comment]
This is working for me.

![works-for-me](https://cloud.githubusercontent.com/assets/2064938/18830931/8844df20-843f-11e6-923b-1b1379ef39cb.png)

@abbyad Can you upload your configuration so I can debug?

**Comment by SCdF** [comment]
@marc Is this related to #2784 : no correctly configured clinics?

**Comment by abbyad** [comment]
Very likey @SCdF.

@garethbowen, sorry for the delay...  replies to visit forms work for me too, but not for alerts or scheduled reminders (#2784). The config is at diy.dev if you want to check it out.

**Comment by garethbowen** [comment]
I've had a look at that specific example on diy.dev (thanks for that) and the problem is that the way the code is written "reporting_unit" is synonymous with "clinic". Either of those strings will iterate up the contact hierarchy and return the first parent found with type "clinic". In this case, because your contact is at a "health_center" not a "clinic" no "reporting_unit" is found and it defaults to the given string.

IMO the bug is that "reporting_unit" shouldn't be treated the same as "clinic". Instead "reporting_unit" should resolve to the contact's phone.

NB: this is in core code and will affect all message sender resolution.

@abbyad Does this make sense to you?

**Comment by garethbowen** [comment]
@mandric Seeing as Marc is away on holiday, does my suggestion above make sense to you?

**Comment by mandric** [comment]
Yeah makes perfect sense to me @garethbowen.

**Comment by mandric** [comment]
I think we can improve this a little, comments on the commit.

**Comment by garethbowen** [comment]
@mandric I've responded to you comments - if you disagree maybe grab me on Slack/Hangouts to try and work out what's best...
