### ISSUE TITLE
Discuss : make a small change to the tasks config for People tab redesign

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2792]
Currently, the tasks titles include the patient name (things like `"{{contact.name}} referral follow up"`), because so far we've been displaying the task name on a single line so you need to stuff all the info in the name.

It's not working very well on small screens:
![screen shot 2016-09-29 at 14 54 50](https://cloud.githubusercontent.com/assets/911434/18962209/34692086-8670-11e6-9b4e-4a2baa387d7e.png)

The new People tab will have patient name split out to a separate line, which will help : 
![screen shot 2016-09-29 at 17 19 24 copy](https://cloud.githubusercontent.com/assets/911434/18962250/58d4c01a-8670-11e6-9ade-4382b091e52e.png)

But! With the current configs, with patient name included in the title, you get this, which defeats the purpose : 
![screen shot 2016-09-29 at 18 15 07](https://cloud.githubusercontent.com/assets/911434/18962327/b5afbb00-8670-11e6-9efc-20baa7b36431.png)
The name is duplicated, and the wrap is bad (screenshot is 320px)

So! I vote we edit the existing configs, to change task titles from e.g. `"{{contact.name}} referral follow up"` to  `"Referral follow up"`. We can roll it out along with the People tab update.
But since I'm not the one really in charge of updates, please give your opinions @garethbowen @sglangevin @abbyad (who is OOO right now) and @diannakane.

**Comment by diannakane** [comment]
I have already expressed this to @estellecomment but pasting here for others: I'm curious if this change will affect people-centric SMS workflows using task rules for schedules. Will the CHW still receive a SMS indicating the person whom the visit is for, or only the name of the visit? I am otherwise in support of this change, just curious about any unintended consequences of changing the config.

**Comment by sglangevin** [comment]
@diannakane it depends on how the config is done for SMS workflows. It seems like we'll want to add something to the config for the SMS message, which may or may not affect how it looks visually. Perhaps the config for SMS has an additional field where we list the structured message that is different from the title?

Generally, I agree with @estellecomment that it's repetitive to have the name in two places and using two lines would enable the user to see the full name of the task for longer task titles. We should keep a note about this change on the checklist for running the update to v2.9 (or whichever version includes the people tab updates) so that we make sure tech leads update the task titles along with the update. Unless there is a way to automate this, which would be even better.

**Comment by garethbowen** [comment]
:+1: for modifying the config to remove this duplication. We need to make sure the patient name is displayed everywhere the task is (eg: in the Tasks tab).

When we get around to sending SMS for tasks I think we'll have to include a separate configuration for what the SMS should say because sending "Chaire postnatal followup" in an SMS doesn't provide enough context. So you might have "Claire" followed by "Postnatal followup" in the task list, and then send an SMS which says "Remember to visit Claire for her scheduled postnatal followup this week".

So @diannakane I don't think this will affect the people-centric SMS workflow as we'll have separate configurations for the SMS and the UI.

**Comment by estellecomment** [comment]
Cool! 
I filed a temporary 2.9 release issue with that todo and assigned it to Gareth.
Looks like everybody likes it, decision made, closing this issue!
