### ISSUE TITLE
Tasks list is not getting updated when task is resolved in another window / by another user

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2800]
Introduced in the last couple days : we need to keep track of resolved tasks, to know when the task goes from unresolved to resolved. 

(note that this would only happen if you were resolving the task in another page or browser, which is not really likely to happen, and if it did you could refresh, but since CHWs don't necessarily know how to refresh, it's best to have it.)

**Comment by SCdF** [comment]
Two questions:
 - I think the answer is "no", but is this the kind of thing we can test for in an e2e test?
 - Do we even support multiple tabs open to the same local DB? Sounds like a bit of a nightmare, i.e. making a change in one tab would have to fire a changes feed on the other tab… somehow, and that change would have to be marked as coming from… somewhere.

**Comment by estellecomment** [comment]
You could have a CHW's manager (or nurse at facility) fill in a form about a patient, that would clear the associated task for the CHW, I think. In that case it would be two different users.

**Comment by estellecomment** [comment]
And yeah we can probably e2e test : submit the appropriate report, check the task disappears from list.

**Comment by SCdF** [comment]
@sglangevin can you talk about the complexities over this so it's documented somewhere, and then we can drop it out of the sprint (since it sounds like a much larger issue that we're maybe even OK with existing).

**Comment by sglangevin** [comment]
So I'm not sure that we want to allow any user to complete another user's task any time. This seems like something that we'd want to configure for cases where we want to enable a particular workflow. Otherwise, we might have cases where a manager sees the tasks their CHPs need to complete and can complete them even if the manager isn't supposed to complete them. They'd then be marked complete for the CHP. I can also see cases where one CHP might want to complete the task of another CHP (for cases where two CHPs take care of the same group of families). I think we need to flesh out the user stories for this and decide how best to handle it and what should be configurable.

**Comment by garethbowen** [comment]
Closing as ancient.
