### ISSUE TITLE
Display History list filters at bottom of list

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2810]
Currently they're displayed at the top. We want them displayed at the bottom as well (handy for long lists).
Design spec : https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.66nj6r9pxmxe

**Comment by SCdF** [comment]
This seems inconsistently represented on the various mockups. It's in some but not others.

Additionally, I'd be worried about how scrolling would work in such as instance. If you change how much content is displayed below you, your current viewport doesn't change, and it looks clean and understandable. If you change how much content is displayed **above** you, your viewport will shift dramatically (because it's statically the distance from the top of the page, and you removed content above you), and be disorienting and confusing.

**Comment by sglangevin** [comment]
@SCdF - that makes sense to me. @diannakane, could we leave out the filters at the bottom and just add the up arrow that was in the mock-ups? That way it's easy to get back to the filters if you have a long list.

**Comment by diannakane** [comment]
I agree with that.

**Comment by estellecomment** [comment]
Closing and updating the spec, we're not doing that.

**Comment by diannakane** [comment]
@estellecomment Should we update the spec given that we will likely do this
in a future iteration?

**Comment by estellecomment** [comment]
Yes we most definitely should! I crossed it out : https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.66nj6r9pxmxe
