### ISSUE TITLE
Make migrations compatible with CouchDB 2.0

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2855]
We have two or three migrations that use temporary views which have been removed in couchdb v2. Use either mango or create then delete persistent views to achieve the same result.

**Comment by SCdF** [comment]
Some migrations also access the `_config` endpoint that is now more of a pain to access.

**Comment by SCdF** [comment]
Things that need to be looked at:
 - [ ] `disable-erlang-support.js` edits `_config`
 - [ ] `enable-erland-support.js` edits `_config` ... since we now have erlang disabled I'm wondering what would happen if I just deleted both of those migration scripts? Would the world end?
 - [ ] `extract-user-settings-roles.js` uses `_config` to add the `_admin` role to admins.
 - [ ] `convert-bad-dob-format.js` uses a temp view
 - [ ] `remove-empty-parents.js` uses a temp view

**Comment by garethbowen** [comment]
We can't delete both erlang migrations unless we're convinced that nobody has run `enable` without also running `disable. You could probably just delete the `enable` one though...

**Comment by SCdF** [comment]
@garethbowen for your consumption https://github.com/medic/medic-api/pull/107

**Comment by SCdF** [comment]
@garethbowen commented on your comment. We can talk when we're both around.

**Comment by garethbowen** [comment]
Will be ATed with CouchDB2.
