### ISSUE TITLE
Queries from ANC Analytics do not work

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2975]
As reported in https://github.com/medic/medic-projects/issues/1135 the links to reports from a CHW or about a Patient are not showing any results.

Although we plan to replace the ANC analytics (to be generated by nools), in the meantime is there a quick way to fix these queries so that existing projects can continue to use these dashboards? If not we may want to remove the links in the ANC analytics until they are usable again, or the whole thing is replaced by nools based analytics

**Comment by garethbowen** [comment]
PR please @alxndrsn : https://github.com/medic/medic-webapp/pull/2980

This should be backported to 2.9.x - I can do that if you like.

There were actually three bugs here:

1. The reports freetext view had accidentally been changed to use a string as a key instead of an array of string. While this is fine, the corresponding code calling the view hadn't been changed to match.
2. The view wasn't lowercasing UUIDs for keys but the front end code was, which meant it was impossible to search by UUID.
3. The ANC analytics templates were out of date by passing the entire contact in the `data-send-to` rather than just the _id.

All 3 links (patient, chw, and send message) now work as expected.

![anc](https://cloud.githubusercontent.com/assets/2064938/20870787/cad5885a-baf2-11e6-8b9f-7ff7c73adb9d.png)

**Comment by alxndrsn** [comment]
Comments in-line.

**Comment by abbyad** [comment]
Works well in `2.9.0-beta.9`, moving to Ready
