### ISSUE TITLE
Scheduled messages not showing accurate date

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3012]
When a message goes back to the scheduled state (eg in #3011) the date shown in the Reports tab is the "due" state, not the newest scheduled date in the history.

**Comment by garethbowen** [comment]
PR please @alxndrsn : https://github.com/medic/medic-webapp/pull/3026

It turns out this is due to #3011 - we have special handling for the scheduled state because if a message is scheduled we want to show the due date, not the date when the state transition occurred. So once #3011 is fixed it'll go back to showing the right date.

**Comment by alxndrsn** [comment]
The code seems to assume that the current state is also stored in the `state_history` list.  If that's the case, then this seems fine.
