### ISSUE TITLE
Place ID is blank

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3037]
In people's tab, click on district. Place Id is blank....What should be this ID and is anyone using it from UI perspective @diannakane @sglangevin. 
![image](https://cloud.githubusercontent.com/assets/6979995/21762134/f15e5ad0-d6bb-11e6-9964-470d7e5ad3bf.png)

**Comment by diannakane** [comment]
I think it's there as a holding place for projects that need to use it. I
don't know of any that use it so it probably should be hidden.

**Comment by garethbowen** [comment]
This is the ID used for referring to the place by SMS, usually a 5 digit number. It's the most important piece of info on this page when defined. It's not useful for smartphone deployments.

It's difficult to determine if a deployment is SMS, smartphone, or both so I'd prefer to leave it as is. We could think about making fields here configurable (maybe as part of #2914).

@diannakane Thoughts?

**Comment by diannakane** [comment]
We have a design issue for showing or hiding information on a person/place profile card. My understanding is that these are currently hard-coded and can only hide information that's not being used. Slightly different from #2914  https://github.com/medic/medic-design/issues/6

It sounds like the real confusion here is how to handle mixed SMS/App deployments. It seems like we may want the option of having place IDs in any project using SMS at all so that nurses and CHWs can both report on the same places from different devices. 

If we implement the suggestion to use Place IDs in mixed deployments, then any project not using it would be considered app-only and it could be hidden.

@sglangevin any thoughts?

**Comment by garethbowen** [comment]
Yes the fields are hardcoded but we could make the contact info card just another configurable section in #2914 so fields can be added/removed per project as required.

**Comment by diannakane** [comment]
That would be perfect. I think that would satisfy design issue #6 as well.

**Comment by sglangevin** [comment]
Places don't normally have 5-digit IDs, do they? I thought those IDs were used for cases and now for people? Seems like place pages don't really need that field, but making it configurable would solve this. Only other consideration is what the hard-coded fields should be because it seems like we should have some to avoid extra design and configuration work on projects.

Another related question: can we remove "Belongs to" for the top-level places? They will never have anything above them in the hierarchy.

**Comment by diannakane** [comment]
We would need it for submitting place-specific forms for SMS projects, e.g.
community events, household surveys like equity lens and form 513,
potentially form 514 but those are linked to CHWs anyhow so we could use
the phone number to identify that.

**Comment by garethbowen** [comment]
This is now configurable. CR done with #2914.
