### ISSUE TITLE
Disallow creating a place without a Primary Contact?

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3042]
I was looking at #2815 with @ngaruko , and was confused why we ever would have places without primary contacts.

From the discussion in the issue, it seems that on the design side, it's a rule to never have contactless places ( @diannakane still true?).

On the technical side, changing primary contacts is likely to lead to mess, so we'd much rather have them set right away too.

Is there any reason we are allowing places without primary contacts? 
Right now it depends on the form, if it's not a required field then you don't have to set it. Are there projects who need contactless places? @abbyad

**Comment by diannakane** [comment]
We thought it was a tech requirement to have a PC with every place. I can't come up with any reason why we should mandate this from the design side. For example, a manager may want to create a list of Areas before recruiting CHWs.

We will also avoid the potential user annoyance of having to select or create a contact in order to add a place, which is a separate type of action that you may not be interested in doing or have the relevant information at hand at that time. 

It's not a big sticking point if anyone feels strongly that it should be required; I just can't think of a reason why we should enforce this.

**Comment by sglangevin** [comment]
I thought we specifically decided that a primary contact is not required. I think it makes more sense not to require a primary contact unless there is a technical reason that we have to have one. There are plenty of cases where a place doesn't really have a primary contact or the person creating the place doesn't know who the primary contact is at the time they are creating the place.

**Comment by diannakane** [comment]
Agreed.

**Comment by garethbowen** [comment]
Agreed. Closing. Reopen if we come up with a reason why this is needed.
