### ISSUE TITLE
Reporting Rates dashboard uses reports for invalid weeks in calculations

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3051]
Reported by @bishwas-medic in https://github.com/medic/medic-projects/issues/1258, the Reporting Rates dashboard incorrectly uses reports with invalid week numbers (eg week number 54) in its calculations. We should also test the behaviour with invalid month numbers.

**Comment by sglangevin** [comment]
Possibly related: https://github.com/medic/medic-projects/issues/1317

**Comment by garethbowen** [comment]
It seems unfair to blame reporting rates for this, and I think it would be really hard to fix it to discard invalid values. Instead, we should work out how to validate these forms so we can reject them if they come in with an invalid ISO week (or month, year, whatever).

This might need a custom validation function (`isISOWeek(week, year)`) or something because the number of ISO weeks is variable per year. This shouldn't be hard to do and will give good feedback to the user who entered the invalid week.

**Comment by bishwas-medic** [comment]
I was thinking of filing a Feature Request for a new validation function for checking ISO Week like @garethbowen mentioned. But I don't think that alone will solve the issue of the wrong reports appearing in the Reporting Rates dashboard, since we are already checking for wrong weeks in validation and correctly labeling the reports as invalid and sending a proper reply to the users too. Those invalid report are still appearing on the analytics.

For example, this was a report sent for Week 54 of 2016 which the webapp labelled as invalid (max week is set to be 53) and sent a reply informing about the error.
<img width="1199" alt="screen shot 2017-02-14 at 5 32 22 pm" src="https://cloud.githubusercontent.com/assets/13689284/22928302/d606f51a-f2dd-11e6-9a7a-777b1c7475a3.png">

But this report is still listed on the Reporting Rates analytics:
<img width="1199" alt="screen shot 2017-02-14 at 5 32 22 pm" src="https://cloud.githubusercontent.com/assets/13689284/22928342/161ff976-f2de-11e6-90fd-528e86c24203.png">

There are lot of similar example of this happening. So, I think there should be a check for invalid isoWeeks in reporting rates alongside the custom validation function.

**Comment by garethbowen** [comment]
The error reports being included in the percentages appears to be fixed in 2.10 so I'll close this for acceptance testing.

@bishwas-medic Please raise a feature request for the ISO week validation - I think it's a good addition.
