### ISSUE TITLE
create 0.4.x beta market

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3052]
Henok found it confusing on his instance that dashboard gave him the option to upgrade from 2.x to 0.4.x.  This is because we are pushing betas for 0.4.x and 2.x to the same market, but also looks like a bug in the dashboard because that upgrade path breaks semver rules.  Basically determine if we really need separate beta markets for 0.4.x.  We currently have the following markets alpha -> beta -> rc -> release on https://staging.dev.medicmobile.org/.   The Beta and RC markets are shared, whatever is tagged with `beta` or `rc` will go there, alpha is fixed to master branch and release has two markets (v0.4 and v2).

**Comment by abbyad** [comment]
The 2.x version in question was on beta as part of the v2.9 testing before it was released. It can now be moved to the Release market. At this time I do not think we need a separate beta for 0.4.

As for the semvar issue, although we currently have the v0.4 on the beta channel we cannot update to it since v2.9 is installed - which is the expected behaviour. There is therefore no issue with semvar. 
![image](https://cloud.githubusercontent.com/assets/789512/22033878/5042c2a0-dcb8-11e6-9be4-9a720e89ecc4.png)

**Comment by henokgetachew** [comment]
@abbyad I'm pretty sure I saw the update option next to the 0.4 version.  I can't compare now as the latest beta is a 2.9 one.  I will keep watching out for this.
