### ISSUE TITLE
Task schedules created using the `reported_date` of a report do not show/hide at the expected time

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3097]
Task schedules created using the `reported_date` of a report as the base date for the schedule appear based on the time that the report was created as opposed to the relative day.

Example:
- Submit a patient assessment at 5:30 pm on Tuesday where the outcome is a follow up in 2 days
- Expected: task appears at 12:00:01 am on Thursday
- Actual: task appears at 5:30 pm on Thursday.

Another example:
- Submit a patient assessment at 3 pm on Wednesday where the outcome is a follow up in 1 day
- Expected: task appears at 12:00:01 am on Thursday
- Actual: task appears at 3 pm on Thursday 

This is happening for all different types of task windows. Initially I thought it was related to tasks where the `start` or `end` of the task was `0` but it is happening for non-zero values as well. Essentially, tasks are appearing late and remaining visible for too long because we have the same issue on the other end of the window.

**Comment by sglangevin** [comment]
I know there was a request from @derickl for a v2.8.x release for some LG-related bug fixes. If we are going to do that, it would be great to include this bug fix as well as it is needed for Muso.

**Comment by sglangevin** [comment]
Task rules in question: https://github.com/medic/medic-projects/blob/master/muso/tasks/task-rules.js

**Comment by garethbowen** [comment]
CR please @estellecomment : https://github.com/medic/medic-webapp/pull/3121

@sglangevin This change modifies the `utils.addDate` function to zero out the time, so for example, `utils.addDate('2017-01-01T16:32:12.555', 1)` => `'2017-01-02T00:00:00.000'`. I figure that because you're adding a number of days having a time becomes nonsensical. The advantage of this approach is it'll just work on upgrade. The disadvantage is if somewhere a tech lead wants to retain the time component they won't be able to use this function. Let me know if this is an issue...

**Comment by estellecomment** [comment]
(that's a really clear bug description @sglangevin! Really helpful!)

**Comment by estellecomment** [comment]
Couple comments so I'm leaving it open for you, but LGTM.
