### ISSUE TITLE
How should sentinel handle exceptions?

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3122]
This is a (software) design issue. Stemmed from thinking in https://github.com/medic/medic-webapp/issues/3102#issuecomment-277851423

> What is the proper error handling for unhandled exceptions inside a transition?
Should sentinel ever crash because of an unhandled exception in a transition?
When a transition returns an error, is it ever retried, how? What are the effects of returning an error from a transition?

> Currently the documentation states below, but I don't know how the re-run is handled exactly.
```
* callback(err)
  The document is saved and `ok` property value is false if `err` is truthy.
  Use this when a transition fails and should be re-run.
```
>We should figure this stuff out too and document.

>I think transitions should continue running even when errors occur. Any transition can do anything, like use some random API. If that random API is down that doesn't mean simpler transitions should also fail/never run. If an errors occur (even exceptions thrown?) in a transition the doc continues towards a complete state. If transitions want to be dependent on each other they can coordinate via the transitions property. The failed transition should mark itself as failed in the doc and the transition handles that state during backlog processing or the next change.

**Comment by SCdF** [comment]
Here is my 2¢: Sentinel should never:
 - Crash so hard that node catches it and kills the process
 - Crash while processing a transition so hard that other transitions that were valid to run do not run[1]
 - Crash while processing a transition so hard that the nature of that crash is not recorded against the document under transition as a transition error
 - Mark a document as "done" such that if a group of documents cause a crash in a transition that we then subsequently fix, that group of documents do not get run through the now fixed transition again

[1] You could argue here that transitions depend on other transitions and thus if one fails none of the others should run. I

**Comment by mandric** [comment]
I don't think it's practical to try to catch all exceptions and never crash. There is always some potentially unhandled exception or programming error that can cause the program to crash.  Crashing and logging back traces at this point is the best thing for the program to do because it was not programmed to handle that state.  There is nothing inherently wrong with crashing.  And in some cases a process might crash and recover on restarting.  I don't believe it's the best idea to design sentinel to run forever, that's why we have backlog processing etc so it can recover during errors.  

I'm on the fence about whether a transition can cause a crash though.  Ideally a transitions should be programmed to handle its own exceptions, just like every part of the stack.  If a transition is not doing this then it's a bug in the program and crashing is just another way of error logging and retrying.

See also: https://www.joyent.com/node-js/production/design/errors

> The best way to recover from programmer errors is to crash immediately. You should run your programs using a restarter that will automatically restart the program in the event of a crash. With a restarter in place, crashing is the fastest way to restore reliable service in the face of a transient programmer error.

**Comment by sglangevin** [comment]
@SCdF @garethbowen is this one still relevant?

**Comment by garethbowen** [comment]
I vote we close it off. The only time an exception is thrown that crashes sentinel is when it's unexpected and it's not a good idea to just catch all and hope for the best.
