### ISSUE TITLE
Tasks should appear and clear at midnight in the user's timezone

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3205]
In #3097 we changed the nootils `addDate` function to zero out the time component so tasks show and hide at midnight. However because the date is UTC it doesn't show/hide at midnight from the user's perspective.

The current workflow is something like:

1. report submitted at 1pm local time
2. reported_date stored in UTC (eg: 1am UTC tomorrow)
3. task config calls addDate, which
  a. adds a day for the day 1 follow up (1am UTC in 2 days time)
  b. zeroes out the time (12am UTC in 2 days time)

The task is expected for tomorrow, but is actually shown in two days.

The workflow that would work is:

1. report submitted at 1pm local time
2. reported_date stored in UTC (eg: 1am UTC tomorrow)
3. task config calls addDate, which
  a. converts the date to local time (1pm - assume same timezone as submission)
  b. adds a day for the day 1 follow up (1pm tomorrow)
  c. zeroes out the time (12am tomorrow)

This is one option for a solution, there are bound to be others.

This is required for 2.11 but not necessary in 2.10.

**Comment by SCdF** [comment]
This change is deceptively simple. I'm worried I'm misunderstanding (date handling is the most confusing thing around). I'm also not completely sure how to write an effective unit test, since it's not possible to change system timezones from node where these tests are running from.

Please stare at this carefully: https://github.com/medic/medic-webapp/pull/3211

**Comment by garethbowen** [comment]
Comment on the PR. Back to you!

**Comment by SCdF** [comment]
Merged.
