### ISSUE TITLE
Exporting server logs fails with api 500

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3209]
On lg.dev, admin user

Request to API returns 500:
![image](https://cloud.githubusercontent.com/assets/911434/23655520/8f60ed74-0335-11e7-8ca4-938ae3ff3323.png)

Api logs say :
```
2017-03-07T11:53:51.604Z - info: 127.0.0.1 - admin [07/Mar/2017:11:53:51 +0000] "POST /api/v1/export/logs?format=zip&locale=en HTTP/1.0" - - "https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 
2017-03-07T11:53:52.203Z - error: Server error:
 [Error: Log export exited with non-zero status 1]
```
And couch logs say nothing because no request gets to couch. Things go wrong in api.

Locally, I get the same thing, excepts it prompts me for the sudo password (?!) first, and then fails the same way : 
```
::1 - - [07/Mar/2017:11:51:36 +0000] "POST /api/v1/export/logs?format=zip&locale=en HTTP/1.1" - - "http://localhost:5988/medic/_design/medic/_rewrite/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
Password: <password>
Server error:
 [Error: Log export exited with non-zero status 1]
```
And then subsequent requests fail without password prompt. (don't know if that's related at all)

**Comment by SCdF** [comment]
@estellecomment the api *logs* prompt you for a sudo password? Are we evaling and using some kind of root-only tool to generate zip files or something?

**Comment by estellecomment** [comment]
Well, it's the node program for api prompting me, not the log file, but you get what I mean. 

Yeah I was thinking of something like that...

**Comment by browndav** [comment]
This is fixed in recent builds of our OS images, and was definitely a regression. To get it to work on a not-yet-updated instance, try adding line eight of https://github.com/medic/medic-os/blob/master/platform/initrd/common/etc/sudoers#L8 to `/etc/sudoers` using `visudo`.

@SCdF: We're not eval'ing; there's a script that takes no user input (`/boot/print-logs`), and simply finds/dumps all of the log files. We have `sudo`'s environment-sanitization feature turned on, but I'm still really uncomfortable with the privilege level. It wouldn't be too tricky to use an unprivileged account other than `vm` for this – e.g. create a `log-access` account, use `gardener ALL = (log-access) NOPASSWD: /boot/print-logs`, and then invoke the script from `medic-api` as `sudo -u log-access /boot/print-logs`.

**Comment by browndav** [comment]
Would it be useful to do patch this en-masse on all machines, or do you think we're better off just waiting to upgrade?

**Comment by browndav** [comment]
Duplicated by https://github.com/medic/medic-webapp/issues/3089.

**Comment by browndav** [comment]
Related, but different cause: https://github.com/medic/medic-webapp/issues/3089.

**Comment by mandric** [comment]
@browndav what needs code review?  The `sudoers` file above?

**Comment by browndav** [comment]
Yeah – just looking for verification that this fixes the issue. Probably worth testing at the same time, and then you can just move it to `5 - Ready`.

**Comment by mandric** [comment]
`/boot/print-logs` does not exist on lg.dev, so it's more than just a `sudoers` tweak.

**Comment by browndav** [comment]
This is resolved in the latest `medic-os` master, which will be going out to all production instances within the next two weeks. The update process will replace the entirety of the `bootinit` scripts in `/boot` as well as the `sudoers` configuration beneath `/etc`.

Moving to ready.
