### ISSUE TITLE
Moving angular-mocks from 1.6.2 to 1.6.3 causes karma to fail

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3213]
```
  TypeError: angular.module(...).info is not a function
  at node_modules/angular-mocks/angular-mocks.js:799
```

**Comment by garethbowen** [comment]
The problem is angular-mocks was on 1.6.3 and angular itself was on 1.6.2. These two need to be kept in sync. The production library is locked by the shrinkwrap, but the dev dependencies aren't, so the can get out of sync. I've locked down angular-mocks to 1.6.3 to match the shrinkwrapped angular libraries and we'll just have to remember to bump it when we bump angular.
