### ISSUE TITLE
update_message_task does not update scheduled_tasks in 0.4

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3246]
https://github.com/medic/medic-projects/issues/1645

**Comment by alxndrsn** [comment]
@mandric @garethbowen Please advise if:

* we are still fixing stuff on 0.4
* it would be appropriate to backport the `doc.scheduled_tasks` code in `getTask()` hilighted in the linked issue comments from 2.10 to 0.4.

**Comment by sglangevin** [comment]
The affected instance has a clone on 2.10 available for testing. Would it be faster to complete that testing and update production? Or backport the bug fix and do a release of 0.4? Ideally we would get this resolved as soon as possible if SMS messages are not going out.

**Comment by alxndrsn** [comment]
PR for review at https://github.com/medic/medic-webapp/pull/3247

**Comment by garethbowen** [comment]
@alxndrsn I was hoping not to fix any more stuff in 0.4, but until testing completes we can't be 100% sure that every project can get on 2.x yet, so I think we still have to support it. That said, my understanding was we'd decided that 0.4 wasn't compatible with medic-gateway (possibly because of this bug, possibly because of others).

So we have a few options:

1. move them off gateway
2. push through testing and deploy 2.10
3. patch the issue and release 0.4.16

1 is a bad idea. 2 is ideal. 3 may be necessary depending on how long 2 takes and how critical the issue is for this project.

The PR is all good, so if you want to do a 0.4.16 release follow [the process](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#webapp).

Maybe also make sure that someone is testing the 2.10 clone Sharon mentioned because there might well be another 0.4+gateway bug we haven't found yet...

**Comment by alxndrsn** [comment]
@bishwas-medic 0.4.16 is building and should be ready for release shortly.

**Comment by mandric** [comment]
@alxndrsn we missed a release a step so that it shows up on [Releases tab](https://github.com/medic/medic-webapp/releases) too.  I looked at [the process doc](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#webapp) above and it's not very clear, I think we meant to say "tag release in GitHub"?  Or we need to add another step for doing the release in github.

> Tag release in git. CI will publish to the correct market depending on the name of the tag.

**Comment by alxndrsn** [comment]
@mandric interesting!  I certainly tagged it in git, and on the releases tab you linked there's an entry for `0.4.16`...but nothing's been uploaded there.  Is this something that can & should be fixed for this release?  I don't know the process, but if the documentation can be updated that would definitely be helpful.

**Comment by mandric** [comment]
Right you certaintly tagged it in git, just didn't do it through the GH interface so we're missing an entry in the Releases tab.  I think we want to just update the doc.  I can update it and file a PR so we can decide what makes most sense.  I'm just not sure we want to advise tagging through GH  because it does both the release entry and the git tag.

**Comment by alxndrsn** [comment]
We could also use the releases API to push the changelog content to github.  Sounds like a big effort, though.

In the `medic-gateway` repo, if you push a tag that matches `vX.Y.Z`, travis creates the entry in github releases and adds the apks there - maybe interesting?

**Comment by mandric** [comment]
That seems like a nice trick but the problem is you need to also include the changelog entry... which is a pain.  I think quickest thing right now is include the GH release step in the process doc as a separate step.

**Comment by ngaruko** [comment]
Do we need to AT this @alxndrsn @sglangevin @mandric ? Any clue how?

**Comment by mandric** [comment]
I'm not sure, I think this has been released already so it doesn't require AT?
