### ISSUE TITLE
Full access users cannot create users, even when they have the appropriate permissions

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3262]
This was reported by a project team and then again by @ngamita during testing of an upgraded instance. Here are the permissions provided to the full access user:
![image](https://cloud.githubusercontent.com/assets/1286381/24125284/2cbbba0a-0d85-11e7-97c6-0def670b4021.png)
![image](https://cloud.githubusercontent.com/assets/1286381/24125293/3bd77560-0d85-11e7-9e3a-92c57aeacb76.png)
![image](https://cloud.githubusercontent.com/assets/1286381/24125305/4fe7de46-0d85-11e7-8794-4b67c8903a1f.png)

Here is the console output after pressing Submit on the create user modal:
![image](https://cloud.githubusercontent.com/assets/1286381/24125232/ee40f9de-0d84-11e7-8796-a5e0451f9cd1.png)

It appears that the problem is due to the fact that full access users cannot access the `_users` db but they need to in order to be able to create users. In 0.4, full access users could create users, and this is needed so that PMs can create users for their projects.

**Comment by sglangevin** [comment]
Original issue: https://github.com/medic/medic-projects/issues/1658

**Comment by SCdF** [comment]
This ticket about removing couchdb admins is related: https://github.com/medic/medic-webapp/issues/2942

Basically, right now only a true couchdb admin can edit / add users. This is a problem because:
 - Like *this* ticket states, there are other people who should be able to add users who can't
 - Like *that* ticket states, having a couchdb admin being a credential given out is a bad idea

To solve both problems we should follow the outside I gave in the linked ticket.

**Comment by SCdF** [comment]
So this might be good enough for us, for now: https://github.com/medic/medic-api/pull/131 @garethbowen take a look plz.

It's somewhat of a hack:
 - it uses roles, not our "permissions", which is in theory wrong, since there are permissions around whether or not they can view, create, edit and delete users
 - Except apparently for "Full access" users these things are ignored anyway
 - and also many of these permissions aren't actually employed in the webapp, but are instead only used in api, which, since api doesn't block access to doing things manually, doesn't really matter
 - it still doesn't let you delete users for some reason, because some urls / verbs require super duper admin in _users, and that appears to be one of them (I'm going to ask the user-group, documentation doesn't make it obvious)
 - It allows people with this role to edit configuration / the ddoc. This is arguably a terrible idea (editing the ddoc means editing views, enabling erlang, writing to disk…), but it aligns with the the UI implies they can do

Am I right in thinking there is a permission re-think in the works?

**Comment by SCdF** [comment]
(also, dropping #2942, solving this is actually kind of massive and out of scope)

**Comment by garethbowen** [comment]
One small code suggestion - back to you.

**Comment by SCdF** [comment]
So I talked to the CouchDB folks about how we can make this nicer. The summary is: don't monkey with the security object on system dbs (those that start with _) and instead do it all through an intermediary (that would be api for us).

Doing this right would be part of our permissions re-think, and part if #2942.

**Comment by SCdF** [comment]
Merged.

Note there are known issues with this technique:
 - Full Users can just do everything, medic permissions don't matter (this is already true)
 - Full Users that aren't real CouchDB admins can't delete users.
 - Probably more.

To deal with this "correctly", look at #2942.

**Comment by abbyad** [comment]
Can create and edit users, but not delete them. 

`PUT https://clone-barefoot.app.medicmobile.org/_users/org.couchdb.user%3Atest 403 (Forbidden)`
`Error submitting modal Object {data: Object, status: 403, config: Object, statusText: "Forbidden"}`

Tested using 2.11.0-beta.

**Comment by abbyad** [comment]
This issue was about creating users, not deleting them so I'll leave it to @sglangevin to decide what the intended behaviour is here. Do we want to let any user that has these permissions to edit and delete other users, only create users, or only create and edit users? If it is the latter, then we can close this issue and move it to Ready.

**Comment by abbyad** [comment]
For sanity check, here are my permissions:
![image](https://cloud.githubusercontent.com/assets/789512/24769638/2d78c962-1ad5-11e7-84f2-e46e96d0ecc4.png)

**Comment by sglangevin** [comment]
I think this is sufficient for satisfying the request as now PMs will be able to create and edit users. This will be resolved once we improve our roles and permissions.
