### ISSUE TITLE
Cannot submit a form where field values have Hindi characters

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3308]
Cannot save an XForm with Hindi characters: `Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.`

![image](https://cloud.githubusercontent.com/assets/789512/24433075/39c23da8-13f4-11e7-911a-e037dc4fe95b.png)

Testing with a single Hindi character gives the error as well. If I remove the Hindi chars in the text area in question I can submit the form.

**Comment by garethbowen** [comment]
Reproduced locally with a non-minified stacktrace:

```
Error submitting form data:  DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at attachContent (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:187460:15)
    at http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:187504:9
    at processQueue (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:36825:37)
    at http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:36869:27
    at Scope.$digest (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:37964:15)
    at http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:38193:26
    at completeOutstandingRequest (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:26256:10)
    at http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:26536:7
```

**Comment by alxndrsn** [comment]
Offending code at https://github.com/medic/medic-webapp/blob/master/static/js/services/enketo.js#L273-L279:
```js
var attachContent = function(doc, content) {
  doc._attachments = doc._attachments || {};
  doc._attachments.content = {
    content_type: 'application/xml',
    data: btoa(content)
  };
};
```

**Comment by garethbowen** [comment]
Yeah I'm on it

**Comment by garethbowen** [comment]
Code review please @alxndrsn 

I'm pretty sure your way would've worked, but there's a PouchDB article on [how to work with attachments](https://pouchdb.com/guides/attachments.html) that I followed instead. I took the opportunity to clean some things up while I was in there so use `?w=1` to make it a bit easier on yourself. I mostly created the AddAttachment service because I couldn't get a unit test to test the Blob bit, so the unit test coverage is slightly worse than it was. I'm planning to write an e2e test to cover this soon as part of #3288

**Comment by alxndrsn** [comment]
Merge at will!

**Comment by abbyad** [comment]
Works well! Moving to Ready.
