### ISSUE TITLE
False positive error uploading translations

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3350]
The import of a properties file succeeds to update the translations, but there is always this error:
`Error submitting modal TypeError: Cannot read property 'push' of undefined`

Followed by a `Possibly unhandled rejection: undefined` when the modal is closed.

![image](https://cloud.githubusercontent.com/assets/789512/24767369/ba123272-1acc-11e7-864f-044f2f2c7f7b.png)

Tested on 2.11.0-beta.1 and also seen on 2.10.2

**Comment by garethbowen** [comment]
I haven't managed to reproduce this but I suspect it's caused by [this line](https://github.com/medic/medic-webapp/blob/master/static/js/services/properties.js#L26) as it's the only `push` I could easily find. I suspect this could be a problem if using the `translation_key` but trying to update the `messages` property in settings. Needs more investigation.

**Comment by SCdF** [comment]
@abbyad do you really mean *every* time? If so can you provide (privately of course) a server and a file that I can run the test on myself?

**Comment by abbyad** [comment]
Happens 100% of the time for me. Will send you details.

**Comment by abbyad** [comment]
Reproduced by selecting a language, exporting the language file, and importing the same file (with or without edits). 
Tested using Chrome 56 on Windows, and the file has Unix LF.

**Comment by SCdF** [comment]
Reproduced, and it's where @garethbowen thoughts it would be.

![image](https://cloud.githubusercontent.com/assets/583851/24960444/bbce797a-1f8d-11e7-9648-7025f0360b57.png)

Unfortunately I haven't reproduced it locally yet, which is odd.

**Comment by garethbowen** [comment]
@SCdF There's probably a "corruption" in the app_settings somewhere - have you tried importing their app_settings then importing the file?

**Comment by SCdF** [comment]
Ran out of time last night, but the plan today is to work out exactly how this (untyp-- OK I'll stop) data structure is supposed to look and then work out if either a) there is an undefined edge case we're not taking care of and so take care of it or b) their app_settings are corrupt and make the error clearer.

**Comment by SCdF** [comment]
I think this change sort of broke it: https://github.com/medic/medic-webapp/issues/3127 ?

Sort of. Specifically, it marked the `messages` field as deprecated, so the app settings that is causing import failures doesn't have that field, which is why the push is failing.

It also might be that the import code is still correct, but the export code is not correctly exporting translation files, and is putting translations in the "settings" section (which tries to get them to be pushed into `messages`) when really they should be in the standard translation section.

**Comment by SCdF** [comment]
@estellecomment please review https://github.com/medic/medic-webapp/pull/3383

**Comment by estellecomment** [comment]
Done. Code looks good but I don't understand what you're doing!

**Comment by SCdF** [comment]
@estellecomment added a comment to the PR. Let's discuss!

**Comment by ngaruko** [comment]
Hi @abbyad Are you able to confirm if this was fixed in that particular environment it was occuring

**Comment by sglangevin** [comment]
Seems to be working for me. @abbyad please test on the instance where this was occurring and let us know if it's working for you. In the meantime, moving to Ready.
