### ISSUE TITLE
Some reports not being replicated

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3437]
As a CHW supervisor I should see all reports that were submitted by people I supervise. I have been seeing odd replication issues where a supervisor does not see certain reports. One such case where a supervisor user account does not see reports from their CHW is if the `patient_id` did not match a patient. This scenario seems reproducible.

For instance, [this report](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/0ba96f94b93899b06a4136ab5c409de6) can be seen by admin, but not Marni's supervisor `mch` who is assigned to the MCH Health Center:
![image](https://cloud.githubusercontent.com/assets/789512/25666685/39d62748-2fef-11e7-9281-0ac9f549ce02.png)

![image](https://cloud.githubusercontent.com/assets/789512/25667219/dab9c5a6-2ff0-11e7-9ef5-171bdcbfe470.png)

**Comment by abbyad** [comment]
I just reproduced on `2.12.0-alpha.5615` as well, so this issue has unfortunately not been magically been resolved by some other work since 2.11.

**Comment by garethbowen** [comment]
@abbyad The key to this bug is in the error: "No person with ID number '30001' found.". The way replication works is you can see any contact below you on the hierarchy and any report that is about one of those contacts. Because this report doesn't have an associated contact we don't know who is allowed to see it. Does that make sense?

When no patient_id is supplied at all the code falls back to use the contact_id. We could change the code to use the patient_id when the contact with that ID exists, and fallback to using the contact._id if it doesn't. This would mean a doc with an unknown patient behaves the same as a doc with none. Would that work for you? Is it important that supervisors see incorrectly submitted reports?

**Comment by abbyad** [comment]
That's a helpful explanation. I do think that supervisors do need to see incorrectly submitted reports to be able to support their CHWs. The solution you propose seems like the right approach.

**Comment by abbyad** [comment]
Just relaying a comment by @ranjuts that came up for project that is being deployed, which reinforces the need for managers to see all reports submitted by their CHWs, even if the ID is incorrect:

> Logged in as u=`REDACTED_USERNAME`. Can’t see if a report submitted by person in my place has invalid ID. Is that expected? The ‘medic’ user can see this report with invalid ID. I, as `REDACTED_USERNAME` would expect to see all reports submitted by people in my area.

**Comment by sglangevin** [comment]
@garethbowen @abbyad we have a lot in 2.13 already, so I'd like to focus on getting that release out. We can either include this in 2.13 once other features are done (if time) or schedule this for either 2.13.1 or 2.14.

**Comment by garethbowen** [comment]
@sglangevin Because of this and some other confusing edge cases I'm thinking about making a change to how replication works. The change would be to replicate reports about people you can see, or _by_ people you can see. This is what you'd expect most of the time, but when depth is involved you'll start seeing more than you expect.

For example, if you can see 1 level below your facility, and the CHP (level 1) submits a report about a patient (level 2) then before you wouldn't see that report, but after the proposed change you will.

It's debatable if this is correct. I discussed it with @abbyad and we felt that for supervisors to do their job they need to be able to see everything their CHP is doing. What do you think?

**Comment by sglangevin** [comment]
If we do that I am guessing we will have a lot of problems with LG supervisors, who are the ones we created replication depth for in the first place. They will all of a sudden be able to see 10s of thousands of reports that they weren't replicating before. Unless we can prove they will still be able to log in, I'd advocate strongly against this until we are able to make our hierarchy flexible and use that as a way to better limit what supervisors have access to when they log (e.g. creating a hierarchy level for supervisor area that only contains the CHWs they manage). Even with that, we can still have issues with supervisors who manage a lot of people.

In general, I do agree with supervisors seeing the data that CHWs submit but I don't feel comfortable with this change unless we can test it on a clone of LG's database to prove that it will not break for the supervisors who are using the app.

**Comment by garethbowen** [comment]
So LG supervisors want to see the people they supervise but not the reports they're submitting? What sorts of workflows are they doing?

**Comment by sglangevin** [comment]
It's not that they don't want to see the reports, it's that they will run out of memory on their devices if we force them to download everything. And for now, their workflows don't require seeing the reports because they are using the app to fill in supervisory reports.

**Comment by garethbowen** [comment]
@abbyad What if I marked these messages as unassigned so if the supervisor has the "can_view_unallocated_data_records" permission then it'll replicate to them? I assume this won't affect LG because they should have that option turned off. It does mean that incidents like the one you had the other day with the carrier sending thousands of messages will get replicated though...

**Comment by abbyad** [comment]
Right, replicating all the reports to supervisors will be problematic. @garethbowen, I was under the impression that `unassigned` meant that the sender is unknown... is that what your new proposal would do?

**Comment by garethbowen** [comment]
@abbyad You're right, it'd conflate the two concepts. I'll think about it some more...

**Comment by garethbowen** [comment]
Code review please @estellecomment 

I'm sorry - this one's a total mess. Because of the ridiculous way we structure our repo I forgot to branch for webapp which means I couldn't PR so here are the individual commits...

### Sentinel

- https://github.com/medic/medic-sentinel/commit/3652b69b497c2b5640e166066a0ea9777b1b612f

### API

- https://github.com/medic/medic-api/commit/8ad0d07aea0a0c53c275816d3013b655b8030eef
- https://github.com/medic/medic-api/commit/3ded0d128af438963ebd29c7a971837dd3d41479

### Webapp

- https://github.com/medic/medic-webapp/commit/5b237079ab866b83f12ceaa94905e17ace772cfc
- https://github.com/medic/medic-webapp/commit/ac2775e64f80c2361b97f8ecd1f3e58c5f5c8bcb
- https://github.com/medic/medic-webapp/commit/03c57975f353bc3dd7de8f5ce4b2431e2a9251b0

**Comment by estellecomment** [comment]
😄  
Commits are clean so it's totally followable.

Code LGTM.
Did you bump sentinel in webapp? Can't see it in the listed commits.
Api bump looks right.

Nice!

**Comment by ngaruko** [comment]
Judging from the discussion above, I would like to check with @abbyad and @sglangevin if a)the replication now works as expected b) there aren't any other 'side-effects' (like too much data being send to supervisors).
