### ISSUE TITLE
Allow Android users to log out if they have the can_logout permission

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3450]
Android users who are using a branded version of the Medic Android app cannot currently log out. We have a `can_logout` permission. If this permission is enabled, users should have access to the logout button in the hamburger menu and be able to log out.

Relevant to permissions work to be done later this year.

**Comment by alxndrsn** [comment]
@sglangevin Which users are expected to need this?

**Comment by alxndrsn** [comment]
This will require minor changes to the android app - currently the "Logout" menu item is completely unavailable in branded builds.  There are two options for enabling it:
* enable on a per-brand basis, so every user for this brand will have the option available.  This could be done via manually adding to the branded build's menu file, or better via a feature flag configured in `build.gradle`
* enable it via a javascript hook, e.g. `medicmobile_android.enableLogout()`

There are other options, e.g. include the menu item by default, but remove it via a JS hook if `can_logout` is _not_ granted, but it would be safer for the wrapper to deny the option until explicitly told otherwise.

**Comment by sglangevin** [comment]
This was requested by a partner who has multiple users sharing an Android tablet. They wanted to be able to easily log out and log back into different accounts without having to clear data every time. Ideally we'd be able to use the `can_logout` permission to control whether or not an Android app user can logout.

**Comment by SCdF** [comment]
@sglangevin / @alxndrsn do they need to be able to log out in the android app specifically, or just have logout exposed in the Medic menu?

**Comment by alxndrsn** [comment]
@SCdF You may be hinting at this: all my talk about android in my previous comment is probably irrelevant, as the option could just be done inside the angular hotdog menu.

**Comment by sglangevin** [comment]
As long as we are able to use the `can_logout` permission to control whether or not a user sees the option to logout, I think that suffices. Ideally we'd use the permission for both desktop and Android users, so controlling it in the web app may make more sense than controlling it within the Android container.

This is not high priority at the moment, just wanted to file it for later.

**Comment by sglangevin** [comment]
This one has become higher priority as this project is preparing to roll out. Ideally we should have a permission `mobile_users_can_logout` that, when enabled, makes the Logout option appear in the hamburger menu. If disabled or un-set, the Logout option should not appear, as the default should be for it not to appear.

**Comment by garethbowen** [comment]
Add a confirmation dialog: "Are you sure you want to log out?"

**Comment by garethbowen** [comment]
Triaged as High priority because CiC are waiting on this.

**Comment by garethbowen** [comment]
This will need to be backported to 2.14.x and maybe 2.13.x as well - decision pending.

**Comment by garethbowen** [comment]
Code review please @SCdF . Feel free to leave the backporting to me...

**Comment by SCdF** [comment]
@garethbowen I'll leave you to merge / cp

**Comment by ngaruko** [comment]
LGTM
