### ISSUE TITLE
Slow initial replication for users with lots of docs

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3508]
CouchDB reverts to a slow strategy when a changes feed is requested with more than 100 doc ids. 100 is fine. 101 is slow.

This is affecting LG in production since upgrade to 2.11.

Work out why and fix.

**Comment by SCdF** [comment]
The gist of the problem is talked about in https://issues.apache.org/jira/browse/COUCHDB-1288

Basically we were hitting the slow path (>100 docs). This was causing us performance issues, with lots of cache misses and things like that (in theory).

Changing the code to side-step the slow path by batching `_changes` requests into chunks of 100 fixed the performance issues we were having.

@alxndrsn @garethbowen and myself built a branch to fix this issue, and tested it.

I've rebased that and re-written the git comments etc with this ticket in mind:
 - https://github.com/medic/medic-api/pull/159 (master)
 - https://github.com/medic/medic-api/pull/158 (2.11.x)

@garethbowen / @alxndrsn I think we're ready to merge these, but I'm not 100% sure so I didn't. I just did as much as I could in reworking / merging commits with git commit messages etc.

**Comment by mandric** [comment]
It would be nice to have tests documented for this.  Currently there is no easy way to know how to reproduce the issue (assert the problem exists) and how to know if it's fixed (assert the problem is fixed).

**Comment by sglangevin** [comment]
Removing from 2.12.0 and 2.13.0 as this will be released in 2.11.2.

**Comment by sglangevin** [comment]
@garethbowen has corrected me. Added back to 2.12.0 so we make sure it gets into that release. 2.13.0 hasn't been branched from master yet, so I think we're good there.

**Comment by sglangevin** [comment]
I'm going to call this Ready since the fix has been deployed to both LG instances and everything is working well.
