### ISSUE TITLE
Contact freetext search indexes useless things

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3523]
We are indexing all fields by default for contacts_freetext search[1], and have a huge index. Some of the search keys would never be used by a user and could be removed.

Examples of weird/useless keys, from lg.dev (prod data):
 - `"true"` and `"false"` are popular keys, coming from e.g. `pregnant_at_registration:true`
 - `“approx”` is a key, from indexing `date_of_birth_method: approx`
 - bits of location are indexed, e.g. we index the value `"-0.617624 35.274224 0 0"` so we'll have keys for `35.274224` (arguably useful) and `0` (useless)
 - bits of dates are index keys, e.g. from `"dob_raw": "Fri Dec 30 2011 00:00:00 GMT+0300 (EAT)"` so `“00:00:00”` and `(GMT+0300)` are indexed. (Note that `2011-12-30` is already a key)

Remove "true"/"false".
The others are trickier.

[1] except `'_id', '_rev', 'type', 'refid', 'geolocation', '*_date'`

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by SCdF** [comment]
@estellecomment did you have any inkling of how we would fix this?

I know that making search better is something that we want to work on in the very distant future (after 3.0, and then after the major UI update). I am completely confident that we will cover this issue then, either by making it utterly irrelevant (moving to an actual search technology) or intentionally redesigning how we use views to not be terrible (what you're suggesting, but on a grander scale).

It sounds like perhaps we could investigate blacklisting some things, though it gets very complex very quickly, and you can quickly come up with reasons not to do it. Obvious candidates would be true / false, Mon -> Fri, Jan -> Dec, all pure numbers.

However, doing that would probably have to have a large impact IMO, because of the cost of rebuilding those indexes.

**Comment by SCdF** [comment]
I am going to close this. I think this will be fixed from two different directions dealt with in other tickets:
 - #2849 Moving search views out into their own DDOC will reduce their drag on general app performance
 - (no ticket) We want to replace Pouch/Couch views with another tool (perhaps [lunr](https://lunrjs.com/)), which should improve the accuracy of results
