### ISSUE TITLE
Wrap text in tasks list

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3525]
Currently if a task has a long title, it gets truncated and `…` appended.  Instead this text should be wrapped.

**Comment by SCdF** [comment]
@alxndrsn why? It sounds like the … logic is intentional (otherwise presumably the handling would be uglier). Has someone asked for this, or has this caused a problem in production, or do you just not like how it looks?

**Comment by alxndrsn** [comment]
Requested by @ranjuts due to production problems.

**Comment by alxndrsn** [comment]
@SCdF what does the following mean?

> otherwise presumably the handling would be uglier

**Comment by sglangevin** [comment]
Why are the task names long in the first place? Are there long names or the task title is long?

**Comment by alxndrsn** [comment]
It's a product of the lengths of the task title and contact name, the font size and the width of the phone screen.  As we can't control any of these factors, wrapping the text seems like a safe way to handle long strings.

**Comment by sglangevin** [comment]
Cool, that's helpful - I was just curious. Not sure if this is helpful in the specific situation that you are talking about, but we do have the option to display a task summary screen before opening the form. It would be easy to list the task name or form name, along with the patient's name, on that screen. Not sure if that would be useful here.

**Comment by SCdF** [comment]
> @SCdF what does the following mean?
> > otherwise presumably the handling would be uglier

Sorry, mostly a redundant sentence. Just saying that the handling of long lines looks to be intentionally done a certain way.

**Comment by amandacilek** [comment]
FWIW, working on some typography updates to our content rows. One update is for Tasks rows to have at least two lines of text by default - the [Title of the task] in bold, followed by the person the task is about (the patient's name) on a new line. The title of the task can still potentially be too long and have the same issue of truncating or wrapping, but this at least breaks the two components apart.

**Comment by ranjuts** [comment]
Hey @amandacilek that's great to know! One quick suggestion if the work is still in progress would be to perhaps switch the position of the task title and the patient's name. CHWs are mostly searching for the patient name rather than the kind of task so perhaps that should be the highlighted portion rather than the task name. It also aligns with the people centered approach we have taken to our workflows and app. Moreover, the icon for the task indicating the task type accompanies the task listing as well which is already highlighting it to a significant extent. 

Just one point of view which I thought was worth sharing, I am sure there are many other things you have to consider.

**Comment by diannakane** [comment]
I like how you're thinking, @ranjuts. I can see how a CHW may be scanning their tasks for the names of the people they need to visit. 

The question is whether we can format the list items to bring attention to the right things while creating consistency throughout the app.

We've been trying to create more consistently between how list items are displayed -- tasks on the Tasks tab, tasks on the household profile, tasks on the person profile, and, once submitted, as reports on both the household and person profiles and on the History page. A couple considerations: 
-- we've been talking about removing name from a task on the person profile
-- we've been discussing a switch from displaying who submitted the report on the history page to who the report is about, or finding a way to accommodate both
cc: @amandacilek

**Comment by ranjuts** [comment]
`-- we've been talking about removing name from a task on the person profile
-- we've been discussing a switch from displaying who submitted the report on the history page to who the report is about, or finding a way to accommodate both`

Both of these make a lot of sense! I have experienced people being confused with how the history page currently displays the name of the person who sends in the report rather than who it is about, when its a person centric workflow. I don't have any bright ideas for accommodating both even though that seems ideal but a thought in terms of consistency- even in the history tab display of reports could begin with the name of the person who it is about and follow with the whens and whats of the report/action. Details such as date and time of report, person who reported, content of the report could follow. 

There's obviously more to consider re what you display for place (eg. do you only display the place for the person who the report is about even if the report was submitted by someone from a sibling place or level much higher than the person who the report is about etc)

**Comment by garethbowen** [comment]
@diannakane @amandacilek I'm not sure where this issue ended up. Should we allow line wrapping so the content is always shown, or should we leave it as is with the ellipsis and wait for the design to be complete?

**Comment by amandacilek** [comment]
Dianna, Ranju and I talked and I believe we are all comfortable with this approach:
![screen shot 2017-06-26 at 4 48 24 pm](https://user-images.githubusercontent.com/26235957/27564842-5c7ca8a6-5a8f-11e7-9886-16783d0fd535.png)

Tasks are now always two lines of text:
- Name of the person the task relates to
- Name of the task

This places more emphasis on the name of the person, while allowing more of the task name to show. The task name should still truncate if it is long.

**Comment by garethbowen** [comment]
Given that this is now no longer a simple patch, I'm going to remove it from the milestone. Either reschedule this issue, or close and create another one when the redesign is prioritised.

**Comment by alxndrsn** [comment]
@garethbowen it would be great to get the simple fix to make long titles usable (i.e. wrap the text) while we're waiting for big changes to be scheduled.

**Comment by amandacilek** [comment]
Sure, I mean if making it 2 lines is a _big change_, then I'm fine allowing a bandaid that at least matches the treatment of Tasks on the profile pages (with wrapping text). 

![screenshot_2017-03-22-07-51-30](https://user-images.githubusercontent.com/26235957/27597141-6001150c-5b16-11e7-8a49-6782013de0bf.png)

**Comment by alxndrsn** [comment]
> if making it 2 lines is a _big change_

Whether or not its a big change, it's taken nearly 4 weeks to get there.  In hindsight, it would have been constructive for me to apply wrapping to the text _before_ starting this conversation 😄

**Comment by ranjuts** [comment]
Was there a decision here? Are we wrapping until the other changes get implemented? @amandacilek @alxndrsn

**Comment by garethbowen** [comment]
Ok, decision made, I think we're all happy with wrapping instead of ellipsis for now.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
LGTM, merged.
