### ISSUE TITLE
Primary contact name on LHS is not updated after updating a contact even though it shows correctly on RHS.

### ISSUE THREAD

**Issue by ranjuts** [medic/medic-webapp#3527]
First encountered it at: https://ebpp-indonesia.app.medicmobile.org. However, seen it in another instance as well so guessing its an webapp issue rather than a project. 

version of webapp: 2.11.1

- I only edited the name of the person (via the person's profile). This person was already assigned the primary contact of the place. 

<img width="865" alt="untitled" src="https://cloud.githubusercontent.com/assets/5404004/26776663/abcd2202-4a0c-11e7-91f3-f8d6e1baf01f.png">

Seems to be updated everywhere except on LHS
<img width="906" alt="untitled" src="https://cloud.githubusercontent.com/assets/5404004/26776879/ae7e7338-4a0d-11e7-8663-bc6f9ae5a5c2.png">

**Comment by sglangevin** [comment]
This is due to nested contacts, which have been removed as per #2635. This will be fixed in version 2.13 and higher of the web app. For now, the facility can be edited manually in Couch to fix the display, you can create a new person in that facility and set them to be the primary contact, or you can delete the place and re-create it. Closing as this has already been fixed and will be released soon.
