### ISSUE TITLE
Split the form configuration page into JSON and XML tabs

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3559]
The current admin page is quite cluttered with both lists and both upload forms on one single page.

Scheduling because it's the result of a code review. In order to get #3433 in to 2.12.0 quickly I'm splitting the UI improvements off for 2.13.0.

**Comment by garethbowen** [comment]
Code review please @alxndrsn

**Comment by alxndrsn** [comment]
@garethbowen this was approved and merged; can it be closed?

**Comment by garethbowen** [comment]
Not quite. I need to update the documentation, and then I'll close this.

**Comment by garethbowen** [comment]
Wrong issue... Yes this can be closed now. Sorry for the confusion.

**Comment by ngaruko** [comment]
I assume this if the page `#/configuration/forms/json` (and the xml page).  The `Go to Medic Reporter` button/link has got a different styling/class (`btn-link`) from the other 2 buttons (`btn-primary`) on the page. Is this intentional/conventional or?
![image](https://user-images.githubusercontent.com/6979995/28544014-e43380b6-7115-11e7-96b0-6618dc38fac8.png)

**Comment by garethbowen** [comment]
@bede It's intentional. It's a link to another app, the other two are buttons that do something.
