### ISSUE TITLE
Validate sentinel transition configs at transition load time

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3585]
If there's a problem in the config of a sentinel transition (typo, missing field, ...), we won't know until the transition actually tries to run on a doc. 

Add a `onLoad` func in transition api, for transitions to validate their config when they're loaded by `transitions/indox.js`.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
@garethbowen I'm happy with the code as-is, though there are some discussions starters on the PR.

Could you please also:
 - Document the changes to the API where appropriate (either in the sentinel readme or in medic-docs, I forget where that documentation is right now)
 - Create a medic-webapp PR so that the e2e / int tests run (this wasn't a checkbox in your PR, I thought Milan added it?)

**Comment by sglangevin** [comment]
@henokgetachew this one also goes with the other two. Can you please AT this one as well?
