### ISSUE TITLE
Make travis use CouchDB 1.6 again

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3590]
Travis dropped support for CouchDB1.6 natively and broke our builds. We hacked around it to only test on 2.0.

We should add support back for 1.6 before we release 2.13.0

**Comment by SCdF** [comment]
@garethbowen  https://github.com/medic/medic-webapp/pull/3591

**Comment by garethbowen** [comment]
@SCdF I found the issue I created: #3572

The reason we couldn't find it is because it's closed. The reason it's closed is the commit message had the word "fixed" at the end, and the issue number in the description, so GH auto closed it for me. Thanks GH!

It looks like it just works so I guess they fixed the underlying issue.

There's one change required but once you've fixed that, merge away.

**Comment by SCdF** [comment]
Merged.
