### ISSUE TITLE
Exporting reports filtered by place results in an empty xml

### ISSUE THREAD

**Issue by eljhkrr** [medic/medic-webapp#3593]

**Comment by SCdF** [comment]
Hi @eljhkrr this sounds like a bug.

Can you please provide more information?

For example:
 - The server / partner it is relevant to
 - Steps to reproduce (and whether or not it was reproducible)
 - What you would expect to happen
 - What actually happened

Any other relevant information, such as the software version, browser version etc.

**Comment by eljhkrr** [comment]
@SCdF This was observed on the kilifikids-kaiti instance.

To reproduce the bug:
Filter reports by place, confirm there are reports for the particular place and then export them. Only header fields will be present on the exported xml without any data rows. Exports with type, date & status filters are working as expected.

**Comment by SCdF** [comment]
Thanks for filling in more details @eljhkrr. I looked up the software version for you: it's 2.11.3.

*(You can find out which version of the software you're running on the about page)*

I'd be also interested in the browser you're using, it's version, and the operating system you're running on.

**Comment by sglangevin** [comment]
@SCdF there are two parts to this:

First, exporting has moved and changed a lot from 0.4 to 2.x. It's now on the Reports tab and we don't have different options for which format the file is downloaded in. We've had requests from some partners that we bring back the csv and xls options for downloads. This is something I'd like to include in 2.14 so it's not prioritized for now but will be soon.

The second piece of this is a bug that I haven't had a chance to file yet but that I discovered during recent testing of the export feature. All of the filters are working as expected except for the filter by place. I'm going to update the title of this issue to represent the bug we have in filtering by place and we can open a new issue (to be fixed in the future) for the file type of the export.

**Comment by sglangevin** [comment]
I've updated the title here - @eljhkrr's steps to reproduce should work well as that's how I've recreated the bug on my laptop.

**Comment by garethbowen** [comment]
Two PRs for code review please @estellecomment

**Comment by estellecomment** [comment]
Commented on the commit for api one : https://github.com/medic/medic-api/commit/255a2f612ff306ce4169c0b4b059710cad1e395d

And then good to merge.

**Comment by sglangevin** [comment]
Working well in v2.13.0-beta.2. Moving to ready.
