### ISSUE TITLE
Fix `npm ls` errors

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3628]
In webapp, sentinel, and api we get errors when we `npm ls`. There are two main causes - using version `latest` and using git hashes for dependencies.

I think the error on `latest` is because it's a specific version, not a range, so it quickly gets out of sync with the version in the package-lock.json. Change this to a wide range to solve it.

I think the error on git hashes is somehow it makes it hard for package-lock to guarantee the code although I can't find any documentation to confirm this. These are forks of public libraries that we've had to patch. Publish these packages to npm as `@medic/<package-name>` under our organisation and depend on those instead.

**Comment by SCdF** [comment]
FWIW Node 5.x now supports proper git tagged versions (`"foo": "medic/foo-fork^1.2.2"`). I haven't looked into whether this stops `npm ls` from complaining though.

**Comment by SCdF** [comment]
I've done https://www.npmjs.com/package/@medic/grunt-contrib-watch and https://www.npmjs.com/package/@medic/enketo-core

@alxndrsn with https://www.npmjs.com/package/@medic/enketo-core I just gave it the version that was in the existing package.json. The tag we were attached to had a very different version number, so I'm not sure how you want to version this. Also, none of the tags were in either the medic or medic-2.11.x branch, so again, not sure how best to deal with this one. I'll leave it you.

**Comment by SCdF** [comment]
It was more complicated than I thought, because the package name changes and so all of your imports and other things change.

Api: https://github.com/medic/medic-api/pull/175
Sentinel: https://github.com/medic/medic-sentinel/pull/140

Webapp: https://github.com/medic/medic-webapp/pull/3632
Note also the changes I had to make to our enketo-core fork to make it work: https://github.com/medic/enketo-core/compare/8a372c1...61b093e9ca1cbfc5fc73f546a5e1101a0d2c1563

Current webapp PR still has issues with enketo-core. Not sure what the exact problem is yet.

**Comment by garethbowen** [comment]
I've merged this so master will be green again, however there is one more improvement that would be good to make, as commented in the PR:

> Instead of changing our enketo-core fork to have different sass import paths, consider using the [grunt-sass importer option](https://github.com/sass/node-sass#importer--v200---experimental) to rewrite the paths at compile time.

I'll leave it up to you to decide if it's worth doing this now or not.

Nice work!

**Comment by SCdF** [comment]
I'm OK with this for now. If we come back to having to edit this again then we can work out how this works.
