### ISSUE TITLE
Blacklist outgoing messages to carriers

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3675]
We have a outgoing-deny-list which is configured on site to blacklist certain numbers. This is really useful particularly for blocking replying to a carrier which can sometimes end in an infinite loop of robots replying to each other. Unfortunately sometimes we forget to configure it, or we don't know the number the messages will come from until it's too late.

Work out some way of blocking by default. One way would be to ship with a default outgoing-deny-list with all the carriers we know of so far (eg: "Safaricom"). Another would be to have code which blocks alpha phone numbers (eg: "Safaricom"). Possibly libphonenumber has something we can use here.

**Comment by SCdF** [comment]
I think this is worth looking into, though I have no idea when

**Comment by garethbowen** [comment]
Documentation: https://github.com/medic/medic-docs/blob/master/configuration/app-settings.md#optional-settings

**Comment by ngaruko** [comment]
LTGM
Tested on `gamma.dev` 3.3
By modifying 
```
outgoing_deny_list
outgoing_deny_shorter_than 
outgoing_deny_with_alpha
```
in settings and sending messages from senders who fall in/out of the criteria. Then checked whether the messages were either pending (if correct `from` settings) or `denied` otherwise:
![image](https://user-images.githubusercontent.com/6979995/49630573-65961700-fa21-11e8-8bf8-7561798ee330.png)
