### ISSUE TITLE
Webdriver logs are mostly spam

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3692]
Pages and pages of this, for instance : 
```
12:41:15.310 INFO - Executing: [find elements: By.cssSelector: #messages-tab])
12:41:15.317 INFO - Done: [find elements: By.cssSelector: #messages-tab]
12:41:15.321 INFO - Executing: [find elements: By.cssSelector: #messages-tab])
12:41:15.328 INFO - Done: [find elements: By.cssSelector: #messages-tab]
12:41:15.332 INFO - Executing: [find elements: By.cssSelector: #messages-tab])
12:41:15.339 INFO - Done: [find elements: By.cssSelector: #messages-tab]
```
It's `browser.wait` trying to find an element for X seconds.

Change to higher log-level could help :
https://github.com/SeleniumHQ/selenium/wiki/Logging#log-levels

**Comment by garethbowen** [comment]
We could exclude all webdriver logs but they're being included because occasionally having the browser interaction helps you understand why the test failed. Ideally webdriver/protractor would collect these repetitive log entries into one line, eg: "Executed (152 times): ...", but AFAIK we have little control over this.

**Comment by estellecomment** [comment]
I'll admit this was a bit of a rage-bug. 

The stack traces are really useless as well. You have to peel your eyes finding the one or two relevant lines out of a page of them...

**Comment by garethbowen** [comment]
This has been improved slightly by storing logs in s3. I can't think of a way to improve it further without excluding useful information. Closing.
