### ISSUE TITLE
Every time I click on the People tab, I get a "Not found" snackbar notification on the RHS

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3718]
Steps to reproduce (on v2.12.1):
1. Log in as admin on demo.dev.
2. Click on the People tab.
3. See the "Not found" snackbar on the RHS and the following errors in the console (inbox.js:11 should be inbox.js:12740)

![image](https://user-images.githubusercontent.com/1286381/28639271-7a8175e6-71fc-11e7-9d04-514524e9b46e.png)

**Comment by alxndrsn** [comment]
The code throwing this error is no longer in master: https://github.com/medic/medic-webapp/commit/a8afb859554ab11b90148a25e0cf5cab62bb686d#diff-58b23f7742c19c23a220c743f654f5baL385

It may still require fixing on `2.12.x` branch.

**Comment by alxndrsn** [comment]
Blocked by https://github.com/medic/medic-webapp/issues/3829

**Comment by garethbowen** [comment]
This is because the `admin` user on demo.dev has a `facility_id` that doesn't exist. When the page is loaded we try to select the "home place" and because it doesn't exist we show the snackbar. I believe this is actually the correct behaviour for the given configuration. @sglangevin What do you think?

In `2.13.x` the snackbar is not shown but it's also not obvious when you're trying to view a document that doesn't exist. @alxndrsn Can you please review the linked PR which adds back the snackbar when the contact isn't found?

**Comment by sglangevin** [comment]
Interesting. That was not at all obvious based on the error in the snackbar. Is there a way to show the user a more helpful error?

**Comment by garethbowen** [comment]
Yeah. Currently the same code is executed when you say, navigate to a URL which has an unknown ID, but we can separate the error handling so a different error message is shown. What should it say? I'm tempted to actually not show any error at all, so having a badly configured facility_id is the same as having none at all. What do you think?

**Comment by sglangevin** [comment]
Yeah, I think that makes sense. Let's not show an error then.

**Comment by garethbowen** [comment]
Code review please @alxndrsn 

This is a slight improvement to the previous already merged change so the snackbar is only shown when the user navigates to a missing contact (discussion in comments above).

**Comment by sglangevin** [comment]
LGTM.
