### ISSUE TITLE
multi_report_alerts : add limit of 100 for num_reports_threshold

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3725]

**Comment by estellecomment** [comment]
@alxndrsn can you review?
PRs : 
 - sentinel https://github.com/medic/medic-sentinel/pull/150
 - documentation and bump in webapp : https://github.com/medic/medic-webapp/pull/3737

**Comment by estellecomment** [comment]
Thanks!

**Comment by alxndrsn** [comment]
:+1: although it's still not clear to me what the config tests are doing at https://github.com/medic/medic-sentinel/blob/36cc1c8f6fb67d322185e846d07aa91f9946da15/test/unit/transitions/multi_report_alerts.js#L92-L123

**Comment by estellecomment** [comment]
Testing that running the transition with invalid config will throw. Is there something specific I can make clearer?

**Comment by ngaruko** [comment]
Does this need AT @estellecomment ?

**Comment by estellecomment** [comment]
Try to run with `num_reports_threshold` >= 100, check it doesn't work

**Comment by ngaruko** [comment]
Awaiting #3715 .... Are you able to test this at the same time when #3715 gets done @abbyad

**Comment by sglangevin** [comment]
Assigning to @abbyad for AT.

**Comment by sglangevin** [comment]
@abbyad looks like we missed AT on this one during 2.13.0 testing. Can you confirm whether you saw this working?

**Comment by abbyad** [comment]
I tested `multi_report_alerts` but not with 100 reports. I can AT this by next week.

**Comment by abbyad** [comment]
Still haven't gotten around to testing this yet. Anyone else looking to use this feature should feel free to AT this.

**Comment by garethbowen** [comment]
Let's get this ATed. Scheduling for 3.0.0.

**Comment by abbyad** [comment]
Clearing my assignment so it's free to be picked up!

**Comment by ngaruko** [comment]
If I understand this correctly, the `Threshold In Number Of Reports` here should be less than 100. Are we able to enforce this in the UI here @abbyad  or do we go with the assumption that in most cases this is done in a non-UI fashion?
![image](https://user-images.githubusercontent.com/6979995/38912041-3711cf0c-4327-11e8-911f-29d3d9adf1ff.png)
Also it is not very clear what is expected when this number is greater than 100, ie does the `user/configurer` get an error message to stick to the limit ?

**Comment by garethbowen** [comment]
@ngaruko We don't use the dashboard UI any more. Use medic-configurer because that's what is used in the field.

I've documented the limit [in medic-docs](https://github.com/medic/medic-docs/blob/master/configuration/transitions.md#configuration-1).

sentinel will fail to start and throw a useful message if this threshold is exceeded, so try setting the configuration and then starting sentinel and make sure it works.

**Comment by ngaruko** [comment]
Tested on `local` using `medic-conf` . 
1 . Make sure `multi_reports_alerts` is disabled in `transitions` ( `"multi_report_alerts": true`)
![image](https://user-images.githubusercontent.com/6979995/38966270-8918ce0a-43d5-11e8-92bd-5a97de2cae03.png)
2. Make sure app_settings.json has 
```"multi_report_alerts": [
    {
      "name": "suspected_cholera",
      "is_report_counted": "function(report, latest_report) {  return latest_report.contact.parent.parent._id === report.contact.parent.parent._id; }",
      "num_reports_threshold": 101,
      "message": "{{num_counted_reports}} patients with {{alert_name}} in {{time_window_in_days}} days reported at {{new_reports.0.contact.parent.name}}. New reports from: {{new_reports.0.contact.name}}, {{new_reports.1.contact.name}}, {{new_reports.2.contact.name}}.",
      "recipients": [
        "+123456",
        "new_report.contact.phone",
        "new_report.contact.parent.parent.contact.phone"
      ],
      "time_window_in_days": 7,
      "forms": [
        "C",
        "D"
      ]
    }
  ] ``` 
with `num_reports_threshold` greater than 100

3. Run ` medic-conf --local`
4. Observe errors in `sentinel`:
![image](https://user-images.githubusercontent.com/6979995/38966995-15b1c2b0-43d9-11e8-81ab-6560f4ab13b6.png)

Checked that the settings were otherwise installed correctly in the app:

![image](https://user-images.githubusercontent.com/6979995/38967173-f448f2b4-43d9-11e8-88d3-ff975f4eec83.png)


*LGTM*
