### ISSUE TITLE
Update content row UI for consistency & improved readability

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3731]
Design spec: https://docs.google.com/document/d/13emD5Zhh59qElEfq5VG7oMJWhSWCvmtKUMg8rttgZxI/edit#bookmark=id.v7zvlp14ke9k

By "content row" we mean the items in the lists of messages, reports, tasks and contact across all tabs (including the tasks and reports displayed on a person or place profile), as well as the list of people on a place page and the configurable profile fields (outside of the top profile section). There are also small changes to be made to each type of content row, but those are to be filed in separate tickets. 

Summary of changes across all tabs:
- [x] Default (minimum) row height is now bigger. Suggested size is 70px tall (4.375rem). Row height can expand beyond 70px as needed to accommodate three or more lines of text.
- [x] Rows are separated from each other with a 1px light grey line
- [x] First row of text on the left side of the row is 16px and bold. If there is only one row of text, it should be vertically centered.
- [x] Second row of text on the left side of the row is 16px
- [x] Third row of text on the left side (not always applicable) is 14px
- [x] All of the secondary supporting text on the right side (e.g. the relative day) is 14px. This should be in gray (#6D6E71) unless otherwise noted (e.g. for overdue tasks or unread reports)
- [x] The first line of text on the left and the first line of supporting text on the right (usually the relative day, if applicable) share the same baseline
- [x] In rows without icons, the primary text is located 20px from the left edge
- [x] In rows with icons, the primary text is located 50px from the left edge
- [x] Icons placed in rows are 30 x 30px. They have a 10px buffer on the left and right sides and a 20px buffer on the top and bottom.

Example updated content row mockups (more in the spec linked above):
Tasks:
![image](https://user-images.githubusercontent.com/1286381/28854374-adad6b2a-76eb-11e7-9c04-a40d06c00313.png)

Reports:
![image](https://user-images.githubusercontent.com/1286381/28696317-b2308cf0-72e9-11e7-8363-b7f4c6f4e106.png)

List of People on Place Profile:
![image](https://user-images.githubusercontent.com/1286381/28696680-e605b666-72eb-11e7-8276-c9982cb2d399.png)

**Comment by garethbowen** [comment]
@amandacilek In the spec it says

> Row background color is always white (doesn’t change based on read status)

Currently in desktop mode we change the background colour when an item is selected. It's very useful to have some indication of which row is currently selected when in the two column layout. Should we keep the background colour on selection, indicate selection with some other style, or have no indication at all?

**Comment by amandacilek** [comment]
The different background color for selected and hovered rows remains as-is (no change to our current system).

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
Back to you @garethbowen

**Comment by garethbowen** [comment]
Merged with almost all of your suggested changes made.

**Comment by sglangevin** [comment]
LGTM. @amandacilek do you also want to do a review? Let me know!

**Comment by amandacilek** [comment]
> LGTM. @amandacilek do you also want to do a review? Let me know!

Thanks, I'd welcome the chance to glance through everything. How do I do that?

**Comment by amandacilek** [comment]
Sharon shared a link to alpha.dev with me and I've taken a first pass through the pages. So excited to see this come to life and overall very happy with how things are looking! The text is so much easier to read. 


@sglangevin @garethbowen Here are some notes and suggestions I have:

The LHS has a 1px vertical grey line along the far left edge but not along the far right edge. It should have the 1px grey line on both the left and right sides (in essence, the whole LHS panel has a 1px grey border, just like the RHS cards).

Display of unread in the top tab bar: Any unread messages are called out by a red circle in the top tab bar next to the page icon, but unread reports don’t seem to be showing up there. 
  - We should call out unread reports in the top bar.
  - While we’re at it, should any overdue Tasks be called out there too? So if I have two overdue tasks, it might be helpful if the top bar had a red circle with “2” letting me know there are two items requiring attention on that page.

On the People and Reports pages, the LHS has “No more people” and “No more reports” at the end of the list. We should extend this same treatment to the Messages and Tasks pages as well, so that “No more messages” and “No more tasks” appear after the last content row on the LHS. Throughout, this text should be grey #777777 and 14px in size.

Tasks page: 
  - The date text should be capitalized: “yesterday” >> “Yesterday”. Apologies if this is not a code issue, but bringing it up just in case it is.
  - Looking at the RHS form detail, the title of the form is too close to the top of the card. Suggest a 20 - 30px gap between the top of the card and the title text.

Reports: The treatment of form fields may need to be revisited. The new treatment works great on profiles but here, where the response fields can sometimes be multiple sentences long, there ends up being too much bold text on the page. Will think on alternative solutions and get back to you all on this one.

**Comment by garethbowen** [comment]
> It should have the 1px grey line on both the left and right sides (in essence, the whole LHS panel has a 1px grey border, just like the RHS cards).

Done.

> We should call out unread reports in the top bar.

We do. If it's not working for you please raise an issue for it with specifics about which instance you were using, which browser, which user, etc.

> While we’re at it, should any overdue Tasks be called out there too?

We could do that, but it seems like a waste of effort when the upcoming nav update is removing the bubbles anyway. If you think it's worth doing please raise a feature request issue with specifics.

> We should extend this same treatment to the Messages and Tasks pages as well, so that “No more messages” and “No more tasks” appear after the last content row on the LHS. Throughout, this text should be grey #777777 and 14px in size.

Done.

> The date text should be capitalized: “yesterday” >> “Yesterday”

That's translated so it's configurable.

> Looking at the RHS form detail, the title of the form is too close to the top of the card. Suggest a 20 - 30px gap between the top of the card and the title text.

Done.

> Reports: The treatment of form fields may need to be revisited. The new treatment works great on profiles but here, where the response fields can sometimes be multiple sentences long, there ends up being too much bold text on the page. Will think on alternative solutions and get back to you all on this one.

Yeah I agree, although some fields on Contacts can be multiple sentences long (eg: the "Notes" field) so I'd like the treatment to be consistent on Reports and Contacts (and anywhere else we follow the same pattern). Perhaps consider having the label #777 and the value black normal weight? This retains the emphasis on the value without having to bold the whole thing.

**Comment by garethbowen** [comment]
Back to you @amandacilek and @sglangevin for AT.

**Comment by sglangevin** [comment]
Cool, looks like everything marked "done" is there and looking good. I don't think we need to add a bubble for overdue tasks because those bubbles will be removed in the nav update anyway and it's a feature request. And I agree there is something weird happening with the unread bubble for reports but I'll file a separate bug for that.

As for the bold text, I agree we need a better solution. Though I'd also point out that the mock-ups show the profile card having bold labels and normal weight values while the other cards have normal weight labels and bold values. So perhaps we should be using bold labels and normal weight values for the profile card and for the report detail on the Reports tab.

**Comment by amandacilek** [comment]
> those bubbles will be removed in the nav update anyway

I don't really remember having a conversation about this. Did we discuss as a team and decide to remove them with the new nav update? If it was decided they would be difficult to do with the new design that makes sense. If they aren't difficult to do with the new design we should keep them as I think they do add value.

**Comment by sglangevin** [comment]
I hadn't seen them in any of the mockups so I assumed they were being removed. Sounds like that may have been a bad assumption though. Does it make sense to have bubbles that represent both unread and overdue things?

**Comment by amandacilek** [comment]
> I hadn't seen them in any of the mockups so I assumed they were being removed. Sounds like that may have been a bad assumption though. Does it make sense to have bubbles that represent both unread and overdue things?

They weren't intentionally omitted from the mockups, I just didn't think to add them. If the LOE is not too great let's keep them with the new design.

I like the idea of calling out both unread and overdue items. Overdue tasks are the task page's equivalent of unread. It's a personal opinion and others may have differing opinions. And understood that it's a feature request, so happy to push this for later.

**Comment by garethbowen** [comment]
@amandacilek Awesome! I was so disappointed when I thought they were being dropped. And adding overdue tasks is a good feature. I'll raise an issue now.

**Comment by garethbowen** [comment]
Created as #3943 and scheduled for 2.15.0 (feel free to reschedule it @sglangevin !)

**Comment by amandacilek** [comment]
> As for the bold text, I agree we need a better solution. Though I'd also point out that the mock-ups show the profile card having bold labels and normal weight values while the other cards have normal weight labels and bold values. So perhaps we should be using bold labels and normal weight values for the profile card and for the report detail on the Reports tab.

Yeah, point taken. I've been thinking of the very top profile card as a completely different entity (which I hope it will be one day) but I understand it's all the same code right now. 

I propose that we revert back to form fields having bold titles and regular weight responses. This keeps the row styling consistent throughout the app and solves the aesthetics on the Reports page. The fact that we emphasize the field title instead of the response is fine for profiles I think. Apologies for reverting back on this one.

**Comment by amandacilek** [comment]
One more little thing on the Messages page: can the grey timestamps below the messages be 14px instead of 16px?

**Comment by garethbowen** [comment]
> I propose that we revert back to form fields having bold titles and regular weight responses.

Done.

> can the grey timestamps below the messages be 14px instead of 16px?

Done.

**Comment by garethbowen** [comment]
Back to you @sglangevin

**Comment by sglangevin** [comment]
LGTM.

**Comment by amandacilek** [comment]
Re-opening because I noticed a few spacing issues this morning.

Text should always start 20px from the left. There are a few places where the text is too close to the left and needs to shift a few pixels to the right.
- On a health center profile, the rows under Area need to shift right
- On an area profile, the rows under People need to shift right

![screen shot 2017-10-06 at 10 05 03 am](https://user-images.githubusercontent.com/26235957/31289530-e3728036-aa7d-11e7-9920-ddfeeb9705f1.png)

On a report detail, the rows at the top seem fine but the text under Outgoing messages is too close to the left and need to shift right.

![screen shot 2017-10-06 at 10 10 52 am](https://user-images.githubusercontent.com/26235957/31289729-ab6a6450-aa7e-11e7-98e3-256212e2f045.png)

The same on Enketo forms

![screen shot 2017-10-06 at 10 11 57 am](https://user-images.githubusercontent.com/26235957/31289764-d0f1948c-aa7e-11e7-86cf-178df15f32d3.png)

Also on profile pages, the card filters and the timestamp/status dot don't align on the right. Let's shift the filters to the right so they have the same spacing as the timestamp.

![screen shot 2017-10-06 at 9 33 00 am](https://user-images.githubusercontent.com/26235957/31289860-2d6f3ba6-aa7f-11e7-913e-60c4cf71fd63.png)

One final thing, on Messages, could we please have a slightly greater gap between the message box and the timestamp? Say 10px?

![screen shot 2017-10-06 at 10 16 57 am](https://user-images.githubusercontent.com/26235957/31289944-8f8f46c8-aa7f-11e7-8b03-96a2cea01bc4.png)

**Comment by garethbowen** [comment]
I've done all the above suggestions except for the enketo forms change as that was starting down a rabbit hole. We can (and should) revisit this when we do the complete forms design update.

**Comment by amandacilek** [comment]
Great! Most of the above were fixed, but the header text on Messages still needs to be adjusted (pushed to the right for a 20px gap):

![screen shot 2017-10-09 at 10 28 20 am](https://user-images.githubusercontent.com/26235957/31350617-a9c60f22-acdc-11e7-8ff3-1e1270c6d5b0.png)

Also, it now looks like there is new additional space on rows with icons. Apologies if I was not clear with my previous recommendations. The rows with icons were good - this extra space on icon rows should be removed so that the icons are once again centered in the space.

In an attempt to clarify:
In rows without icons, the text should be 20px from the left.
In rows with icons, the text should be 50px from the left. Icons are 30 x 30, and there is a 10px buffer on the left and right.

![screen shot 2017-10-09 at 10 33 48 am](https://user-images.githubusercontent.com/26235957/31350856-8ab37e34-acdd-11e7-87d1-8fd98ebd1c99.png)

**Comment by garethbowen** [comment]
One more time!

**Comment by sglangevin** [comment]
Looks good! Moving to ready.
