### ISSUE TITLE
Reports content row improvements

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3735]
Builds on the changes listed in #3731. [Full design spec](https://docs.google.com/document/d/13emD5Zhh59qElEfq5VG7oMJWhSWCvmtKUMg8rttgZxI/edit?ts=5980ade8#bookmark=id.v7zvlp14ke9k).

Each report content row should have 1-3 lines:
- First line: name of person or place that the report is about (Exception: if you are looking at the list of reports on a person's profile page, do not include the name of the person because it is redundant).
- Second line: name of the form (note: this is the only line that will appear on the list of reports on a person's profile, it should be in bold on the person's profile since it is the first and only line of text)
- Third line (optional): breadcrumbs (same breadcrumbs that we have, just moved to the third line). Breadcrumbs can wrap to a second line, but should truncate after the second line. Breadcrumbs should **only** appear when looking at the list of reports on the Reports tab. No breadcrumbs on contact profile pages.

Other changes:
- [x] Unread reports should have a horizontal blue bar at the top right of the content row (see mockup 2 below). Line is 50px long, 4px thick, and color is #007DC7. This only applies to the Reports tab, not to profile pages.
- [x] Unread reports should have a bold, blue relative date/time on the right (see mockup 2 below). Color is #007DC7 and it's 14px and bold. This only applies to the Reports tab, not to profile pages.

Notes:
- Reports on contact profiles look identical to read reports on the Reports tab
- Reports on a person's profile should have only the name of the form on the left side (16px bold since it's the first line of text). Reports on a family/household profile should have two lines (name of person or place and name of form). Reports on the Reports tab have all 3 lines listed above.

### 1 - Report on reports tab (read):
![image](https://user-images.githubusercontent.com/1286381/28855029-2dfb67e8-76ef-11e7-9a65-29902c12fc00.png)

### 2 - Report on reports tab (unread):
![image](https://user-images.githubusercontent.com/1286381/28855058-558c40e8-76ef-11e7-8eb2-8fdf1d78ae0f.png)

### 3 - Report on family profile:
![image](https://user-images.githubusercontent.com/1286381/28855130-bef5946c-76ef-11e7-8774-982732df2b5b.png)

### 4 - Report on person profile:
![image](https://user-images.githubusercontent.com/1286381/28887621-a760b862-7772-11e7-9d30-7e96b4187709.png)

**Comment by sglangevin** [comment]
Mostly there! A few things to fix + a few comments:

- On the person's profile page, the title of the report should be centered vertically. Right now it is at the top of the content row.
- On the Reports tab, the breadcrumbs should wrap to a second line. I realize this is not illustrated in the mock-ups, that was an oversight.
- On small screens (<400 px wide), the text on the right side of the content row (relative date) and the green dot are too close to the right edge of the screen. Can we make it consistent with how it looks on wider screens?
![image](https://user-images.githubusercontent.com/1286381/31090452-7d7eddf2-a75c-11e7-9fdd-6e536fb7e96b.png)
- I noticed that the icons are vertically centered on the Reports tab while in the mock-ups they are lined up with the first two lines of text (form title and person's name). I'm ok with vertically centered, what do you think @amandacilek?
- On the Reports tab, we're still showing the name of the person who submitted the report. According to the spec, we should be showing the name of the person whom the report is about. Would it be possible to make that configurable? It's ok if it's outside the scope of this issue, but we've had quite a few requests to see the patient's name listed on the reports tab.

**Comment by sglangevin** [comment]
Back to you @garethbowen

**Comment by sglangevin** [comment]
Realized that #3731 says that the first row of text should share the same baseline with the relative date, which contradicts vertically centering the first row of text, as seen in the screenshots. @amandacilek can you let us know what your intention was? This applies specifically to cases where a content row with a relative date (task, report) has only one row of text on the left. This primarily happens on a person's profile.

**Comment by amandacilek** [comment]
> Realized that #3731 says that the first row of text should share the same baseline with the relative date, which contradicts vertically centering the first row of text, as seen in the screenshots. @amandacilek can you let us know what your intention was? This applies specifically to cases where a content row with a relative date (task, report) has only one row of text on the left. This primarily happens on a person's profile.

Hey @sglangevin , Gareth and I had a convo about this a while ago on Slack.

My original preference was that the first line of text on the left should share the same baseline with the date _in all cases where we have two or more lines of text_, and be centered in the row when we only have one line of text. I'd hoped we could make two separate distinct designs.

While talking with Gareth it was made clear that I needed to choose one rule to apply across the board instead of different rules depending on text length. I said that if I have to choose between vertically centering that one line of text (essentially only applicable on profiles), or keeping the first line of text and date on the same baseline on all rows across the whole app, I choose the latter.

So you're right that the original spec said one line titles should be centered vertically, but I had to compromise on that.

**Comment by amandacilek** [comment]
> I noticed that the icons are vertically centered on the Reports tab while in the mock-ups they are lined up with the first two lines of text (form title and person's name). I'm ok with vertically centered, what do you think @amandacilek?

I would prefer that the icon stay towards the top of the row next to the bold "title" text as seen in my mockups. I think the proximity makes the icons more useful by because it makes the association clearer (the "title" is essentially the label for the icon). Also, the consistent location (always at the top) is more predictable and makes it easier to scan down a long list.

If that is difficult or causes us other unforeseen problems it's not the end of the world if the icons float vertically, but my preference is to have it the way I've mocked it up.

**Comment by garethbowen** [comment]
> I noticed that the icons are vertically centered on the Reports tab while in the mock-ups they are lined up with the first two lines of text (form title and person's name).

I missed that! Fixed.

> On the Reports tab, we're still showing the name of the person who submitted the report. According to the spec, we should be showing the name of the person whom the report is about. Would it be possible to make that configurable?

Yeah I missed that too. Could you please raise an issue for it as it'll take a little thought. Depending on the use case you might actually want both, eg: "from Sarah, about Jim".

> On small screens (<400 px wide), the text on the right side of the content row (relative date) and the green dot are too close to the right edge of the screen. Can we make it consistent with how it looks on wider screens?

I can't reproduce this - it's possible it's been fixed in subsequent commits. Can you check again and give a bit more detail if it's still happening? This is what it looks like for me...

![bubble-buffer](https://user-images.githubusercontent.com/2064938/31157779-d16b9f2c-a919-11e7-8777-a400a867cb09.png)

> On the Reports tab, the breadcrumbs should wrap to a second line. I realize this is not illustrated in the mock-ups, that was an oversight.

The spec shows the breadcrumbs _not_ wrapping:

![wrapping-district](https://user-images.githubusercontent.com/2064938/31157832-288a229c-a91a-11e7-86bf-96b4949a1b1f.png)

Is this the breadcrumbs you're talking about?

**Comment by garethbowen** [comment]
Back to you @sglangevin

**Comment by sglangevin** [comment]
@amandacilek can you comment on the breadcrumbs question? The spec says they should wrap to a second line but the mockups show them _not_ wrapping. Which did you want?

Everything else here is looking good to me. I'll raise another issue for changing the name on the Reports tab LHS.

**Comment by amandacilek** [comment]
The breadcrumbs should wrap. In my initial mockups they didn't, Estelle provided feedback that they they should, we all agreed, but I never updated this in the mockups because it would be tedious to do, as it involves changing the height and spacing of the rows throughout.

**Comment by garethbowen** [comment]
> The breadcrumbs should wrap.

Thanks @amandacilek . What about the first two lines of text? Should they wrap or have ellipsis? eg:

![rapper](https://user-images.githubusercontent.com/2064938/31197034-47373b0c-a9ac-11e7-80c6-3b6d27cca3c9.png)

vs

![no-rapper](https://user-images.githubusercontent.com/2064938/31197036-4a741d58-a9ac-11e7-827b-ee63273df5c0.png)

**Comment by amandacilek** [comment]
> What about the first two lines of text? Should they wrap or have ellipsis?

Hm, this wasn't a part of the discussion with Estelle. I'm inclined to say we still truncate the first two lines. That maintains consistency with styling on rows throughout the app and helps us somewhat limit the space each of these reports rows takes up on mobile.

**Comment by garethbowen** [comment]
I'd say that the content in the first two lines is more important than the third, so we shouldn't truncate any of it. In practice I think it's unlikely these lines will get long enough for it to be an issue, but if you have, say, two people with similar names it's fairly useful to see which one the report is about. The worst case scenario is say on the contacts tab if you have two rows for two people that look identical and you have to select the person to find out which is which.

**Comment by sglangevin** [comment]
We're generally recommending that people try to keep the form title (second line) short enough that it can be viewed in the various places where we see it in the app. However, if the first line is going to be the name of the person or family that the report is about, it could get long, especially if it's the name of the family. I'm somewhat inclined to say that we should wrap at least the first and third lines and if we're doing 2/3 we should probably wrap all of them.

I agree with Gareth that in practice, it's unlikely that these lines will be so long that it will cause issues, but we can always revisit this if it does.

**Comment by amandacilek** [comment]
I'm willing to give way on this for reports since it's mostly viewed on desktop anyway. I'm not yet ready to wrap text everywhere in our app - that should be a separate conversation. We have to balance the utility of reading the full text with the utility of being able to see and scan multiple rows at once on a small screen.

**Comment by garethbowen** [comment]
Currently the code that generates every content row is the same to enforce consistency between the rows. While I can make specific exceptions for things like word wrapping vs ellipsis truncation I have to be clear about which pages the exception should apply to. Please let me know which of the following lines should be truncated (currently they all are).

- Messages tab LHS line 1 (sender)
- Messages tab LHS line 2 (most recent message content)
- Messages tab LHS line 3 (lineage)
- Tasks tab LHS line 1 (patient)
- Tasks tab LHS line 2 (title)
- Tasks tab LHS line 3 (priority label)
- Reports tab LHS line 1 (sender/patient)
- Reports tab LHS line 2 (form)
- Reports tab LHS line 3 (lineage)
- Contacts tab LHS line 1 (name)
- Contacts tab LHS line 2 (primary contact)
- Contacts tab RHS children line 1 (child name)
- Contacts tab RHS children line 2 (primary contact) 
- Contacts tab RHS tasks line 1 (patient)
- Contacts tab RHS tasks line 2 (title)
- Contacts tab RHS tasks line 3 (priority label)
- Contacts tab RHS reports line 1 (patient/subject)
- Contacts tab RHS reports line 2 (form)

I think that's all of them...

**Comment by amandacilek** [comment]
I think what we're saying is truncation everywhere except for the Reports page for now.

So wrapping these three only:
Reports tab LHS line 1 (sender/patient)
Reports tab LHS line 2 (form)
Reports tab LHS line 3 (lineage)

We can revisit the broader question of truncation vs. wrapping throughout the app at a later date.

**Comment by garethbowen** [comment]
Done.

**Comment by amandacilek** [comment]
![screenshot_2017-10-04-15-29-31](https://user-images.githubusercontent.com/26235957/31202927-97cefbec-a919-11e7-836b-429f53f9b3aa.png)

Curious here... it looks like the date stamp on the right is forcing the name on the left to wrap? Is that how it's always been? Seems like the name should take preference. Or we should just even it out so that they each get half of the available width?

Also not sure if this is just a config thing but I'm not used to date stamps being so complex and long. Do we need the "Tue, Oct 3rd 2017" bit? I never knew they could get this long. Maybe in this case the date should be able to wrap?

**Comment by garethbowen** [comment]
I'm fairly sure the reports RHS header hasn't changed recently but you could compare with an older installation (maybe LG?) to be sure.

Date formats are configurable but I think this is the default.

Maybe put together a design and raise an issue scheduled for 3.1?

**Comment by sglangevin** [comment]
Here's a screenshot from beta.dev (it's on 2.13.0-beta.22 which become 2.13.0 final). Looks like the date format is slightly different. I think that, combined with the increase in font size, has caused what Amanda is describing. I agree that the date is too long here but also agree that we need a design to fix it. Perhaps we could consider scheduling it a bit sooner than 3.1 if it's a quick fix?

@amandacilek can you come up with a suggestion and then we can file an issue?

**Comment by amandacilek** [comment]
Thanks, yeah I never really noticed it until now.

> @amandacilek can you come up with a suggestion and then we can file an issue?

Ok, will do.

**Comment by sglangevin** [comment]
LGTM.
