### ISSUE TITLE
multi_report_alerts : latest_report is not going through is_report_counted function

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3793]
All reports should be tested by is_report_counted function, including the latest one that triggered the transition.

**Comment by SCdF** [comment]
Back to you @estellecomment

**Comment by estellecomment** [comment]
pong @SCdF

**Comment by SCdF** [comment]
Approved, back to you to merge / cp into 2.13

**Comment by garethbowen** [comment]
Merged and backported on your behalf...

**Comment by sglangevin** [comment]
@abbyad was this AT-ed as part of #3416 / #3715? If so, let's move this one to ready.

**Comment by abbyad** [comment]
Not specifically, but can retest

**Comment by sglangevin** [comment]
Assigning to @abbyad for AT.

**Comment by abbyad** [comment]
Testing in 2.13.0-beta.11 I was still seeing an error like this for each report: 
`2017-09-06T21:05:31.490Z - error: error: Could not eval "is_report_counted" function for (report=82c1c868215daa278f45209ab7028505, latestReport=82c1c868215daa278f45209ab7028505). Report will not be counted. Error: Cannot read property 'parent' of undefined`

It appears then that the latest report was still not being counted because this transition was being run before the parent was added.

This latest error is resolved by changing the `is_report_counted` rule from 
`return latestReport.contact.parent.parent._id === report.contact.parent.parent._id;`

to
`return latestReport.contact && latestReport.contact.parent && latestReport.contact.parent.parent && latestReport.contact.parent.parent._id === report.contact.parent.parent._id;`

Given that the latest report is now counted, moving to Ready.
