### ISSUE TITLE
Clearing group in one schedule will mess with other schedules

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3824]
TLDR : [this test](https://github.com/medic/medic-sentinel/pull/163/commits/bca9411c64e3c87a3284b5f314079a11b8c3dae6#diff-6d5b1490870b81f005205db1cc381801R418) fails on lines 487, 489 and 490

When specifying the config for `accept_patient_reports` with multiple types (e.g. `type: 'foo, bar'`), the multiple types are messing with each other when clearing schedules. 

Once you've started clearing the group from schedule `foo`, the groups from schedule `bar` are treated like subsequent groups of the same schedule, instead of being independent.

**Comment by estellecomment** [comment]
@mandric can you code review? PR : https://github.com/medic/medic-sentinel/pull/163

**Comment by garethbowen** [comment]
@estellecomment Should this be closed or are you still working on it?

**Comment by sglangevin** [comment]
@abbyad: AT please.

**Comment by abbyad** [comment]
@estellecomment the broken tests are no longer visible via the link in the OP.

@ngaruko I think this is a good one for you to AT and see how the clearing of schedules works.

**Comment by estellecomment** [comment]
The test is now committed here : https://github.com/medic/medic-sentinel/commit/26baba0dfd7074582abac66bf1c015b17f344e0c#diff-6d5b1490870b81f005205db1cc381801R410

**Comment by SCdF** [comment]
I'm not sure the code here is correct.

Specifically, the code in `findToClear` appears to be saying, when accepting a patient report
 - If there is no `silence_for` configured for that report type, clear all scheduled tasks of the configured types for all registrations for this patient
 - If there a `silence_for` duration, for each registration against this patient, **find the first task that is within this range, and clear it and all subsequent tasks in that group**.

This is may be correct in our default configuration, but I can see some potential bugs in it:
 - It's dependent on tasks being ordered by date inside the group
 - It's dependent on groups being ordered by date inside the list of scheduled tasks
 - Groups cannot overlap
 - Only the first group that is covered by the silence_for duration will be silenced.

@abbyad do you think these edge things matter? I'm not too familiar with how we use groups or what they're for.

**Comment by SCdF** [comment]
On further reflection, I'm not even sure it does what it's comment says it does:

```
// If we have a silence_until value, and at least one msg of the group falls within
// the silence window, then clear the entire group. But not subsequent groups.
```

Here is a link to the code, on a branch where I've done a minor refactor to make it a bit easier to read (IMO): https://github.com/medic/medic-sentinel/blob/3857_fix_refactor/transitions/accept_patient_reports.js#L17-L57

AFAICT that code won't clear the entire group, it will just clear subsequent tasks in that group (and no other groups, despite any validity), as I noted above.

@abbyad , are you able to share any insights as to how this should work? Why does having a `silent_for` duration change the logic surrounding groups, and what should that logic be?

**Comment by SCdF** [comment]
So based on the comments in the code, I have refactored it to say what I think it's trying to say. This very well could be the wrong interpretation, but I figured while I was there I might as well.

```js
const getScheduledTasksByType = (doc, type) => {
  const types = typeof type === 'string' ? [type] : type;

  const scheduled_tasks = doc && doc.scheduled_tasks;
  if (!scheduled_tasks || !scheduled_tasks.length) {
    return [];
  }

  return scheduled_tasks.filter(task => types.includes(task.type));
};


const findToClear = (registration, reported_date, config) => {
    const reportedDateMoment = moment(reported_date);
    const taskTypes = config.silence_type.split(',').map(type => type.trim());
    let silence_until;
    if (config.silence_for) {
        silence_until = reportedDateMoment.clone();
        silence_until.add(date.getDuration(config.silence_for));
    }

    const shouldBeCleared = msgTask => {
        const due = moment(msgTask.due);

        return msgTask.state === 'scheduled' &&
            due >= reportedDateMoment &&
            (!silence_until || due <= silence_until);
    };

    const tasksUnderReview = utils.getScheduledTasksByType(registration, taskTypes);
    let tasksToClear = [];

    // Definitely clear all tasks that should be cleared
    tasksToClear = tasksUnderReview.filter(shouldBeCleared);

    // Additionally, if we're clearing by range, clear all tasks that are in
    // a group with a task that should be cleared
    if (silence_until) {
        const groupTypeCombosToClear = Object.keys(_.groupBy(tasksToClear, ({group, type}) => [group, type]));
        // Reassign, we're going to get ourselves again anyway
        tasksToClear = tasksUnderReview.filter(({group, type}) => groupTypeCombosToClear.includes([group, type]));
    }

    return tasksToClear;
};
```

Main things to note is the interaction with `tasksToClear`, which is what we ultimately return. The rest is mostly untouched. 

@abbyad when you're back let's go through this, work out what functionality we want here and how to make sure we've implemented it right.

**Comment by abbyad** [comment]
Sure thing, let's talk about this in more detail!

In the meantime, and without getting into the code right now, my understanding of this feature is as follows:

**A patient report will clear _all_ messages that belong to a schedule listed in `silence_type` if:**
- **the `silence_for` field or value is absent**

**OR**
- **a message of the same group was scheduled to be sent in the `silence_for` (eg "7 days") after the submission of the patient report.**

Given this I would expect that multiple groups could overlap and be cleared simultaneously. Also, the `silence_for` duration should be set accordingly, along with the message timing of the different groups. In cases where different groups would need different `silence_for` values, the groups should be put in different schedules. For example, if you want a Visit form to prevent visit reminders to go out for the next month, but not clear delivery notifications within that period, then you should split the visit and delivery reminders into two separate schedules.

This seems to be reflected in the documentation in [app_settings](https://github.com/medic/medic-webapp/blob/54748a81e6c04b22d5c912c62936c6333dc2fe1d/kanso.json#L684-L693
), although worth revising since it seems to have already caused confusion: https://github.com/medic/medic-webapp/blob/54748a81e6c04b22d5c912c62936c6333dc2fe1d/kanso.json#L684-L693

**Comment by SCdF** [comment]
Interesting!

This sounds like it may make the code even simpler than my simplification, because at least for the first scenario (with no silence_for) it sounds like you don't care about the task due date at all? Just any task that is scheduled should be cleared.

I'm going to write some tests etc to lock this in, but out of interest, what should happen if you're *inside* a group (at least one of the groups messages has been sent in the past, and there is at least one in the future to come), but your `silence_for` isn't large enough to hit the next entry? The current code would ignore the group, but I'm thinking perhaps it shouldn't?

**Comment by SCdF** [comment]
For AT: this is similar and related to https://github.com/medic/medic-webapp/issues/3857 and can be dealt with simultaneously.
