### ISSUE TITLE
Make it possible to see `clinic` places in the places filter on the Reports tab

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3902]
Reported in https://github.com/medic/medic-projects/issues/1318 (check there for helpful screenshots) and https://github.com/medic/medic-projects/issues/2516. Also requested by Standard partners.

`clinic` places were removed from the places filter when we introduced family registration because it caused performance issues on the reports page. Now that we have SMS projects using v2.x, they need to be able to filter reports by CHW area, which is the same `clinic` level.

We should make this configurable by project, with the default being `clinic` places are hidden from the filter. That way projects that need to see the `clinic` places can then enable seeing them via config.

**Comment by SCdF** [comment]
Over to you for a code review @alxndrsn

**Comment by sglangevin** [comment]
@SCdF this works well for admin but as a restricted user, I'm still not seeing the drop-down to filter by place on the Reports tab. If I'm logged in at the `health_center` level, shouldn't I see the filter by place drop-down with a list of `clinic` places?

**Comment by SCdF** [comment]
So the proposal sort of works, but it looks like this on alpha.dev:
![image](https://user-images.githubusercontent.com/583851/32435884-369dcb98-c2da-11e7-93cd-c523aab08d73.png)

This is because there are orphaned clinics. Whether or not this happens on real instances remains to be seen. However, it's probably useful to surface these honestly, so I think we're going to keep this in.

Talked through this with @garethbowen. 

I'm going to change this to:
 - In determining which places to return, if the top level item is a stub[1] *and* there is only one child, then hoist that child up as the top level item. Repeat until this is not true. For CHWs this will remove all of the top-level stuff they don't have access to, and return their one clinic.
 - In displaying the places dropdown, only show it if there are more than one (instead of more than zero, as it is currently) nodes in the places tree (ie if they have more than one possible selection).
 - When displaying a stub places (ie no display nam), for admins show `[deleted]`, and for restricted users show `[unavailable]`.

[1] Stub means that you cannot retrieve a document with this id. If you're an admin it's been deleted, if you're restricted it's either been deleted or you just don't have access.

**Comment by SCdF** [comment]
Code review please @garethbowen

**Comment by garethbowen** [comment]
Back to you!

**Comment by SCdF** [comment]
Merged
