### ISSUE TITLE
Current password is not required to set a new password

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3910]
It is risky to not prompt the user for the current password before they are able to update it. I mean, anyone could jump to my pc or pick up my phone when I am logged in, change the password and I will be  locked out.
![image](https://user-images.githubusercontent.com/6979995/30407579-09edefee-994d-11e7-984f-a34c84b3dc92.png)

Steps to reproduce:

1. login as user
2. User settings
3. Update password

**Comment by abbyad** [comment]
I can see why it would be good to require the current password to set a new one, but I would perhaps be more concerned by someone getting onto your device and accessing data _without changing passwords_ because then you wouldn't know you were compromised.

**Comment by SCdF** [comment]
@abbyad that is covered by the pin code proposal: https://github.com/medic/medic-webapp/issues/3237

**Comment by garethbowen** [comment]
Scheduling for 2.15.0

**Comment by alxndrsn** [comment]
Can someone confirm what is the _desired_ beahviour here?  My assumption is that we would like:
1. a _confirm current password_ input to appear above the current input boxes, and
2. change the label of _Password_ to _New password_, and
3. change the label of _Confirm password_ to _Confirm new password_

However, I imagine that we might want to make a generic "confirm this action with your password" workflow and e.g. an extra page or modal dialog which asks for the current password - either on submit of this dialog, or before allowing the user to see it - to either elevate the user to a higher level of permissions for a set amount of time, or just make this workflow clearer.

Also, do we want the current-password-check to be enforced by API _as part of the change password action_, or would it be sufficient to perform the check as a separate action (with the obvious caveats about perceived vs actual security gains)?

**Comment by SCdF** [comment]
@alxndrsn that is an interesting different direction I hadn't considered.

What I'm doing at the moment is working on essentially your number-pointed assumption above, as well as changing the in-app code so that it goes through api instead of directly to _users. This api stuff will check everything again (eg password strength etc), as well as checking that the current username + the provided old password are legit.

**Comment by garethbowen** [comment]
Depending how this is implemented this could be useful: https://www.npmjs.com/package/couch-hash-pwd

**Comment by SCdF** [comment]
Update: this has somewhat evolved into a reasonably large refactor of some duplicate code what we've had, both in testing and in actual production code.

I've reworked out user mgmt stuff to use the /api/v1/users api that is present in api, instead of us effectively implementing that logic twice (once there, and once in webapp).

Some difference I've been able to work out myself to allow for integration, such as updating the backend api to allow for users to update themselves as long as they are not updating properties that alter their privilege.

I've come across a disparity that I'd like feedback from @garethbowen and @sglangevin about:
 - In the UI, adding a place and a contact is optional when creating a user
 - In the backend API, these are required fields.

To me it makes sense that these are at least _sometimes_ optional, as this user mgmt stuff is used to create "api users", such as the gateway user. However, it's unclear to me if they should be optional in all situations.

Which of the

**Comment by sglangevin** [comment]
@SCdF place and contact should only be required for "restricted to their place" users. I think that equates to regional manager? But I'm not positive. We should have the same requirements via API as we do in the UI for consistency.

**Comment by SCdF** [comment]
Choice, will do. Side note: the E2E tests caught this ❤️

**Comment by SCdF** [comment]
I hope you're interested in a mighty review @garethbowen, see: https://github.com/medic/medic-webapp/pull/4084

**Comment by SCdF** [comment]
OK @garethbowen so I've done the core of the changes you're interested in. We have three contentious points we need to discuss:
 - https://github.com/medic/medic-webapp/pull/4084#discussion_r156792706
 - https://github.com/medic/medic-webapp/pull/4084#discussion_r156921570
 - https://github.com/medic/medic-webapp/pull/4084#discussion_r156929138

We should discuss these and work out next steps for these.

**Comment by SCdF** [comment]
AT:
 - all user document modifications in the front end now go through a new api: marking a user as known, changing language, changing your profile or password, admins creating, modifying or deleting users
 - You should not be able to change your own password (unless you have general permissions to change anyone's password) without providing your current password

NB: actual hard removal of access to the `_users` DB will be dealt with elsewhere

**Comment by ngaruko** [comment]
The `current password` entry doesn't seem to get verified against the real password. In other words, one can insert anything there (including nothing) and go ahead and change the password.
Also, on changing password, the app exits back to login screen.
Tested on a local instance,  Version 2.15.0-alpha.8793

**Comment by alxndrsn** [comment]
> Also, on changing password, the app exits back to login screen.

This is unavoidable with the current auth management.  There's probably room for improvement in the UX.

**Comment by SCdF** [comment]
@ngaruko what users did you test this with?

If you tested with an administrator or someone else who has permission to modify users the backend api this is attached to doesn't need to verify the password. There are some improvements we could consider here:
 - Not showing the current password field if you don't actually need it (ie you have permissions to just change passwords with no knowledge of the original password)
 - Change the backend so that if you provide a current password we always validate it, even if technically you don't need to

**Comment by ngaruko** [comment]
The user was 'Regional manager - restricted to their place'.

**Comment by SCdF** [comment]
This works if the user doesn't have general permission to modify all users. However, in checking this I've noticed that an incorrect current password is (no longer? I swear I fixed this) explained in the UI properly.

So, work to do on this ticket:
 - [ ] Make sure that if you are passing Basic Auth to authenticate we validate it, regardless of whether we technically need to
 - [ ] The error when Basic Auth is wrong is displayed correctly in the front end

**Comment by SCdF** [comment]
Please take a look @garethbowen

**Comment by SCdF** [comment]
merged

**Comment by ngaruko** [comment]
Looks good. However, there is a small UX issue but I think it about the form rather than the feature. So I will raise it separately. Basically, ( and I am not sure if this is a known issue or a non-issue altogether), when filling a form like this, one would expect to press `Enter/Return` (as the `Submit` button looks ‘ready’) and that should submit the form. But nothing happens. Also, when trying to use tabs, the `Cancel` and `Submit` buttons don’t get highlighted (ie they are skipped).
