### ISSUE TITLE
Horticulturalist in-app UI - small suggested fixes

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4006]
Dianna and I looked over the page and had some feedback and questions which we posed to Stefan and Alex.

**Here is the biggest issue we would like to solve on this page:**
It sounds like I can only install one of these listed items at a time. But when we see all these "Upgrade" buttons it seems like we would want to "Upgrade" _everything_, which means clicking _all_ the buttons. I'm thinking for instance of when I go in to the app store on my phone, and see that I have 22 items with "Update" next to them - I want to Update everything in the list so everything is current. 

**Ideas for how this could be made clearer:**
- Put everything in a radio button list so you can only select one at a time, with only one big Upgrade button at the bottom of the page 
- Or, what if we at least change the button text to "Install" instead? Install sounds more like something I would only do once.

**A few other suggestions for this page:**
- Increase the space between the text under the "Releases" section and the next title "Betas" and add a horizontal grey line after the text. Why? Right now the "There are no new releases you can upgrade to" message is the key one on this page but it is getting drowned out by the rest of content. Additional white space and the horiz line matches the rest of the page and is a small way to add a little more distinction. 
![screen shot 2017-11-01 at 9 48 23 am](https://user-images.githubusercontent.com/26235957/32286416-a07ea8aa-beea-11e7-8780-eac491426abd.png)

- Add a label for the middle column describing what the date means
- The red text: Dianna and I were worried the red may be confusing because users have been trained throughout the app to recognize anything red as something that is late (tasks), requires special attention (warnings, high risk etc.), or is performing poorly (targets). An alternative might be changing the color to blue instead, which still stands out on the page but is less bogged down with negative meaning. Alex says the text is red because that is the bootstrap default for code elements. I'm comfortable leaving this decision up to the devs and tech leads as they are most familiar with this page and who will be using it.

**Comment by SCdF** [comment]
> Or, what if we at least change the button text to "Install" instead? Install sounds more like something I would only do once.

Can definitely do this.

It may be worth checking with tech leads / running them through the page. For me at least having a collection of upgrade buttons makes sense to me, because it is a collection of potential versions I could upgrade to. However, that could either be because it makes sense to users of these pages (like me!), or it could be because I'm one of the people who built it ;-)

> Increase the space between the text under the "Releases" section and the next title "Betas" and add a horizontal grey line after the text. 

More spacing makes sense. It's worth noting that the view you're looking at there (with Releases, Betas and Branches) is no what you'd see on production instances. There, you'd only see the Releases section.

> The red text: Dianna and I were worried the red may be confusing because users have been trained throughout the app to recognize anything red as something that is late (tasks), requires special attention (warnings, high risk etc.), or is performing poorly (targets)

We can definitely change this colour. Note though, the people who deal with the above examples and people who use this page will probably not overlap.

**Comment by sglangevin** [comment]
I think the Upgrade buttons make sense. It's a list of different branches of code, so for the users of this page who will see the Branches section, which is essentially only product team members, I think we can leave that as is (unless anyone strongly prefers something else). Most tech leads will see only Releases and sometimes Betas, but only if they are on a dev instance. One downside of changing to "install" is that it's not going to be something you do once - each branch may get new commits, particularly master, so you'll be going back repeatedly to install again. 

What might be helpful, though, would be to always put master at the top of the list of branches because it's the one used most often for testing, or perhaps have an Alphas section so that we can test code after merge more easily. I also think it would be helpful if the "upgrade" button disappeared if you are on the latest version of code for that branch (you can't upgrade to the same thing again).

**Comment by SCdF** [comment]
> What might be helpful, though, would be to always put master at the top of the list of branches because it's the one used most often for testing, or perhaps have an Alphas section so that we can test code after merge more easily

Currently branches are sorted by date, newest first. We could peg master at the top of branches regardless of age. Can you explain what you mean by an alphas section?

> I also think it would be helpful if the "upgrade" button disappeared if you are on the latest version of code for that branch (you can't upgrade to the same thing again).

Yeah this would be nice. I actually partially had this for awhile, but I think we need more metadata to be able to do this accurately.

**Comment by sglangevin** [comment]
I guess an Alphas section wouldn't make sense because we only have 1 master which is our alpha build. I think it would be helpful to pin master at the top of the branches regardless of age since it's frequently used and usually very close to the top anyway.

**Comment by SCdF** [comment]
Cool. So, so far then:
 - Rename Upgrade to Install
 - Add noted spacing
 - Remove red colouring
 - Pin master to top of branches

**Comment by garethbowen** [comment]
Merged. Good job.

**Comment by ngaruko** [comment]
LGTM. But, not sure if this is relevant since we don't expect horti to be used by mobile users, columns overlap on small screens. Like so:
![image](https://user-images.githubusercontent.com/6979995/35709790-06c0a57e-0819-11e8-8f97-8eef03abaeed.png)
Does this matter @amandacilek ?

**Comment by sglangevin** [comment]
Configuration is not used on mobile.

**Comment by ngaruko** [comment]
LGTM
