### ISSUE TITLE
Strange red bar at the bottom of the page in Enketo forms

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4012]
Seen on Y4, Android app v0.1.157, webapp v2.14.0-beta.2. For some reason, a red bar has appeared at the bottom of the page on Enketo forms. I'm only seeing this on Android, not in Chrome.
![screenshot_2017-11-04-02-59-15](https://user-images.githubusercontent.com/1286381/32396389-3e742068-c0a2-11e7-96f8-2fe53e81aafb.png)

**Comment by alxndrsn** [comment]
Looks like the `margin-bottom` on `.material .card` and `.item-content > div`.

**Comment by garethbowen** [comment]
Back to you @alxndrsn

**Comment by sglangevin** [comment]
I'm still seeing the red bar on Tecno Y4 in Chrome 30. I tested on beta.dev using v0.1.157 of the Android app.

**Comment by garethbowen** [comment]
I can reproduce it with my Tecno. This red border [was added](https://github.com/medic/medic-android/commit/383b056c64724e637ee91f9f6a6e059eb62dcf78#diff-5d9f7a03880b908771de31e18b9f17b9) to warn you when pointing the dev app at a production server. It used to show right around the app but perhaps us removing some padding means the app now overlays the red border.

1. This is probably not a blocker as only people using the unbranded app (ie: us) will see this.
2. Is there a better way to indicate this that won't be hidden by the app itself?
3. ... or can we just remove it altogether?

**Comment by garethbowen** [comment]
@alxndrsn I've reverted the CSS change that got merged and backported because it didn't seem to fix the issue and it caused a separate issue #4034

Let's talk about this when we're both online.

**Comment by alxndrsn** [comment]
Confirmed on `0.1.157` (built locally).

**Comment by alxndrsn** [comment]
Relevant change at https://github.com/medic/medic-webapp/commit/397881d94995c9cc78d419cb0905d4654e19416b#diff-e819fc7a203149c82d44fe6e9d25b808L654

**Comment by alxndrsn** [comment]
> This red border was added to warn you when pointing the dev app at a production server. It used to show right around the app but perhaps us removing some padding means the app now overlays the red border.

I don't agree that it's the same red border.

**Comment by alxndrsn** [comment]
Cannot recreate on `medic-android` version `0.4.0`.

**Comment by garethbowen** [comment]
@alxndrsn In 0.4.0 do you see the red border right around the app or not at all? If you don't see it at all do you think we should fix it so it works, or remove it altogether?

**Comment by alxndrsn** [comment]
The red border is working fine AFAIK.  The problem in `0.1.157` is a bug in the Android standard `WebView` on Y4 (a very old version), which somehow makes the margin of a div which is very low down the DOM _completely transparent_, so that you see the android `View` _behind the `WebView`_.  This is despite other DOM elements behind that div having solid background colours.

We could release a patch for 0.1.157 to make sure that the background colour is something less alarming than red[1], or remove the offending margin from CSS, but to me the correct fix is to update the mobile app to use CrossWalk (i.e. upgrade to `medic-android` `v0.4.0`) instead of releasing specific patches for old versions of the android app or tweaking CSS to handle a problem which has already been fixed in the correct place.

[1]: this has already been patched on `medic-android` `master`

**Comment by garethbowen** [comment]
@sglangevin Can we leave this as a known issue? It doesn't break the app, and the workaround is to update your app.

**Comment by sglangevin** [comment]
Yep, let's leave this one as well. Closing.
