### ISSUE TITLE
New people tab icons have names that are in use by some projects

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4037]
After upgrading a few instances to 2.14.0-beta.x, I saw that some instances are using icons with matching names to the names being used for the new people tab icons, particularly `clinic` and `person`. This can be corrected manually, but it would be safer to rename these hierarchy icons to something that is not already in use by projects. @garethbowen has suggested `medic.clinic`, `medic.health_center`, etc. and I think that would work well. It should also ensure that the new icons will appear upon upgrade without any additional manual tweaks.

**Comment by garethbowen** [comment]
Code review please @SCdF 

This will need to be backported to `2.14.x` but because of the api code it'll be a bit messy so feel free to leave it to me to merge and backport.

Anyone who has already upgraded to the 2.14 alpha or beta will need to manually fix up their icons or manually re-run the migration.

**Comment by SCdF** [comment]
Back to you big G, I'll leave you to do the merging

**Comment by garethbowen** [comment]
Fixed and backported to `2.14.x`.

**Comment by sglangevin** [comment]
Fixed manually on beta.dev and working well. Still need to test that this works out of the box on upgrade.

**Comment by sglangevin** [comment]
Working well on upgrade too - moving to ready.
