### ISSUE TITLE
Intermittent connectivity for medic-gateway causes duplicate messages

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4110]
When there is intermittent connectivity.  Duplicate messages are created.

An example issue: https://github.com/medic/medic-projects/issues/3159.  @rosteve tells me that when the gateway phone is connected to the wifi, duplicates happen but when connected using 3G (faster) there are no duplicates.

It looks to me that medic-gateway as well as API should both keep a list of `guid`s of messages they have acted upon and the status for each.  Therefore, if API for example forwards a message to medic-gateway again for whatever reason, medic-gateway won't send it out since it knows it has already acted on it.

**Comment by alxndrsn** [comment]
If `medic-gateway` is re-supplied the same message, it [may indeed send it twice](https://github.com/medic/medic-gateway/blob/master/src/main/java/medic/gateway/alert/Db.java#L391).  If this behaviour is to be changed, care should be taken to understand if there are circumstances where a `medic-webapp` user may _want to force_ a resend of a message (e.g. a message failed to send because gateway was out of credit), and if there are sufficient statuses in the protocol to allow for this, while at the same time fixing the problem described in this ticket.

@rosteve it would be really helpful to understand some more details of the project that you're seeing these issues on, and some more idea of how many extra messages are being sent out in error...

**Comment by alxndrsn** [comment]
If `medic-gateway` is re-supplied the same message, it [may indeed send it twice](https://github.com/medic/medic-gateway/blob/master/src/main/java/medic/gateway/alert/Db.java#L391).  If this behaviour is to be changed, care should be taken to understand if there are circumstances where a `medic-webapp` user may _want to force_ a resend of a message (e.g. a message failed to send because gateway was out of credit), and if there are sufficient statuses in the protocol to allow for this, while at the same time fixing the problem described in this ticket.

@rosteve it would be really helpful to understand some more details of the project that you're seeing these issues on, and some more idea of how many extra messages are being sent out in error...

**Comment by rosteve** [comment]
Hi @alxndrsn , The project that was initially facing this issue was CMMB Zambia where report got duplicated severally depending when using wifi connection.The partner discovered that by using Mobile Data connection the duplication didn't occur hence this solved the issue

For Chrisitian-Aid Isiolo , the duplication of reports occurred when a single report (as described [in this ticket](https://github.com/medic/medic-projects/issues/3247#issuecomment-358955800).  ) grew beyond the max document size (4MB), and there was a `os_process_error` which thereafter caused duplication  of reports in the instance 


Since the duplication occurred, chw's have been getting multiple sms reminders (about 48 _same_ message reminders having the same message body) coz of the initial duplicate reports that are duplicates. Am currently looking into how to delete the duplicate reports since they are many and only leaving the first report that was submitted for every patient so as to stop the multiple same sms reminders being sent

**Comment by henokgetachew** [comment]
> If medic-gateway is re-supplied the same message, it may indeed send it twice. If this behaviour is to be changed, care should be taken to understand if there are circumstances where a medic-webapp user may want to force a resend of a message
@alxndrsn I don't think that's what's happening (i.e. medic-gateway being re-supplied the same message).  I think what's happening is that medic-gateway is trying to send the message to medic-api and medic-api has received it.  However, probably because of connectivity issues, medic-gateway doesn't get the ack that the message has been received. Therefore, it sends it again. I think this is what's happening on both sides.

**Comment by alxndrsn** [comment]
- [ ] ACK quicker from api to gateway.  Poor connectivity is something we have to deal with, and should expect in our medic-api implementation.
- [ ] implement integration tests for API for the `/sms` endpoint, and if we can for poor connections (e.g. include expected response times in tests)
- [ ] get API to understand that gateway sends a unique UUID with each message, and that if it sees the same UUID twice, then it has no need to re-save a message

**Comment by sglangevin** [comment]
@alxndrsn this is still listed as part of the 2.15.0 release which we are getting ready to start release testing (a beta has been released). Are you able to finish this off so we can include it?

**Comment by alxndrsn** [comment]
This work is currently blocked by https://github.com/medic/medic-webapp/issues/3019, which should significantly improve performance of the sms-gateway api endpoint.

**Comment by alxndrsn** [comment]
This will need backporting to 2.15 branch.

**Comment by SCdF** [comment]
Back to you @alxndrsn

**Comment by alxndrsn** [comment]
TODO
====
- [ ] Merge PR #4367 
- [ ] backport fix to 2.15 (using main `medic` ddoc)
- [ ] release new 2.15 beta

**Comment by ngaruko** [comment]
Any clue how to AT this on `local` or `test instances` @alxndrsn @henokgetachew ?

**Comment by abbyad** [comment]
@henokgetachew said he could take care of AT for this if it is not picked up by the time he is back.

**Comment by henokgetachew** [comment]
I'm not sure how to AT this without putting it in the real world.  I guess we could try throttling connectivity but I'm not sure how well that would work for our needs. @rosteve do you know of a project that's going through this issue right now that we could test this on?

**Comment by rosteve** [comment]
@henokgetachew CMMB Zambia is currently an active project we can test this on. It was majorly affected by this problem

**Comment by ngaruko** [comment]
Since it is hard to reproduce / AT this in non-production environment and we haven't heard it reported in production yet, I will close this and keep an eye out in the field. Aye @henokgetachew @rosteve ?
