### ISSUE TITLE
Changes requests are unsustainably large

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4172]
Requests to changes feed get very big:

![screen shot 2018-02-06 at 21 37 54](https://user-images.githubusercontent.com/191496/35883058-4f8f5848-0b86-11e8-8f6e-1869763c027b.png)

This payload converts to JSON of length 800,975 characters.  As these characters are mostly UUIDs (and so quite random), they are unlikely to compress significantly.

These requests then all time out after 15 seconds:

![screen shot 2018-02-06 at 21 40 42](https://user-images.githubusercontent.com/191496/35883083-6a45611e-0b86-11e8-8e4c-e379eb3abbd4.png)

![screen shot 2018-02-06 at 21 39 37](https://user-images.githubusercontent.com/191496/35883044-437cbfc8-0b86-11e8-8888-e6bc1c3ee6c8.png)

**Comment by garethbowen** [comment]
Good catch. We send all known UUIDs so we get notified if they get deleted from the server. This is due to the fact that we use views for filtering replication and views don't return deleted docs.

Another potential solution is to separate the deletion from the updates and creates. For deletion we could have a scheduled request which checks if docs have been deleted by UUID. This could then be paginated to only check 100 (or 1000?) at a time. We could probably get away with running this only once a day or so.

Yet another solution is to update all clients changes feeds for all deletions (I assume PouchDB will ignore deletions for docs it doesn't know about). This is obviously quite chatty so it probably comes down to how common deletion is in production.

**Comment by SCdF** [comment]
In standup we talked about another solution: whenever a delete comes through in the changes feed, manually run the view code over it to determine who should see the delete. I'm not actually sure this works with our current strategy, though it's worth considering.

**Comment by garethbowen** [comment]
> manually run the view code over it

This is the same solution I'm working on for #2734 to enable doc level permissions. If that works then reusing the function for this too would be straightforward.

**Comment by garethbowen** [comment]
Fixed as part of #4185

**Comment by ngaruko** [comment]
Any details on how to AT this @alxndrsn ?

**Comment by alxndrsn** [comment]
Check if changes requests are still sending a list of document IDs or not.

**Comment by ngaruko** [comment]
Seeing a `request not finished yet` message on the network tab. Not sure if it is anything to worry about @alxndrsn ?
     
![image](https://user-images.githubusercontent.com/6979995/41079980-5a3e6936-6a78-11e8-8afa-a353a8de7ff4.png)

**Comment by garethbowen** [comment]
@ngaruko The changes request sits there waiting for changes to happen on the server. This is exactly as expected. Did you check to see if the doc ids are included as parameters on the request?

**Comment by ngaruko** [comment]
Thanks @garethbowen. Docs ids are not included as parameters on the request.
