### ISSUE TITLE
Replication issue when creating a new CHW area

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4200]
This bug was introduced after the changes made in #4166. To reproduce:
1. Log in as a restricted user to standard.dev
1. Go to the contacts tab and click "New area"
1. Create the area with a new person as the primary contact.
1. Go to the contact profile of that new person. Notice there is no Medic ID generated but that the hierarchy information "Belongs to" is correct.
1. Go to the contact profile of that new person when logged in as a full access user. Notice that there is a Medic ID but there is no hierarchy information for the person ("Belongs to" is blank due to a null parent).

Given that the hierarchy is generated correctly when the person & place are initially created, this seems to be an issue with whatever is happening when the Medic ID is added to the person doc.

**Comment by garethbowen** [comment]
Here's what I have so far.

I _think_ that `e5ea0696-ff9c-4dc8-ac78-a54003e70e06` is the contact that has this issue on standard.dev (@sglangevin correct me if I'm wrong). In rev 1 the contact hierarchy is correct, but in rev 2 after `generate_patient_id_on_people` transition runs then parent is `null`. I very much doubt this transition is at fault, but when dealing with changes sentinel looks up the minified lineage and hydrates the parents so transitions can use the details if needed.

In this case both contact and parents were created on the phone and looking at the `info` docs the contact was replicated to the server 2 seconds before the parent made it. Assuming sentinel picked up the contact and hydrated it in that 2 seconds then it wouldn't have found the parent and (I think) would null out the hierarchy.

I'm fairly sure it's unrelated to #4166 because this is to do with replication from the phone, whereas #4166 is to do with replication from the server. However if I'm right this bug won't occur all the time.

Just looking in the code I see that when [Enketo saves the docs](https://github.com/medic/medic-webapp/blob/master/static/js/services/enketo.js#L434) it doesn't use a bulk save so it's possible that the contact doc was saved, then it was replicated, then the parent doc was saved, then it was replicated. This would likely cause this bug to occur. @alxndrsn @SCdF Any idea why we're not using `bulkDocs` here?

Other than using bulk docs the other solution would be to enforce an order so parents are always saved before children.

**Comment by SCdF** [comment]
As you say: If bulk docs results in them being bulk uploaded then that is good; Otherwise we need to make sure the parents get saved before children.

**Comment by sglangevin** [comment]
Just confirming that is the correct doc. Sorry for not including links in the original post!

**Comment by garethbowen** [comment]
Code review please @SCdF . This needs to be backported to `2.14.x` so feel free to leave the merge to me.

**Comment by SCdF** [comment]
Back to you @garethbowen

**Comment by ngaruko** [comment]
LGTM
