### ISSUE TITLE
Determine if we can build/release Crosswalk with the latest Chrome

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4217]
Crosswalk has been end of lifed in part because Android has had evergreen webview for a while now, so the version of Chrome we ship with our app is getting relatively old. Crosswalk is still really useful for us because of the ability to use 100% of the phones storage so we want to keep using it.

Find out how much work is involved in updating the version of Chrome and rebuilding Crosswalk either with the community or just for our app.

**Comment by alxndrsn** [comment]
Tenta _appear_ to be maintaining more up-to-date versions.  Here's a commit which appears to be Chrome 64: https://github.com/tenta-browser/crosswalk/commit/b84b8597bbb5d2b0e98bfae3dc3deba3c7c4bd97

**Comment by garethbowen** [comment]
There's also ongoing discussion in the community: https://github.com/crosswalk-project/crosswalk/issues/4001

**Comment by rmhowe** [comment]
So it looks like various parties are interested in updating the chromium version within crosswalk and many have tried but none have really gotten anywhere. Someone managed to get an apk for chromium v53 but didn't seem very confident in it and then gave up (which confused me because I think the last stable crosswalk was with chromium 53). Tangerine seem to need to update it as well but are now looking at tenta.

It looks like the best bet at the moment is tenta who appear to have a functional crosswalk with chromium 64, I'll attempt to build it but may get very very stuck.

**Comment by rmhowe** [comment]
Yes that was as far as I could get in building, running `gclient sync` from the tenta repo errors due to the private bitbucket modules.

I've reached out to the tenta team to see if they've managed to get crosswalk working with chromium 64 and whether they'd be willing to make the binaries publicly available.
