### ISSUE TITLE
Error when trying to submit a report as a restricted user on 2.14.0-beta.11

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4235]
I'm getting a DOMException that says the connection to the database is closing when trying to submit a form as a restricted user on beta.dev. Form submissions are working fine for admin. In the UI, I see "Error saving report". This happens on both incognito Chrome and on Android. 

Screenshot of the console from my Android tablet:
![image](https://user-images.githubusercontent.com/1286381/36570940-41f2c322-17e9-11e8-925c-b7145686fb40.png)

**Comment by sglangevin** [comment]
Screenshot of console from Chrome (incognito mode): 
![image](https://user-images.githubusercontent.com/1286381/36571026-ac7a7cb2-17e9-11e8-8585-5f8353f48221.png)

**Comment by SCdF** [comment]
New version of PouchDB is broken?

**Comment by garethbowen** [comment]
@sglangevin Does this happen every time? Does this happen on every device you test? Does this happen with every restricted user? Do you have space on your device? Does this happen when you're offline?

**Comment by garethbowen** [comment]
@sglangevin Victor and I are having trouble reproducing this issue. Can you please put the app in debug mode (Hamburger > About > Enable debug mode) and then reproduce this issue? That will give much more information in the console log. If you go to the console and right click and select "save as..." then you can download the entire console without taking a screenshot. I think I know where this is happening but I don't yet know why...

**Comment by garethbowen** [comment]
I think I've got it... The problem is when IDB is trying to store the Position object returned from the geolocation. Because it's not a plain JSON object it fails. This is why we couldn't reproduce it - we'd been blocking the geolocation. Allowing it causes the error.

The solution is to copy the relevant fields into a JSON object.

**Comment by garethbowen** [comment]
I just merged this directly in to `master` because I needed to test on a real server to prove it works. @vimemo Please review [the relevant commit](https://github.com/medic/medic-webapp/commit/68da84aa02d68eb1d44892f67a8a576734eea11f) and if you're happy set this for acceptance testing.

For AT: Make sure that forms get submitted reliably and that geolocation capture on form submission is still working.

**Comment by sglangevin** [comment]
Forms are working fine but I can't get the geolocation to work. I've tried in Chrome and on a phone and a tablet. The phone and tablet are on WiFi with airplane mode switched off. I'm only getting the `geolocation` field in the `data_record` sometimes and when it is there, it is blank.

**Comment by sglangevin** [comment]
I was testing as a restricted user on beta.dev and on standard.dev.

**Comment by garethbowen** [comment]
Yeah, that's what I was getting too. When was the last time you tested this and got a geolocation result?

**Comment by garethbowen** [comment]
Fixed in 2.14.0-beta.17

**Comment by sglangevin** [comment]
LGTM - GPS is working in Chrome and on Android with a recent version of our Android app.
