### ISSUE TITLE
Upgrading throbber spins forever  when Cancel Button is clicked on  in Horticulturalist's `Update Available` Modal 

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#4243]
Few steps to reproduce:
Login as admin 
Configuration > Update Instance > choose a branch/build then `Upgrade`. 
Once the upgrade is finished, the `Update Available` Modal pops up >> Click `Cancel`

Expected >> Spinner should disappear and app go back to the 'horti' UI .

But, the upgrading throbber spins forever and the page only reloads if one moves to another page or refresh otherwise. 

![image](https://user-images.githubusercontent.com/6979995/36705517-7af5ffce-1bca-11e8-9413-e446b5a9d243.png)

**Comment by SCdF** [comment]
We could probably fix this by forcing a restart on you by specifically watching the changes feed instead of just letting the standard update flow go.

It's worth noting that this will be re-worked with https://github.com/medic/medic-webapp/issues/3993, noting this comment specifically: https://github.com/medic/medic-webapp/issues/3993#issuecomment-339929306

**Comment by ngaruko** [comment]
LGTM.
Tested on `https://alpha.dev.medicmobile.org/medic/_design/medic-admin/_rewrite/#/upgrade`.
Version 3.0.0
![image](https://user-images.githubusercontent.com/6979995/40599483-a10791d2-62a1-11e8-9f34-0ef057300638.png)
