### ISSUE TITLE
`Outgoing messages` sorting broken 

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#4281]
Steps to reproduce:
Run  e2e tests (`grunt e2e`) with `specs: ['e2e/**/sms-gateway.js']` enabled. 
Expected:  Pass  (`Delived` message to come before `Scheduled`)
Observed: Fail with `Scheduled` message showing before `Delivered`. 
![image](https://user-images.githubusercontent.com/6979995/37262223-b17a9064-2606-11e8-888a-de428ff08266.png)

**Comment by garethbowen** [comment]
This test is failing because the two messages in the `ANC Reminders LMP:2` group are being reordered. The change was introduced with the recent change to a shared task-utils library which added [this line](https://github.com/medic/medic-webapp/blob/master/shared-libs/task-utils/src/task-utils.js#L23) which sets the timestamp of the task when updating the state. I don't think this is correct and this line should be removed.

**Comment by garethbowen** [comment]
@dianabarsan What do you think?

**Comment by ngaruko** [comment]
LGTM.... Well done @dianabarsan  & @garethbowen
