### ISSUE TITLE
Wrong "add place" button on the RHS at certain levels of the hierarchy

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4301]
As seen in this screenshot, I've clicked on a district hospital and am viewing the district hospital's profile but I have "Add family" on the RHS instead of "Add CHW area". Clicking on "Add family" does open the add family form, so it's not just an incorrect icon. I was logged in as admin on beta.dev when taking this screenshot - version 2.15.0-beta.1

![image](https://user-images.githubusercontent.com/1286381/37503442-baf7735a-2895-11e8-9227-74caaa0c3567.png)

**Comment by dianabarsan** [comment]
It seems that `contact_summary` function from config throws an error for contacts that are top hierarchy (ie have no `contact.parent` and so `contact.parent.parent` throws). This prevents the code which sets your selected contact to fully run - this includes updating the action bar - so you'll be left with the action bar from the contact that was selected before.
If you refresh the page and click on any of the district hospitals, you'll probably notice that no action bar appears.

**Comment by sglangevin** [comment]
Ok - we need to protect against that then or give guidance on how to create a `contact-summary` that avoid this bug. The `contact-summary` I am using worked fine in previous versions, so protecting against this would be the preferable option.

**Comment by dianabarsan** [comment]
There's also a difference between forms. Some forms for `district_hospital` have a `parent` field, while some don't (beta.dev forms don't, which is also part of what causes this issue). 

I also think the right thing to do is to guard against this, only wanted to provide full context.

**Comment by sglangevin** [comment]
Cool, sounds like we are on the same page. Thanks for the context!

**Comment by garethbowen** [comment]
I'm concerned about using dummy values just to get this particular script to work. It looks to me like the configuration has a bug where it checks `contact.parent.parent` without first ensuring `contact.parent` exists. We _can_ provide a dummy `contact.parent` to make this particular configuration work but it won't protect users from accessing any other fields without proper null checking.

I propose these changes instead...

1. Fail hard. When the contact-summary script throws an exception we shouldn't go on like nothing has happened. The RHS should be cleared and show some error message instead. There should be an error message in the console that makes it clear the contact-summary configuration is broken and as much as possible explain how to fix it.
2. Document that the configuration has to handle nulls, particularly with respect to parents because you never know how many you have!
3. Provide a unit testing framework (in planning) so configurers can easily check their configuration against their hierarchies.

What do you think @dianabarsan and @sglangevin ?

**Comment by sglangevin** [comment]
That sounds like a good approach to me. It would definitely help to have some kind of error message and we can easily document the handling of nulls to make sure we don't run into issues in config.

**Comment by ngaruko** [comment]
LGTM... Can you double-test this with the same config/form @sglangevin before we close the issue?

**Comment by abbyad** [comment]
Works for me on beta.dev with `2.15.0-beta.4`, so moving to Ready.

Tested that icon is correct and link goes to the right place too.
![image](https://user-images.githubusercontent.com/789512/38390235-b35e3f02-38ee-11e8-9faf-5bae262ae441.png)
