### ISSUE TITLE
Unable to delete user from medic webapp

### ISSUE THREAD

**Issue by mukesh2006** [medic/medic-webapp#4340]
Instance URL: https://map-pk.app.medicmobile.org/medic/_design/medic/_rewrite/#/configuration/users
Instance Version: `2.13.1`
User: `medic`
Type of user: `full access`

Problem: Can not delete the users from the webapp. 
Error: `403 Forbidden`

![map-pk-unable-to-delete-user](https://user-images.githubusercontent.com/4347171/38019745-2ac55934-3298-11e8-8163-87245f1f345d.png)

This problem is also seen on [ebpp instance](https://ebpp-indonesia.app.medicmobile.org/medic/_design/medic/_rewrite/#/about) it is on `2.13.5` version.

cc @SCdF

**Comment by SCdF** [comment]
@mukesh2006 I don't think this is a new issue, and is a result of how CouchDB works. This version of our software directly communicates with CouchDB from the UI to create users, and it looks like CouchDB doesn't allow non-admins (from its perspective) to delete users (though it can create them… go figure).

We have actually changed our strategy here in later versions, so that user modification operations go through our api, which uses the expected permissions in the permissions tab to control access to these functions. Unfortunately this fix is only available in 2.15 (which is not yet released). See #3910.

Is this a critical issue? The workaround is to use the fully full `admin` user. Otherwise we could look at backporting the fix to 2.13 or 2.14.

**Comment by mukesh2006** [comment]
@SCdF The `admin` user is able to delete the users so as of now it's not a critical issue for us. We can wait for the next release for the fix.

cc @kanikamedic

**Comment by derickl** [comment]
@SCdF LG will be on 2.13 for the next 5 months before possibly upgrading to what will be available at that time.

The ability to delete users as non-admin will be greatly helpful as we are training them to do some of the maintenance work on their end. I'd be greatly appreciative of a backport to both 2.13 and 2.14 (moh-siaya) since we don't want to give them full admin access. cc @sglangevin

**Comment by SCdF** [comment]
@derickl I can take a look at how easy it is to backport these changes. It might be quite challenging, they were quite extensive. Or it might be fine :-)

**Comment by derickl** [comment]
Thank you @SCdF. I'll await your assessment.

**Comment by sglangevin** [comment]
I don't think we should backport this as the primary needs from LG should be to create and edit new users, both of which are possible with a full access user. Have they specifically asked for access to delete users? In the past, we didn't actually delete the user docs associated to CHPs who dropped out, not sure if that is something you've been doing lately.

If it's easy, we can discuss it, but otherwise we need to stick with current functionality. Also, LG will need greater access to do configuration anyway, so we'll have to share an admin password for that.

**Comment by sglangevin** [comment]
Also, can you explain why this is needed for MOH Siaya? Did we commit to training them on user management as well?

**Comment by SCdF** [comment]
> If it's easy, we can discuss it

It's not, unfortunately. From a quick look weird stuff is going on here, could be hours -> days.

**Comment by SCdF** [comment]
Stakeholders in this ticket (@mukesh2006 / @derickl / @sglangevin ) I'm unassigning this from myself: I don't have any actions left on this ticket.
