### ISSUE TITLE
Write a doc minification script to apply migrations to a running instance

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4362]
Over the last couple of years we've made some changes to how we store data to reduce disk space requirements and/or improve performance, however because the migrations would take a long time to run we decided to make the changes in a backwards compatible way. Unfortunately that means existing documents are unoptimised.

Write a script to execute database optimisations against a running instance.

Optimisations to consider including are...

- minifying contacts
- storing report xml in an attachment
- removing read data which has been migrated into the user db
- anything else you can think of

Features the script could include are...

- run only between certain times each day (overnight, over the weekend, etc) - it will need to remember which docs have been processed in previous executions
- run against certain branches only so individual CHPs download all their changes in one go rather than a couple of changes a day
- throttling so it doesn't lock the server up

The first project this script will be executed against will be LG so follow up with @derickl with any questions.

**Comment by garethbowen** [comment]
Related issue #2012 but note that this has to work against 2.13.0 (LG) where that is for 3.0.0.

**Comment by SCdF** [comment]
NB: we already have one of these for removing the XML: https://github.com/medic/medic-webapp/blob/master/api/manual-migrations/extract-data-record-content.js

It's basically a migration in the current style but moved into a separate directory so it can be run manually.

**Comment by derickl** [comment]
@garethbowen happy to have a follow up conversation on this.

**Comment by garethbowen** [comment]
@SCdF I've created the doc minification scripts and committed into a branch off `master` and a branch off `medic-api/2.13.x`. Would you mind testing the latter against your db? I'm particularly interested in local and remote db size (after compaction) and performance of view generation and form loading.

**Comment by SCdF** [comment]
I tested these locally, but unfortunately I think they are too disruptive with how PouchDB is right now with replication.

Re-replicating as many docs takes the phone out for hours, pouchdb stuck on pushing server side checkpoints up for the vast vast majority of that time.

If we could make PouchDB do fast server side checkpointing, either by fixing the existing backend or fixing it by writing idbnext, making these changes may be worth while.

**Comment by SCdF** [comment]
I did another round of testing for this, and I think these scripts need to be updated so that you pass a facility that you want to convert. This will allow LG and friends who have CHWs who are running out of space / having particular issues with performance to be specifically targeted, and have their phones wiped and re-installed.

Running this over an entire installation would be disastrous for phone performance in the application's current state. Specifically:
 - Us watching the changes feed for every change makes PouchDB pathologically slow when it comes to view re-generation
 - In general PouchDB is very slow with this much data changing, in a way that users have never experienced before (because users start with an empty phone that slowly builds up data, not with a phone full of data)

**Comment by SCdF** [comment]
(NB: I suspect there is currently a bug / performance issue with PouchDB which actually makes these changes cause view generation to be *slower*. This is not the case in CouchDB and there is no logical reason why this would be the case. I'm still investigating.)

**Comment by garethbowen** [comment]
I've raised #4685 to cover the improvement. The script as it is is useful for smaller projects but shouldn't be used on large projects.
