### ISSUE TITLE
Sentinel tries to act on old revisions of deleted docs

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4369]
This was observed while fixing an issue by deleting a problematic doc.  Sentinel tried to act on the old revisions of the doc and kept crashing even if the doc was deleted.  Running compaction was the only way to solve the problem.  This issue might also mean that sentinel is wasting processing power acting on old revisions of docs after they have been removed from the system.

**Comment by alxndrsn** [comment]
@henokgetachew does this need backporting to other versions, or is it specific to `3.0`?

**Comment by alxndrsn** [comment]
Also is there a stacktrace of the crash available?

**Comment by henokgetachew** [comment]
This was the issue @alxndrsn: https://github.com/medic/medic-projects/issues/3711.  Basically the app crashed even if the problematic doc was deleted.

**Comment by alxndrsn** [comment]
Thanks, but the linked issue doesn't seem to contain any more information about the nature of the crash when a document is deleted.

**Comment by alxndrsn** [comment]
Sentinel already tries not to run transitions on deleted docs: https://github.com/medic/medic-webapp/blob/master/sentinel/transitions/index.js#L92-L93

Later in this function it appears that a `not_found` error should be logged and ignored.

**Comment by rmhowe** [comment]
It seems to me that this problem (seen here https://github.com/medic/medic-projects/issues/3711 ) is to do with view generation rather than a problem with sentinel (as suggested by the error messages and particularly as sentinel will only act on the changes feed as new changes come in). The view generation problem appears to be in the `reduce` function for `messages_by_contact_date` which is being refactored as part of https://github.com/medic/medic-webapp/issues/4232 to avoid errors when a message has multiple newlines, so that work should prevent this error from happening again.
