### ISSUE TITLE
Replace medic-reporter

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4516]
[medic-reporter](https://github.com/medic/medic-reporter) is a standalone couchapp that we used for sending test messages without needing an SMS or gateway device. Because it's standalone it is frequently inadvertently broken, and currently is difficult to install because we've dropped dashboard.

Reproduce the main functionality of medic-reporter in the admin app so it's shipped with the webapp, can be tested and maintained easily, and just works.

It appears that we no longer need the form UI as users are happy to fill in the SMS manually, so the bits we need to input are: the SMS message, the from phone number, and the locale.

**Comment by browndav** [comment]
It's worth noting that we _are_ able to do a manual install by taking a build from staging and using the `couchup` tool on it – so if there was a one-off specific need for the tool, we could probably still accommodate it.

**Comment by sglangevin** [comment]
@ngamita @billwambua @rosteve can you comment on whether or not tech leads are using the "Forms" section of medic-reporter for testing? I personally don't use it to test textforms but if you know it is used for Medic Collect testing, for example, let us know. If no one is using it, it is likely to be removed.

**Comment by ngamita** [comment]
We use medic-reporter for testing text forms or Standard instances without need for setting up a gateway. I think it's still too early to take this feature away as on many occasions we've also worked with the Partnerships folks to perform demos to partners using the same medic-reporter on several occasions. If it's difficult to install, is it possible to have a separate standalone that can be pointed to any instance to enable the sending of messages and not having each instance with the Medic reporter with this we can measure it's usage over time and phase it out slowly as the usage drops. Also we're fine having ONLY SMS message, the from phone number, and the locale without the HTML.

**Comment by billwambua** [comment]
The medic-reporter `Forms` section is quite useful for quick testing of `medic-collect` projects quickly rather than always going through the long process of deleting existing forms, uninstalling and uploading the `apk` to the phone.

Collect forms are sometimes unusually long, hence can't be accurately keyed in the `Compose` section. So, having a working and easy to use visual `Forms` section is a big help in configuration testing.

**Comment by sglangevin** [comment]
@ngamita to clarify, we are just talking about re-writing medic-reporter and moving it to a different location, not removing it. And we're just wondering which parts of the current medic-reporter functionality need to be included. Sounds like we should just keep everything, though we can probably remove the drop-down for "Format" unless that is used? I have never used it myself.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
Back to you @garethbowen

**Comment by SCdF** [comment]
Back to you @garethbowen

**Comment by ngaruko** [comment]
Just checking if there was a consensus on how this should work @garethbowen @sglangevin @abbyad . My understanding from the discussion above is that it should have the same functionality as before, minus the `forms` and `local` sections. As such one would expect forms to still be send via the `message body` like so:
![image](https://user-images.githubusercontent.com/6979995/40521974-76d293b6-6022-11e8-92f6-7b99f447df69.png)
Ideally this would be picked up as `pregnancy form` but it appears as a simple message in the UI. Is this intentional/expected or configuration-dependent?
![image](https://user-images.githubusercontent.com/6979995/40522054-06167114-6023-11e8-8d25-12ea4cd0ff6f.png)

**Comment by garethbowen** [comment]
@ngaruko Sounds like a different issue - can you please raise a new issue and link to an example of an affected report?

**Comment by ngaruko** [comment]
Closing this an opening a [new issue](https://github.com/medic/medic-webapp/issues/4584) for the above
