### ISSUE TITLE
Dev: Administrator app changes only take effect the *second* time grunt watch catches it, translations never work

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4536]
If you are devving on the admin app your changes aren't reflected the first time grunt watch cycles, but the second time.

**Steps to reproduce**:
 - Have grunt watching (e.g. `yarn grunt`)
 - Make an admin app change you should be able to see, also add a translation and use it somewhere
 - Note that grunt watch notices it, and does some very important-looking stuff
 - Once grunt has finished refresh the admin app

**What should happen**:
 - You should see your changes

**What actually happens**:
 - You don't see your changes
 - Additionally, if you make another nothing change (ie touch a file to make grunt watch fire) you do get your code changes
 - But you don't get your translation changes until you start grunt fresh

**Environment**:

- Client platform: MacOS
- App: admin (haven't tested with anything else)
- Version: master

**Comment by SCdF** [comment]
@garethbowen I can't work out from looking at Gruntfile why this would be the case. Can you try to reproduce on your end? Maybe it's just me...

**Comment by SCdF** [comment]
OK I don't think this is grunt, I think this is how the app is cached. If I **refresh** the app twice I get my changes.

**Comment by garethbowen** [comment]
I think with all the changes that have happened to the repo (admin app, restructuring, etc) the watch configuration is well out of date. I'll have a play today to see if I can get it to be more logical and also fix this issue at the same time.

**Comment by garethbowen** [comment]
Review please @SCdF ...

> If I refresh the app twice I get my changes.

I think you were just refreshing too soon. What I think was happening was grunt would deploy the main ddoc, the deployment notification would flash up on the screen, you would refresh the admin app and get the old code, then api would extract the medic-admin ddoc from the primary ddoc, then if you refresh again you get the new code.

This PR changes it so instead of compiling and pushing the primary ddoc we just push the secondary ddocs directly skipping the api ddoc extraction code altogether. This is far faster and works reliably for me. The only problem I can see is if ddoc extraction runs later and overwrites the new code with the old code again which will occur if you change the configuration in some way because settings are stored on the ddoc. (We really need to fix this...). I'm not sure if this is a blocker or not.

> you don't get your translation changes until you start grunt fresh

I've added a watcher for this so it should work now.

**Comment by SCdF** [comment]
> The only problem I can see is if ddoc extraction runs later and overwrites the new code with the old code again which will occur if you change the configuration in some way because settings are stored on the ddoc. (We really need to fix this...). I'm not sure if this is a blocker or not.

That does sound pretty bad honestly. Wouldn't that also mean that any configuration you have wouldn't make it into medic-client as well?

**Comment by garethbowen** [comment]
Yeah, good point. Well, maybe review that PR but don't merge. I'll fix the settings soon and then we should be good to go. This has been holding us back long enough...
