### ISSUE TITLE
Implement a http to https redirect for Docker instances

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4547]
When you access an instance using the http protocol you should be permanently redirected to the https version as we only support https. This works on non-Docker instances, but when I try now I get "503 Service Temporarily Unavailable".

**Comment by browndav** [comment]
This is an ALB issue. Multiple feasible methods exist; I'm currently narrowing this down to the easiest option with the least administrative burden.

**Comment by browndav** [comment]
We have a working design for this; it's a stateless nginx container from CoreOS that does nothing but issue permanent redirects, zero configuration. Currently updating checklist; expect this to add one step to the initial deploy and one step to container launching (adding the ALB rule to route correctly). I've forked it over to https://github.com/medic/docker-nginx-https-redirect so we can make local config modifications for performance/security if needed, but it's deadly simple.

Because the redirects will be permanent, I don't expect this container to see much load at all. Currently discussing container placement with Henok.

**Comment by browndav** [comment]
This is complete. It is deployed to the development environment in `eu-west-2` and is available on ECR as `720541322708.dkr.ecr.eu-west-2.amazonaws.com/medic/http-redirector:1.0.0`.

**Comment by browndav** [comment]
Docker container repository is https://github.com/medic/docker-nginx-https-redirect; it should build with `docker build -t medic/http-redirector:1.0.0 .`

**Comment by ngaruko** [comment]
Tested on `alpha.dev` .... `http://alpha.dev.medicmobile.org` ==> redirects to `https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/messages/phone:+[***********]`
