### ISSUE TITLE
When exporting, duplicate reports are exported sometimes

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4610]
When filtering by certain places, the export feature downloads multiple copies of some reports. 

**Steps to reproduce**:
 - Log in as admin to beta-old.dev or standard.dev
 - Go to the reports page
 - On beta-old.dev, use the places filter to filter by Antoine's district. On standard.dev, use the places filter to filter by General Hospital 11
 - Click Export
 - Notice that multiple copies of some reports are downloaded (I used a pivot table to show a count by _id to make sure there were really duplicates). On beta-old.dev, there were up to 28 copies of some reports, while on standard.dev, it was only up to 3 copies.

**What should happen**:
 - Should download 1 copy of each report.

**What actually happens**:
 - Downloads multiple copies of each report

https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/
https://standard.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/

**Environment**:
- Instance: beta-old.dev, standard.dev
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 2.15.0-beta.16

**Other**:
I found the same issue when I filtered by Clinic Visit forms for all places on beta-old.dev then exported, so I am wondering if it has to do with malformed contacts somewhere again, but I'm not sure.

**Comment by SCdF** [comment]
This is unsurprising when I think about it, as the current implementation also batches the search request along with the hydration / writing out to CSV bit.

Or there is a bug in the search library.

**Comment by dianabarsan** [comment]
Please review, @SCdF .

The issue was Search library allowing `skip` to be greater than results length. 
When paginating reports, if the `skip` was greater than results length, the `end` index in `slice` would be a negative number.
So `Export` service kept receiving data until `skip` was at least 2 x results length.

I am also fixing another bug, where `Boolean` filters (`verified` and `valid`) were not cast from `Strings` - which caused `verified` and `valid` filters to not be reflected in the exports.

I am also enabling sharedLibs unit tests in Travis - but disabling bulk-docs-utils unit tests as they are broken.

**Comment by dianabarsan** [comment]
Merged into `2.15.x` and forward ported to `2.16.x` and `master`.

**Comment by sglangevin** [comment]
LGTM on 2.16.0-beta.17. Moving to ready.
