### ISSUE TITLE
Enable response body compression

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4643]
Old medic-os instances had gzip compression enabled in nginx, but Docker instances don't have nginx and compression is no longer happening. This can be enabled in express but [it's better to implement it at a reverse proxy level](https://expressjs.com/en/advanced/best-practice-performance.html#use-gzip-compression).

This is a blocker for using Docker in production.

**Comment by browndav** [comment]
Let's chat at stand about this one briefly today. Brief summary as I understand it: ALBs won't add gzip/deflate but will pass ith through provided the `Content-Length` header is correct; there's [Express middleware](https://github.com/expressjs/compression) to perform gzip/deflate with native node bindings, and there's also the option of bringing nginx back into the picture for purposes of compressing data only.

**Comment by garethbowen** [comment]
From the express documentation linked above:

> For a high-traffic website in production, the best way to put compression in place is to implement it at a reverse proxy level

That's my only real concern. I doubt we count as a "high-traffic website" for express so we may be fine. I was hoping there would be some easy performant AWS way to do it but it appears there isn't, so I'm comfortable with trying the express middleware until we hit some performance limit.

**Comment by dianabarsan** [comment]
Unfortunately, this doesn't work with CouchDB heartbeats for online users `_changes` requests. 
Looking for alternatives / fixes.

**Comment by ngaruko** [comment]
Response headers compressed for [compressible docs](https://alpha.dev.medicmobile.org/medic/_changes?style=all_docs&heartbeat=10000&since=743-g1AAAAJBeJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____szKYE5NygQLsRpapaRamKdg04DEmSQFIJtlDTQoFm2RsYGZqaZBGqkkOIJPiQSYluuNTlwBSVw-1MRVso3misYlJCqluz2MBkgwNQApo2HyE-1OMLJJMTIzIMm0BxLT9INO8IG4zT01MMjUhy7QDENPug0yLAJuWbJJmmGpgSpZpDyCmgcOtF2yaqUGKYZq5MTZ9WQBBdpmG&limit=100) :


 and not compressed for[ incompressible contents](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAF2klEQVR4Xq2Ua2gc1xXH/+fc2dndWa3eiqy4fgljIjvYCiKFNKE2wcYuQbsru3IfpJGpnU8hpfRDcUtCBZYsGYt+Ki2JoSn0Q0kKSdMnFOLEJIU0LbikNHHSxo7iyLIkS7u2tK/Zued0GRbkVFpjVfnBYVjuPefH/u/cwRqgWiHZn2w3mcQxZBK9WIbxeTN829A9Rxp2IR0/yanohJPxTiOVOKQA1Tby5yetDdPqcyLjfQVpd6wt035m9zd7R7sHt48h5Uw8lEke31dN4TPJrIPlAZnm5vtT3re3pSITONw5iv0YAfAMtmO468jGEaSds0glfuAONPSgxlrlK5v6G3bF04mTSLtnO49uO7X1yNbxE8MnvnvxysWh515+7qmOw12ne77WM4J+HncyidNOKnEgjHzN0deaFCCkEweddLwap3um9XDHKRzCGIDvPf/r55/WKtOz0+cBnMB+jG/86pZRpHmUU/EJ0+8dx2Bj652i5xXRDkPGHnuk5Tv9kSEoDrggaXNa/IX5Of7+YydLb7z9xp6DXzr4MAAk4onOt955a9+5oXOlqfcni5uimwlMRSXtYd8+iYHoDgBaK7pjtFsGtvS46Y5qtNGzsYx3itPeyPav3zcKYOT1Sxee0WV8rZHPFUcAPNU39OBZp7qfw774eLV31BmoRr/KW881qSqUoql7DkzK9BOB3mrxyJR8RbierWQVX4Y5/+brSx9MfvBs7lbuJwAifsV/5/K1y8N/uPC7KfSgZaYwFwgAhH0UhAbFIVTT6xvsa8IwJPTVpBgfRNOfK20D57W0Kwb1A4KEzTUCBGgxTciW5gR/xNQLL7+AYwPHfjY7P/taZ3vnz3EA921s2uxMlT8Vh2OEZRTEGmgptkE3zO41D7/64isvfhiKvZR3b4HoW0DQ7qopthmwA5DgdhgiPjq9bvrHjUs8fvR07vg3nux978P3ZvY+vffmF7f2RieX3q247JFA8L/cVLZLGkSgJXUo+afg1cU3CQPxh4zQkCEs+KIGlgII6hAouImwNAdcQAmb4WBPlwN/TsEuoR6umgSRlJQbVO3H8tvijx1Yvhwx9lcloco9DuiHuyp9MdZGUVhe7Q7IHKpy0KP3MoKlsrVXS8wOIP4KnwBggnn7evTvv5iW7IZoELtuJbvq1+XGL80TYnUjEcogEFaFARgANhxfF4USsdvWsP0cHb40j9twANDwcFhaLVPwwaoMVSGuK5YVwjr/FqqgQjYfBYCXXoI5ejRcUgZCYfjjR7VphgFmrAu+LRcJWAFgcBChBwCcVVukAqZWkNsV6mGzCpMkUZcg86L2moatEIiungoTFHWoI65AqIU0WLDBzEIh3OQhomUEtgxxWhB1Eu0RKzfgGBbXRSDyWbkoyPfhrE1MHaT+nPW+8HiyYd+hPlWiIPfP6ya5o5VdzytOX5xc+teZ6xxv55mZhcbpa9TmOGRVQURQa5WTTZTfullurE1smkjzc5VY185Nse4HHgcYyPFr8HY8CK+zkSP6+9xfcDXZ3By5ejXb8dffoDfaor4KiBhaXoS77QH9pHsLZgOB4frilQiBICoIAh9KhEACFSmTFgArQbgOwHFgY23wIwn4EBAYygYaiSJAHeqKjYoGBFIpVBAUclBDkEKBbPEmShyXIF+CAUECiILEgiCgMGoBVEEqwJrFVhZhXLC9dWUR+St/gzAj958rkIjA9T7WxY+umRgMtKj1LjDd3XVbeca2DMvNPa1o3LkfzTsfRfvunurzEbTt3s/N93fbPAKYJNWbqGsXL8NsCMSugqIARUDGhYkCbAzWQ/0zDlQMSCuLJUj+UxJiVPLzsPlpFEQpWLplame8jqhXitVeVSfhRJb+PTYt86/8FOKSzb9bNF7PReGIqSx+5FMzR1Wm/PVE7az6cWcgKDHlPrlUCWcZdiT7fsCEijDYGAeABUDrjnqlnhmRaJIAA4s8Ik6MAENAEdaWcSfo/xczAAmvVg1YVHBXyN1F/V9VUpguBpvXwwAAAABJRU5ErkJggg==) (images)

![image](https://user-images.githubusercontent.com/6979995/43113547-e4d07b2a-8f4e-11e8-9a45-0f72a714cdd9.png)
