### ISSUE TITLE
Translate our startup messages for non-English speakers

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4680]
People who do not have English as their primary language find our startup messages ("Loading assets", "Fetching Info (100 docs)..." etc) very confusing.

We do not currently translate these because angular has not yet started, and so we do not have the translation service yet. If this is the very first run we would also not have their language, because it wouldn't be the cookie yet, and we wouldn't have their user document yet.

Do we have any ideas on what we could do here to make this less confusing for users? The two most obvious options would be:
 - Add minimal translation support: hard code different languages, also load the user's context document if it doesn't already exist to make sure we get the language
 - Change what is rendered so it works across languages and cultures without requiring people have a firm grasp of english.

I think the former is easier but a bit more hacky (we'd now have translations in two places, but it's pretty contained and isn't that large of a deal IMO), and the latter is probably better, but much harder and would require a large amount of design work

**Comment by garethbowen** [comment]
I think we can achieve the former. API should set the user's language cookie at the same time as it sets the session and userctx cookies after successful login. If the user's language isn't set we can default it to the configured server locale which is correct 99% of the time.

Then it's just a matter of duplicating where translations live. I think hardcoding them is fine here. The alternative would be to have a special set of translations that the server looks up and writes into the HTML/cookie/somewhere but I think hardcoding will do for now.

**Comment by kennsippell** [comment]
What about trying to use animations which communicate the same concept instead of translated words? I think icons can communicate nearly as clearly as localized words here, and a progress bar would actually be the best case scenario for users performing a longer sync.

What about a progress bar with an animated icon for each phase? So for `Fetching info (100 docs)...` have a progress bar + something like [this](https://gifer.com/en/EXfc).

The other three phases - `Loading assets...`, `Loading app…` and `Starting app…` seem quite short on my machine (too fast for me to read each of them individually) -- is this much longer on slower phones? If not, the generic spinning wheel means `Loading stuff...` throughout most mobile ecosystems.

I'd be super interested to discuss what information is important here which is more clear in words than animation. Happy to create a mockup!

**Comment by garethbowen** [comment]
We have [a related issue](#4480) to add a progress bar that could be done as part of this work.

On our target devices the stages take much longer - we started with just a generic loading icon for everything but added the text when it became clear that was insufficient.

I'm open to using icons instead of text but it's actually quite difficult to convey the difference between each of these steps in a way users will understand (loading app vs loading assets vs...).

**Comment by alxndrsn** [comment]
> People who do not have English as their primary language find our startup messages ("Loading assets", "Fetching Info (100 docs)..." etc) very confusing.

Do users who _do_ have English as their primary language find our startup messages any _less_ confusing?

**Comment by alxndrsn** [comment]
> People who do not have English as their primary language find our startup messages ("Loading assets", "Fetching Info (100 docs)..." etc) very confusing.

Do users who _do_ have English as their primary language find our startup messages any _less_ confusing?

It's worth noting that the primary intent of these messages is to help tech leads, developers and other technical staff when they're trying to understand startup problems or slowness.  Secondary to that, I think the changing messages and numbers convey to end users that "something useful" is happening, rather than just watching a spinner rotate interminably.

**Comment by alxndrsn** [comment]
> Happy to close this PR if y'all want to see another approach here.

To be clear, I think translating is a definite improvement on English-only messaging, and the PR is good for this.  As per discussion, adding a progress bar and then de-emphasising of the text would be a further improvement (e.g. grey the text, or only show it when a certain UI element is clicked).

**Comment by alxndrsn** [comment]
> Personally, I had no idea what the difference was between "Loading assets..." vs "Loading app..." vs "Starting app...".

And I suspect a CHW would have even less idea, and even if they did it's not useful information in itself.  But for tech staff who are debugging slow or failed app startup, they may be useful.

**Comment by alxndrsn** [comment]
Fixed in #4860

**Comment by ngaruko** [comment]
LGTM
Tested on `gamma.dev v3.3` with Swahili translation
