### ISSUE TITLE
Users without permission to view contacts, tasks, messages can view those pages

### ISSUE THREAD

**Issue by newtewt** [medic/medic-webapp#4711]
Logging in with a user that has no permission to view anything is able to navigate directly to urls and see some information. 

**Steps to reproduce**:
Create a role with no permissions and assign a user to the role. 
Log in as that user
There are no tabs shown to the user
Paste a url from below and go
The user is taken to the messages view with messages displayed. 

http://localhost:5988/medic/_design/medic/_rewrite/#/messages/ 
http://localhost:5988/medic/_design/medic/_rewrite/#/contacts/
http://localhost:5988/medic/_design/medic/_rewrite/#/tasks/

**What should happen**:
User is shown an access denied error

**What actually happens**:
User is taken to the page and sees data.

**Environment**:

- Instance: local environment or https://beta-old.dev.medicmobile.org/
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 3.0.0, 2.16.0-beta8

**Comment by dianabarsan** [comment]
As an online user (previous National Manager), I am redirected to /error/403 when trying to access any tab in webapp (the tabs in the navingation are visible). 
I think this is because the checked permissions (`can_access_tasks`, `can_access_messages`, `can_access_contacts`, `can_access_analytics` and `can_access_reports`) don't exist (the ones that exist are: `can_view_analytics_tab`, `can_view_analytics`, `can_view_contacts`, `can_view_contacts_tab` etc).

**Comment by garethbowen** [comment]
@dianabarsan Good spotting, thanks! I think we should use `can_view_messages`, `can_view_contacts`, etc. The ones that end with `_tab` are about whether the tab is shown in the UI so configurers can hide infrequently used tabs. If you have `can_view_messages` but not `can_view_messages_tab` then you can access messages via the hamburger menu.

@vimemo Was the intention to reuse the existing permissions or create new ones?

**Comment by vimemo** [comment]
can_view_x sounds good. I was not aware of can_view vs can_access.

**Comment by newtewt** [comment]
Getting accessed denied now when the roles are not on the account.
