### ISSUE TITLE
Add display of visit counts and conditionally style them (UHC mode)

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4758]
For UHC mode, we already display "Date last visited". We would like to keep that, and add in a visual display of "Number of visits this month".

**Clarification**
Although they sound similar, “Date last visited” and “Visits this month” are two completely different data points. Date last visited is calculated based upon a _rolling_ count of “how many days ago” and is not tied to the calendar at all. Visits this month is tied directly to the calendar month. Date last visited never resets while visits this month resets back to 0 at the beginning of each month. 

**Visits this month**
We would like to add large visit count numbers to the right side of each family row. The visit count will display a count of the number of times that family has been visited so far within the current month. The exact definition of the calendar month should be left configurable. Some partners may follow the calendar literally, while other partners have different definitions of a month (ex: Muso counts from the 26th of one month until the 25th of the next month). Whatever forms have been configured to calculate "Date last visited" will be the same forms used to calculate "Visits this month".

**Basic layout** 
- The count can be "0", "1", "2", "3", "4" visits etc. Two digits should be allowed (but probably not common). After two digits (highly unlikely) we should display a summary such as "99+".
- The count number is located in the upper right of the row and sits on the same baseline as the contact name text. Noto Sans, bold, 24px (H1).
- The word "visit(s)" is below the count number and sits on the same baseline as the date last visited text. Noto Sans, bold, 14px.
- Both the visit count and the word "visit(s)" are right-aligned (meaning any extra characters push the word to the left). The far right edge of both text boxes is aligned. There is a 10px gap between the far right edge of the text boxes and the right edge of the screen.
- Both the number digit and the word "visit(s)" should be internationalized so various language translations and scripts can be configured

![markup](https://user-images.githubusercontent.com/26235957/43285186-064ef94a-90d3-11e8-92d5-0812f56f6cd6.png)

**Conditional styling**
- We would like to give partners the ability to conditionally style the counts, or not
- If the partner has no specific goals, just like with Targets, the text is normal black
- If the partner does have specific goals, we use red to indicate "bad", yellow to indicate "ok" and green to indicate "good" or "goal met". Red = # E33030, Yellow = # C38813, Green = # 538E8D.
- Adding to this, we can also, optionally, display an icon next to the count number. This icon is only available as an option if the partner has a goal. If the partner does not have a goal there will never be an icon. The icon is FontAwesome fa-exclamation-triangle [ & # x f 0 7 1 ; ]. Size 16px, color # E33030.
- The icon is positioned to the left of the count number on the same baseline. 
- Note: We would like to remove the red warning icon by the date last visited text that we implemented in 2.16.1. The new functionality and location of the icon as described here replaces what we did in 2.16.1. It used to be tied to date last visited - now it is instead tied to visits this month.

![screen shot 2018-07-26 at 2 18 36 pm](https://user-images.githubusercontent.com/26235957/43289137-db683028-90de-11e8-9426-b524ccb24af1.png)

**Muso's desired configuration**
- The text of the counts should be red if the count is “0”, yellow if “1” and green if 2 or more. 
- If the count is "0" or "1" it should also be accompanied by a red warning icon. 

Here is what the visit counts will always look like at the very beginning of the month ("0 visits" for every single family):
![beginning of month](https://user-images.githubusercontent.com/26235957/43285205-136bdf58-90d3-11e8-8c38-7addbb5fd4cb.png)

Here is what the visit counts should look like after three visits have been made:
![after first week copy](https://user-images.githubusercontent.com/26235957/43285224-1d090d4c-90d3-11e8-85fe-86a3f5d42b58.png)

And here is what the visit counts might look like even later in the month:
![after second week copy](https://user-images.githubusercontent.com/26235957/43285230-23cbef50-90d3-11e8-9cc0-eba7be8bb7a6.png)

**Another clarification**
You will notice that it is sometimes possible for families with 2 visits to appear above families with 1 visit in the list, due to the sorting based upon “Date last visited”. We are aware of this outcome but think it makes sense in light of the emphasis on _frequency_ of home visits. It is possible we might get a request in down the road to add the ability to sort "By number of visits this month" but that is an issue for another time.

**Comment by SCdF** [comment]
FWIW, here is what I already knocked out to support this. This is a `reduce` function that gets baked into our application (more on that later). I wrote it in about 20 minutes and it still needs testing etc:

```js
function(key, values, rereduce) {
  if (rereduce) {
    return values.reduce(function(acc, value) {
      return {
        max: Math.max(acc.max, value.max),
        count: acc.count + value.count
      }
    });
  }

  var oneMonthAgo = new Date().getTime() - (31 * 24 * 60 * 60 * 1000);

  var trueValues = values.filter(function(value) { return value > oneMonthAgo; });

  if (trueValues.length) {
    return {
      max: Math.max.apply(null, trueValues),
      count: trueValues.length
    };
  } else {
    return {
      max: Math.max.apply(null, values),
      count: 0
    };
  }
}
```

Worth noting that it does **not** pass all of your requirements:.

> Visits this month is tied directly to the calendar month. Date last visited never resets while visits this month resets back to 0 at the beginning of each month.

We could change the reduce function to be keyed off a calendar month if we like, that is an easy change. To me though, that seems weird, because it's a non-consistent amount of time.

> The exact definition of the calendar month should be left configurable. 

This is not possible using the complete-but-not-tested approach I used above (having a `reduce` function attached to a CouchDB view), because reduce functions are a piece of constant code that you cannot parameterise, shipped with the application.

If we really need this, options include (@garethbowen look at me sternly as required):
 - Having a UI config for this, and generating reduce functions and pushing them up to the server, allowing you to change the reduce function in deployed systems. While this is terrible, it's less terrible that it sounds if we confirm that changing the reduce function doesn't re-fire view indexing (it shouldn't as it's not used by indexing). If we really need configurability, this is my preferred option.
 - Keep the `contacts_by_last_visited_date` view as it is, but no longer reduce on the server side, instead downloading all of the view results locally and "reducing" there. Big downside of this is that you cannot filter by date, so you need to download as many entries as your contacts have ever had visits, every time you render or re-render this page.
 - Changing the `contacts_by_last_visited_date` view, or using some existing / new view, that has a composite key of contactId and lastReportedDate, and run N view calls, one for each contact that you care about, with `[contactId, minimumDateAsWorkedOutFromConfiguration]`, and then run a `_reduce` on that.

The first idea is IMO the best because it has the best performance characteristics, but it does something we have never done before: changing the `view` property of a production ddoc live. This feels a bit gross and needs to be thought over a bit more, but I think is not the end of the world once you think about it for a bit.

The other two are more conservative, but have bad performance characteristics. The first requiring that you pull more data that you need, and the second requiring that you perform far more view calls than you need. @amandacilek are these online or offline users? If they are offline only then pulling more data is not as big of a deal.

**Comment by SCdF** [comment]
**NB**: I'm still confirming that changing the reduce function won't re-generate the whole view, I'm getting the feeling maybe it will? Definitely something we need to test (ie put `log` calls into the view code and see if changing reduces causes them to re-run) if we want to consider this approach.

**Comment by SCdF** [comment]
**Update**: I have deleted my above comments (in case you wonder where they went, because they are no longer true or relevant to the discussion.

I've talked to the CouchDB folks, and reduce functions are partially run at index time and stored (for performance reasons), so:
 - We can't have a reduce with any dynamic time-based logic in there, because it doesn't all run when you query, so a reduce function that only counts reports based on "this month" cannot work
 - We shouldn't upload reduce functions dynamically because they would cause the entire view to re-generate, due to the data structures used by Couch.

OK to that leaves us with two real options for this ticket:
 - Keep the contacts_by_last_visited_date view as it is, but no longer reduce on the server side, instead downloading all of the view results locally and "reducing" there. Big downside of this is that you cannot filter by a list of contacts and also filter by date, so you need to download as many entries as your contacts have ever had visits, every time you render or re-render this page.
 - Changing the contacts_by_last_visited_date view, or using some existing / new view, that has a composite key of contactId and lastReportedDate, and run N view calls, one for each contact that you care about, with [contactId, minimumDateAsWorkedOutFromConfiguration], and then run a _reduce on that.

The former is almost certainly the best approach, the latter invoking way more IO than the former (though neither are ideal).

**Comment by dianabarsan** [comment]
In light of the recent requests, if the two features: LastVisitedDate and VisitsCount were separate, how would this apply?

> Note: We would like to remove the red warning icon by the date last visited text that we implemented in 2.16.1. The new functionality and location of the icon as described here replaces what we did in 2.16.1. It used to be tied to date last visited - now it is instead tied to visits this month.

Should the LastVisitedDate warning still be displayed when VisitsCount is disabled?

**Comment by dianabarsan** [comment]
Merged into `2.18` and forward ported to `3.0.x` and `master`.

**Comment by dianabarsan** [comment]
To enable the specific `goal` (which color codes the number of visits), you need to configure it in `app_settings`. Add the following section:

```
"uhc": {
    "contacts_default_sort": "last_visited_date",
    "visit_count": {
        "month_start_date": 21,
        "visit_count_goal": 2
     }
}
```

where:

 Setting                        | Default           | Accepted values              | Description                                                                                                                             
--------------------------------|-------------------|------------------------------|------------------------------------------------------------------------------------------------------------------------------------------
 contacts_default_sort          | empty string | * | **last_visited_date**: default contact sorting will be based on last visited date *: default contact sorting will be alphabetical 
 visit_count / month_start_date | 1                 | 1-31                         | Designates the monthly date when the visit count is reset.                                                                               
 visit_count / visit_count_goal | 0                 | integer >= 0                 | Designates the monthly visit count goal.

**Comment by ngaruko** [comment]
Thanks @dianabarsan for comments above. LGTM.
Tested on `beta-old.dev` with 2.18
![image](https://user-images.githubusercontent.com/6979995/44690317-7ba14c80-aaae-11e8-98af-6ae9f9fb6432.png)

**Comment by garethbowen** [comment]
Documentation added here: https://github.com/medic/medic-docs/blob/master/configuration/app-settings.md#optional-settings
