### ISSUE TITLE
Use user.facility_id saved in `_users` instead of `medic` db

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#4774]
Revert to using `facility_id` and `roles` saved in `_users.user` instead of `medic.user-settings` when determining authorization context for filtered replication.

**Comment by ngaruko** [comment]
Does this need AT'ing @dianabarsan @garethbowen ?

**Comment by garethbowen** [comment]
For AT:

1. Change the `facility_id` in the user-settings doc so it's different from the one in the users db.
2. Replicate into a fresh indexed db
3. Ensure you get the docs for the facility referenced in the users db not the one from the user-settings doc.

This is important because the user can theoretically change their own user-settings doc but we need to make sure that doesn't bypass our security filter.

**Comment by dianabarsan** [comment]
This is correct. Additionally, you could also change the `roles` in the user-settings doc and make sure your user is still having correct permissions.

**Comment by newtewt** [comment]
@dianabarsan  it seems like we are still using the  medic user-settings for the users page in the admin console. Would this need updating to use the _users doc? The way I discovered this is by deleting my roles and it shows blank on the users page but I'm getting into the app with the appropriate security.

**Comment by SCdF** [comment]
> @dianabarsan it seems like we are still using the medic user-settings for the users page in the admin console. 

This is intentional. It should work fine as long as data integrity is maintained as only through the app (ie things will go wrong if people edit stuff directly in couch, but through our UI it should wrok)

**Comment by dianabarsan** [comment]
@newtewt This is something that was recently discussed ( https://github.com/medic/medic-webapp/issues/3379 and https://github.com/medic/medic-projects/issues/1809 ).
