### ISSUE TITLE
Ability to add partner logos to the About page

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4850]
This is an issue related to white labeling of the webapp #4849. That ticket is of higher priority than this one.

**About page partner logos**
- The top left corner of the webapp can only accommodate one logo. If a project would like to display a collection of logos representing all of the organizations and funders involved in the project, we will create a new space for these at the bottom of the About page. It is not required for partners to place any logos on this page but it would be a nice option for those who wish to make use of it.
- We should create a new section at the bottom of the page titled “Supporting partners” or something similar
- I’m open to suggestions from developers about how we should code the container boxes here. My initial suggestion is this: The containers are sized 100 x 100 pixels, and arranged in a horizontal row below the header. We should allow for multiple rows of icons. The exact number that will fit on each row depends on the overall size of the screen - the icons should responsively wrap to additional rows as necessary as the page scales.

![about page](https://user-images.githubusercontent.com/26235957/45906609-a169fa80-bda9-11e8-984d-0966b92e6bbb.png)

**Comment by Jodge** [comment]
I think we can use Bootstrap Carousel Plugin in the unlikely event that the support partners logos gets too many

@garethbowen I am foreseeing a situation whereby one uploads an **HD** image let says `1920x1080` , should the `api` do the auto generation of thumbnail such that what ends up being stored is relatively in consistence to `100x100` suggested by @amandacilek ?

**Comment by garethbowen** [comment]
@Jodge I think we should just have the logos wrap instead of using a carousel plugin. It's quite likely to wrap on small phones and it doesn't matter if we use more vertical space at the bottom.

Yeah there's definitely a risk of someone uploading a file that's too big. I don't like downscaling on the server side because it's a bunch of extra code for a feature that's not going to be used much, and the quality is never as good as using a professional image editor. Instead maybe we should implement a [file size validation](https://developer.mozilla.org/en-US/docs/Web/API/File) so people can't upload images that are too big?

The if you combine that with css to limit the dimensions of the image it should work ok.

**Comment by Jodge** [comment]
Sounds good

**Comment by garethbowen** [comment]
Ready for AT. This should also be reviewed by design before it gets released.

**Comment by ngaruko** [comment]
LGTM. Again, we will need the design eyes to have a look at the aesthetic side of things, @amandacilek . Images used were random png downloaded from the net. 
![image](https://user-images.githubusercontent.com/6979995/50873667-c56b4d80-1425-11e9-87c3-90a5c3612ce4.png)

==
![image](https://user-images.githubusercontent.com/6979995/50873804-580bec80-1426-11e9-9311-201e5a55b71f.png)

**Comment by ngaruko** [comment]
Ha... Back to you @Jodge .

**Comment by Jodge** [comment]
**Add little less space here** @amandacilek that image OXFAM has big white space around it, that's why that space from the **Supporting partners* header seems big

**Comment by ngaruko** [comment]
I will leave this too to you @amandacilek to close off once you are satisfied with the look and feel of the page.

**Comment by amandacilek** [comment]
I'm fine with this one now, thanks.
