### ISSUE TITLE
Inputs group not saved when its relevance is set to false

### ISSUE THREAD

**Issue by derickl** [medic/medic-webapp#4875]
We've historically hidden the inputs group in forms with the following relevance condition `'./source='user'` and up to version 2.16.x, this group was persisted regardless of the relevance condition. From 2.18 (also tested against master), the above behaviour changed such that the inputs group is empty for newly submitted forms (since the group is marked as not relevant when the source is the contact).

I've tested this on `jssdemo.app` and cross checked with recently submitted data on MUSO which is running 2.18. @binokaryg has tested this on 2.13 and 2.16 they work as expected.

To work around this, I've tried to create a dynamic appearance condition that evaluates to 'hidden' for the inputs group when source = 'contact' but that seems to get ignored such that the group is visible when it should ideally be hidden. Do we know of another way to do this?

_I've stripped out most of the data for brevity_

**First time submission**
```
{
  "_id": "b38f5c26-1c31-4419-ac59-3d7ed6b4f8e6",
  "_rev": "2-ccf42e4cb5602ba174d4110d2de34e76",
  "form": "delivery",
  "type": "data_record",
  "content_type": "xml",
  "reported_date": 1538998689801,
  "contact": {
    "_id": "147e8a73-1b1a-472d-83f7-e458a0e53a0a",
    "parent": {
      "_id": "a6cb7c24-6b6d-46f2-8f99-2e9c1b149e2d",
      "parent": { "_id": "533bfd12-1e17-4c7e-84ff-fe48cf3f4594" }
    }
  },
  "fields": {
  }
}
```

**After editing**
```
{
  "_id": "b38f5c26-1c31-4419-ac59-3d7ed6b4f8e6",
  "_rev": "3-3b8a93ffe3eb464aa6082717306900f3",
  "form": "delivery",
  "type": "data_record",
  "content_type": "xml",
  "reported_date": 1538998689801,
  "contact": {
    "_id": "147e8a73-1b1a-472d-83f7-e458a0e53a0a",
    "parent": {
      "_id": "a6cb7c24-6b6d-46f2-8f99-2e9c1b149e2d",
      "parent": { "_id": "533bfd12-1e17-4c7e-84ff-fe48cf3f4594" }
    }
  },
  "fields": {
    "inputs": {
      "meta": {
        "location": { "lat": "", "long": "", "error": "", "message": "" },
        "deprecatedID": ""
      },
      "source": "user",
      "source_id": "",
      "contact": {
        "_id": "ddc9be4b-0eed-45f2-a566-cc31c6a1701e",
        "patient_id": "07936",
        "name": "Family 1 Primary",
        "date_of_birth": "0",
        "sex": "",
        "phone": "",
        "parent": {
          "contact": { "phone": "", "name": "Family 1 Primary" },
          "parent": { "parent": { "use_cases": "" } }
        }
      }
    }
}
```

**Comment by derickl** [comment]
@alxndrsn would you have any insights on this?

**Comment by derickl** [comment]
This behaviour has the potential to lead so data quality issues especially around tasks where we heavily use the inputs section to pass data around. Given that MUSO has been running a 2.18 for a few months, it would be great to prioritise this.

**Comment by alxndrsn** [comment]
@vimemo did you do some work with the `hidden` tag recently?  Could this help @derickl?

**Comment by binokaryg** [comment]
Here is a small test form to demonstrate the issue:
```<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>Test Report</h:title>
    <model>
      <instance>
        <test-4875 delimiter="#" id="test-4875" prefix="J1!test-4875!" version="2018-10-11 0-10">
          <inputs>
            <meta>
              <location>
                <lat/>
                <long/>
                <error/>
                <message/>
              </location>
            </meta>
            <source>user</source>
            <source_id/>
            <contact>
              <_id/>
              <patient_id/>
              <name/>
            </contact>
          </inputs>
          <patient_uuid/>
          <patient_id/>
          <patient_name/>
          <group_chw_info>
            <call_button/>
          </group_chw_info>
          <meta>
            <instanceID/>
          </meta>
        </test-4875>
      </instance>
      <instance id="contact-summary"/>
      <bind nodeset="/test-4875/inputs" relevant="./source='user'"/>
      <bind nodeset="/test-4875/inputs/source" type="string"/>
      <bind nodeset="/test-4875/inputs/source_id" type="string"/>
      <bind nodeset="/test-4875/inputs/contact/_id" required="true()" type="string"/>
      <bind nodeset="/test-4875/inputs/contact/patient_id" type="string"/>
      <bind nodeset="/test-4875/inputs/contact/name" type="string"/>
      <bind calculate="../inputs/contact/_id" nodeset="/test-4875/patient_uuid" type="string"/>
      <bind calculate="../inputs/contact/patient_id" nodeset="/test-4875/patient_id" type="string"/>
      <bind calculate="../inputs/contact/name" nodeset="/test-4875/patient_name" type="string"/>
      <bind nodeset="/test-4875/group_chw_info/call_button" readonly="true()" type="string"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/test-4875/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body class="pages">
    <group appearance="field-list" ref="/test-4875/inputs">
      <label>Patient</label>
      <group ref="/test-4875/inputs/contact"/>
    </group>
    <group appearance="field-list" ref="/test-4875/group_chw_info">
      <label>Missing Birth Report</label>
      <input ref="/test-4875/group_chw_info/call_button">
        <label>**Name: <output value=" /test-4875/patient_name "/> **</label>
      </input>
    </group>
  </h:body>
</h:html>
```

**Comment by vimemo** [comment]
This is the only pyxform change for hidden tags:
(4952)[https://github.com/medic/medic-projects/issues/4952]
Is this update related to this?

**Comment by derickl** [comment]
@alxndrsn @vimemo the two issues aren't related. My local pyxform setup hasn't changed in quite a while :). I have a feeling it has to do with how non-relevant nodes are treated in 2.18+

**Comment by abbyad** [comment]
The conclusion from the product team call is to always save the inputs section since it is needed for editing a form and at time for analytics, while the data costs of storing it are minimal.

**Comment by abbyad** [comment]
Discussed issue with @dianabarsan and she will investigate including this in 2.18.1. Two options discussed were:
1. Always save inputs, even if non-relevant. This means existing forms do not need to be modified.
1. Introduce a feature to conditionally hide a group, and use that for `inputs`.  This would mean changing all existing forms.

Option 1 seems easier for backwards compatibility so will be explored as the primary option.

**Comment by garethbowen** [comment]
Related: #4543

**Comment by abbyad** [comment]
It was suggested that perhaps we should fix this in the form by having two input groups. One would only show when relevant so that you can select the patient (I'll refer to this group as `user_selected_inputs`), and the other is the traditional `inputs` which would always be relevant, and always hidden. The `inputs` would get values prepopulated, or calculated from the other `user_selected_inputs` section.

I tried two versions of this, but don't think either work, so open to other suggestions!

## Attempt 1: Get patient only in `user_selected_inputs`
The `user_selected_inputs` only has a `db:person` field to get the patient. The `inputs/_id` either gets the value from the app, or "calculated" from 'user_selected_inputs/_id'. We can get the value assigned, but all of the associated fields (eg Name) are not populated. Also, using a calculate on a field has led to problems in the past since prepopulated values could be cleared, especially without _Actions and Events_ (https://github.com/medic/medic-webapp/issues/4131) to control when the calculation is done. 

## Attempt 2: Duplicate all inputs to `user_selected_inputs`
This method duplicates all input fields that come from the person's doc into the `user_selected_inputs`, and "copying" over the values to `inputs` when they are filled. This is also subject to the same calculation problem as above, where they would get overwritten. Also, any reference in a label to an input field would need a _third_ copy of the field to refer to.

## Next steps
Are there any other form changes that should be considered?
Would it be worth considering introducing an attribute to specify that a field/group needs to saved regardless of the relevant condition (eg `<inputs mm:always_save='true'>`)? This would be instead of the option 2 above of conditionally hiding a field/group, which seems like it would open a bigger can of worms.

**Comment by alxndrsn** [comment]
From a semantic perspective it seems entirely reasonable that a group called `inputs` would be excluded from the output.  If specific input fields are required later, could they be copied over to a field which _is_ `relevant`?

**Comment by garethbowen** [comment]
Back to you @alxndrsn

**Comment by alxndrsn** [comment]
PRs for:
* [x] `master` - https://github.com/medic/medic-webapp/pull/4907
* [ ] `3.1.x`
* [ ] `3.0.x`
* [ ] `2.18.x`

**Comment by ngaruko** [comment]
LGTM

**Comment by derickl** [comment]
LGTM (tested on beta-old.dec)
