### ISSUE TITLE
Update place icons

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4895]
I've updated the place icons that are embedded in our app. The visual changes are quite minor and thus this is low priority (this was part of a larger project of trying to standardize our icon library). 

These five icons are embedded in our app and will need to be changed in the code. The latest icon files are here: https://github.com/medic/medic-projects/tree/master/icon-library/people_and_places

**Comment by Jodge** [comment]
@amandacilek one of the icons you have provided i.e. **medic-chw-area.svg**  resembles another icon on the app **medic-clinic.svg** should this be treated on and the same thing? if so should we replace it with this new one but retain the naming

**Comment by Jodge** [comment]
@garethbowen the icon **medic-family.svg** should it be part of the _**contact_schema.js**_ for Enketo contact form!? Not sure how this hierarchy should be structured

**Comment by amandacilek** [comment]
Hi Jodge, I meant to maintain the original naming of all of these but perhaps I made a mistake. My intent was that all of the names remain the same - no changes. If "medic-clinic" was the old naming for the tan icon with the CHW and two houses, we can change the name of the new file to "medic-clinic" to match. 

Here are the icons in order of hierarchy:
![screen shot 2018-10-17 at 10 41 08 am](https://user-images.githubusercontent.com/26235957/47105706-8ef0ae80-d1f9-11e8-807e-a381e5d61507.png)

**Comment by Jodge** [comment]
I see, noted. Thanks

**Comment by garethbowen** [comment]
For AT make sure the icons in the app _and_ the standard configuration have been updated correctly.

**Comment by newtewt** [comment]
@Jodge  looks like `config/standard/resources/medic-clinic.svg` is still the old icon. Should be updated too. https://github.com/medic/medic-projects/blob/master/icon-library/people_and_places/medic-chw-area.svg

@amandacilek  @garethbowen  @abbyad  
In standard config we define the image below in the resources.json file so it is available but I'm not sure anything actually uses it. I can't find a default or a standard config form that uses it. 

https://github.com/medic/medic-projects/blob/master/icon-library/people_and_places/medic-family.svg

**Comment by amandacilek** [comment]
Yep that's the new correct icon for chw area.

A family in our app is considered the lowest level "place" (another term sometimes used for family is "household"). So the family icon is for the lowest place level in our hierarchy. The icon for family is used on the LHS list when families are displayed, and on the RHS family contact profile. Some projects might use it for a family level form such as family survey.

**Comment by Jodge** [comment]
@amandacilek the names of icons in `icon-library` was really confusing since it is not consistent with the naming in `standard/resources` so figuring which should replace which was kind of murky

**Comment by amandacilek** [comment]
I'm sorry about that. Sharon initially named these files and I copied the existing names when I updated them. What are they named in standard/resources? Is there still confusion about anything or are we clear now?

**Comment by Jodge** [comment]
@amandacilek  so the old `medic-clinic.svg` should be renamed to `medic-family.svg` while on the **resource.json** should now be `"medic-clinic": "medic-chw-area.svg"` @newtewt is that what you are saying?

`medic-chw-area.svg` is already on the standard/resources under the name `icon-places-clinic.svg` and the resource.json `"branch": "icon-places-clinic.svg"`

**Comment by garethbowen** [comment]
@newtewt Looking at the code the [icon we ship](https://github.com/medic/medic-webapp/blob/master/api/src/resources/medic-clinic.svg) is identical to the [icon you've linked](https://github.com/medic/medic-projects/blob/master/icon-library/people_and_places/medic-chw-area.svg).

Which configuration were you using? Standard, default, or something else?

Is it possible the horti bug stopped api from being upgraded to have these icons?

**Comment by newtewt** [comment]
Let me know if this helps clear up or maybe just adds more confusion. Would be fine to jump on a quick call too. 

This is how the icons are displaying in the 3.3.x branch. 

**Default Config**
District > ![district](https://user-images.githubusercontent.com/10531066/49180676-57f6d800-f323-11e8-8f55-12682cda7019.png)

Center > ![center](https://user-images.githubusercontent.com/10531066/49180681-5c22f580-f323-11e8-9a5a-655b2c9b7c09.png)

CHW Area > ![chw](https://user-images.githubusercontent.com/10531066/49180685-5e854f80-f323-11e8-8b6b-4f33253e0995.png)

Family > Not sure how we would see this. See details below
Person >  ![person](https://user-images.githubusercontent.com/10531066/49180694-66dd8a80-f323-11e8-8272-d32932832747.png)

**Standard Config**
District >  ![district](https://user-images.githubusercontent.com/10531066/49180676-57f6d800-f323-11e8-8f55-12682cda7019.png)
Center > ![center](https://user-images.githubusercontent.com/10531066/49180681-5c22f580-f323-11e8-9a5a-655b2c9b7c09.png)
CHW Area > ![old_chw](https://user-images.githubusercontent.com/10531066/49180740-8d032a80-f323-11e8-87a8-5c7511999ce1.png) This is because in the `config/stanard/resources.json` file `"medic-clinic": "medic-clinic.svg"` and not `"medic-clinic": ""icon-places-clinic.svg"`. `icon-places-clinic.svg` is the new image. The `medic-clinic.svg` could be replaced with the new image. 
Family > Not sure how we would see this. See details below
Person > ![person](https://user-images.githubusercontent.com/10531066/49180748-92f90b80-f323-11e8-8da1-c5345d2b3805.png)



**Family Icon**
For family in the default config the file isn't uploaded or maybe I'm missing it somewhere. It is only shown in the `config/standard/resources/icon-people-family.svg`

For standard config. The file is shown in `resources.json` as  `"family": "icon-people-family.svg"` Looking in the properties files for forms I cannot find anything that references `"icon: "family"` and looking at the contact-schema there are no icons listed as family. Maybe the config in 3.3.x is out of date but as far as I can tell the new family icon won't display anywhere.

**Comment by garethbowen** [comment]
Right - so it's the standard config that's wrong, not the default config. @Jodge Can you update this last icon in the standard configuration please?

@newtewt Currently we only have three types of places. In the code these are always called "district_hospital", "health_center", and "clinic". However different projects call them different things which confusing things immensely. IIRC "health_center" is the "area", the "clinic" is the "family". Of those icons you've shown I think the little house with a plus on it should never be shown in the standard configuration.

**Comment by amandacilek** [comment]
That all makes sense to me, Nick. The brown icon in Standard Config with the dotted circle needs to be updated to the brown icon with two houses and a CHW.

It looks like we are using Standard Config as our Default Config. That's fine but just noting that Standard is SMS so there’s no family level (no family icon). Standard is not our most commonly used config. Other configs do have the family level.

**Comment by garethbowen** [comment]
Merged and backported to 3.3.x

**Comment by newtewt** [comment]
Looks good to me
