### ISSUE TITLE
Work out what happened to Tecno W4 pouch patch

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4947]
#2797 may have regressed again - I can't immediately see why it would now work

**Comment by garethbowen** [comment]
I removed it when we upgraded to PouchDB 7 ( https://github.com/medic/medic-webapp/commit/87f5dba0ba5a3f280c61b62a06fba6154a285607#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 ). I think it was no longer needed because PouchDB removed the safari hacks that were incorrectly picking up Tecno phones. It would be worth checking to make sure though...

**Comment by garethbowen** [comment]
Closing because it was removed on purpose. Reopen if it shouldn't have been removed.
