### ISSUE TITLE
Link to webapp from admin app

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#5035]
Related: https://github.com/medic/medic-webapp/issues/4922

**Comment by garethbowen** [comment]
@amandacilek We decided not to do this as part of #4960 - can you remember why? IIRC it was because the admin app opens in a new window so if we add this link then you'd end up with two webapp windows open.

I'm starting to think when db admins log in they should go directly to the admin app so they don't have to wait for the webapp to load first.

Then if we make the configuration link in webapp not open in a new tab and add this link admins can go back and forward as they please.

**Comment by amandacilek** [comment]
Yes, I think we were initially trying to avoid a three tab situation. I think your plan makes sense Gareth.

**Comment by Jodge** [comment]
I see, well put, crystal clear now, thanks!

**Comment by ngaruko** [comment]
LGTM - Not sure if there was a consensus on how to name the links (`App Settings` and `Application`)- they seem to be changing with every new version @Jodge 
![image](https://user-images.githubusercontent.com/6979995/51579043-6da00c80-1f24-11e9-9e31-da6b278eef48.png)

**Comment by garethbowen** [comment]
@ngaruko There should be a logout button there too, I think?

**Comment by ngaruko** [comment]
We have that @garethbowen 
![image](https://user-images.githubusercontent.com/6979995/51579236-0df63100-1f25-11e9-8806-1649fd7d05aa.png)
 . If there is no objection about the nomenclature, I will go ahead and close this.

**Comment by garethbowen** [comment]
"App Settings" is correct. "Application" is a new one - I think it's ok unless anyone has any other suggestions?

Both are translatable so it's not hard to change if we don't like them.
