### ISSUE TITLE
Missed replacing the current household icon with the new medic-family icon

### ISSUE THREAD

**Issue by newtewt** [medic/medic-webapp#5212]
Spoke with @amandacilek  in slack about the household icon being the wrong icon. The current household image is `icon-places-household@2x.png` in the config/standard/resrouces directory and needs to be updated to the [medic-family](https://github.com/medic/medic-projects/blob/master/icon-library/people_and_places/medic-family.svg). This was an original effort in #4895 but was missed because it was likely not used.

**Comment by garethbowen** [comment]
Merged and backported to `3.3.x`

**Comment by abbyad** [comment]
The icon replaced was meant to be a house, as it is used in Standard config to [represent home-visits in a target](https://github.com/medic/medic-webapp/blob/95c7339b6bc7d8585856817d7c26cb7da15242be/config/standard/app_settings.json#L6053-L6061).

There may be others that need to be updated to the latest in the icon library, but that one in particular should still represent a house.

**Comment by amandacilek** [comment]
I'm sorry for the confusion. I thought we missed something with our earlier ticket but maybe we didn't. I actually thought the new icon library _replaced_ the old standard library and was surprised to realize they are two separate things. 

So yes, the standard config is missing the family icon because there is no concept of families in standard hierarchy. And maybe it can keep the house icon if it's using that for something related to houses. But that means that we should only be using the standard icon library for standard projects - all _webapp_ projects should be set up using the icons from the new icon library (which does include the families icon). Is that an accurate summary?

**Comment by newtewt** [comment]
Does this needs to be reverted or should I revert and add the medic-family as a new resource?

**Comment by amandacilek** [comment]
I think let's revert and not hold up 3.3. I need to talk to the standard team to figure out what's going on with the icons.

**Comment by garethbowen** [comment]
Reverted and backported. Closing this issue. Please raise a new one once we've worked out what we want to do here.
