### ISSUE TITLE
Transmit anonymous statistics via HTTP and SMS

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#710]
Building upon #707, implement opportunistic transmission of anonymous statistics. We should support sending these by SMS (to an international number that's configurable in app_settings), and via HTTP/HTTPS (using a URL that's configurable in app_settings).

In principle, this should be pretty straightforward; the implementation details (like deciding when to try sending a message, and/or detecting the presence of a working gateway or internet connection) are likely to require the most effort.

**Comment by garethbowen** [comment]
This issue is now solely concerned with http submission.

**Comment by abbyad** [comment]
The data arrives on the hosted instance, and getting @sglangevin to complete the acceptance testing

**Comment by sglangevin** [comment]
Can we put the "Content" field last? Also, can we add the rest of the fields that Amanda recommends here: https://docs.google.com/a/medicmobile.org/spreadsheets/d/11eu_f1_Q_ZRdNfB6DwQKcM6lcz3sAFQDNFLUxiHmXfU/edit#gid=0

It seems to work as expected otherwise - I was able to download and open the .xml file. One question I had was how we will be able to tell when 2 reports come from the same user so we can track their progress over time.

Is there another way for me to test this with a locally installed version of DIY? I'm not sure what number to send info to in order to test or what the message structure should be.

**Comment by garethbowen** [comment]
> Can we put the "Content" field last?

You mean in the Report view, right? I think @mandric has just made the change in alpha to put the message content as the last field.

> ... can we add the rest of the fields that Amanda recommends[?]

Do you mean the "suggested additions"? We can definitely add more fields. I think adding fields should be a separate issue because it's not about the statistics submission method. Please raise an issue with the fields you'd like added.

> ... how [can] we will be able to tell when 2 reports come from the same user so we can track their progress over time[?]

The "from" phone number should be the same, and unique from all other installations. 

> Is there another way for me to test this with a locally installed version of DIY?

You can send stats *to* your locally installed instance by installing the forms. If you want to test sending stats *from* your locally installed instance you need to configure the phone number of the instance you want to send stats to.

**Comment by sglangevin** [comment]
@garethbowen it would be great to test sending stats from my locally installed instance to the stats.app instance - can you help me set that up? Will I have to wait until next month to test it or is there some sort of manual way to send stats?

The rest makes sense, I'll add a new issue for those stats.

**Comment by garethbowen** [comment]
@sglangevin We don't have a phone number for stats.app yet. You can test internet submission, but not SMS submission currently.

**Comment by sglangevin** [comment]
@garethbowen that's fine - can we test internet submission manually or do I have to wait until the monthly report is due?

**Comment by garethbowen** [comment]
@sglangevin There are two factors which make this not straight forward to answer.

Firstly, the stats must be generated. These can be seen at: `/_utils/database.html?medic/_design/medic/_view/usage_stats_by_year_month`. This is what should be submitted when everything is configured. If you select one you should either not see a field called `submitted` or the field should be `false`. If you don't see any records at all then no stats have been generated - let me know.

Secondly, if the stats are generated and not yet submitted and internet submission is configured, they will be submitted at 30 minutes past the hour, every hour. So configure internet submission in the configuration wizard, and then wait for 30 minutes past. The document from above should change to `submitted: true` and you should then see the record in app.stats. Otherwise - let me know.
