### ISSUE TITLE
Implement overflow strategy for top-level tabs

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#740]
We're planning to add the "Configuration" section as a top-level tab. This means – especially on mobile – that some screen sizes won't be able to accommodate all of the tabs.

Figure out a way to make tabs that won't fit on the screen available. Here's an example screenshot from an unrelated application; it's not exactly what we want, but illustrates the general concept.

![untitled](https://cloud.githubusercontent.com/assets/763977/5384521/11af5aa0-806f-11e4-953f-417052439056.png)

**Comment by garethbowen** [comment]
Design mockups:

Mobile view @ 320px wide:

![smallest-mobile](https://cloud.githubusercontent.com/assets/2064938/6362182/31080d36-bcef-11e4-9a49-5a80c1de421d.png)

Tablet view @ 400px wide:

![smallest-tablet](https://cloud.githubusercontent.com/assets/2064938/6362183/3108296a-bcef-11e4-9bc3-13e325e47d61.png)

Desktop view @ 770px wide:

![smallest-full-size](https://cloud.githubusercontent.com/assets/2064938/6362184/31125278-bcef-11e4-94c9-b5e233a668e1.png)

**Comment by garethbowen** [comment]
We couldn't reach an agreement on the mockups so I'm just going to squeeze one more tab in for now, pending UX review.

**Comment by browndav** [comment]
Ideas for later: in tiny-mobile mode (320px), add a top-level menu that contains the equivalent of all of the first-level tabs, plus send message and logout. 3 screens: (1) main screen (tab select, logout, send message); (2) pick your message conversation; (3) view the conversation.

This could also be a slide-out "tray" or "overlay", rather than a top-level screen (see Slack's channel list on iOS or Android for an example, or the Medic public website).

**Comment by garethbowen** [comment]
This has become important again now that we have the Events tab. Furthermore whether tabs are shown or hidden has become configurable so we can no longer restrict the installation to a subset of tabs.

**Comment by abbyad** [comment]
We plan to do a more significant UI overhaul for the mobile app, but you are right, it seems as though we need to solve this before then.  Our current mockups don't have have a logo in the top left corner, but if all the tabs are shown that doesn't help enough.

Here are some options with my thoughts:
**1) Scrollable tabs:** simple interface, yet not likely familiar for users.
**2) Dropdown:** as in @garethbowen's example [here](https://github.com/medic/medic-webapp/issues/740#issuecomment-75879156): possibly simpler to implement, but not as quick to navigate between tabs and we'd lose the ability to see the notifications from other tabs.
**3) Regular tabs with a "more" dropdown:** can show the most common tabs as we do now, and lesser used tabs are mostly hidden. 

My preference is currently for 3, but it is not evident to me how we'd show the active tab if it is from the "more" dropdown.

**Comment by abbyad** [comment]
We have decided to remove the logo and `+` button from the mobile view, which allows us to fit up to six tabs without overflow. 

Here is an example at 401px wide: 
![screen shot 2015-08-25 at 10 43 09](https://cloud.githubusercontent.com/assets/789512/9469640/259e1660-4b16-11e5-995c-6bc231b58db7.png)

In mobile view we wouldn't have more than five tabs anyhow, since Configuration is hidden. This allows us to have even larger tabs, shown here at 400px with `.header .tabs a` `width` set at the current 6em, as well as and 7em, respectively:
![screen shot 2015-08-25 at 10 43 57](https://cloud.githubusercontent.com/assets/789512/9469654/3a836f1c-4b16-11e5-8373-b48fb86decdd.png)

![screen shot 2015-08-25 at 10 54 59](https://cloud.githubusercontent.com/assets/789512/9470018/ed8cb27a-4b17-11e5-8c84-02bd48e1803c.png)

Fortunately, we don't have a need more than six tabs for the foreseeable future. Here is a list of all planned or possible tabs:
- **Tasks**
- **Contacts**
- **Reports**
- **Targets** aka Analytics
- *Messages - not in the mobile app*
- *Configuration - not in the mobile view or mobile app*
- *Resources - not for the first iteration*

**Recap of overflow strategy:** Remove the logo and `+` from mobile view, and use current tabs structure.

I will open a separate UI issue for the size of the tabs.

**Comment by nice-snek** [comment]
hi frand @SCdF, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
We sort of solve this now. We also seem happy with the idea that configuration etc is for desktop browsers, where as the smaller set of icons (which we don't have overflow problems with) are for mobile, reducing the need to solve this issue generically. Closing.
