### ISSUE TITLE
Bad Gateway In Easy Setup Wizard 

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#766]
First run using `medic-os-v1.1.0-x86-alpha-20150107.iso` has 502 after clicking `Start`
![image](https://cloud.githubusercontent.com/assets/789512/5674658/83110e18-977c-11e4-8c36-c64c11d6da13.png)

**Comment by garethbowen** [comment]
I think this is probably fixed by https://github.com/medic/medic-api/commit/fee585d0ededd12ddd619d844766a86441a342c0

First see if you can reproduce it by going back to the easy setup wizard and hitting start again. If it's what I think it is it'll happen every time you click start.

Second, upgrade to the latest alpha and try and reproduce again.

**Comment by abbyad** [comment]
Correct, updating from `0.4.3-alpha.1090` to `0.4.3-alpha.1102` seems to have resolved the issue.
