### ISSUE TITLE
Convert Facilities configuration page to Angular

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#778]

**Comment by abbyad** [comment]
Here is mockup that can be used as a guide - it combines People & Places into a single tab. I can provide more details as needed.

![image](https://cloud.githubusercontent.com/assets/789512/6198460/b0553bf4-b3d0-11e4-82fc-b734bbd6cfe2.png)

The intention is to first focus on bringing current Facilities functionality to Angular, without breaking the current hierarchy. The future functionality (eg groups, households, caregivers and patients) fits within this concept and will be designed for later iterations.

**Comment by browndav** [comment]
A few questions:

# Have you done mockups of the "Add Person" and/or editing interactions? It's not clear to me why there are two "Add Person" buttons, or how I'd go about changing someone's phone number. It's also not clear how I'd move a person from one catchment area to another, or associate a catchment area with a different clinic. All of those things are possible in the current version.

# Are the import/export features intended to be part of this? Do we have some example output? In any case, I'd split that off in to a new feature-request issue.

# Are the add place / add person buttons context-aware (i.e. does 'Add Place' disappear if the filter isn't set up to include any places)? Is there really any utility in viewing a flat list of intermixed people and places? You might be able to simplify this by making the people and places selections mutually exclusive.

# Have we really thought through the distinction between people and users? There's probably an opportunity to manage both of those in a more integrated way – when CHWs start accessing the web app, there's the potential for a lot of duplication.

Finally, it'd be helpful to have a day or two to walk through this with the full dev team before we jump in to this; it's a major redesign and probably has implications for other components.

**Comment by abbyad** [comment]
1. Mockups of Add Person/Place, editing would make use of similar modals with different headers. Modals are being used since that pattern is already in use. Eventually these large modals would be replaced throughout entire web-app.

![image](https://cloud.githubusercontent.com/assets/789512/6200087/edb23f46-b435-11e4-942a-2b8dfb424394.png)


![image](https://cloud.githubusercontent.com/assets/789512/6200085/d3b71f3a-b435-11e4-942e-876861ec8d10.png)

2. Import and Export All in the mockup are top level functions accessed through the hotdogs/burger. These are currently in the webapp's facilities page. For simplicity's sake we can make the export here as `Export All` instead of Exporting only the people/places visible. 

3. We went through several iterations on this, and found that there are times that you want to see both. As for the buttons, they are times when viewing people you may want to add places and vice versa... meaning that the buttons on the left are not context aware, but the buttons on the right would be.

4. That seems to be a logical filter... Show "District Types" only, that belong to District 1, 3, 5. Can you give another example of something that breaks? 

5. Yes, we have thought about that. As you can see in the first mockup we do want to eventually have User permissions accessible from this contact page, but have left it for a later iteration since there is more to figure out there. For instance, we would still need a `Users` page to manage Users that are not contacts (eg Analytics or Gateway users). Because of that we decided to leave the two distinct for now until we have more Contacts logging in.

The intention with this design was to not break the overall way we consider facilities throughout the webapp, but still be a transition towards the way we want to be presenting "people" to the user. We can definitely discuss this further and see what needs to be tweaked.

**Comment by browndav** [comment]
Let's talk on Tuesday, rather than fill this up with back and forth comments over the weekend. Do you have any other written material or mockups I can go through before then?

Once we're on the same page on Tuesday, I'd like us to spend an hour walking through this with the full development team.

**Comment by abbyad** [comment]
Updated mockups for a first iteration. Later iterations will look at integrating different types of people and their relationships (eg Caregivers and Patients).

![slide1](https://cloud.githubusercontent.com/assets/789512/6261066/1e90a7cc-b7b7-11e4-8ff8-63bf51a347da.PNG)
![slide2](https://cloud.githubusercontent.com/assets/789512/6261067/1e9ac324-b7b7-11e4-8ab2-d3d4bf5c412a.PNG)
![slide3](https://cloud.githubusercontent.com/assets/789512/6261069/1eab6d28-b7b7-11e4-9fc8-a1b399366b17.PNG)
![slide4](https://cloud.githubusercontent.com/assets/789512/6261068/1eab0f0e-b7b7-11e4-98b0-d93f9c0fdee0.PNG)
![slide5](https://cloud.githubusercontent.com/assets/789512/6261070/1eacb5ca-b7b7-11e4-8141-ffec1d7adbd7.PNG)

**Comment by abbyad** [comment]
Overall looks good! The first iteration has a single Add Contact modal, which should be split into Add People and Add Person (as shown in the mockups above). Reopening for that change then other minor changes/fixes will be opened as separate issues.

**Comment by abbyad** [comment]
Works well in `0.5.0-alpha.1223`, new issues will be created for any further changes or bugs.
