### ISSUE TITLE
Add Facilities filtering to Messages tab

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#794]
Filter the Message list as done in the Reports tab with a Facilities/Contact filter

**Comment by garethbowen** [comment]
This will involve a major rework. Currently the messages are based on a couchdb view which doesn't allow this. The solution is to switch to lucene indexes which is the way the other tabs work. Lucene doesn't have a reducing mechanism so we'd have to rework how we group by contact.

I think the way forward may be to do a lucene query then reduce the results in the front end so the LHS only shows one contact and the most recent message. Then on select we can still query the view for the full conversation. This would allow us to easily add freetext filtering, as well as any other sensible filtering we want.

Currently we can efficiently show all conversations because we reduce the content to a minimal set. With switching to lucene we'll need to put a limit on what we fetch, but it'll have to be limited by message, not conversation. We can still paginate but again it'll paginate by message, not by conversation.

**Comment by browndav** [comment]
This may be relevant in the context of #910 (contact/place refactor) and/or #947 (embed vs. link for contacts/places).

**Comment by abbyad** [comment]
Closing as ancient
