### ISSUE TITLE
Clear the details pane after any filter change

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#840]
If you filter or search it seems as though the details pane for the Contact should be reset to "blank", especially when the Contact is no longer found in the Contact list on the left. 

Can anyone think of a reason to maintain the existing details pane after a filter/search change? If not then it would likely be best to reset the details pane to blank upon any search.

![screen shot 2015-03-23 at 23 47 36](https://cloud.githubusercontent.com/assets/789512/6795499/01aba44e-d1b7-11e4-81a2-ff05e2bb2f76.png)

We can create a more helpful "blank" details page, but that can be done at a later time, and in a different issue.

**Comment by browndav** [comment]
I think I have a possible reason, or at least something to complicate this.

If the user creates a new contact while all contacts in the left pane are hidden by a filter, it's not entirely clear what the right behavior is – we want the user to see that a new contact was created, we want the user to be able to edit the contact, but we also want to maintain some semblance of filter consistency in the left pane. We probably also want to avoid just clearing the filters, since that could cause a pretty dramatic UI shift and possibly confuse people. IIRC, we're currently showing the new contact in the right pane (regardless of whether it shows up in the left pane), which might be in conflict with your clear-the-right-pane approach.

I can look a bit closer at it today if needed.

**Comment by garethbowen** [comment]
The detail pane now clears on filter. Also the first item is selected automatically.

When a contact is created or edited it is always shown on the RHS. The updated contact isn't necessarily shown on the LHS unless it happens to be in the top 50 for the given filter.

**Comment by browndav** [comment]
@abbyad: If, during acceptance testing, it looks like we need UX changes in/around creating new contacts while a filter is present, feel free to file another issue and we can look at it in more detail there. I know you were looking at that late last week w/ the design team.

**Comment by abbyad** [comment]
I'll keep that in mind @browndav and create a new issue if needed.

In the meantime, the post filter behaviour looks good in 0.5.0-alpha.1244. Moving to Ready.
