### ISSUE TITLE
Include Facility Creation in DIY wizard

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#858]
Asking a user their Facility Name during the onboarding wizard and automatically creating the one facility in their system will help them get going on Medic Mobile more quickly.

**Comment by browndav** [comment]
Assigning to @abbyad to indicate need for feature triage/scheduling.

**Comment by garethbowen** [comment]
If we ship with demo facilities and messages it would be confusing for users to add their own before the demo data is removed.

Secondly, creating the facility without a parent, contact, or phone number isn't very useful. For example, it won't show up in the Send Message dialog.

**Comment by abbyad** [comment]
The feedback we have been getting is that we need to guide the user through Contact creation when they first initialize the webapp. Since the Contact tab is new we don't have a tour for it yet and we haven't mapped it out yet either. It seems as though the first step is to do a comprehensive workflow mockup for Contact creation. We would need one of these for general setup (eg a Tech Lead setting it up for a partner) and one as it relates to DIY.

@diannakane is this something you can take on with @sglangevin? We can go over it together and create a more complete issue when it is ready to be implemented.

**Comment by abbyad** [comment]
Adding `Needs Design Work` label. Keep in mind #857 which has overlapping design considerations.

**Comment by diannakane** [comment]
Sounds good

**Comment by sglangevin** [comment]
Yep, I can help out.

**Comment by diannakane** [comment]
![img_1827](https://cloud.githubusercontent.com/assets/1675870/7643004/5229a2ac-fa4a-11e4-97e8-3374727095d9.JPG)
Here's a sketch of the facility tab for the wizard. We'd like the facility created here to default to the health center level. Can we hide the district level from DIY?

**Comment by browndav** [comment]
Is this a must-have for DIY Beta Two? We're trying to stabilize and get started on the mobile application as quickly as possible due to deadline/time constraints.

**Comment by abbyad** [comment]
We will reevaluate the urgency of this issue after the acceptance testing of #910 - it may no longer be needed.

**Comment by abbyad** [comment]
According to @sglangevin we are fine without this, as it was `decided that we would create a how-to guide for users so that they understand how to use the Contacts tab (creating places, setting primary locations and setting points of contact)`

Closing for now. If something like this becomes a requirement later on a new issue can be opened.

**Comment by browndav** [comment]
The above mention was in error.
