### ISSUE TITLE
Support multiple gateways for outgoing messages

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#890]
Right now we can support multiple SMSsync gateways for incoming messages. For outgoing messages, the first gateway to hit the instance would indiscriminately start processing messages, with potential duplicate messages if another gateway attempts to process outgoing messages before the first completes.

In order to use a single instance across several countries, each with their own gateway, we would need to be able to filter outgoing messages by country code. At this time we only need to differentiate by outgoing phone number, not sender, content, or user specified.

If possible, it would be beneficial to have additional filter flexibility, such as a set or range. For instance, in many countries where we work it is cheaper or even free to send messages to a number on the same network. Since it is often possible to determine the operator by phone number prefix, a gateway could be responsible for individual network operators or subset. For example, [Kenyan phone numbers](http://en.wikipedia.org/wiki/Telephone_numbers_in_Kenya#Mobile_phone_numbers) have 3 digits that identify the operator:

![image](https://cloud.githubusercontent.com/assets/789512/7124671/ec578106-e1f8-11e4-9dcb-430f0a290d4d.png)

The minimum needed for this issue is country code differentiation, but if that goal can be met with more powerful regex-like filtering then that would be preferred.

**Comment by browndav** [comment]
This depends on #819, since we'll want to support outbound routing in a single location.

Slight complication: having multiple instances of SMSsync hitting the same instance of medic-transport means we'll have to find some way for each SMSsync instance to identify itself uniquely. I'm imagining that the routing rules will live within medic-transport (and eventually be edited via the medic-webapp configuration panel), but they'll need to reference a particular SMSsync handset/installation.

More than slight complication: there are a couple ways to make this work for modems. One would be to refactor toward supporting multiple GSM modem USB devices on a single installation; the other would be to use multiple instances of Medic OS and have them talk to either a medic-transport meta-driver or directly to medic-webapp. The latter is probably an ugly layering violation.

I take it that supporting multiple copies of SMSsync in the outbound case is the immediate goal?

**Comment by browndav** [comment]
@mandric, @garethbowen: We should chat this week about the proper layer to put this in. My instinct is that it belongs in medic-transport, but I can envision a couple ways it could be put in medic-webapp proper. Not sure yet.

**Comment by abbyad** [comment]
`simply supporting multiple copies of SMSsync for the outbound-message case is the immediate goal?`
Correct

**Comment by abbyad** [comment]
To avoid having to reimplement, this be tackled once SMSsync is processed through medic-transport (#819)

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by estellecomment** [comment]
@abbyad Is this still needed? We're going towards integration with carriers/aggregators for larger scale projects right? Please close if that's the case.

**Comment by abbyad** [comment]
Correct, and we can open new issues specific to circumstances if something like this comes up again.
