### ISSUE TITLE
Person with leading `_` in name not showing in Contacts

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#896]
If a Person's name starts with a `_` (and possibly other special characters) they do not show up in the "unfiltered" Contacts list:

![screen shot 2015-04-18 at 00 27 31](https://cloud.githubusercontent.com/assets/789512/7214009/3e6e323e-e562-11e4-8fd4-32361f8ae65c.png)

...unless you narrow the search down with free text or specific districts:

![screen shot 2015-04-18 at 00 27 18](https://cloud.githubusercontent.com/assets/789512/7214010/4681fbfe-e562-11e4-87ca-94ae14a51cb0.png)

Removing the `_` or changing to a `&` makes the Person appear normally:

![screen shot 2015-04-18 at 00 34 36](https://cloud.githubusercontent.com/assets/789512/7214014/b8937416-e562-11e4-93d6-128ef3bffe24.png)

![screen shot 2015-04-18 at 00 28 25](https://cloud.githubusercontent.com/assets/789512/7214008/39aa1bc8-e562-11e4-9f59-6b73bc289c91.png)

**Comment by garethbowen** [comment]
This is due to an inconsistency between the sorting in couchdb/lucene and the sorting in the front end. couchdb sorts `_` after `z` so it doesn't return a contact with a name starting with a `_` until you're on the last page of the result set. Then, the front end sorts `_` before `a` so it jumps to the top of the list.

When you apply a specific filter all you're doing is making sure there is only one page of contacts.

I'll look at making the sorts consistent.

**Comment by abbyad** [comment]
Works well in 0.5.0-alpha.1323, moving to Ready
