### ISSUE TITLE
Update browserlist to Chome 110+ or perhaps a last 10 version declaration

### ISSUE THREAD

**Issue by fardarter** [medic/medic-webapp#8997]
Using the issue format to ask a question. I see the current browserlist config has Chrome 90 as a target. Is there a reason that FF is a rolling window but Chrome is a fixed version?

```
# Browsers that we support

Chrome >= 90
last 4 Firefox versions
```

@garethbowen at risk of telling you something you already know, your bundler may be using the browserlist config to determine your target JS version, and with 2021 being the year of release for v90, you may be shipping less efficient/larger code that you desire. If it's already known and there is a reason, maybe a comment in the file could be helpful.

**Comment by garethbowen** [comment]
That matches our documented support matrix here: https://docs.communityhealthtoolkit.org/core/releases/#dependencies

The reason Chrome is set to 90 is because the CHT is mostly used in a webview which is almost always the Android Webview which is Chromium based. Because many android phones are not set to autoupdate we know that lots use old versions of webview. We will continue to progressively increase the minimum browser version when possible but it needs careful communication and is quite expensive for partners to verify which phones need updating and which don't.

Firefox on the other hand is realistically only used on desktops which are much better at keeping up to date so we can safely stick to a rolling version there.
