### ISSUE TITLE
Patient's weeks pregnant field is blank (Analytics)

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#950]
![screen shot 2015-05-14 at 5 13 32 pm](https://cloud.githubusercontent.com/assets/1286381/7644660/2710d140-fa5d-11e4-8325-7f90a9018dac.png)
The patient shown in the upcoming appointments chart doesn't have an estimate for weeks pregnant.

**Comment by garethbowen** [comment]
@sglangevin It would be great if we could get the registration document for this pregnancy, even just a screenshot of the report in the Reports tab would help.

**Comment by sglangevin** [comment]
![screen shot 2015-05-14 at 6 00 14 pm](https://cloud.githubusercontent.com/assets/1286381/7645001/1c10ce66-fa63-11e4-8893-d93ff580d951.png)

**Comment by garethbowen** [comment]
@sglangevin What's the received date?

**Comment by sglangevin** [comment]
![screen shot 2015-05-14 at 6 03 13 pm](https://cloud.githubusercontent.com/assets/1286381/7645027/8655c77c-fa63-11e4-8239-1e87523e2209.png)

**Comment by garethbowen** [comment]
This bug affects recent registrations without LMP. The problem was we were using the reported date as the date of conception, so any patient registration received 6 days ago was calculated to be 0 weeks pregnant, which doesn't get shown in the UI.

The calculation for Weeks Pregnant is based on the ANC Visualisations PDF which says...
> for LMP cases = weeks since LMP-2
> for no LMP = weeks since registration (can we have a dynamic column label to display “weeks since reg” instead of weeks pregnant where appropriate?)

We're showing approximate "weeks pregnant" rather than "weeks since reg" as some configurations could have both LMP and non-LMP registrations, so we need a better calculation for "weeks pregnant" for non-LMP that just registration date. This also affects EDD for non-LMP registrations, which is currently reported date + 40.

Reading [Wikipedia](http://en.wikipedia.org/wiki/Gestational_age) I believe we're calculating "weeks pregnant" and EDD incorrectly in both cases. When the LMP is known the EDD should be `LMP + 40 weeks` and the weeks pregnant should be simply the number of weeks since the LMP. ie: The calculation `weeks since LMP-2` should just be `weeks since LMP`.

When we don't have the LMP I propose we pick a number of weeks to approximate the LMP. This is required to show the EDD columns and to include non-LMP registrations in the Women With Upcoming EDDs widget. The minimum value for the LMP approximation is 4 weeks as there's no way to confirm pregnancy before that. However I think it's unlikely that most women will be registered right away and a value of 5 or 6 weeks would be more accurate.

@sglangevin What do you think?

**Comment by mandric** [comment]
Nice work here, this is a touchy subject but makes sense to me too @garethbowen.  I'm sure @diannakane and others have opinions here as well.

**Comment by btbonval** [comment]
@alxndrsn working from the impact side doing many of these same calcs, I might be able to address some of this.

I think `weeks since LMP - 2` should be `weeks since LMP + 2`.

As @abbyad brought up in slack, there is EDD and then there is max expected delivery date. EDD is typically 40 weeks since LMP. But patients can deliver a few weeks earlier or later. So EDD + 2 weeks is actually MDD. Due to the buffer, that calculation seems to useful in decisions whether the patient has already delivered. For impact metrics, we use EDD in some cases regarding the patient's schedule and so forth and MDD in other cases regarding whether the patient has given birth.

We already have data from a project with both LMP and no LMP that has been running for 6 months to a year (hard to tell, the data is not clean). Part of our impact metrics are trying to decide an average EDD error given no LMP was supplied to get a better estimate on MDD for patients who have no LMP recorded. At current time, there is a single data point. This statistic might change drastically from region to region with changing cultural norms (and possibly different training).

**Comment by btbonval** [comment]
Also as a PS, we've been using EDD + 4 weeks in impact but it is configurable per deployment.

**Comment by yembrick** [comment]
Hey. @garethbowen , you are right, weeks pregnant = weeks since LMP for LMP cases, that was a mistype originally. @btbonval, why do you think LMP + 2, maybe Im missing something. 

Bryan and I are starting an analysis that shows how many weeks are between receiving a reg form and a delivery form (with and without LMP). This should allow us to approximate weeks pregnant at registration time for non-LMP cases, but I think that would probably just help us tweak things for that sub population group, I dont think we have enough data to assume anything broadly at this point.

**Comment by sglangevin** [comment]
@garethbowen Let's calculate weeks pregnant as:
* Weeks since LMP for LMP registrations
* Weeks since registration + 4 for no LMP registrations

I agree that this is conservative, but @yembrick suggested that perhaps we make the weeks pregnant calculation configurable for no LMP registrations in the future.

**Comment by sglangevin** [comment]
I can't easily test this for no LMP because we don't have any of those in our sample data set. Looks good for LMP. I've added a comment to #1092 to request that R forms be included in the sample dataset.

**Comment by sglangevin** [comment]
Strike that - @garethbowen gave me a good testing pointer. Either way it will help to have some R forms in sample data for the future.
