### ISSUE TITLE
Allow actual date of birth to be used for immunization reports

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#992]
Moving https://github.com/medic/medic-sentinel/issues/68 to here:

> Right now, the support is for age in weeks. Introduce a trigger to be invoked on registration that will construct date of birth from fields: Year, month and day reported as separate fields.

**Comment by diannakane** [comment]
adding in Amanda's additional detail on where this has been used to some extent, which we might be able to build from:

"What Dave built for CIC is the ability for the SIM app to turn date of birth (3 fields) into days/months old (could similarly be weeks id imagine). We don't have schedules being set from it, but that could be used on the sim app side to take entered date of birth and send the system weeks since birth which would allow the system to generate schedules as it currently does"

**Comment by nice-snek** [comment]
hi frand @garethbowen, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
@abbyad Is this still needed? We seem to have gotten by ok for the last two years...

**Comment by mandric** [comment]
I'm pretty sure we support any date field?  But I'm not exactly sure what part of the app you are talking about.  Can you provide come configuration example(s) of what you are using and what you would like?  Or a link to a running instance/configuration?

**Comment by mandric** [comment]
Oh I see, we might assemble a new field like `birth_date` based on the other fields `birth_date_year` `birth_date_month` and `birth_date_day`... and then generate a schedule based on that...

**Comment by sglangevin** [comment]
This has been requested again recently but is not required right now. I'd like to see more investigation into what needs to be supported. We currently support age in days and age in weeks, so I'd be interested to know if we would want to support age in months, age in years, full birthdate, etc. I'd put this on hold for now until requirements can be gathered.

**Comment by garethbowen** [comment]
Thanks @sglangevin . Closing for now. We can reopen if/when we have clear requirements.
